Split Microsoft.EntityFrameworkCore.Analyzers into language-specific analyzers
dotnet/efcore pull request #22195
Opened 2020-08-24 16:24 UTC by sharwell

Fixes #22177

2020-08-24 16:28 UTC, roji commented
Oh wow, thanks for submitting this! We'll have a chat in EF triage a bit later today about it.

2020-08-24 17:45 UTC, Youssef1313 requested changes
nit: some markdown parsers require blank lines around tables.
Also, [MD022](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022---headings-should-be-surrounded-by-blank-lines) requires blank lines around headings.

2020-08-24 17:45 UTC, Youssef1313 commented on src/EFCore.Analyzers.CSharp/AnalyzerReleases.Shipped.md
> +### New Rules
```suggestion
### New Rules

```

2020-08-24 17:45 UTC, Youssef1313 commented on src/EFCore.Analyzers.CSharp/AnalyzerReleases.Shipped.md
> +### New Rules
```suggestion
### New Rules

```

2020-08-24 17:45 UTC, Youssef1313 commented on src/EFCore.Analyzers.CSharp/AnalyzerReleases.Shipped.md
> +### Removed Rules
```suggestion
### Removed Rules

```

2020-08-24 17:55 UTC, Youssef1313 requested changes

2020-08-24 17:55 UTC, Youssef1313 commented on src/EFCore.Analyzers.VisualBasic/AnalyzerReleases.Shipped.md
> +### New Rules
```suggestion
### New Rules

```

2020-08-24 17:55 UTC, Youssef1313 commented on src/EFCore.Analyzers.VisualBasic/AnalyzerReleases.Shipped.md
> +### New Rules
```suggestion
### New Rules

```

2020-08-24 17:55 UTC, Youssef1313 commented on src/EFCore.Analyzers.VisualBasic/AnalyzerReleases.Shipped.md
> +### Removed Rules
```suggestion
### Removed Rules

```

2020-08-24 17:55 UTC, Youssef1313 commented on src/EFCore.Analyzers.VisualBasic/VisualBasicInternalUsageDiagnosticAnalyzer.cs
> +            };
Why not return syntax directly?

2020-08-24 17:58 UTC, sharwell commented on src/EFCore.Analyzers.CSharp/AnalyzerReleases.Shipped.md
> +### New Rules
These are direct copied from the existing files in the repository.

2020-08-24 17:59 UTC, sharwell commented on src/EFCore.Analyzers.CSharp/AnalyzerReleases.Shipped.md
> +### New Rules
➡️ See https://github.com/dotnet/efcore/pull/22195#discussion_r475795538

2020-08-24 17:59 UTC, sharwell commented on src/EFCore.Analyzers.VisualBasic/AnalyzerReleases.Shipped.md
> +### Removed Rules
➡️ See https://github.com/dotnet/efcore/pull/22195#discussion_r475795538

2020-08-24 17:59 UTC, sharwell commented on src/EFCore.Analyzers.VisualBasic/AnalyzerReleases.Shipped.md
> +### New Rules
➡️ See https://github.com/dotnet/efcore/pull/22195#discussion_r475795538

2020-08-24 17:59 UTC, sharwell commented on src/EFCore.Analyzers.VisualBasic/AnalyzerReleases.Shipped.md
> +### New Rules
➡️ See https://github.com/dotnet/efcore/pull/22195#discussion_r475795538

2020-08-24 17:59 UTC, sharwell commented on src/EFCore.Analyzers.CSharp/AnalyzerReleases.Shipped.md
> +### Removed Rules
➡️ See https://github.com/dotnet/efcore/pull/22195#discussion_r475795538

2020-08-24 18:00 UTC, sharwell commented on src/EFCore.Analyzers.VisualBasic/VisualBasicInternalUsageDiagnosticAnalyzer.cs
> +            };
It seems likely that someone would want to alter this in the future to provide more specific results for VB.

2020-08-24 18:55 UTC, roji commented
Postponing merging this PR as per https://github.com/dotnet/efcore/issues/22177#issuecomment-679304818

2020-10-16 22:21 UTC, smitpatel commented
This can be rebased and merged to main now.

2020-10-22 19:04 UTC, roji commented
Note: am going to defer working on this until we make a decision on what happens with pubternality... Even though we may still want to provide analyzers for other purposes, this is the only one we currently have.

2022-03-22 04:39 UTC, AraHaan commented
Is there plans to continue this soon?

2022-05-18 19:38 UTC, closed without merging

2022-05-18 19:40 UTC, dougbu commented
If this PR or something like it is needed still, please retarget release/6.0