Fix to #21402 - Test using OData
dotnet/efcore pull request #22367
Opened 2020-09-02 05:04 UTC by maumar

Adding infrastructure and rudimentary tests using OData. Ported Northwind, ComplexNavigations and GearsOfWar models. Only setup for sqlserver currently.

Resolves #21402

2020-09-02 06:27 UTC, smitpatel commented on EFCore.Runtime.slnf
> +      "test\\ef.Tests\\ef.Tests.csproj"
```suggestion
```
This are excluded since they are not part of EF Core runtime.

2020-09-02 06:29 UTC, smitpatel commented on test/EFCore.OData.Tests/EFCore.OData.Tests.csproj
> +  </PropertyGroup>
```suggestion
  <PropertyGroup>
    <TargetFrameworks>$(StandardTestTfms)</TargetFrameworks>
    <AssemblyName>Microsoft.EntityFrameworkCore.OData.FunctionalTests</AssemblyName>
    <RootNamespace>Microsoft.EntityFrameworkCore</RootNamespace>
    <SkipTests Condition="'$(OS)' != 'Windows_NT' AND '$(Test__SqlServer__DefaultConnection)' == ''">True</SkipTests>
  </PropertyGroup>
```

2020-09-02 06:29 UTC, smitpatel commented on EFCore.Runtime.slnf
> +      "test\\EFCore.OData.Tests\\EFCore.OData.Tests.csproj",
```suggestion
      "test\\EFCore.OData.FunctionalTests\\EFCore.OData.FunctionalTests.csproj",
```

2020-09-02 06:30 UTC, smitpatel commented on test/EFCore.OData.Tests/Extensions/HttpContentExtensions.cs
> +            string json = await content.ReadAsStringAsync();
```suggestion
            var json = await content.ReadAsStringAsync();
```

2020-09-02 06:31 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTests.cs
> +        [Fact]
```suggestion
        [ConditionalFact]
```

2020-09-02 06:31 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTests.cs
> +        [Fact]
and likewise in other places.

2020-09-02 06:34 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/NorthwindODataQueryTests.cs
> +            var requestUri = string.Format("{0}/odata/Order Details", BaseAddress);
Should we have OData specific AssertODataQuery method?
which takes the requestUri and linq query and execute them and compare results (how we do when we specify efquery and l2oquery separately)

2020-09-02 09:08 UTC, maumar commented on test/EFCore.OData.Tests/Query/NorthwindODataQueryTests.cs
> +            var requestUri = string.Format("{0}/odata/Order Details", BaseAddress);
Was planning to add it in a later checkin.

2020-09-02 14:31 UTC, smitpatel commented on test/EFCore.OData.Tests/Extensions/HttpContentExtensions.cs
> +            string json = await content.ReadAsStringAsync();
inline temporary variable

2020-09-02 14:34 UTC, smitpatel commented on test/EFCore.OData.Tests/Extensions/ODataTestExtension.cs
> +            var route = routingFeature.RouteData.Routers.OfType<ODataRoute>().FirstOrDefault();
either use hard cast to IRoutingFeature in line above or make this line null safe.

2020-09-02 14:35 UTC, smitpatel commented on test/EFCore.OData.Tests/Extensions/ODataTestExtension.cs
> +            route.RouteAsync(routeContext).Wait();
Wait could do a lot of damage in xunit. consider switching to actual await

2020-09-02 14:39 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTestFixture.cs
> +    public class ComplexNavigationsODataQueryTestFixture<T> : ComplexNavigationsQuerySqlServerFixture
put a constraint on T.

2020-09-02 14:40 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTests.cs
> +                    SqlServerTestStore.CreateConnectionString("ComplexNavigations")));
Consider storing the name in a property.
Use same name if these tests don't initialize the database else a different name.

2020-09-02 14:41 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTests.cs
> +            var customers = result["value"] as JArray;
are they customers?

2020-09-02 14:41 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTests.cs
> +            var requestUri = string.Format("{0}/odata/LevelThree", BaseAddress);
add for level 2 & 4 also so we can verify those are also working.

2020-09-02 14:44 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/GearsOfWarControllers.cs
> +        public IEnumerable<Officer> GetFromOfficer()
There was also another inheritance other than this in gears, right?
If yes then which other controller has ability to query for derived type?

2020-09-02 14:46 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/GearsOfWarODataQueryTests.cs
> +            configuration.AddControllers(controllers);
this could use refactoring to move stuff to base class common to all tests.

2020-09-02 14:49 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/NorthwindODataQueryTestFixture.cs
> +    public class NorthwindODataQueryTestFixture<T> : NorthwindQuerySqlServerFixture<NoopModelCustomizer>
Why do fixture classes deriving from SqlServer fixture? I am not seeing anything used from base class.

2020-09-02 16:26 UTC, AndriySvyryd commented
You should add an entry to `.github/dependabot.yml`

2020-09-02 16:27 UTC, AndriySvyryd commented on test/EFCore.OData.Tests/Extensions/ODataTestExtension.cs
> +using ODataPath = Microsoft.AspNet.OData.Routing.ODataPath;
Is this necessary?

2020-09-02 16:31 UTC, AndriySvyryd commented on test/EFCore.OData.Tests/PortArranger.cs
> +            var isInUse = connections.Any(c => c.LocalEndPoint.Port == port || c.RemoteEndPoint.Port == port);
inline variable

2020-09-02 16:41 UTC, AndriySvyryd commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTests.cs
> +            var response = Client.SendAsync(request).Result;
await

2020-09-02 17:24 UTC, AndriySvyryd commented on test/EFCore.OData.Tests/Query/GearsOfWarODataQueryTests.cs
> +            var response = Client.SendAsync(request).Result;
await everywhere

2020-09-02 17:29 UTC, AndriySvyryd commented on test/EFCore.OData.Tests/Query/NorthwindODataContext.cs
> +                    e.Ignore(o => o.ShippedDate);
Why are so many properties ignored?

2020-09-02 17:29 UTC, AndriySvyryd commented
Do the test initialize their own databases? I.e. if you drop all databases and just run these tests

2020-09-02 17:37 UTC, smitpatel commented on test/EFCore.OData.Tests/Query/NorthwindODataContext.cs
> +                    e.Ignore(o => o.ShippedDate);
That's what we do in northwind, no?

2020-09-02 17:39 UTC, AndriySvyryd commented on test/EFCore.OData.Tests/Query/NorthwindODataContext.cs
> +                    e.Ignore(o => o.ShippedDate);
Can we reuse existing code?

2020-09-02 18:20 UTC, maumar commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataQueryTests.cs
> +            var customers = result["value"] as JArray;
copy paste ;)

2020-09-02 18:21 UTC, maumar commented on test/EFCore.OData.Tests/Query/GearsOfWarControllers.cs
> +        public IEnumerable<Officer> GetFromOfficer()
factions and locustleaders I added the infra for them, just not the tests

2020-09-02 18:22 UTC, maumar commented on test/EFCore.OData.Tests/Query/NorthwindODataQueryTestFixture.cs
> +    public class NorthwindODataQueryTestFixture<T> : NorthwindQuerySqlServerFixture<NoopModelCustomizer>
I did for the database creation infra

2020-09-02 18:24 UTC, maumar commented on test/EFCore.OData.Tests/Extensions/ODataTestExtension.cs
> +using ODataPath = Microsoft.AspNet.OData.Routing.ODataPath;
name clash, Using the type only in one place so I could fully qualify. Thoughts?

2020-09-02 18:39 UTC, maumar commented on test/EFCore.OData.Tests/Query/NorthwindODataContext.cs
> +                    e.Ignore(o => o.ShippedDate);
copied from the original northwind

2020-09-02 19:25 UTC, maumar commented
@AndriySvyryd tests fixture inherits from NorthwindQuerySqlServerFixture so it automatically provisions the database when necessary.

2020-09-02 21:19 UTC, AndriySvyryd commented
> @AndriySvyryd tests fixture inherits from NorthwindQuerySqlServerFixture so it automatically provisions the database when necessary.

We shouldn't use the same database across test assemblies as that causes a race condition. Either rename it, use a different model or merge with SQL Server FTs.

2020-09-02 22:09 UTC, maumar commented
> > @AndriySvyryd tests fixture inherits from NorthwindQuerySqlServerFixture so it automatically provisions the database when necessary.
> 
> We shouldn't use the same database across test assemblies as that causes a race condition. Either rename it, use a different model or merge with SQL Server FTs.

Will rename. I'm bit scared of adding all the odata dependencies to our existing test suites.

2020-09-02 22:32 UTC, maumar commented on test/EFCore.OData.Tests/Extensions/ODataTestExtension.cs
> +            route.RouteAsync(routeContext).Wait();
removed that entire code - not needed

2020-09-02 22:34 UTC, maumar commented on test/EFCore.OData.Tests/Query/ComplexNavigationsODataContext.cs
> +            modelBuilder.Entity<Level1>().Property(e => e.Id).ValueGeneratedNever();
I hit some issues with efcore specific stuff, e.g. keyless entities. also the proper context needs to be injected into controllers. Did the easy thing for now just to get tests going. Was planning to tweak this in future checkins

2020-09-03 04:43 UTC, smitpatel commented on EFCore.Runtime.slnf
> +      "test\\EFCore.OData.Tests\\EFCore.OData.Tests.csproj",
Also update the folder name to match project and csproj file name in this file.

2020-09-09 07:10 UTC, maumar commented
refactored and updated @smitpatel @AndriySvyryd

2020-09-09 07:30 UTC, smitpatel commented on EFCore.Runtime.slnf
> +      "test\\EFCore.OData.FunctionalTests\\EFCore.OData.FunctionalTests.csproj",
Also add in EFCore.slnf
and EFCore.Relational.slnf

2020-09-09 16:14 UTC, smitpatel commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataContext.cs
> +    public class ComplexNavigationsODataContext : PoolableDbContext
Can we not reuse the same context generated in functional tests?

2020-09-09 16:17 UTC, smitpatel commented on test/EFCore.OData.FunctionalTests/Query/GearsOfWarControllers.cs
> +        public ITestActionResult Get([FromODataUri] string key)
Which class has hierarchy in all these apart from Gear? Add a method to query the derived type too.

2020-09-09 16:18 UTC, smitpatel commented on test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTests.cs
> +        public static IEdmModel EdmModel;
Where is this used?

2020-09-09 17:10 UTC, maumar commented on test/EFCore.OData.FunctionalTests/Query/GearsOfWarControllers.cs
> +        public ITestActionResult Get([FromODataUri] string key)
locusthorde : faction and locustcommander : locustleader I swear I added it before, must have been in a different branch

2020-09-09 17:18 UTC, maumar commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataContext.cs
> +    public class ComplexNavigationsODataContext : PoolableDbContext
will try

2020-09-10 17:15 UTC, bricelam approved these changes
LGTM

2020-09-10 17:15 UTC, bricelam commented on test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
This concerns me, but then again it might be totally fine.

2020-09-10 17:15 UTC, bricelam commented on test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
> +    <IsPackable>true</IsPackable>
No need to publish this one

2020-09-10 17:15 UTC, bricelam commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTestFixture.cs
> +            Dispose(true);
Just inline this. The bool overload is only useful if you allocate native resources.

2020-09-10 17:15 UTC, bricelam commented on test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTestFixture.cs
> +
Careful, smitbot will reject your double linebreaks.

2020-09-10 17:15 UTC, bricelam commented on test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTestFixture.cs
> +        protected virtual void Dispose(bool disposing)
(ditto)

2020-09-10 17:15 UTC, bricelam commented on test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTestFixture.cs
> +        protected virtual void Dispose(bool disposing)
(ditto)

2020-09-10 19:46 UTC, maumar commented on test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
> +    <IsPackable>true</IsPackable>
Added it because CI was complaining, will check again without as I changed some stuff there

2020-09-10 20:57 UTC, maumar commented
@smitpatel @bricelam do you have a clue why the helix job has failed? the tests seem to be all passing/skipped

2020-09-10 21:14 UTC, smitpatel commented
Looking at previous iterations of the run and windows is still running, there is some still running process. Runs are getting timed out (even though xunit test run finished).

2020-09-12 01:14 UTC, maumar commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTestFixture.cs
> +                //issue: dotnet/runtime #35990
any ideas how to make this less hacky? @smitpatel @AndriySvyryd @bricelam @roji? WaitForShutdown is blocked from completing until dispose is called, but then again can't call WaitForShutDown on potentially disposed object.  /cc @halter73 @Tratcher

2020-09-12 01:39 UTC, AndriySvyryd commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTestFixture.cs
> +                //issue: dotnet/runtime #35990
For starters you should override DisposeAsync instead and use await.

Then you can try this:
```C#
var shutdownTask = _selfHostServer.WaitForShutdownAsync();
_selfHostServer.Dispose();
await shutdownTask;
```

2020-09-12 01:42 UTC, halter73 commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTestFixture.cs
> +                //issue: dotnet/runtime #35990
Registering a no-op IHostLifetime that replaces the default ConsoleLifetime might be the way to go for testing. The Host unit tests demonstrate how this can be done:

https://github.com/dotnet/runtime/blob/ef4bc4d503b71f9de1a8988da6db38bcfcfb0cc4/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs#L495

Something similar can likely be done ODataQueryTestFixtureInitializer's ConfigureServices callback.

2020-09-14 17:42 UTC, Tratcher requested changes

2020-09-14 17:42 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +                    .UseKestrel(options => options.Listen(IPAddress.Loopback, port))
This should bind to port 0 and then fetch the result from the server after it's started.

2020-09-14 17:42 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +            var baseAddress = string.Format("http://localhost:{0}", port.ToString());
Since you're not binding to IPv6 then you should directly address IPv4 to avoid connection delays.
```suggestion
            var baseAddress = string.Format("http://127.0.0.1:{0}", port.ToString());
```

2020-09-14 17:42 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTestFixture.cs
> +                var shutdownTask = _selfHostServer.WaitForShutdownAsync();
Why do you even call [WaitForShutdownAsync](https://github.com/dotnet/runtime/blob/7f34be5319af78de3cb5fe12438f2756a864bddd/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs#L87)? It's redundant with [StopAsync](https://github.com/dotnet/runtime/blob/7f34be5319af78de3cb5fe12438f2756a864bddd/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L95). WaitForShutdownAsync is for code that's waiting for someone else to call StopAsync.

2020-09-14 17:46 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +                    .UseKestrel(options => options.Listen(IPAddress.Loopback, port))
https://github.com/microsoft/reverse-proxy/blob/ab34da2c3f91cff0cb0b61172d0c9d510c21692e/test/ReverseProxy.FunctionalTests/Common/Helpers.cs#L13

2020-09-15 05:27 UTC, maumar commented on test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataContext.cs
> +    public class ComplexNavigationsODataContext : PoolableDbContext
#22520

2020-09-18 19:33 UTC, maumar commented
@smitpatel ping for the final check

2020-10-16 22:24 UTC, smitpatel commented on test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTestFixture.cs
> +        public override async Task DisposeAsync()
What if we moved _selfHostServer to the interface too and implemented this as DIM? 💡

2020-10-16 22:25 UTC, smitpatel commented on test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTests.cs
> +        [ConditionalFact(Skip = "TODO: fix routing")]
Skip with a tracking issue number or unskip.

2020-10-16 22:25 UTC, smitpatel approved these changes

2020-10-20 19:58 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
This is a bit odd. Even in AspNetCore we only use Microsoft.NET.Sdk for tests. Why do you need .Web here? Because of the shared framework dependencies it brings in?

2020-10-20 19:58 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Properties/launchSettings.json
> +﻿{
Delete this file.

2020-10-20 19:58 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/EndpointRouteConfiguration.cs
> +    public sealed class EndpointRouteConfiguration : IEndpointRouteBuilder
This seems overkill. @javiercn ?

2020-10-20 19:58 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +
```suggestion
```

2020-10-20 19:58 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +            var baseAddress = selfHostServer.Services.GetService<IServer>().Features.Get<IServerAddressesFeature>().Addresses.First();
```suggestion
            var baseAddress = selfHostServer.Services.GetService<IServer>().Features.Get<IServerAddressesFeature>().Addresses.First();
            var clientFactory = selfHostServer.Services.GetRequiredService<IHttpClientFactory>();
```

Or just let the caller resolve it from the host, they don't need you to do it for them.

2020-10-20 19:58 UTC, Tratcher commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +            var clientFactory = default(IHttpClientFactory);
```suggestion
```

2020-10-21 05:17 UTC, maumar commented
@Tratcher iirc I used blank Asp.net core web app as the basis for the project - I modified the project to Microsoft.NET.Sdk and it works fine

2020-10-27 01:02 UTC, maumar commented
@Tratcher @javiercn I have addressed the feedback, please take another look

2020-10-27 16:09 UTC, Tratcher approved these changes
The host changes look good. I'm still not sure why you needed to implement a IEndpointRouteBuilder.

2020-10-27 16:35 UTC, javiercn commented on test/EFCore.OData.FunctionalTests/Query/EndpointRouteConfiguration.cs
> +    public sealed class EndpointRouteConfiguration : IEndpointRouteBuilder
Agree,

I'm not sure what you are trying to achieve here, but there's definitely a better way to do it than this.

2020-10-27 16:43 UTC, javiercn commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +    public class ODataQueryTestFixtureInitializer
This is overkill, I would recommend you replace all/most of the infrastructure with the library we ship to do this type of testing. See [here](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1) for details

2020-10-27 16:44 UTC, javiercn commented on test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
> +    public class ODataQueryTestFixtureInitializer
I just saw that you are spinning up kestrel, I would avoid that if you can, because it'll make tests faster and much more stable.

2020-10-29 00:40 UTC, merged

2021-02-12 01:46 UTC, smitpatel commented on test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
We need HttpGet/ControllerBase/ModelBinder from MVC to run these tests. Reference to Web SDK is needed.