implements #18845
dotnet/efcore pull request #22497
Opened 2020-09-11 15:56 UTC by scomert

2020-09-11 15:56 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=22497) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=22497) before we can accept your contribution.<br/><br/>:x: scomert [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=22497)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=22497) it.</sub>

2020-09-11 20:57 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
> +                if (_enableRegex)
I think we should just always to this--no need for a flag. Thoughts?

2020-09-11 20:59 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
> +                            return Regex.IsMatch(pattern, input);
These arguments are backwards. (Note well, SQLite and .NET disagree on this.)

2020-09-11 21:00 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                    arguments[0].TypeMapping);
Again, reverse the arguments.

2020-09-11 21:01 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                return _sqlExpressionFactory.Function("regexp",
@smitpatel Should we be really cool 🤓 and generate a REGEXP operator instead of a function call?

2020-09-11 22:01 UTC, smitpatel commented
Base branch change to main. Please rebase on latest main.

2020-09-11 22:02 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Infrastructure/SqliteDbContextOptionsBuilder.cs
> +        ///     Configures enabling Regex.IsMatch method translation
```suggestion
        ///     Configures enabling Regex.IsMatch method translation.
```

2020-09-11 22:02 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Infrastructure/SqliteDbContextOptionsBuilder.cs
> +        }
```suggestion
        => WithOption(e => e.WithEnableRegex());
```

2020-09-11 22:03 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
> +                    new SqliteRegexTranslator(sqlExpressionFactory)
Sort alphabetically.

2020-09-11 22:03 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +            var regexIsMatchMethod = typeof(Regex).GetMethod(nameof(Regex.IsMatch), new Type[] { typeof(string), typeof(string) });
Save this in private static field.

2020-09-11 22:04 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                return _sqlExpressionFactory.Function("regexp",
Can if it has different structure than SqlFunction.

2020-09-11 22:07 UTC, smitpatel commented on test/EFCore.Sqlite.FunctionalTests/RegexIsMatchTest.cs
> +    public class RegexIsMatchTest : IClassFixture<RegexIsMatchFixture>
Remove additional test class. Instead use existing - NorthwindFunctionsQueryTestBase
Also Assert the SQL generated using AssertSql in the derived type in Sqlite.

2020-09-11 22:07 UTC, smitpatel commented on test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
> +            optionsBuilder.UseSqlite("Database=Crunchie", b => b.EnableRegex()) ;
```suggestion
            optionsBuilder.UseSqlite("Database=Crunchie", b => b.EnableRegex());
```

2020-09-12 00:28 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                return _sqlExpressionFactory.Function("regexp",
`X REGEXP Y` is equivalent to `regexp(Y,X)`

2020-09-12 00:34 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                return _sqlExpressionFactory.Function("regexp",
Operator vs function syntax. I don't have preference. If you fancy, we can add it 😉

2020-09-12 07:04 UTC, roji reviewed
One thing to be careful is the finer details of regex behavior. For example, in PostgreSQL the default is to have single-line behavior (where `.` doesn't match \n), while the .NET default behavior isn't. It may be OK to translate [the default overload of IsMatch](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.ismatch?view=netcore-3.1#System_Text_RegularExpressions_Regex_IsMatch_System_String_System_String_) (the one without RegexOptions) to whatever the default behavior is on Sqlite, but it would mean a subtle behavior mismatch.

2020-09-12 07:05 UTC, roji commented
For comparison, here's the [regex SQL generation in EFCore.PG](https://github.com/npgsql/efcore.pg/blob/1e0fabfea0132e1e7fe09811a4970a00d4f157be/src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs#L439) ([and here's the translation](https://github.com/npgsql/efcore.pg/blob/7fee80c8e96a2314ed62d011d1e3e20f17189728/src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRegexIsMatchTranslator.cs#L34)). In PG regex is a 1st-class operator instead of a function.

2020-09-12 19:37 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                return _sqlExpressionFactory.Function("regexp",
Personally, I like the operator ...lol, but only because it feels more pretentious. 😏

I'll let @scomert decide.

2020-09-12 19:38 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                return _sqlExpressionFactory.Function("regexp",
One non-subjective benefit is that it keeps the arguments in the same order as .NET

2020-09-12 19:42 UTC, bricelam commented
@roji The beauty here is that SQLite *doesn't* provide an implementation. (Well, outside of [an optional extension](https://github.com/sqlite/sqlite/blob/master/ext/misc/regexp.c) that the user would need to compile themselves.) The idea being that you just re-use your platform's regex so the app and the database have the same semantics.

2020-09-12 22:30 UTC, roji commented
Ah, I see - so this would end up calling back into .NET Regex.IsMatch then?

2020-09-12 23:34 UTC, bricelam commented
Yes, the database would call back into Regex.IsMatch

2020-09-13 19:14 UTC, bricelam requested changes

2020-09-13 19:14 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
> +                    });
add `isDeterministic: true` (looks like I missed it on `ef_mod` too)

2020-09-13 19:14 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +            if (method == regexIsMatchMethod)
We have to use the `Equals` method. I can't remember the exact bug, but I think one of the platforms (Mono?) can return different instances. Or maybe it was something to do with `ReflectedType` being different depending on how the expression gets traversed...

2020-09-13 19:16 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +            if (method == regexIsMatchMethod)
I have a vague memory about this no longer being relevant, but I don't remember the actual story. FWIW I compare MethodInfos in EFCore.PG with the operator all the time and haven't received complaints...

2020-09-13 19:22 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +            if (method == regexIsMatchMethod)
Oh I hope that's the case. @smitpatel?

2020-09-14 08:25 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +            if (method == regexIsMatchMethod)
Use `Equals`. I remember that we had bug and we changed specific `==` to `Equals` method. Unless we have someone from One.NET verifying that it will always be same and `==` is safe to use, I see very low value in changing this. Using `==` over `Equals` is just aesthetic.

2020-10-11 15:35 UTC, bricelam approved these changes

2020-10-11 15:35 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                    new[] { false, false },
Note to self: review these

2020-10-11 15:36 UTC, bricelam commented
Looks like we need to override the test in Cosmos too

2020-10-12 16:20 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +        private readonly static MethodInfo regexIsMatchMethod = typeof(Regex).GetMethod(nameof(Regex.IsMatch), new Type[] { typeof(string), typeof(string) });
Nit: static field declaration should be before private fields.

2020-10-12 16:20 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +
```suggestion
```

2020-10-12 16:20 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +        /// <summary>
```suggestion

        /// <summary>
```

2020-10-12 16:21 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +            _sqlExpressionFactory = sqlExpressionFactory;
```suggestion
            Check.NotNull(sqlExpressionFactory, nameof(sqlExpressionFactory));

            _sqlExpressionFactory = sqlExpressionFactory;
```

2020-10-12 16:23 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
> +                        return Regex.IsMatch(input, pattern);
@bricelam - Regex usage without timeouts makes me nervous!

2020-10-12 16:24 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                    new[] { false, false },
false are right.
Also given function is non-nullable, we will simplified function is null directly rather than decomposing into arguments. So values here wouldn't matter much.

2020-10-12 16:25 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
> +        public override Task Regex_IsMatch_MethodCall(bool async)
```suggestion

        public override Task Regex_IsMatch_MethodCall(bool async)
```

2020-10-12 17:00 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                    new[] { false, false },
(wanted to make sure the null handling was consistent with [the reference implementation](https://github.com/sqlite/sqlite/blob/master/ext/misc/regexp.c))

2020-10-30 04:15 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
> +                        return Regex.IsMatch(input, pattern);
It's a shame we don't have access to DbCommand.CommandTimeout here.

2020-10-30 04:37 UTC, bricelam commented
(Rebased, squashed, and cleaned it up a bit)

2020-10-30 04:39 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
> +                    new[] { false, false },
Updated the SQL function to propagate NULL like the official extensions.

2020-10-30 04:41 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
> +                        return Regex.IsMatch(input, pattern);
We can always add an overload that takes a timeout later.

2020-10-30 05:49 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexMethodTranslator.cs
> +                    arguments[0].TypeMapping);
This would be incorrect.
We need to infer type mapping from both args and apply to each other if one of them ends up being without type mapping.
And returning type mapping is bool type mapping (rather than string). Passing null should populate it automatically. Or you can explicitly from type mapping source.

2020-10-30 05:49 UTC, smitpatel commented on test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
> +                ss => ss.Set<Customer>().Where(o => Regex.IsMatch(o.CustomerID, @"^T")),
Random-ness but should also try version of the query where first arg is constant to verify proper type mapping assignment.

2020-10-30 20:54 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexMethodTranslator.cs
> +                    arguments[0].TypeMapping);
lol, I like how SQLite didn't even care. "You want to map bool to TEXT? Ok, whatever--it's all the same to me."

2020-10-30 21:15 UTC, smitpatel commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> +WHERE regexp(""c"".""CustomerID"", ""ALFKI"")");
Shouldn't ALFKI be printed like `'ALFKI'` ?

2020-10-30 21:15 UTC, smitpatel approved these changes

2020-10-30 21:25 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> +WHERE regexp(""c"".""CustomerID"", ""ALFKI"")");
Doh.

2020-10-30 22:00 UTC, merged