Exception message review
dotnet/efcore pull request #22519
Opened 2020-09-13 07:58 UTC by roji

Part of #7201

2020-09-14 08:31 UTC, smitpatel requested changes
Odd number of files :trollface:

2020-09-14 08:46 UTC, roji commented
The problem is me having to boot to Windows for VS to generate the file... That is just too much pain to handle in the same session as doing the review itself...

2020-09-14 16:07 UTC, smitpatel commented
As per @Pilchie's message in teams, can you retarget this to main?

2020-09-14 16:21 UTC, roji commented
Will do soon, and also resolve conflicts with your PR.

2020-10-17 07:25 UTC, roji commented
Rebased, is ready for review.

2020-10-17 20:01 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
> +    <value>Unable to generate a valid 'id' value to execute a ReadItem query. This usually happens when the value provided for one of the properties is null or an empty string. Please supply a value
```suggestion
    <value>Unable to generate a valid 'id' value to execute a 'ReadItem' query. This usually happens when the value provided for one of the properties is 'null' or an empty string. Please supply a value that's not 'null' or an empty string.</value>
```

2020-10-17 20:01 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
> +    <value>Unable to execute a ReadItem query since the partition key value is missing. Consider using the 'WithPartitionKey' method on the query to specify partition key to use.</value>
```suggestion
    <value>Unable to execute a 'ReadItem' query since the partition key value is missing. Consider using the 'WithPartitionKey' method on the query to specify partition key to use.</value>
```

2020-10-17 20:02 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
>      <value>Unable to execute a ReadItem query since the 'id' value is missing and cannot be generated.</value>
```suggestion
    <value>Unable to execute a 'ReadItem' query since the 'id' value is missing and cannot be generated.</value>
```

2020-10-17 20:07 UTC, AndriySvyryd commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>The provided DbFunction expression '{expression}' is invalid. The expression must be a lambda expression containing a single method call to the target static method. Default values can be
Why did you remove quotes?

2020-10-17 20:08 UTC, AndriySvyryd commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>The entity type '{entityType}' is mapped to the DbFunction named '{functionName}' with return type '{returnType}'. Ensure that the mapped function returns `IQueryable&lt;{clrType}&gt;`.</v
```suggestion
    <value>The entity type '{entityType}' is mapped to the DbFunction named '{functionName}' with return type '{returnType}'. Ensure that the mapped function returns 'IQueryable&lt;{clrType}&gt;'.</value>
```

2020-10-17 20:09 UTC, AndriySvyryd commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>'FindMapping' was called on a RelationalTypeMappingSource with a non-relational TypeMappingInfo.</value>
Missing quotes

2020-10-17 20:09 UTC, AndriySvyryd commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>Cannot create a SelectExpression with a custom TableExpressionBase since the result type '{entityType}' is part of a hierarchy and does not contain a discriminator property.</value>
Quotes

2020-10-17 20:11 UTC, AndriySvyryd approved these changes

2020-10-18 09:37 UTC, roji commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
> +    <value>Unable to generate a valid 'id' value to execute a ReadItem query. This usually happens when the value provided for one of the properties is null or an empty string. Please supply a value
We don't currently quote null in any messages (and there are many) - if we want to start doing that we should do it everywhere,no? (though I don't think we should)

2020-10-18 09:38 UTC, roji commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>The provided DbFunction expression '{expression}' is invalid. The expression must be a lambda expression containing a single method call to the target static method. Default values can be
Sorry, mistake - will revert.

2020-10-18 09:40 UTC, roji commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
> +    <value>Unable to generate a valid 'id' value to execute a ReadItem query. This usually happens when the value provided for one of the properties is null or an empty string. Please supply a value
FWIW we also don't quote e.g. numeric literals

2020-10-18 09:43 UTC, roji commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>'FindMapping' was called on a RelationalTypeMappingSource with a non-relational TypeMappingInfo.</value>
We seem to be inconsistent with quoting type names (as opposed to method names, which is what was discussed in #7201) - there are many unquoted instances. Should we always quote type names?

2020-10-18 09:43 UTC, roji commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>Cannot create a SelectExpression with a custom TableExpressionBase since the result type '{entityType}' is part of a hierarchy and does not contain a discriminator property.</value>
As above.

2020-10-18 18:44 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
> +    <value>Unable to generate a valid 'id' value to execute a ReadItem query. This usually happens when the value provided for one of the properties is null or an empty string. Please supply a value
We should quote it if it's used as a literal, if you were to use it as an adjective quotes wouldn't be necessary - "a null or empty string"

2020-10-18 18:45 UTC, AndriySvyryd commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>'FindMapping' was called on a RelationalTypeMappingSource with a non-relational TypeMappingInfo.</value>
Yes, we should

2020-10-19 22:59 UTC, roji commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
> +    <value>Unable to generate a valid 'id' value to execute a ReadItem query. This usually happens when the value provided for one of the properties is null or an empty string. Please supply a value
Added note to discuss null quoting in #7201

2020-10-19 23:00 UTC, roji commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +    <value>'FindMapping' was called on a RelationalTypeMappingSource with a non-relational TypeMappingInfo.</value>
Done here, also added TODO note in #7201

2020-10-20 02:29 UTC, AndriySvyryd commented
@smitpatel needs to approve to make the bot happy

2020-10-20 02:48 UTC, smitpatel commented
Or dismiss the review and avoid re-reviewing 😉

2020-10-20 02:48 UTC, smitpatel commented
@msftbot merge this PR after 1 min

2020-10-20 02:49 UTC, merged

2020-10-20 07:49 UTC, roji commented
> Or dismiss the review and avoid re-reviewing wink

The bot is more mysterious than I thought!