Microsoft.Data.Sqlite: Add Default Timeout connection string keyword
dotnet/efcore pull request #23091
Opened 2020-10-24 15:15 UTC by nmichels

- Fixes #22505

2020-10-24 16:53 UTC, bricelam requested changes
LGTM

2020-10-24 16:53 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
> +                    DefaultTimeout = ConnectionOptions.DefaultTimeout.Value;
I think that if the user sets SqliteConnection.DefaultTimeout, it should take precedence. Only fallback to the connection string value when it’s unset.

2020-10-24 16:55 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
> +                    DefaultTimeout = ConnectionOptions.DefaultTimeout.Value;
Also, do we ever use this value when the connection is closed? If so, we may need to read the value in the ConnectionString property setter.

2020-10-24 17:54 UTC, nmichels commented on src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
> +                    DefaultTimeout = ConnectionOptions.DefaultTimeout.Value;
Hi @bricelam 
By unset you mean different from the default value (30)? Or should we implement a private property and explicitly check wheter the DefaultTimeout has changed in it's setter?
I'm not sure, but I think that it doesn't make sense to use this property value when the connection is closed.
Thanks!

2020-10-24 18:23 UTC, nmichels commented on src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
> +                    DefaultTimeout = ConnectionOptions.DefaultTimeout.Value;
In fact, if we move this code snippet to the ConnectionString property setter we will have the desired precedence.

2020-12-08 19:57 UTC, bricelam approved these changes
I reworked this a bit while rebasing since the underlying code changed in PR #23549

2020-12-08 20:23 UTC, smitpatel approved these changes

2020-12-08 21:14 UTC, merged