Add EF.Functions.Random
dotnet/efcore pull request #23145
Opened 2020-10-30 09:27 UTC by RaymondHuy

Enhance https://github.com/dotnet/efcore/issues/16141

2020-11-09 23:33 UTC, bricelam requested changes
Looking good

2020-11-09 23:33 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRandomTranslator.cs
> +                            _sqlExpressionFactory.Constant(9223372036854775807.0))
Hmm, this value is lossy. I wonder if we should use `9223372036854780000.0` instead to avoid strange bugs in the future.

2020-11-09 23:33 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
> +WHERE ef_compare(abs(random() / '9223372036854780000.0'), '1.0') < 0");
```suggestion
                @"SELECT COUNT(*)
FROM ""Orders"" AS ""o""
WHERE abs(random() / 9.22337203685478E+18) < 1.0");
```

2020-11-09 23:33 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
> +                ss => EF.Functions.Random() < 1,
There's actually a 0.000000000000006% chance that this will be 1.0 on SQLite.

2020-11-09 23:33 UTC, bricelam commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindDbFunctionsQueryCosmosTest.cs
> +                c => true);
We should add these to NorthwindDbFunctionsQueryTestBase (and override in provider-specific tests to assert the SQL)

2020-11-09 23:33 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
> +WHERE ef_compare(abs(random() / '9223372036854780000.0'), '1.0') < 0");
Note, this will be the SQL if we change it to `double`.

2020-11-09 23:38 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
> +                ss => EF.Functions.Random() < 1,
When we move the tests (see comment below), we should **not** call `base` and instead just use `<=` in the test to avoid that one random CI failure over the next decade.

2020-11-09 23:45 UTC, bricelam commented on src/EFCore.SqlServer/Query/Internal/SqlServerRandomTranslator.cs
> +                    method.ReturnType)
I wonder if this should just be the base Relational implementation. Thoughts, @maumar, @roji & @smitpatel?

2020-11-09 23:45 UTC, bricelam commented on src/EFCore.SqlServer/Query/Internal/SqlServerRandomTranslator.cs
> +                    method.ReturnType)
Provider | SQL
--- | ---
SQL Server | RAND()
SQLite | abs(random() / 9223372036854775807.0)
PostgreSQL | random()
MySQL | RAND()
Oracle | DBMS_RANDOM.VALUE
DB2 | RAND()
Firebird | RAND()

2020-11-09 23:51 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerRandomTranslator.cs
> +                    method.ReturnType)
Being 😈 

We can put in relational, if provider implements it differently then provider behavior will win. Though side-effects are, if providers don't implement it then they will get invalid SQL error rather than our nice client eval failure. Looking at the table above, there are 3 database which needs to override relational behavior and 2 of them are known to be in sync and will override it. So we may be increasing values for some providers' customers and decreasing for some others.

2020-11-10 06:45 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerRandomTranslator.cs
> +                    method.ReturnType)
I say let's just leave it for providers to implement... There's just not that much value in putting this in relational...

2020-11-10 17:25 UTC, RaymondHuy commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindDbFunctionsQueryCosmosTest.cs
> +                c => true);
Hi @bricelam I see in `NorthwindDbFunctionsQueryTestBase `class contains some testcases that can't be translated in Cosmos. I've already added them to `NorthwindDbFunctionsQueryTestBase `but I only let the `NorthwindDbFunctionsQuerySqliteTest `and `NorthwindDbFunctionsQuerySqlServerTest `override them, for `NorthwindDbFunctionsQueryCosmosTest `I keep it separate, it it ok ?

2020-11-10 18:10 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
> +                    new SqlServerRandomTranslator(sqlExpressionFactory)
Alphabetical order

2020-11-10 18:12 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteRandomTranslator.cs
> +                                method.ReturnType),
Can we add comment here with link to https://github.com/dotnet/efcore/issues/15586
Little abuse for now is fine.

2020-11-10 20:03 UTC, bricelam commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindDbFunctionsQueryCosmosTest.cs
> +                c => true);
Typically, we add `[ConditionalTheory(Skip = "Issue ######")]` if we think the test should eventually pass or just override with something like this if we don't ever expect it to pass:

```
AssertTranslationFailed(() => base.The_base_test(async));
```

2020-11-11 15:25 UTC, RaymondHuy commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindDbFunctionsQueryCosmosTest.cs
> +                c => true);
Thanks for your comments @bricelam  @smitpatel , I've just updated my PR.

2020-11-11 18:26 UTC, bricelam commented on src/EFCore/DbFunctionsExtensions.cs
> +        public static decimal Random([CanBeNull] this DbFunctions _)
Discussed as a team; we'd like to change this to `double`.

2020-11-11 18:27 UTC, bricelam commented on src/EFCore.SqlServer/Query/Internal/SqlServerRandomTranslator.cs
> +                    method.ReturnType)
Discussed as a team; we'd like to provide a default Relational implementation that translates to RAND()

2020-11-11 18:35 UTC, bricelam approved these changes
LGTM. Are you interested in providing a base Relational implementation?

@smitpatel What's the best way to "override" the base implementation in SQLite?

2020-11-11 18:37 UTC, bricelam commented
> if provider implements it differently then provider behavior will win

Does that mean they can just add a new provider-specific method translator and it will win?

2020-11-11 18:38 UTC, smitpatel commented
> Does that mean they can just add a new provider-specific method translator and it will win?

Yes. The ordering is
- User defined functions
- Plugins
- Provider translations
- Relational translations

2020-11-12 13:50 UTC, RaymondHuy commented on src/EFCore.SqlServer/Query/Internal/SqlServerRandomTranslator.cs
> +                    method.ReturnType)
Thanks @bricelam  @smitpatel  I've just added the default Relational implementation.

2020-11-30 18:33 UTC, smitpatel commented on src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
> +                return Expression.Constant(new Random().NextDouble());
We should integrate the call to server side rather than a constant. With a constant basically running the same query again and again will use the same value for the random function which is different for other databases.

2020-12-02 11:30 UTC, RaymondHuy commented on src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
> +                return Expression.Constant(new Random().NextDouble());
Thanks @smitpatel  I've just updated my PR

2020-12-22 01:08 UTC, RaymondHuy commented
Hi @smitpatel  @bricelam  Are there anything else I need to change so that this PR can be merged ?

2020-12-22 02:49 UTC, smitpatel commented
@RaymondHuy - I will process this PR and merge it to master in a day or two. I don't believe we need anymore changes here. Thank for you contribution.

2020-12-22 21:44 UTC, smitpatel approved these changes

2020-12-22 22:21 UTC, merged