Add EF.Functions.IsNumeric
dotnet/efcore pull request #23232
Opened 2020-11-07 15:53 UTC by RaymondHuy

Enhance https://github.com/dotnet/efcore/issues/23114

2020-11-09 23:59 UTC, bricelam requested changes

2020-11-09 23:59 UTC, bricelam commented on src/EFCore.SqlServer/Query/Internal/SqlServerIsNumericFunctionTranslator.cs
> +                        argumentsPropagateNullability: new[] { true },
```suggestion
                        nullable: false,
                        argumentsPropagateNullability: new[] { false },
```

2020-11-09 23:59 UTC, bricelam commented on src/EFCore.SqlServer/Query/Internal/SqlServerIsNumericFunctionTranslator.cs
> +                        argumentsPropagateNullability: new[] { true },
`ISNUMERIC(NULL)` returns 0, not NULL

2020-11-09 23:59 UTC, bricelam commented on src/EFCore.SqlServer/Query/Internal/SqlServerIsNumericFunctionTranslator.cs
> +                ? _sqlExpressionFactory.Convert(
Why `Convert`? AFAICT, it's not needed.

2020-11-13 17:42 UTC, RaymondHuy commented on src/EFCore.SqlServer/Query/Internal/SqlServerIsNumericFunctionTranslator.cs
> +                ? _sqlExpressionFactory.Convert(
Thanks @bricelam  I've just updated my PR.

2020-11-30 22:13 UTC, bricelam approved these changes

2020-11-30 22:41 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
> +                    new SqlServerStringMethodTranslator(sqlExpressionFactory),
A-B-C

2020-11-30 22:42 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerIsNumericFunctionTranslator.cs
> +        private static readonly MethodInfo _methodInfo = typeof(SqlServerDbFunctionsExtensions)
Was just wondering why this did not error out for nullable.

2020-12-02 06:19 UTC, RaymondHuy commented on src/EFCore.SqlServer/Query/Internal/SqlServerIsNumericFunctionTranslator.cs
> +        private static readonly MethodInfo _methodInfo = typeof(SqlServerDbFunctionsExtensions)
Thanks @smitpatel  I've just updated my PR.

2020-12-22 01:09 UTC, RaymondHuy commented
Hi @smitpatel  @bricelam  Are there anything else I need to change so that this PR can be merged ?

2020-12-22 02:49 UTC, smitpatel commented
@RaymondHuy - I will process this PR and merge it to master in a day or two. I don't believe we need anymore changes here. Thank for you contribution.

2020-12-22 19:17 UTC, merged