Fix to #19994 - Query/Test: figure out how to represent shadow properties in expected result queries
dotnet/efcore pull request #23579
Opened 2020-12-04 02:52 UTC by maumar

Building the mapping when we generate the expected data, so we also have access to navigations and entities for shadow navigations in the future.
Discriminators are added at the test class level since we use same expected data setup for TPH and TPT.

Fixes #19994

2020-12-08 21:30 UTC, smitpatel requested changes
Please unique-fy the whole thing with expected query rewriter and shadow mappings.
Right now shadow mappings are on expected data which you are copying over to test base duplicating it.

Ideally the shadow property mapping should be on fixture base since that determines the model fixture is using. We could just apply shadow property mapping rewriter always and autoamatically without testbase asking for it.

2020-12-10 15:39 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalFixture.cs
> +        public override Dictionary<(Type, string), Func<object, object>> GetShadowPropertyMappings()
This is fine.

2020-12-10 15:40 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalFixture.cs
> +        public override Dictionary<(Type, string), Func<object, object>> GetShadowPropertyMappings()
Also a TPT test wouldn't be accessing discriminator anyway (if it does then efquery will fail) so we may not even need to clear this.

2020-12-10 15:41 UTC, smitpatel commented on test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryTestBase.cs
> +        public override Task Project_shadow_properties(bool async)
why? 🤔

2020-12-10 15:42 UTC, smitpatel commented on test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
> +                    e => GetExpectedData().Set<Gear>().ToList().SingleOrDefault(g => g.Nickname == ((Gear)e)?.Nickname)?.AssignedCity?.Name
Do we need ToList in the middle?

2020-12-10 15:43 UTC, smitpatel commented on test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
> +            //ShadowPropertyMappings = CreateShadowPropertyMappings(Gears);
remove

2020-12-10 15:43 UTC, smitpatel commented on test/EFCore.Specification.Tests/TestUtilities/ExpectedQueryRewritingVisitor.cs
> +        ///// <summary>
remove

2020-12-10 15:44 UTC, smitpatel commented on test/EFCore.Specification.Tests/TestUtilities/ExpectedQueryRewritingVisitor.cs
> +                        var methodInfo = typeof(ExpectedQueryRewritingVisitor).GetMethod(nameof(GetShadowPropertyValue))
store the method in static field. construct generic method using that MethodInfo like how we do in all places in query.

2020-12-10 15:44 UTC, smitpatel commented on test/EFCore.Specification.Tests/TestUtilities/ExpectedQueryRewritingVisitor.cs
> +
remove empty line between if and else block.

2020-12-15 10:27 UTC, maumar commented on test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
> +                    e => GetExpectedData().Set<Gear>().ToList().SingleOrDefault(g => g.Nickname == ((Gear)e)?.Nickname)?.AssignedCity?.Name
can't do ?. in the Expression<Func<>>

2020-12-15 10:33 UTC, maumar commented on test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryTestBase.cs
> +        public override Task Project_shadow_properties(bool async)
¯\_(ツ)_/¯

2020-12-15 11:25 UTC, maumar commented on test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryTestBase.cs
> +        public override Task Project_shadow_properties(bool async)
no shadow props in the owned model

2020-12-15 17:17 UTC, smitpatel commented on test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
> +                    e => GetExpectedData().Set<Gear>().ToList().SingleOrDefault(g => g.Nickname == ((Gear)e)?.Nickname)?.AssignedCity?.Name
AsQueryable()?

2020-12-16 22:42 UTC, maumar commented on test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
> +                    e => GetExpectedData().Set<Gear>().ToList().SingleOrDefault(g => g.Nickname == ((Gear)e)?.Nickname)?.AssignedCity?.Name
thats still Expression<Func<>>, but can do AsEnumerable instead of ToList, so at least it's delayed a bit

2020-12-16 22:47 UTC, smitpatel commented on test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
> +                    e => GetExpectedData().Set<Gear>().ToList().SingleOrDefault(g => g.Nickname == ((Gear)e)?.Nickname)?.AssignedCity?.Name
Ah, now I get it. You want to use ?. which does not work in tree building but works in enumerable world. Yes. AsEnumerable is way to go.

2020-12-16 22:57 UTC, maumar commented
updated

2020-12-16 23:05 UTC, smitpatel approved these changes

2020-12-17 00:12 UTC, merged