Update branding to 3.1.12
dotnet/efcore pull request #23861
Opened 2021-01-12 20:54 UTC by wtgodbe

Also update SDK

2021-01-12 21:08 UTC, wtgodbe commented
nonshipping packages are still in the process of being uploaded to the transport feed, will re-run when that's done

2021-01-12 22:08 UTC, JunTaoLuo approved these changes
When CI passes.

2021-01-12 22:44 UTC, dougbu requested changes

2021-01-12 22:44 UTC, dougbu commented on NuGet.config
> +    <add key="darc-int-dotnet-extensions-77d62c5" value="true" />
nit: Why disable so many extensions feeds❔

2021-01-12 22:44 UTC, dougbu commented on eng/common/SetupNugetSources.ps1
> +        $DisabledPackageSources.RemoveChild($DisabledPackageSource)
Why are Arcade-owned files being updated❔ There's no Arcade-related changes elsewhere in this PR.

2021-01-12 22:45 UTC, wtgodbe commented on NuGet.config
> +    <add key="darc-int-dotnet-extensions-77d62c5" value="true" />
That's a darc quirk, I'm not sure what causes it - @mmitche?

2021-01-12 22:46 UTC, wtgodbe commented on eng/common/SetupNugetSources.ps1
> +        $DisabledPackageSources.RemoveChild($DisabledPackageSource)
We found this issue during the build of 3.1.11. We had to change the way that nuget.configs are handled with regards to `disabledPackageSources`. The change has since been made in Arcade.

2021-01-12 22:46 UTC, wtgodbe commented on eng/common/SetupNugetSources.ps1
> +        $DisabledPackageSources.RemoveChild($DisabledPackageSource)
We did it directly in the repo's `eng/common` files because we didn't have time to get an arcade update to fix the issue

2021-01-13 06:24 UTC, wtgodbe commented
/azp run

2021-01-13 17:14 UTC, merged