Allow providers to override HandleAmbientTransactions
dotnet/efcore pull request #24209
Opened 2021-02-21 10:31 UTC by roji

Accessing `Transaction.Current` (in HandleAmbientTransactions) is a heavy operation - profiling shows it to take around 0.3% of the total running time.

Npgsql has connection string parameter to disable this check at the ADO level. Allowing providers to override HandleAmbientTransactions would allow EFCore.PG to skip this if the parameter is set.

HandleAmbientTransactions isn't a great name for a publicly-exposed method, but I don't really have anything better...

2021-02-24 01:12 UTC, AndriySvyryd requested changes
It would be better to just wrap `Transaction.Current` and expose it on `ITransactionEnlistmentManager`, this way all places using it would benefit.

2021-02-25 09:25 UTC, roji commented
Good point for doing it for other places (e.g. BatchExecutor).

Though the intent here was to also allow skipping the _ambientTransactions checks that come after (Count, TryPeek), i.e. to skip HandleAmbientTransactions altogether (even if perf-wise it's probably not very significant). Should we do both? Am OK to also only do Transaction.Current.

2021-02-25 09:26 UTC, roji commented on src/EFCore.Relational/Update/Internal/BatchExecutor.cs
> +                        && transactionEnlistManager?.CurrentAmbientTransaction is null
Note slight behavior change where the connection doesn't implement ITransactionEnlistmentManager but Transaction.Current is non-null. New behavior seems more correct.

2021-02-25 15:22 UTC, AndriySvyryd commented
> Though the intent here was to also allow skipping the _ambientTransactions checks that come after (Count, TryPeek), i.e. to skip HandleAmbientTransactions altogether (even if perf-wise it's probably not very significant). Should we do both? Am OK to also only do Transaction.Current.

If we expose `HandleAmbientTransactions` then we would also need to expose `_ambientTransactions` in some way in case the provider wants to do something else than skipping. I'd prefer to defer this for now until there's a another use case for this.

2021-02-25 15:29 UTC, AndriySvyryd approved these changes

2021-02-25 15:41 UTC, roji commented
Makes sense, changed HandleAmbientTransactions back to private.

2021-02-25 16:27 UTC, merged