Annotate ChangeTracking for nullability
dotnet/efcore pull request #24261
Opened 2021-02-24 19:55 UTC by smitpatel

Part of #19007

2021-02-24 20:48 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/CurrentProviderValueComparer`.cs
> +                _converter(x.GetCurrentValue<TModel>(_property)!),
This is currently banged. GetCurrentValue can return null values which goes through some "converter".

2021-02-24 20:50 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/IInternalEntityEntryFactory.cs
> +            [NotNull] object entity);
@ajcvickers - Can this be really nullable?

2021-02-24 20:59 UTC, smitpatel commented on src/EFCore/ChangeTracking/ObservableHashSet.cs
> +            OnCollectionChanged(NotifyCollectionChangedAction.Remove, item!);
@roji - This feels like a bug in code analysis.

Also occurrence below.

2021-02-24 21:33 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/StateManager.cs
> +                && !entityType.IsAssignableFrom(entry!.EntityType))
@roji - TryGet above has annotation that true means entry is non-null still hitting error here.

2021-02-24 21:39 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/SimpleNullableDependentKeyValueFactory.cs
> +            => HandleNullableValue(((Func<IUpdateEntry, TKey?>)_propertyAccessors.OriginalValueGetter!)(entry), out key);
@roji - Are these TryGet correct given TKey is struct?

2021-02-25 08:02 UTC, roji requested changes

2021-02-25 17:49 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/StateManager.cs
> +                && !entityType.IsAssignableFrom(entry!.EntityType))
Yes, but shouldn't compiler remember the information of the variable too? Rather than relying on block structure? I will update code for now.

2021-02-25 17:50 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/SimpleNullableDependentKeyValueFactory.cs
> +            => HandleNullableValue(((Func<IUpdateEntry, TKey?>)_propertyAccessors.OriginalValueGetter!)(entry), out key);
TKey can be null when returning false. Only in case of where TKey is a struct constraint compiler is not allowing TKey?

2021-02-25 17:51 UTC, smitpatel commented on src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
> +        [CA.MemberNotNull("SourceEntry")]
This is via ctor only. If SourceEntry is passed in non-null then InboundNavigation is also non-null.

2021-02-25 17:52 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
> +                        _unchangedReferenceMap?.Remove(entity);
Given that one case did it and other didn't, seems like.

2021-02-25 17:55 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
What is overall guidance on ReadValues? `ReadValue` kind function can return null value if the value of the property was indeed null. Are user supposed to pass `ReadShadowValue<string?>` if their property is nullable and there can be null?

2021-02-25 17:56 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntryNotifier.cs
> +            [CanBeNull] ILocalViewListener? localViewListener,
@ajcvickers

2021-02-25 17:56 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
> +                    // TODO-Nullable: This whole code path is null unsafe. We are passing null parameter but later using parameter
May be never hitting the code path.

2021-02-25 17:57 UTC, smitpatel commented on src/EFCore/ChangeTracking/PropertyValues.cs
> +        public virtual bool TryGetValue<TValue>([NotNull] string propertyName, out TValue? value)
But the value can be null even when true

2021-02-25 18:04 UTC, roji commented on src/EFCore/ChangeTracking/Internal/StateManager.cs
> +                && !entityType.IsAssignableFrom(entry!.EntityType))
It should or at least could :)

2021-02-25 18:13 UTC, roji commented on src/EFCore/ChangeTracking/Internal/SimpleNullableDependentKeyValueFactory.cs
> +            => HandleNullableValue(((Func<IUpdateEntry, TKey?>)_propertyAccessors.OriginalValueGetter!)(entry), out key);
Oh, I see now - for me it allows `TKey?` in the signature but then complains that the function doesn't implement the interface method - most probably because the interface method has no constraints on TKey but here we do. Minimal repro:

```c#
interface IMyInterface<T>
{
    void Foo(T value);
}

class MyClass2<T> : IMyInterface<T> where T : struct
{
    public void Foo(T? value) => throw new NotImplementedException();
}
```

Note that for the class constraint it works fine. 

This looks like a language limitation, we should report it. Do you want to file an issue or should I?

2021-02-25 18:16 UTC, roji commented on src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
> +        [CA.MemberNotNull("SourceEntry")]
But what this attribute is saying, is that "after InboundNavigation is invoked (regardless of return type or anything), SourceEntry isn't null" (in fact I'm a bit surprised it's possible to put this on a property as opposed to a method). I don't think there's a way to currently say "if this property is non-null, that property is also non-null". There's [MemberNotNullWhen] which is very close, but it's only for boolean-returning methods, so not usable with null.

2021-02-25 18:20 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/SimpleNullableDependentKeyValueFactory.cs
> +            => HandleNullableValue(((Func<IUpdateEntry, TKey?>)_propertyAccessors.OriginalValueGetter!)(entry), out key);
I will let you do the honors.

2021-02-25 18:21 UTC, smitpatel commented on src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
> +        [CA.MemberNotNull("SourceEntry")]
But this attribute let me mark SourceEntry as non-null whenever I checked for InboundNavigation non-null.

2021-02-25 18:24 UTC, roji commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
Basically, the question is if we want to force the user of ReadShadowValue to *always* check for null, or to be able to say that if a null is returned it's a bug. Which is the right thing depends on how we use InternalEntityEntry, but consider that the user can already specify a totally incorrect type (int instead of string), and that's a bug; the nullable/non-nullable case is similar.

Another way of looking at it is that by using `ReadShadowValue<string>`, the user is saying ("asserting") they don't expect to have a null returned - not unlike putting a bang.

2021-02-25 18:27 UTC, roji commented on src/EFCore/ChangeTracking/PropertyValues.cs
> +        public virtual bool TryGetValue<TValue>([NotNull] string propertyName, out TValue? value)
It's the same logic as with GetValue above (or with ReadShadowValue), i.e. whether the user calls `TryGetValue<string>` or TryGetValue<string?>`. We should make a global decision on that and apply everywhere.

2021-02-25 18:34 UTC, smitpatel commented on src/EFCore/ChangeTracking/ChangeTracker.cs
> +                    n.NodeState!(n);
I looked at this function. Basically state can be nullable. For this particular invocation we are passing callback as state which is non-null so in resulting graph nodes states are non-nullable but there is no way to encapsulate that.

2021-02-25 18:34 UTC, smitpatel commented on src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
> +        [CA.MemberNotNull("SourceEntry")]
Since this is getter only, I think it is ok work-around, till compiler may add something to denote this relationships.

2021-02-25 18:36 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs
> +        public virtual object? CreateFromKeyValues(object?[] keyValues)
How does this violate? It returns first key property (since there is only 1 property).
If the key object is non-null then it is returned. And if any (and in this case only 1) key value is null then null is returned.

2021-02-25 18:38 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/ISnapshot.cs
> +        T? GetValue<T>(int index);
Implementation in Snapshot.cs missed my regex. Those should be updated to T?.
(pending discussion of what should be return value of GetValue<T>

2021-02-25 18:39 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/Snapshot.cs
> +            return types.Length switch
Did you use bang after "expression-bodied"?

2021-02-25 19:23 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
null/nullable looks somewhat different use case from invalid type to me.
This code path can very well return null values in valid cases and we don't have null assertion around it. So current consumer of this APIs are already checking for null if they want the value to be non-null.
If we start adding assertion then people have to call with specific "nullable" type if they are expecting null value, which would require code change on their end. Further it is tiny ? so easy to miss out. Does adding the "assertion" here worth the breaking change for the value it provides?

cc: @dotnet/efteam

2021-02-25 19:27 UTC, ajcvickers commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
As originally designed, the T here is intended to exactly match the property type. For value types that always meant using a nullable type if the property was a nullable type. My feeling is that this probably doesn't change. That is, I think it's fine if the type nullability must that in the model for both value and reference types.

2021-02-25 19:28 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
Also, my random guess also says that, if there is non-null property which ends up with null value here, then we would throw error earlier when the value was ingested by ChangeTracker. Just a random guess.

2021-02-25 19:32 UTC, roji commented on src/EFCore/ChangeTracking/Internal/SimpleNullableDependentKeyValueFactory.cs
> +            => HandleNullableValue(((Func<IUpdateEntry, TKey?>)_propertyAccessors.OriginalValueGetter!)(entry), out key);
https://github.com/dotnet/roslyn/issues/51490, let's see what comes out of there...

2021-02-25 19:34 UTC, roji commented on src/EFCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs
> +        public virtual object? CreateFromKeyValues(object?[] keyValues)
Ah, I missed the fact that this is for single-value keys only.

2021-02-25 19:38 UTC, roji commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
> As originally designed, the T here is intended to exactly match the property type. For value types that always meant using a nullable type if the property was a nullable type.

Yeah, the fact that it was already "annotated" this way for value types is also a good argument.

I can see both sides here, and I don't know enough about how this is used in our codebase. If we want callers to always consider possible nulls, then adding the question mark is a good idea; otherwise it probably isn't.

2021-02-25 19:39 UTC, roji commented on src/EFCore/ChangeTracking/Internal/Snapshot.cs
> +            return types.Length switch
I did :)

2021-02-25 19:44 UTC, ajcvickers commented on src/EFCore/ChangeTracking/Internal/IInternalEntityEntryFactory.cs
> +            [NotNull] object entity);
Not now we don't have shadow entity types. :-)

2021-02-25 19:44 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
My main worry is break only. For value types I assume with/without ? nothing would change. But for reference type, users would need to start adding ? where they did not need to before to get back the same behavior. Breaking this makes is consistent and easy to explain but can still break. Also I don't know how much customers are using this kind of API directly. (There are some given people do deal with entity entries)

@AndriySvyryd - thoughts?

2021-02-25 19:48 UTC, roji commented on src/EFCore/ChangeTracking/Internal/SimpleNullableDependentKeyValueFactory.cs
> +            => HandleNullableValue(((Func<IUpdateEntry, TKey?>)_propertyAccessors.OriginalValueGetter!)(entry), out key);
Right, I keep forgetting [this part](https://github.com/dotnet/roslyn/issues/51490#issuecomment-786151093): T? in the interface on an unconstrained type parameter means allowed to be default not allowed to be null. This is because for value types, `int` and `int?` are different CLR types, while for reference types they aren't.

@smitpatel should this method actually be returning `Nullable<TKey>` (it wasn't doing that before)?

2021-02-25 19:49 UTC, ajcvickers commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
Customers don't use this directly, but they do use the EntityEntry/PropertyEntry APIs that call into here to avoid boxing when accessing property values. In those cases the T will often (but not always) be inferred from the property selector lambda in the API. There are non-generic APIs for all this that are not strict about type checking and return an object, so these could always be used as a workaround if people are trying to get nulls back inappropriately.

If people are using NRTs, then it seems reasonable to me that they use the correct T here. However, it would be bad if we broke anyone who isn't using NRTs.

Also interested to hear @AndriySvyryd's thoughts.

2021-02-25 19:50 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/SimpleNullableDependentKeyValueFactory.cs
> +            => HandleNullableValue(((Func<IUpdateEntry, TKey?>)_propertyAccessors.OriginalValueGetter!)(entry), out key);
That was quick death.

2021-02-25 19:51 UTC, roji commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
Unless I'm mistaken, before this change we're actually already returning T as you mentioned above - so changing to T? would be a breaking change if done publicly.

2021-02-25 19:59 UTC, ajcvickers commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntryNotifier.cs
> +            [CanBeNull] ILocalViewListener? localViewListener,
I looks to me like these should all be non-nullable.

2021-02-25 20:01 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
Binary break - may be.
Functional break no. We were returning null when T=string before. Now we will return nullable string as before too.
For T where it is struct, I don't know how to specify constraints.

2021-02-25 20:21 UTC, AndriySvyryd commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
I think this should return `T`, this isn't exposed publicly, so it's not an API breaking change.
For users not using NRT this should have no effect.
For users using NRT and having nulls in a non-nullable property something else would throw anyway, either query or SaveChanges.

2021-02-25 20:41 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
I will update APIs in internal namespace.
Does this apply to public API also on EntityEntry or similar (if there is any)?

2021-02-25 21:13 UTC, AndriySvyryd commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
I'd say yes for CurrentValue, however it's normal for OriginalValue to be `null` for required properties when working with disconnected entities.

2021-02-25 21:51 UTC, ajcvickers commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
@AndriySvyryd At least for value types, I don't believe an original value can ever be null if the type is not nullable. If original values are not set, then the current value is returned.

2021-02-25 21:52 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +            return navigationBase.GetCollectionAccessor()!.Remove(Entity, value.Entity);
Any comments on this @AndriySvyryd - or should merge with bangs for now?

2021-02-25 22:01 UTC, roji commented on src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
> +        [CA.MemberNotNull("SourceEntry")]
> But this attribute let me mark SourceEntry as non-null whenever I checked for InboundNavigation non-null.

Are you sure the compiler treats SourceEntry as non-null only after InboundNavigation has been confirmed to be non-null? Because the way I understand this attribute, any access to InboundNavigation will mean that SourceEntry is now considered non-nullable - I don't think that's what you're looking for.

2021-02-25 22:30 UTC, AndriySvyryd commented on src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
> +        protected virtual T? ReadShadowValue<T>(int shadowIndex)
Ok, then let's drop the `?` on all these members and enable NRT on (some) tests to verify.

2021-02-25 23:17 UTC, smitpatel commented on src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
> +        [CA.MemberNotNull("SourceEntry")]
If you think it is wrong, I will remove it.

2021-02-25 23:46 UTC, ajcvickers commented on src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
> +                    // TODO-Nullable: This whole code path is null unsafe. We are passing null parameter but later using parameter
@smitpatel The `parameter` parameter of `CreateSnapshotExpression` should allow nulls. Not all overloads use the parameter.

2021-02-26 09:21 UTC, roji commented on src/EFCore/ChangeTracking/Internal/RelationshipsSnapshot.cs
> +                    propertyBase is not INavigation navigation || !navigation.IsCollection,
nit: pattern matching FTW:

```suggestion
                    propertyBase is not INavigation { IsCollection: true },
```

2021-02-26 09:21 UTC, roji commented on src/EFCore/ChangeTracking/Internal/RelationshipsSnapshot.cs
> +                    ((HashSet<object>)_values[index]!)?.Remove(removedEntity);
If you want the runtime check, remove the bang; if we know it should never be null, remove the question mark.

2021-02-26 09:21 UTC, roji commented on src/EFCore/ChangeTracking/Internal/RelationshipsSnapshot.cs
> +                var snapshot = (HashSet<object>)_values[index]!;
Seems like you can remove the bang. Actually isn't the whole function replaceable by a `??=`?

2021-02-26 09:21 UTC, roji commented on src/EFCore/ChangeTracking/Internal/SidecarValues.cs
> +                => IsEmpty ? default! : _values.GetValue<T>(index);
This could be a case where it's more correct to return `T?`, since there's an additional Empty state. Is the user expected to know before calling this whether it's empty or not? If not, we probably want to force them to deal with the Empty state.

2021-02-26 09:21 UTC, roji commented on src/EFCore/ChangeTracking/PropertyEntry`.cs
> +        public new virtual TProperty? OriginalValue
Left intentionally? CurrentValue doesn't it it.

2021-02-26 09:21 UTC, roji commented on src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
> +        [CA.MemberNotNull("SourceEntry")]
I think so. Here's a minimal repro:

```c#
Console.WriteLine(foo.InboundNavigation);
Console.WriteLine(foo.SourceEntry.Length); // no warning

class Foo
{
    public string? SourceEntry { get; }

    [MemberNotNull("SourceEntry")]
    public string? InboundNavigation { get; }
}
```

The second WriteLine has no null warning, although we haven't done anything to check it. Just the fact that we accessed the InboundNavigation (without checking if it's null or not!) is enough to turn it off, which doesn't seem right.

2021-02-26 09:26 UTC, roji commented on src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
> +                    // TODO-Nullable: This whole code path is null unsafe. We are passing null parameter but later using parameter
@smitpatel do you want to do this?

2021-02-26 09:27 UTC, roji commented on src/EFCore/ChangeTracking/PropertyValues.cs
> +        public virtual bool TryGetValue<TValue>([NotNull] string propertyName, out TValue? value)
I think this is still left, since we made the decision to have GetValue return TValue and not TValue?.

2021-02-26 09:28 UTC, roji approved these changes
Looks almost perfect, see comments below.

2021-02-26 09:28 UTC, merged

2021-02-26 09:43 UTC, roji commented
May bad, forgot to remove auto-merge, sorry.

2021-02-26 16:36 UTC, smitpatel commented on src/EFCore/ChangeTracking/PropertyEntry`.cs
> +        public new virtual TProperty? OriginalValue
Missed

2021-02-26 16:39 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/SidecarValues.cs
> +                => IsEmpty ? default! : _values.GetValue<T>(index);
The way whole T of GetValue flows, this shouldn't be invoked with non-null type if it can be empty. It is same as we returning T from other places, if you ask for wrong nullability it will throw exception. `default!` throws exception for us. @ajcvickers - Thoughts?

2021-02-26 17:36 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/CompositePrincipalKeyValueFactory.cs
> +                    return default!;
Long chain.
So basically this implements PrincipalKeyValueFactory<object[]> hence type becomes non-nullable. The reason for T = object[] because it is used as dependents map which uses dict underneath which cannot use nullable type as key. So while it is default! it shouldn't hit the code path here.