Documented InvalidOperationException for QueryableExtensions methods
dotnet/efcore pull request #24323
Opened 2021-03-04 23:27 UTC by Marusyk

Added InvalidOperationException to xml docs for:

- LastOrDefaultAsync
- AverageAsync
- MinAsync

Fixes #24307

2021-03-05 11:00 UTC, roji requested changes
LastOrDefaultAsync doesn't throw InvalidOperationException when the source is empty - it returns default.

2021-03-06 23:28 UTC, maumar submitted a review, later dismissed

2021-03-08 17:08 UTC, smitpatel commented on src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
> +        /// <exception cref="InvalidOperationException"> <paramref name="source" /> contains no elements. </exception>
This is incorrect. There is no exception thrown when sequence contains no elements if the result type is nullable.

2021-03-13 12:58 UTC, roji approved these changes
Thanks.

2021-03-13 12:58 UTC, merged