Add CommandSource to CommandEventData
dotnet/efcore pull request #24421
Opened 2021-03-16 21:42 UTC by Giorgi

This PR is my attempt to implement #23719

If the approach looks good I can fix the failing tests and add new ones for this feature.

2021-03-17 11:24 UTC, roji commented
I think some sort of tag mechanism for updates (#14078) would probably be more appropriate... This approach tells you that the command is coming e.g. from SaveChanges, but you still have no idea what is being changed and how. That seems to provide limited usefulness to interceptors and the like.

2021-03-17 14:40 UTC, Giorgi commented
Tags for `SaveChanges` sounds useful but I think these are two different use cases. The scenario that I had in mind is that if you run a batch update with `ExecuteSqlRaw` it might be useful to differentiate between that and `SaveChanges`

2021-03-17 17:46 UTC, roji commented
> Tags for SaveChanges sounds useful but I think these are two different use cases. The scenario that I had in mind is that if you run a batch update with ExecuteSqlRaw it might be useful to differentiate between that and SaveChanges

Wouldn't SaveChanges (and raw SQL) tags fulfill the same need? Also, assuming your application has many different things being executed by both SaveChanges and ExecuteSqlRaw, how useful is it to just know that something is SaveChanges or ExecuteSqlRaw?

2021-03-17 18:20 UTC, Giorgi commented
I guess it would if you are writing the queries and the interceptors but if you are writing an interceptor for others to use you probably can't rely on tags being present.

2021-03-17 18:25 UTC, roji commented
I guess it's hard for me to imagine a generic interceptor (written for others) which cares specifically about whether a command comes from SaveChanges or ExecuteSqlRaw... Do you have any example in mind?

2021-03-17 18:54 UTC, Giorgi commented
I wanted to process exceptions caused by ExecuteSqlRaw but IDbCommandInterceptor fires for both ExecuteSqlRaw and SaveChanges so I needed a way to find which one caused the interception to fire. For SaveChanges I use ISaveChangesInterceptor as it gives me access to the `DbUpdateException` to process. That's why I opened #24193

I guess it's a very specific use case but that's where the idea came from :)

2021-03-19 17:30 UTC, Giorgi commented
@ajcvickers So should I implement tests for the new feature or do you want to discuss it first internally? Or maybe you want changes made to the way it is implemented?

2021-03-24 18:45 UTC, ajcvickers commented on src/EFCore.Relational/Diagnostics/CommandEndEventData.cs
> +            CommandSource commandSource,
Please create a new constructor overload here, rather than adding a parameter to an existing constructor. This will prevent the change from being breaking for existing callers.

2021-03-24 18:49 UTC, ajcvickers commented on src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
>          public static DbCommand CommandCreated(
@dotnet/efteam Can we break these methods? Should we break once to introduce a parameter object?

2021-03-24 18:50 UTC, ajcvickers commented on src/EFCore.Relational/Storage/IRelationalCommand.cs
> +        int ExecuteNonQuery(RelationalCommandParameterObject parameterObject, CommandSource source);
Can the CommandSource go into the parameter object to avoid a break here?

2021-03-24 18:51 UTC, ajcvickers requested changes
Looking good; added some comments around avoiding breaking changes.

2021-03-24 19:29 UTC, Giorgi commented on src/EFCore.Relational/Storage/IRelationalCommand.cs
> +        int ExecuteNonQuery(RelationalCommandParameterObject parameterObject, CommandSource source);
@ajcvickers Should I create a new constructor for `RelationalCommandParameterObject` too? If so what should existing ones set the CommandSource to?  

CommandSource.Unknown or CommandSource.None or make it nullable?

2021-03-28 09:15 UTC, Giorgi commented
@ajcvickers The test failed because `PassiveReaderCommandInterceptor` is used in two different tests: one that uses `FromSqlRaw` and another uses LinqQuery. Should I create a separate interceptor for each case or do you have a better idea for testing this feature?

2021-04-23 16:40 UTC, ajcvickers commented on src/EFCore.Relational/Diagnostics/CommandCorrelatedEventData.cs
> +            : this(
Mark this overload as obsolete. Something like:

```
[Obsolete("Use the overload with CommandSource")]
```

2021-04-23 16:42 UTC, ajcvickers commented on src/EFCore.Relational/Diagnostics/CommandCorrelatedEventData.cs
> +            : this(
Likewise for other places where overloads were added to avoid breaking changes and new code should call the new overload.

2021-04-23 16:45 UTC, ajcvickers commented on src/EFCore.Relational/Diagnostics/CommandSource.cs
> +    public enum CommandSource
I discussed this with the team and we agreed on the following set of the values:

```
Unknown
LinqQuery
SaveChanges
Migrations
FromSqlQuery
ExecuteSqlRaw
ValueGenerator
Scaffolding
BulkUpdate
```

(BulkUpdate is not currently used, but we think we will need it.)

2021-04-23 16:46 UTC, ajcvickers requested changes
Looking good! Sorry for being so slow on this.

2021-05-16 22:09 UTC, Giorgi commented
@ajcvickers Updated

2021-07-28 09:17 UTC, ajcvickers approved these changes

2021-07-28 09:34 UTC, merged

2021-07-28 09:34 UTC, ajcvickers commented
Thanks @Giorgi! Sorry for being so slow.

2021-07-28 10:04 UTC, Giorgi commented
Thanks for merging @ajcvickers