Case insensitive SqliteDataReader. Fixes dotnet/efcore#24011
dotnet/efcore pull request #24588
Opened 2021-04-05 17:14 UTC by wdesgardin

Fixes #24011

2021-04-05 17:14 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24588) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24588) before we can accept your contribution.<br/><br/>:x: wdesgardin [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24588)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=24588) it.</sub>

2021-04-12 18:33 UTC, bricelam requested changes

2021-04-12 18:33 UTC, bricelam commented on test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> +        [InlineData("SELECT 1 as Id, 2 as id;", "id", 2L)]
```csharp
[InlineData("SELECT 1 as Id, 2 as id;", "ID", 1L)]
```
...or should it throw?

2021-04-13 23:01 UTC, wdesgardin commented on test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> +        [InlineData("SELECT 1 as Id, 2 as id;", "id", 2L)]
Hi @bricelam, thanks for reviewing this pr. Can you confirm that I need to open an issue to know if the team wants an exception to be raised in this particular case ?

2021-04-16 17:52 UTC, bricelam commented on test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> +        [InlineData("SELECT 1 as Id, 2 as id;", "id", 2L)]
We discussed this as a team today, and we think it should throw. Would you like to update PR? If not, I'm happy to merge this as is and make the update myself.

2021-04-26 18:58 UTC, bricelam approved these changes

2021-04-26 20:00 UTC, merged