Optimize using StringBuilder
dotnet/efcore pull request #24755
Opened 2021-04-25 09:52 UTC by SergerGood

2021-04-25 10:39 UTC, ArminShoeibi commented
Nice.
https://stackoverflow.com/questions/42721009/performance-of-stringbuilder-append

2021-04-25 13:27 UTC, roji commented
@SergerGood any specific reason to do this change? Are you seeing performance differences between appending a char and a string?

@ArminShoeibi your link seems to point to a Java-related question, not .NET.

2021-04-25 13:28 UTC, roji commented on src/EFCore.Relational/Metadata/IViewColumn.cs
> +                builder.Append("ViewColumn: ").Append(Table.Name).Append('.');
This makes the code less readable, in a codepath that is not perf-sensitive in any way.

2021-04-25 13:30 UTC, ArminShoeibi commented
> @ArminShoeibi your link seems to point to a Java-related question, not .NET.

oh, my bad.

2021-04-25 17:10 UTC, SergerGood commented
> @SergerGood any specific reason to do this change? Are you seeing performance differences between appending a char and a string?

@roji https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1834

2021-04-25 17:15 UTC, SergerGood commented on src/EFCore.Relational/Metadata/IViewColumn.cs
> +                builder.Append("ViewColumn: ").Append(Table.Name).Append('.');
In the same place:

https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Metadata/IViewColumn.cs#L50

https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Metadata/IViewColumn.cs#L52

2021-04-25 20:23 UTC, roji requested changes
Here's a quick benchmark:

|       Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |---------:|----------:|----------:|------:|------:|------:|----------:|
|   AppendChar | 5.923 ns | 0.0093 ns | 0.0072 ns |     - |     - |     - |         - |
| AppendString | 6.682 ns | 0.1175 ns | 0.0981 ns |     - |     - |     - |         - |

So there's roughly a half-nanosecond difference between these two methods, which doesn't seem significant in any of the code paths being touched. Not all quality rules make sense in all contexts...

We can still do this, but please revert the other changes which remove string interpolation - IMO these just make the code less readable for no reason.

<details>
<summary>Benchmark code</summary>

```c#
[MemoryDiagnoser]
public class Program
{
    private StringBuilder _builder;

    [Benchmark]
    public void AppendChar()
    {
        _builder.Clear();
        _builder.Append('x');
    }

    [Benchmark]
    public void AppendString()
    {
        _builder.Clear();
        _builder.Append("X");
    }

    [GlobalSetup]
    public void Setup() => _builder = new StringBuilder();

    static void Main(string[] args)
        => BenchmarkRunner.Run<Program>();
}
```

2021-04-25 20:23 UTC, roji commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                builder.Append(name, partStart, name.Length - partStart);
Is there any reason to do this change? The previous code seems simpler.

2021-04-25 20:23 UTC, roji commented on src/EFCore.Relational/Metadata/IColumn.cs
> +                builder.Append("Column: ").Append(Table.Name).Append('.');
Please revert

2021-04-25 20:23 UTC, roji commented on src/EFCore.Relational/Metadata/IFunctionColumn.cs
> +                builder.Append("FunctionColumn: ").Append(Table.Name).Append('.');
Please revert

2021-04-25 20:23 UTC, roji commented on src/EFCore.Relational/Metadata/ISqlQueryColumn.cs
> +                builder.Append("SqlQueryColumn: ").Append(Table.Name).Append('.');
Please revert

2021-04-25 20:23 UTC, roji commented on src/EFCore.Relational/Metadata/IViewColumn.cs
> +                builder.Append("ViewColumn: ").Append(Table.Name).Append('.');
Still doesn't seem like an improvement to me (note that here there are three things, whereas in your two examples there are two). Can you please revert unless there's a good reason to do this?

2021-04-25 20:23 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
> +                            .Append("SELECT ").AppendLine(columnType)
Please revert

2021-04-26 18:49 UTC, SergerGood commented on src/EFCore.Relational/Metadata/IViewColumn.cs
> +                builder.Append("ViewColumn: ").Append(Table.Name).Append('.');
I don't know if it's good reason or not.

``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i5-9300H CPU 2.40GHz, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=6.0.100-preview.3.21202.5
  [Host]     : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, CoreFX 6.0.21.20104), X64 RyuJIT
  DefaultJob : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, CoreFX 6.0.21.20104), X64 RyuJIT
```
|              Method | CharactersCount |     Mean |    Error |   StdDev |   Median |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------- |---------------- |---------:|---------:|---------:|---------:|-------:|------:|------:|----------:|
| **StringInterpolation** |               **5** | **32.56 ns** | **0.679 ns** | **1.764 ns** | **32.28 ns** | **0.0134** |     **-** |     **-** |      **56 B** |
|              Append |               5 | 14.08 ns | 0.309 ns | 0.356 ns | 14.13 ns |      - |     - |     - |         - |
| **StringInterpolation** |              **10** | **35.03 ns** | **0.714 ns** | **1.046 ns** | **35.00 ns** | **0.0153** |     **-** |     **-** |      **64 B** |
|              Append |              10 | 14.56 ns | 0.903 ns | 2.502 ns | 13.31 ns |      - |     - |     - |         - |

<details>
  <summary>Benchmark code</summary>
  
  ```csharp
    [MemoryDiagnoser]
    public class Program
    {
        private StringBuilder _builder;
        private string _text;
    
        [Params(5, 10)]
        public int CharactersCount { get; set; }
    
        [Benchmark]
        public void StringInterpolation()
        {
            _builder.Clear();
            _builder.Append($"Column: {_text}.");
        }
    
        [Benchmark]
        public void Append()
        {
            _builder.Clear();
            _builder.Append("Column: ").Append(_text).Append('.');
        }
    
        [GlobalSetup]
        public void Setup()
        {
            _builder = new StringBuilder();
            _text = new string('a', CharactersCount);
        }
    
        private static void Main() => BenchmarkRunner.Run<Program>();
    }
  ```
</details>

2021-04-26 18:50 UTC, SergerGood commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                builder.Append(name, partStart, name.Length - partStart);
The reason is that there is a ready-made native better method for this.

``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i5-9300H CPU 2.40GHz, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=6.0.100-preview.3.21202.5
  [Host]     : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, CoreFX 6.0.21.20104), X64 RyuJIT
  DefaultJob : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, CoreFX 6.0.21.20104), X64 RyuJIT
```
|          Method | CharactersCount |     Mean |    Error |   StdDev |   Median |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------- |---------------- |---------:|---------:|---------:|---------:|-------:|------:|------:|----------:|
| **StringSubstring** |               **5** | **23.03 ns** | **1.147 ns** | **3.308 ns** | **21.55 ns** | **0.0076** |     **-** |     **-** |      **32 B** |
| AppendSubstring |               5 | 11.99 ns | 0.134 ns | 0.119 ns | 11.96 ns |      - |     - |     - |         - |
| **StringSubstring** |              **10** | **22.92 ns** | **0.341 ns** | **0.302 ns** | **22.81 ns** | **0.0076** |     **-** |     **-** |      **32 B** |
| AppendSubstring |              10 | 11.77 ns | 0.216 ns | 0.169 ns | 11.78 ns |      - |     - |     - |         - |


<details>
  <summary>Benchmark code</summary>
  
  ```csharp
    [MemoryDiagnoser]
    public class Program
    {
        private StringBuilder _builder;
        private string _text;
        private int _partStart;
    
        [Params(5, 10)]
        public int CharactersCount { get; set; }
    
        [Benchmark]
        public void StringSubstring()
        {
            _builder.Clear();
            _builder.Append(_text.Substring(_partStart));
        }
    
        [Benchmark]
        public void AppendSubstring()
        {
            _builder.Clear();
            _builder.Append(_text, _partStart, _text.Length - _partStart);
        }
    
        [GlobalSetup]
        public void Setup()
        {
            _builder = new StringBuilder();
            _text = new string('a', CharactersCount);
            _partStart = CharactersCount / 2;
        }
    
        private static void Main() => BenchmarkRunner.Run<Program>();
    }
  ```
</details>

2021-04-26 22:14 UTC, roji commented on src/EFCore.Relational/Metadata/IViewColumn.cs
> +                builder.Append("ViewColumn: ").Append(Table.Name).Append('.');
String interpolation indeed has a perf cost, but this code is completely non-perf-sensitive, so readability is more important than 20ns.

2021-04-26 22:16 UTC, roji commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                builder.Append(name, partStart, name.Length - partStart);
https://github.com/dotnet/efcore/pull/24755#discussion_r620687279

2021-04-27 16:56 UTC, SergerGood commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                builder.Append(name, partStart, name.Length - partStart);
I revert using string interpolation.. but there are many examples. And I'm still in favor of uniform approach. 
https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs#L134

https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs#L451

What about Substring in the same file?

https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Design/Design/Internal/CSharpHelper.cs#L283

2021-04-27 17:22 UTC, roji commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                builder.Append(name, partStart, name.Length - partStart);
We can certainly make things more consistent - but given that nothing here is perf-sensitive, I'd go with what produces the shortest/simplest code, which is string interpolation in most cases (e.g. the CommandTimeout case above).

Accordingly, can you revert this particular change as well? All the rest looks fine.

2021-04-27 17:27 UTC, SergerGood commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                builder.Append(name, partStart, name.Length - partStart);
Yes. Done

2021-04-27 17:31 UTC, roji approved these changes

2021-04-27 17:31 UTC, roji commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                builder.Append(name, partStart, name.Length - partStart);
Thanks.

2021-04-27 17:58 UTC, merged