Caching access to virtual properties
dotnet/efcore pull request #24775
Opened 2021-04-27 09:17 UTC by vonzshik

Reading from virtual properties in a cycle/sequentially is very slow because the compiler can't cache the returned value from the property (because there might be side effects). This pr helps to alleviate this problem for some of the properties (the worst offender is `QueryContext.Context`, which is called every time a new `MaterializationContext` is created, but changing this is not trivial). Below is the benchmark results of reading from fields and properties in a cycle of 10.

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 5 2400G with Radeon Vega Graphics, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=6.0.100-preview.3.21202.5
  [Host]     : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, CoreFX 6.0.21.20104), X64 RyuJIT
  DefaultJob : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, CoreFX 6.0.21.20104), X64 RyuJIT

```
|                Method |      Mean |     Error |    StdDev |
|---------------------- |----------:|----------:|----------:|
|                 Field |  2.885 ns | 0.0515 ns | 0.0456 ns |
|              Property |  2.895 ns | 0.0644 ns | 0.0537 ns |
|       VirtualProperty | 17.204 ns | 0.3340 ns | 0.2961 ns |
| VirtualPropertyCached |  4.847 ns | 0.0433 ns | 0.0384 ns |

<details>
<summary>benchmark code</summary>

```csharp
public class VirtualPropertyBenchmark
{
	public int ValueField;

	public int ValueProperty { get; set; }

	public virtual int ValuePropertyVirtual { get; set; }

	[GlobalSetup]
	public void Setup()
	{
		ValueField = 42;
		ValueProperty = 42;
		ValuePropertyVirtual = 42;
	}

	[Benchmark]
	public int Field()
	{
		var valueSum = 0;
		for (var i = 0; i < 10; i++)
		{
			valueSum += ValueField;
		}

		return valueSum;
	}

	[Benchmark]
	public int Property()
	{
		var valueSum = 0;
		for (var i = 0; i < 10; i++)
		{
			valueSum += ValueProperty;
		}

		return valueSum;
	}

	[Benchmark]
	public int VirtualProperty()
	{
		var valueSum = 0;
		for (var i = 0; i < 10; i++)
		{
			valueSum += ValuePropertyVirtual;
		}

		return valueSum;
	}

	[Benchmark]
	public int VirtualPropertyCached()
	{
		var valueSum = 0;
		var value = ValuePropertyVirtual;
		for (var i = 0; i < 10; i++)
		{
			valueSum += value;
		}

		return valueSum;
	}
}
```

</details>

On fortunes benchmark this change got me around 50 ms/minute.

cc @roji

2021-04-27 09:17 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24775) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24775) before we can accept your contribution.<br/><br/>:x: vonzshik [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24775)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=24775) it.</sub>

2021-04-27 12:21 UTC, roji reviewed
I admit I'm surprised - this simple change seems to get us a 1% increase in RPS... Seems like we're at a point where virtual dispatch starts to make a difference?

We should do the same in SplitQueryingEnumerable, and possibly also look at FromSqlQueryingEnumerable (for DbDataReader) and Cosmos.

2021-04-27 13:09 UTC, roji commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                                    _relationalQueryContext, _dataReader!.DbDataReader, resultContext,
For most of the things being accessed in the enumerator, it's not possible for them to change mid-query (e.g. DbDataReader, at least for SingleQueryingEnumerable - SplitQueryingEnumerable requires more careful attention). So there may be some good opportunities here - I'm interested in seeing how much perf virtual dispatch elimination can get us.

2021-04-27 15:26 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                            var resultContext = _resultCoordinator.ResultContext;
Should we just make our result coordinators sealed and non-virtual properties? They are public and overridable because of pub-ternal philosophy. It it is hurting perf then I don't think it is worth sticking to it.

2021-04-27 15:59 UTC, roji commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                            var resultContext = _resultCoordinator.ResultContext;
Sure, we can go that way too. Though we're accessing some other virtual properties in MoveNext which we should probably cache (DbDataReader, CancellationToken), so we'd go down the caching route anyway...

2021-04-27 17:41 UTC, AndriySvyryd commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                            var resultContext = _resultCoordinator.ResultContext;
We should make members on `QueryContext` and derived classes non-virtual too.

2021-04-27 19:00 UTC, roji commented
Pushed a commit eliminating some more virtual lookups in the QueryingEnumerables.

2021-04-27 19:01 UTC, roji commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                            var resultContext = _resultCoordinator.ResultContext;
@AndriySvyryd yeah.. I pushed a commit which at least caches QueryContext.Context so it doesn't get recalculated all the time.

2021-04-27 22:42 UTC, smitpatel requested changes
No need of _resultContext. Make whole structure for co-ordinating results non-virtual or leave them I can take care of it in future.

_cancellationToken/_dbDataReader are fine.

2021-04-28 19:04 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                enumerator._dbDataReader = dataReader.DbDataReader;
Also null out _dbDataReader in dispose when disposing _dataReader.

2021-04-28 19:05 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                var resultCoordinator = enumerator._resultCoordinator = new SingleQueryResultCoordinator();
unused variable resultCoordinator?

2021-04-28 19:05 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
> +                var resultCoordinator = enumerator._resultCoordinator = new SingleQueryResultCoordinator();
as above

2021-04-28 19:06 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
> +                var resultCoordinator = enumerator._resultCoordinator = new SplitQueryResultCoordinator();
same as above file

2021-04-28 19:20 UTC, smitpatel approved these changes

2021-04-28 20:42 UTC, merged

2021-04-28 20:42 UTC, roji commented
Thanks again for this @vonzshik!!