Add Translation for MathF (#18842)
dotnet/efcore pull request #24829
Opened 2021-05-04 12:41 UTC by ntovas

Fixes #18842

2021-05-04 12:41 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24829) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24829) before we can accept your contribution.<br/><br/>:x: ntovas [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24829)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=24829) it.</sub>

2021-05-04 16:08 UTC, smitpatel commented
- The reflection is going wrong in those types causing errors because methods are not found.
- You will need to add a test for each new method translation you are adding.

2021-05-04 17:49 UTC, bricelam requested changes

2021-05-04 17:49 UTC, bricelam commented on src/EFCore.SqlServer/Query/Internal/SqlServerMathTranslator.cs
> +            { typeof(MathF).GetRequiredRuntimeMethod(nameof(MathF.Abs), new[] { typeof(double) }), "ABS" },
`decimal` and `double` overloads don't exist on this type (only `float`)

2021-05-04 18:01 UTC, bricelam commented
@smitpatel Should we translate `Math.PI` to `PI()`? (might be a bit silly for a constant...)

2021-05-04 18:09 UTC, smitpatel commented
If it is easy, sure.

2021-05-04 18:26 UTC, ntovas commented
@smitpatel hey, I couldn't find where are the tests for this functionality.

2021-05-04 18:39 UTC, smitpatel commented
https://github.com/dotnet/efcore/blob/main/test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs

2021-05-04 18:59 UTC, bricelam commented
> If it is easy, sure.

Needs a new *member* translator, but it should be pretty easy. Maybe I'll tack it on when merging this PR... (unless @ntovas wants to give it a go first)

2021-05-04 19:00 UTC, bricelam commented
...we should probably file an issue to translate the [Cosmos math functions](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-mathematical-functions) too...

2021-05-04 19:02 UTC, roji commented
@bricelam there's #24463 waiting for @maumar in case you're in the math mood.

2021-05-04 19:03 UTC, ntovas commented
@bricelam I would like to give to try it, but I will need a bit more context, specially on *member translator*

Also I could make the same fix for CosmosDb

2021-05-04 19:07 UTC, bricelam commented
Method translators: https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
Member translators: https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerMemberTranslatorProvider.cs

2021-05-12 17:19 UTC, smitpatel commented
Cosmos tests are failing.

2021-05-12 17:22 UTC, ntovas commented
> Cosmos tests are failing.

I will look at them and will add any changes, most likely on Saturday, if it's ok for you.

2021-06-07 16:30 UTC, merged