Dannyjacosta enhanced doc 1
dotnet/efcore pull request #24839
Opened 2021-05-04 22:36 UTC by dannyjacosta

Please check if the PR fulfills these requirements

- [x] The code builds and tests pass (verified by our automated build checks)
- [x] Commit messages follow this format
        Summary of the changes
        - Added a link to a video where Entity Framework Core team members guide you through the process of contributing and provide advise and good practices.

        
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

Review the guidelines for [contributing](CONTRIBUTING.md) for more details.

2021-05-05 01:28 UTC, dannyjacosta commented
Sorry for the non descriptive title. I didn't notice it was taken automatically from the branch name.

2021-05-05 12:04 UTC, roji requested changes

2021-05-05 12:04 UTC, roji commented on .github/CONTRIBUTING.md
> +Here is a [video](https://www.youtube.com/watch?v=9OMxy1wal1s) where members of the Entity Framework Core team provide guidance, advise and samples on how to contribute to this project.
```suggestion
Here is a [video](https://www.youtube.com/watch?v=9OMxy1wal1s) where members of the Entity Framework Core team provide guidance, advice and samples on how to contribute to this project.
```

2021-05-07 09:04 UTC, roji approved these changes

2021-05-07 09:05 UTC, merged

2021-05-07 09:05 UTC, roji commented
Thanks @dannyjacosta!