Implement DateOnly/TimeOnly support for Sqlite
dotnet/efcore pull request #24989
Opened 2021-05-27 16:18 UTC by roji

Closes #24506

2021-05-27 16:24 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                    ? timeOnly.ToString(@"HH:mm:ss.FFF", CultureInfo.InvariantCulture)
Note: this does millisecond-only precision, as per https://github.com/dotnet/efcore/issues/24506#issuecomment-808335218. Though maybe we should consider allowing persisting/reading more precision, even if the Sqlite functions wouldn't support it? Don't know how out support works elsewhere on Sqlite.

2021-05-27 16:24 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +            else if (type == typeof(TimeOnly))
Should we have REAL/INTEGER support for TimeOnly? The TimeSpan one is currently days as a double (e.g. 1.5 days), which isn't appropriate here.

This could simply be something like the number of milliseconds from midnight?

2021-05-27 16:24 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
> +        public virtual DateOnly GetDateOnly(int ordinal)
Note that trying to switch to DateOnly/TimeOnly on columns which already contain full timestamps will fail - not sure if we want to ensure some sort of backwards compat here (I don't think so).

2021-05-27 17:13 UTC, bricelam approved these changes

2021-05-27 17:13 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                    ? timeOnly.ToString(@"HH:mm:ss.FFF", CultureInfo.InvariantCulture)
Probably best to be consistent `TimeSpan` for now and use `HH:mm:ss.fffffff` (or just `o`). I want to revisit all of these someday and try to get rid of `rtrim(rtrim(..., '0'), '.')` in the SQL.

2021-05-27 17:13 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
> +        public virtual DateOnly GetDateOnly(int ordinal)
Nah, it's easy enough to migrate your database:
```sql
UPDATE A
SET dateOnly = date(dateOnly),
    timeOnly = strftime('%H:%M:%f', timeOnly);
```

2021-05-27 17:58 UTC, roji commented on src/EFCore.Relational/EFCore.Relational.csproj
> +    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
We certainly can, though it's not a huge deal to keep multitargeting either. Discuss in design?

2021-05-28 12:01 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                    ? timeOnly.ToString(@"HH:mm:ss.FFF", CultureInfo.InvariantCulture)
OK, making the change. FYI using `HH:mm:ss.FFFFFFF` - uppercase F means trailing 0's don't appear (but if we want really fully consistency I can do fffffff). Also, if the value doesn't have any sub-second component, I just use `HH:mm:ss`, making the representation shorter/lighter. Let me know if this all sounds good.

2021-05-28 13:22 UTC, roji commented on src/EFCore/EFCore.csproj
> +    <ProjectReference Condition="'$(BuildingByReSharper)' != 'true'" Include="..\EFCore.Analyzers\EFCore.Analyzers.csproj" ReferenceOutputAssembly="False" OutputItemType="Analyzer" />
@bricelam without doing this, building EFCore.Relational failed once I started multitargeting. This seems like some obscure SDK issue which I reproduced in isolation, but it goes away when EFCore uses the analyzer. This flags some warnings because of internal type usages from EFCore.Abstractions, which I suppressed.

```
/home/roji/.dotnet/sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file '/home/roji/projects/efcore/artifacts/obj/EFCore.Analyzers/project.assets.json' doesn't have a target for 'net6.0'. En
sure that restore has run and that you have included 'net6.0' in the TargetFrameworks for your project. [/home/roji/projects/efcore/src/EFCore.Analyzers/EFCore.Analyzers.csproj]                                                                                                         
/home/roji/.dotnet/sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file '/home/roji/projects/efcore/artifacts/obj/EFCore.Analyzers/project.assets.json' doesn't have a target for 'net5.0'. En
sure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. [/home/roji/projects/efcore/src/EFCore.Analyzers/EFCore.Analyzers.csproj]                                                                                                         
```

2021-05-28 14:04 UTC, roji commented
@bricelam made all the changes, can you take a final quick look?

2021-05-28 17:46 UTC, roji commented
Why does the build hate me so much

2021-05-28 20:40 UTC, smitpatel commented on src/EFCore.Relational/Storage/DateOnlyTypeMapping.cs
> +#endif
newline at EOF?

2021-05-28 20:45 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerFixture.cs
>              // Full-text binary search
Move comment

2021-05-28 20:46 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +        public override Task Where_DateOnly_Year(bool async)
Skip tests with tracking issue number and remove Task.CompletedTask.

2021-05-28 20:50 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +        public override Task Where_DateOnly_Year(bool async)
I don't care that much, but do we want to do that for unimplemented features? It would pollute our logs or a lot.

2021-05-28 20:54 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerFixture.cs
>              // Full-text binary search
Seems OK, no? One Mission configuration for binary search (BriefingDocument stuff), another for DateOnly/TimeOnly?

2021-05-28 21:04 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +        public override Task Where_DateOnly_Year(bool async)
Task.CompletedTask or empty test body should only be used for this which will never work (unsupported scenario or invalid test).
For unimplemented features Skip tests with issue numbers. We have done that for many years now already, there is no pollution worth caring at this point.

2021-06-01 16:21 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
> +            => Task.CompletedTask;
Convert all Task.CompletedTask to base calls.
Even better if you convert them to AssertSql with empty string.

2021-06-01 17:04 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                    ? timeOnly.ToString(@"HH:mm:ss.FFF", CultureInfo.InvariantCulture)
Yes, that sounds right

2021-06-01 17:46 UTC, bricelam requested changes

2021-06-01 17:46 UTC, bricelam commented on src/EFCore.Relational/Storage/TimeOnlyTypeMapping.cs
> +            return timeOnly.Ticks % 10000000 == 0
```suggestion
            return timeOnly.Ticks % TimeSpan.TicksPerSecond == 0
```

2021-06-01 17:46 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateOnlyMemberTranslator.cs
> +                { nameof(DateTime.DayOfWeek), "%w" }
```suggestion
                { nameof(DateOnly.Year), "%Y" },
                { nameof(DateOnly.Month), "%m" },
                { nameof(DateOnly.DayOfYear), "%j" },
                { nameof(DateOnly.Day), "%d" },
                { nameof(DateOnly.DayOfWeek), "%w" }
```

2021-06-01 17:46 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    "date",
Can you file an issue to simplify nested calls like we do for strftime?

For example, `strftime('%Y', date($date, '1 years'))` can be simplifed to `strftime('%Y', $date, '1 years')`.

2021-06-01 17:46 UTC, bricelam commented on src/EFCore.Relational/Storage/TimeOnlyTypeMapping.cs
> +            return timeOnly.Ticks % 10000000 == 0
(in `SqliteTimeOnlyTypeMapping`  too)

2021-06-01 17:46 UTC, bricelam commented on src/EFCore/EFCore.csproj
> +    <ProjectReference Condition="'$(BuildingByReSharper)' != 'true'" Include="..\EFCore.Analyzers\EFCore.Analyzers.csproj" ReferenceOutputAssembly="False" OutputItemType="Analyzer" />
Double-check that the .nuspec generated on pack hasn't change.

2021-06-01 17:46 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                        : timeOnly.ToString(@"HH:mm:ss.FFFFFFF", CultureInfo.InvariantCulture);
Hmm, this is actually inconsistent with the current TimeSpan format. I think most existing databases will be using `TimeSpan` for these columns, so it probably makes the most sense to match that format: `HH:mm:ss.fffffff`

2021-06-01 17:46 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +        private static double ToJulianTime(int hour, int minute, int second, int millisecond)
lol, not sure *Julian time* is a thing... `GetTotalDays`?

2021-06-01 17:47 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                    ? timeOnly.ToString(@"HH:mm:ss.FFF", CultureInfo.InvariantCulture)
Hmm... Having second thoughts. (Comments below.)

2021-06-03 11:02 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
> +            => Task.CompletedTask;
Done.

2021-06-03 11:06 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                        : timeOnly.ToString(@"HH:mm:ss.FFFFFFF", CultureInfo.InvariantCulture);
#25027

2021-06-03 11:16 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    "date",
#25027

2021-06-03 11:21 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +        private static double ToJulianTime(int hour, int minute, int second, int millisecond)
GetTotalDays is weird given that this will only ever give a fraction of a day... But this is just a private thing, will do.

2021-06-03 11:25 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                        : timeOnly.ToString(@"HH:mm:ss.FFFFFFF", CultureInfo.InvariantCulture);
Making the change here and in SqliteTimeOnlyTypeMapping, but if it's OK with you I'm leaving FFFFFFF in TimeOnlyTypeMapping (as a default for other databases)?

2021-06-03 11:44 UTC, roji commented on src/EFCore/EFCore.csproj
> +    <ProjectReference Condition="'$(BuildingByReSharper)' != 'true'" Include="..\EFCore.Analyzers\EFCore.Analyzers.csproj" ReferenceOutputAssembly="False" OutputItemType="Analyzer" />
That was a good suggestion - this change makes Microsoft.EntityFrameworkCore.Analyzers disappear from the nuspec, not good.

I can dig into it, but as the issue above disappears when we just target net6.0, we should maybe just do that...

2021-06-03 11:47 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
> +                    ? timeOnly.ToString(@"HH:mm:ss.FFF", CultureInfo.InvariantCulture)
Made the switch back to fffffff for Sqlite, see https://github.com/dotnet/efcore/pull/24989#discussion_r644711542.

2021-06-03 16:40 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateOnlyMemberTranslator.cs
> +            if (member.DeclaringType != typeof(DateOnly))
invert if and combine with if later?

2021-06-03 21:57 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateOnlyMemberTranslator.cs
> +            if (member.DeclaringType != typeof(DateOnly))
Done

2021-06-10 09:50 UTC, roji commented
@bricelam (@smitpatel) have squashed and rebased this for net6.0, and cleaned up. In case you want to do a final review.

2021-06-10 20:30 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteTimeOnlyTypeMapping.cs
> +                : FormattableString.Invariant($@"'{value:HH\:mm\:ss\.fffffff}'");
Oh I see, it *is* lower case here. The `Ticks` code doesn't belong here, does it?

2021-06-15 17:22 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
> +        public virtual DateOnly GetDateOnly(int ordinal)
Happy to wait and see if anyone asks for them

2021-06-15 17:41 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteTimeOnlyTypeMapping.cs
> +                : FormattableString.Invariant($@"'{value:HH\:mm\:ss\.fffffff}'");
I played around with this, and the current code seems correct. It matches the current behavior of TimeSpan.

At the ADO.NET level, TimeSpan uses `{0:c}` but `c` is the default so it's technically the same, the format is invariant.

2021-06-15 17:42 UTC, bricelam approved these changes

2021-06-15 17:44 UTC, merged

2021-06-15 17:44 UTC, roji commented
Thanks @bricelam