Add support for `InfiniteTimeSpan` in `SetCommandTimeout`.
dotnet/efcore pull request #25085
Opened 2021-06-12 10:07 UTC by taha-ghadirian

Add support for `InfiniteTimeSpan` In `Context.Database.SetCommandTimeout()`.

Issue #25068 Comment [858547728](https://github.com/dotnet/efcore/issues/25068#issuecomment-858547728)

2021-06-13 07:53 UTC, roji requested changes
This change isn't correct: passing null to the overload which accepts an `int?` doesn't apply an infinite timeout - it applies "the default value used is defined by the underlying ADO.NET data provider" (see the XML docs there).

As per the documentation on [DbCommand.CommandTimeout](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.commandtimeout?view=net-5.0#System_Data_Common_DbCommand_CommandTimeout), for an infinite timeout we should set to 0.

2021-06-13 07:53 UTC, roji commented on src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
> +            if(timeout == Timeout.InfiniteTimeSpan)
```suggestion
            if (timeout == Timeout.InfiniteTimeSpan)
```

2021-06-13 08:18 UTC, taha-ghadirian commented
Requested changes done, 
Thanks for letting code problems 🙏

2021-06-14 13:15 UTC, taha-ghadirian commented
@roji Requested changes applied.

2021-06-15 02:12 UTC, roji commented
Can you please add some testing in CommandConfigurationTests.CommandTimeout?

2021-06-15 03:30 UTC, taha-ghadirian commented
Hello @roji, Thanks for your note. Tests added and checked as successful ;)

2021-06-15 09:53 UTC, roji commented on test/EFCore.SqlServer.Tests/CommandConfigurationTests.cs
> +                Assert.Equal(0, context.Database.GetCommandTimeout());
```suggestion
            }

            [ConditionalFact]
            public void Setting_CommandTimeout_to_infinite_sets_to_zero()
            {
                using var context = new TimeoutContext();

                context.Database.SetCommandTimeout(Timeout.InfiniteTimeSpan);
                Assert.Equal(0, context.Database.GetCommandTimeout());
```

2021-06-15 10:51 UTC, roji approved these changes
Thanks, I split out a separate test but otherwise all looks good.

2021-06-15 11:29 UTC, merged