Drop computed columns before non-computed
dotnet/efcore pull request #25238
Opened 2021-07-12 12:05 UTC by roji

Fixes #25237

2021-07-12 16:10 UTC, bricelam requested changes

2021-07-12 16:10 UTC, bricelam commented on src/EFCore.Relational/Migrations/Operations/DropColumnOperation.cs
> +    public class DropColumnOperation : ColumnOperation, ITableMigrationOperation
I'm against this change. IMHO, it's an anti-pattern the encourages providers to diff during SQL generation. Instead, can we update the base migrations annotation provider to add an IsComputed annotation?

2021-07-12 16:23 UTC, roji commented on src/EFCore.Relational/Migrations/Operations/DropColumnOperation.cs
> +    public class DropColumnOperation : ColumnOperation, ITableMigrationOperation
> Instead, can we update the base migrations annotation provider to add an IsComputed annotation?

We certainly can, but it's odd to have computed as a full property in one context (AddColumnOperation) and as an annotation in another... I'm also worried about what happens when some provider needs to know about other facets when dropping, for some obscure reason... Would we copy those across as annotations as well? If we do, don't we end up in the same place?

2021-07-28 21:03 UTC, bricelam commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +                    }
Instead of storing this in the migrations operation, let's just use the DiffContext instead. The code here would be something like this:
```suggestion
                    if (string.IsNullOrWhiteSpace(diffContext.FindColumn((DropColumnOperation)operation).ComputedColumnSql)
                    {
                        dropColumnOperations.Add(operation);
                    }
```

2021-07-28 21:05 UTC, bricelam commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +                    }
Also double-check the behavior of `null` vs whitespace. I think there's an overload of HasComputedColumnSql() that marks the column as computed, but doesn't actually specify the SQL. Although, it probably throws that it's not defined before it gets here...

2021-07-29 11:08 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +                    }
> Instead of storing this in the migrations operation, let's just use the DiffContext instead.

Done, check it out.

> Also double-check the behavior of null vs whitespace. I think there's an overload of HasComputedColumnSql() that marks the column as computed, but doesn't actually specify the SQL. Although, it probably throws that it's not defined before it gets here...

Seems so - I did a quick console test using this PR code, and got the following exception stack trace:

```
Unhandled exception. System.InvalidOperationException: The computed column SQL has not been specified for the column 'Name.Blogs'. Specify the SQL before using Entity Framework to create the database schema.
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Initialize(ColumnOperation columnOperation, IColumn column, RelationalTypeMapping typeMapping, Boolean isNullable, IEnumerable`1 migrationsAnnotations, Boolean inline) in /home/roji/projects/efcore/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs:line 1145
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Add(IColumn target, DiffContext diffContext, Boolean inline)+MoveNext() in /home/roji/projects/efcore/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs:line 1090
```

<details>
<summary>Test code</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<Blog>().Property(b => b.Name).HasComputedColumnSql();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>

2021-07-29 17:46 UTC, bricelam commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +                    }
No, it's a valid model--we just can't create the full schema for it.

2021-07-29 17:51 UTC, bricelam approved these changes

2021-07-29 17:51 UTC, bricelam commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> -            operation.AddAnnotations(MigrationsAnnotations.ForRemove(source));
Still need this hook. It allows providers to flow the information they need (e.g. memory-optimized)

2021-07-29 17:51 UTC, bricelam commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> -            operation.AddAnnotations(MigrationsAnnotations.ForRemove(source));
I'm surprised there's not an existing test for that. Do we run memory-optimized tests on CI?

2021-07-29 17:54 UTC, bricelam commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> -            operation.AddAnnotations(MigrationsAnnotations.ForRemove(source));
Ah, some temporal tests did fail. 🙂

2021-07-29 20:48 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> -            operation.AddAnnotations(MigrationsAnnotations.ForRemove(source));
Oh oops... Corrected, tests passing now.

2021-07-29 20:50 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +                    }
Hmm, that seems... nuanced... But doesn't really matter.

2021-07-29 22:32 UTC, merged