Code Cleanup for EFCore project
dotnet/efcore pull request #25350
Opened 2021-07-28 11:01 UTC by ajcvickers

Will do other projects if the changes here look good to everyone.

2021-07-28 18:34 UTC, AndriySvyryd commented on src/EFCore/ChangeTracking/Internal/Snapshot.cs
> +                => index switch
😕

2021-07-28 18:57 UTC, AndriySvyryd commented on src/EFCore/EF.CompileAsyncQuery.cs
> -// <auto-generated />
😕

2021-07-28 19:01 UTC, AndriySvyryd commented on src/EFCore/Query/Internal/CompiledAsyncEnumerableQuery.cs
> -// <auto-generated />
😕

2021-07-28 19:06 UTC, AndriySvyryd commented on src/EFCore/Query/Internal/CompiledAsyncTaskQuery.cs
> -// <auto-generated />
😕

2021-07-28 19:07 UTC, AndriySvyryd requested changes
⬆️

2021-07-28 19:11 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
> +                                (
?

2021-07-28 19:25 UTC, smitpatel commented on src/EFCore/EF.CompileQuery.cs
> +        public static Func<TContext, TParam1, TParam2, TParam3, TParam4, TParam5, TParam6, TParam7, TParam8, IEnumerable<TResult>>
This doesn't match template, which means every time it will cause changes whenever file is regenerated for whatever reason.

2021-07-29 08:46 UTC, roji commented on src/EFCore/Diagnostics/CoreLoggerExtensions.cs
> +                modelVersion,
Single line no?

2021-07-29 08:46 UTC, roji commented on src/EFCore/EF.CompileAsyncQuery.tt
> +        for (var i = 1; i <= parameterCount; i++)
I'd avoid doing this - keeping code single-line in the templates helps readability in my opinion (easier to spot code vs. content)...

2021-07-29 08:46 UTC, roji commented on src/EFCore/Infrastructure/EntityFrameworkEventSource.cs
> +
?

2021-07-29 08:46 UTC, roji commented on src/EFCore/Infrastructure/ExpressionExtensions.cs
> +                this Expression target,
Is this right?

2021-07-29 08:46 UTC, roji commented on src/EFCore/Internal/InternalDbSet.cs
> +                        throw new InvalidOperationException(
Can be simplified with conditional operator

2021-07-29 08:46 UTC, roji commented on src/EFCore/Metadata/Internal/ConstructorBindingFactory.cs
> +                static(f, e, p, n) => f?.Bind((IConventionEntityType)e, p, n),
Seems wrong

2021-07-29 08:46 UTC, roji commented on src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
> +            this IEntityType entityType,
Single line?

2021-07-29 08:46 UTC, roji commented on src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
> +                || existingNavigation.ClrType == type
?

2021-07-29 08:46 UTC, roji commented on src/EFCore/Metadata/Internal/Model.cs
> +                ?? (entityType.HasSharedClrType
:(

2021-07-29 08:46 UTC, roji commented on src/EFCore/Metadata/Internal/ModelConfiguration.cs
> -        public ModelConfiguration()
Were we missing an [EntityFrameworkInternal] attribute here (based on the comment)?

2021-07-29 08:46 UTC, roji commented on src/EFCore/Metadata/RuntimeServiceProperty.cs
> +                => NonCapturingLazyInitializer.EnsureInitialized(
:(

2021-07-29 08:46 UTC, roji commented on src/EFCore/Query/Internal/CompiledAsyncTaskQuery.tt
> +<#
As above, prefer leaving single line for code templates where possible

2021-07-29 08:46 UTC, roji commented on src/EFCore/Query/Internal/CompiledQueryBase.cs
> +                static(t, c, q) =>
:(

2021-07-29 17:00 UTC, bricelam reviewed
Can you run it on the System.ComponentModel.Annotations code next?

2021-07-29 17:25 UTC, roji commented on src/EFCore/ChangeTracking/CollectionEntry.cs
> +        /// <exception cref="OperationCanceledException"> If the <see cref="CancellationToken" /> is canceled. </exception>
I've been wanting to raise the question of the trailing xmldoc space in a design meeting but was too scared to open a pandora's box of flame wars

2021-07-29 17:26 UTC, AndriySvyryd commented on src/EFCore/Diagnostics/CoreLoggerExtensions.cs
> +                modelVersion,
I think R# doesn't format multiline calls back to a single line as it's set to preserve existing new lines

2021-07-29 17:27 UTC, roji commented on src/EFCore/ChangeTracking/CollectionEntry.cs
> +        /// <exception cref="OperationCanceledException"> If the <see cref="CancellationToken" /> is canceled. </exception>
(note to mention the leading and trailing spaces *inside* the XML elements - those are blasphemous)

2021-07-29 17:27 UTC, AndriySvyryd commented on src/EFCore/Infrastructure/ExpressionExtensions.cs
> +                this Expression target,
Probably confused by the comment below

2021-07-29 17:28 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/ModelConfiguration.cs
> -        public ModelConfiguration()
This is already in .Internal

2021-07-29 17:56 UTC, bricelam commented on src/EFCore/ChangeTracking/CollectionEntry.cs
> +        /// <exception cref="OperationCanceledException"> If the <see cref="CancellationToken" /> is canceled. </exception>
+1 Utter blasphemy.

2021-07-29 17:58 UTC, bricelam commented on src/EFCore/ChangeTracking/CollectionEntry.cs
> +        /// <exception cref="OperationCanceledException"> If the <see cref="CancellationToken" /> is canceled. </exception>
lol, I remember the MSDN team had *add* code to ignore leading whitespace. We were literally the only team at Microsoft doing this.

2021-07-29 20:42 UTC, roji commented on src/EFCore/ChangeTracking/CollectionEntry.cs
> +        /// <exception cref="OperationCanceledException"> If the <see cref="CancellationToken" /> is canceled. </exception>
Copy that, I'll put aside all 6.0 work and get to work on removing those whitespaces.

2021-09-17 21:35 UTC, AndriySvyryd commented
@ajcvickers Are you planning to pick this up soon? We need to do it before RTM

2021-09-18 07:09 UTC, ajcvickers commented
@AndriySvyryd Good point; will do.

2021-09-23 14:56 UTC, closed without merging