Cosmos FromSql
dotnet/efcore pull request #25525
Opened 2021-08-15 17:58 UTC by roji

Notes:

* Did not implement FromSqlInterpolated for now as we're not sure we want to. Current naming is FromSqlRaw (as opposed to FromSql).
* Cosmos has no DbParameter - parameters are added via [QueryDefinition.WithParameter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.querydefinition.withparameter?view=azure-dotnet) where the name/value are given directly. The main use of accepting DbParameter in relational is to allow configuring parameter facets (size, precision, scale), but as these concepts don't exist in Cosmos we simply don't support it. So Cosmos FromSql supports only direct values.
* The current implementation always integrates the raw SQL as a subquery, even when it isn't composed over. This is because we currently always send `SELECT c FROM root c` for entity projection, which adds an additional level of nesting (with c as key), compared to `SELECT *`; this means we don't know how to materialize results from `SELECT *`, or projections such as `SELECT c.Region, c.PostalCode` (even when all the entity's properties are properly projected). Always wrapping in a subquery allows us to produce the correct nested structure; we should probably plan for producing `SELECT *` at some point.
    * Note also that since by default we map all DbSets to the same container with a discriminator, and we compose to filter by the discriminator, we'll (almost?) always be composing anyway (compared to relational where we only compose for discriminator for TPH sub-types).

### Subqueries in Cosmos

Docs say only correlated subqueries are supported (https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-subquery). However, this seems to (implicitly) refer to subqueries within JOIN:
* Works (correlated subquery in join): `SELECT Count(1) FROM c JOIN (SELECT VALUE t FROM t IN c.Tags)`
* Does not work (non-correlated): `SELECT Count(1) FROM c JOIN (SELECT * FROM root)`
* In other words, JOIN subqueries (like JOIN in general) are just a mechanism for projecting out from the same document (which means they must be correlated)
* So it will never be possible to use FromSql in a JOIN (unlike in relational) - only in FROM.

Composition over subquery in FROM:

Operator       | Sample Northwind SQL
-------------- | ---------------------------------------------------------------------------------------------------------------------------------------------
WHERE          | `SELECT * FROM (SELECT * FROM root c WHERE c.Discriminator = 'Customer') c WHERE c.City = 'Berlin'`
ORDER BY       | `SELECT * FROM (SELECT * FROM root c WHERE c.Discriminator = 'Customer') c ORDER BY c.PostalCode`
LIMIT / OFFSET | `SELECT * FROM (SELECT * FROM root c WHERE c.Discriminator = 'Customer') c OFFSET 1 LIMIT 3`
GROUP BY       | `SELECT c.City, Count(1) FROM (SELECT c.City, Count(1) AS Count FROM c WHERE c.Discriminator = 'Customer' GROUP BY c.City) c GROUP BY c.City`

Closes #17311

2021-08-15 18:00 UTC, roji commented on src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
> +                && Sql == queryRootExpression.Sql
Was this a bug? SQL can contain literals which are case-sensitive?

2021-08-16 15:43 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +        private sealed class ParameterNameGenerator
Leaving this private for now, rather than a service - we can make this better (but then use it in other places?).

2021-08-16 16:08 UTC, smitpatel commented on src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
> +using JetBrains.Annotations;
?

2021-08-16 16:11 UTC, smitpatel commented on src/EFCore.Cosmos/Query/Internal/FromSqlExpression.cs
> +    public class FromSqlExpression : RootReferenceExpression, ICloneable, IPrintableExpression
No IClonable.

2021-08-16 16:14 UTC, smitpatel commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +            _sqlBuilder.Append(objectArrayProjectionExpression.ToString());
It is non-object by design. ToString is intended. Ideally it should print out the way required in SQL. It just ends up matching ToString output.

2021-08-16 16:15 UTC, smitpatel commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +                _ => null
This should throw exception.

2021-08-16 16:16 UTC, smitpatel commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +        private sealed class ParameterNameGenerator
We don't need reset if we initialize new every time when we enter GetSqlQuery.

2021-08-16 16:18 UTC, roji commented on src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
> +using JetBrains.Annotations;
This is for [StringFormatMethod] on FromSqlRaw

2021-08-16 16:22 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
> +                && Sql == queryRootExpression.Sql
at least ordinal?

2021-08-16 16:23 UTC, smitpatel commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +                    => constantValues,
Constant values are actually inlined as constant and not parameters. See relational implementation.

2021-08-16 16:24 UTC, smitpatel commented on test/EFCore.Cosmos.FunctionalTests/Query/FromSqlQueryCosmosTest.cs
> +AssertSql(
This feels wrong indentation #python

2021-08-16 16:26 UTC, smitpatel requested changes
Joins/SelectMany to generate a query with FromSqlRaw inside lambda is not possible perhaps write a test for EF.CompiledQuery which generates same. If parameterExtractingEV says constant values in the tree, we inline the values and don't send server parameters.

2021-08-16 16:28 UTC, roji commented on src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
> +                && Sql == queryRootExpression.Sql
`==` is the same as Ordinal (we use that a lot)... You prefer verbose with string.Equals?

2021-08-16 17:47 UTC, roji commented
> Joins/SelectMany to generate a query with FromSqlRaw inside lambda is not possible perhaps write a test for EF.CompiledQuery which generates same. If parameterExtractingEV says constant values in the tree, we inline the values and don't send server parameters.

Relevant test is FromSqlRaw_queryable_composed_compiled_with_parameter

2021-08-16 21:35 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
> +                && Sql == queryRootExpression.Sql
nah, as long as same result, I don't care.

2021-08-16 21:36 UTC, smitpatel commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +                    throw new ArgumentOutOfRangeException();
InvalidOperationException with the argument tree printed

2021-08-16 21:37 UTC, AndriySvyryd commented
> Cosmos has no DbParameter - parameters are added via QueryDefinition.WithParameter where the name/value are given directly. The main use of accepting DbParameter in relational is to allow configuring parameter facets (size, precision, scale), but as these concepts don't exist in Cosmos we simply don't support it. So Cosmos FromSql supports only direct values.

We should create an issue for adding support for parameters. While they doesn't offer new functionality they are more convenient than manually seriliazing values to json, especially with https://github.com/dotnet/efcore/issues/17306

2021-08-16 22:58 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +                    throw new ArgumentOutOfRangeException();
Was trying to avoid a new string :trollface:

2021-08-16 23:16 UTC, roji commented
> We should create an issue for adding support for parameters. While they doesn't offer new functionality they are more convenient than manually seriliazing values to json, especially with #17306

@AndriySvyryd can you open that issue? I'm not sure exactly what you have in mind...

2021-08-16 23:22 UTC, AndriySvyryd commented
> @AndriySvyryd can you open that issue? I'm not sure exactly what you have in mind...

Perhaps it just works, added a note to https://github.com/dotnet/efcore/issues/17306

2021-08-16 23:29 UTC, smitpatel commented on src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
> +                    throw new ArgumentOutOfRangeException();
Just print out the expression tree. No need of exception message or resources.

2021-08-17 00:17 UTC, merged