Query: add translation for string.IndexOf(string, int) #25396
dotnet/efcore pull request #25655
Opened 2021-08-23 04:04 UTC by yosoyhabacuc

Summary of the changes:
        - Added support to _indexOfMethodInfoWithStartingPosition in SqlServerStringMethodTranslator
        - Created a TranslateIndexOf method inside the same class to be used by both _indexOfMethodInfo and _indexOfMethodInfoWithStartingPosition
        - Created test for Indexof_with_one_arg, to check the existing implementation still works
        - Modified test method Indexof_with_starting_position to check the change
Fixes issue  #25396

2021-08-23 04:04 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=25655) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=25655) before we can accept your contribution.<br/><br/>:x: yosoyhabacuc [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=25655)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=25655) it.</sub>

2021-08-31 14:49 UTC, ajcvickers commented
Note: EF Core 6.0 is closed for new features; this will need retargeting to main.

Assigning @smitpatel

2021-09-02 22:29 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +            searchExpression = _sqlExpressionFactory.ApplyTypeMapping(searchExpression, stringTypeMapping);
do same for instance here only.

2021-09-02 22:30 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +            SqlExpression[] charIndexArguments;
Declare & initialize with predefined size so we can set first 2 arg with one code in both path and last argument based on condition.

2021-09-02 22:32 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +                    argumentsPropagateNullability: new[] { true, true },
this array size should match the size of arguments.

2021-09-02 22:33 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +                            new CaseWhenClause(
bad indent.

2021-09-02 22:33 UTC, smitpatel requested changes
Rebase on main branch

2021-09-06 03:07 UTC, yosoyhabacuc commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +            searchExpression = _sqlExpressionFactory.ApplyTypeMapping(searchExpression, stringTypeMapping);
Done.

2021-09-06 03:09 UTC, yosoyhabacuc commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +            SqlExpression[] charIndexArguments;
Done.

2021-09-06 03:09 UTC, yosoyhabacuc commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +                    argumentsPropagateNullability: new[] { true, true },
Done.

2021-09-06 03:09 UTC, yosoyhabacuc commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +                            new CaseWhenClause(
Done.

2021-09-06 19:57 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +                charIndexArguments = charIndexArguments.Append(_sqlExpressionFactory.Add(startIndex, _sqlExpressionFactory.Constant(1))).ToArray();
unnecessary double allocation. Declare charIndexArguments as a list and just call Add.

2021-09-06 19:58 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +            var argumentsPropagateNullability = Enumerable.Repeat(true, charIndexArguments.Length).ToArray();
No need to call ToArray since the function takes IEnumerable parameter only.

2021-09-06 20:25 UTC, yosoyhabacuc commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +                charIndexArguments = charIndexArguments.Append(_sqlExpressionFactory.Add(startIndex, _sqlExpressionFactory.Constant(1))).ToArray();
My fault, I didn't see params were IEnumerable. It's fixed now.

2021-09-06 20:25 UTC, yosoyhabacuc commented on src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
> +            var argumentsPropagateNullability = Enumerable.Repeat(true, charIndexArguments.Length).ToArray();
Done.

2021-09-06 20:51 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
> +    WHEN N'a' = N'' THEN 0
@maumar - Should get this simplified at some point?

2021-11-11 03:11 UTC, smitpatel commented
Since original PR wasn't rebase on latest main, closing in favor of #26623

2021-11-11 03:11 UTC, closed without merging