Case sensitive parameters 18861
dotnet/efcore pull request #26287
Opened 2021-10-08 19:48 UTC by KevRitchie

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:

        Summary of the changes

        - Check SqliteParameterCollection for parameters that already exist ignoring casing
        - Update Bind to check for parameters regardless of casing
        - Add test for case-insensitive parameter binding

Fixes #18861

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

2021-10-08 19:48 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=26287) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=26287) before we can accept your contribution.<br/><br/>:x: KevRitchie [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=26287)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=26287) it.</sub>

2021-10-08 21:04 UTC, smitpatel commented
release/6.0 branch is closed for commits unless critical ship blockers. Please rebase your branch on top main branch.

2021-10-08 22:09 UTC, KevRitchie commented
@roji makes perfect sense.  It would be best to keep everything moving in the same direction.

2022-01-25 22:15 UTC, bricelam commented
Finally circling back to this... 

@roji your comment about perf doesn't apply in this situation. The .NET parameter collection object would remain case-sensitive. You need to check for a parameter using the exact case it was added in.

This just adds a fallback during execution where, if the parameter fails to bind to the SQL, we'll try a case-insensitive match instead. Perf isn't affected for parameters specified using the exact case. This just allows what is currently a negative scenario to succeed if the SQL happens to contain a different case. This is similar to the code added in #24588 for data readers where, only if we fail to find an exact match for the column, we'll fallback to a case-insensitive match.

I think we should move forward with this change.

2022-01-25 22:30 UTC, bricelam requested changes

2022-01-25 22:30 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteParameterCollection.cs
> -                if (parameter.Bind(stmt))
This code shouldn't require any changes since parameter.Bind will return true if any match was found.

We do however have to update `GetStatements`.

2022-01-25 22:30 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs
>                  && (index = FindPrefixedParameter(stmt)) == 0)
We should also add a similar case-insensitive fallback for `FindPrefixedParameter`.

2022-01-25 22:30 UTC, bricelam commented on test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
> +                command.Parameters.AddWithValue("@Param", "harvest");
Needs more coverage:

SQL | Parameter name(s) | Expected Result
--- | --- | ---
SELECT $param | Param | Adds prefix and binds using a case-insensitive match
SELECT $param, $Param | `$param` and `$Param` | Both parameters are bound using case-sensitive matches
SELECT $param, $Param | `$Param` and *then* `$param` | Both parameters are bound using case-sensitive matches. Order doesn't matter
SELECT $param, $PARAM | $Param | Throws ambiguous parameter exception
SELECT $param, $PARAM | Param | Throws ambiguous parameter exception

2022-01-25 22:32 UTC, bricelam commented on test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
> +                command.Parameters.AddWithValue("@Param", "harvest");
Also make sure the new `GetStatements` code is covered.

2022-01-25 22:39 UTC, roji commented
@bricelam if I'm understanding you correctly, you're saying that operations on SqliteParameterCollection would be case-sensitive only (so e.g. Contains for name `foo` would return false when there's a parameter with name `FOO`), but the matching of placeholders in the SQL (e.g. `@FOO`) would bind in a case-insensitive way (so `@foo` in the SQL would successfully bind to a parameter with `FOO`)?

If I've understood correctly, isn't this behavioral discrepancy problematic? I'd expect the same behavior to apply to both operations on SqliteParameterCollection and in placeholder binding (i.e. the name should either be case-sensitive or case-insensitive, but not sometimes one and sometime the other)?

2022-01-26 08:13 UTC, ajcvickers commented
@bricelam Agree this seems reasonable to move forward with.

@roji Not sure why those things need to behave the same. SqliteParameterCollection doesn't have a behavior that works when the generated SQL does. However, the generated SQL is not limited by a limitation in the specific ways SqliteParameterCollection can be used.

2022-01-26 09:19 UTC, roji commented
> Not sure why those things need to behave the same.

Simply because both are about whether the parameter name is treated in a case-sensitive way or not? At the very least, it seems confusing to have two opposite behaviors around the same thing.

Put another way... Why exactly do we feel it's important to add the case-insensitive fallback for placeholder binding? I'm generally not a fan of lax/fuzzy/case-insensitive logic, but if do for some reason, why is that reason not equally valid for SqliteParameterCollection?

2022-01-28 17:47 UTC, bricelam commented
To use Dapper as an example, I think a lot of people could conceivably write this code and expect it to just work:

```cs
var post = connection.Query<Post>(
    "select * from post where id = $id",
    new { Id = 1 });
```

They aren't really thinking about how the case of the C# anonymous type's property and the SQL parameter need to match up.

2022-01-29 12:24 UTC, roji commented
@bricelam yeah, I get that. I occasionally also get requests from people wanting to assign a string value to an NpgsqlDbType.Integer parameter, with Npgsql doing an implicit conversion - and tell them that I think it's a bad idea.

I guess I'm just a strictly-typed, case-sensitive kind of guy, just like C# :) I don't think it's a big deal for users to make their Dapper placeholders match the actual parameters; it also removes the ambiguity around what happens if there are two placeholders with the same case. I'd love for Npgsql to be in the same place as SQLite is now (fully case-sensitive), but an attempt to do that for 6.0 backfired pretty badly. I also specifically find it weird for the parameter collection to behave in one way, and for actual placeholder binding to behave in another way.

I've said my piece, if you guys still think it's important to do this (the issue only has two votes!), then that's fine by me...

2022-06-07 20:27 UTC, bricelam commented
@KevRitchie I'm still happy to take this change. Are you still interested in addressing the comments from [my review](https://github.com/dotnet/efcore/pull/26287#pullrequestreview-862928792)?

2022-06-09 21:44 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteParameterCollection.cs
> -                if (parameter.Bind(stmt))
Yes, for the error message that says which parameters weren't bound. Today, it just does a case-sensitive check:

https://github.com/dotnet/efcore/blob/b19c1e729fde2dc54ecc005dcd87272c905db888/src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs#L332-L335

2023-03-30 12:52 UTC, ajcvickers commented
Note from triage: closing this for now due to lack of activity. Happy to re-open if work resumes.

2023-03-30 12:52 UTC, closed without merging