Add Migration name check
dotnet/efcore pull request #26396
Opened 2021-10-18 19:14 UTC by KevRitchie

Summary of the changes:

- Add a check during the Validate method of MigrationsAddCommand to throw a CommandException when someone tries to call their migration "migration".
- Add a new resource "CircularBaseClassDependency" to notify the user that "You cannot add a migration with the name 'Migration'".

Fixes #23222

2021-11-02 21:05 UTC, bricelam approved these changes

2022-01-25 22:36 UTC, bricelam requested changes

2022-01-25 22:36 UTC, bricelam commented on src/ef/Commands/MigrationsAddCommand.cs
> +            }
We don't need this check since the one inside `MigrationsScaffolder` will be from hit here too.

2022-01-25 22:36 UTC, bricelam commented on src/ef/Properties/Resources.resx
> +  </data>
After removing the check in this assembly, this resource is no longer needed.

2022-02-28 22:08 UTC, bricelam approved these changes
LGTM

2022-04-04 21:46 UTC, Marusyk approved these changes

2022-05-18 20:46 UTC, AndriySvyryd commented
@bricelam Is there anything preventing this from being checked in apart from the conflict?

2022-05-19 20:59 UTC, bricelam commented
Nope, good to merge.

2022-05-19 23:45 UTC, merged

2022-05-19 23:45 UTC, AndriySvyryd commented
Thanks for your contribution