Change timer from method variable to property of SqlConnectioninteral
dotnet/efcore pull request #26495
Opened 2021-11-01 08:04 UTC by Dr-Ogden-Wernstrom

- [ ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ ] The code builds and tests pass locally (also verified by our automated build checks)
- [ ] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Code follows the same patterns and style as existing code in this repo

2021-11-01 08:04 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=26495) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=26495) before we can accept your contribution.<br/><br/>:x: Dr-Ogden-Wernstrom [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=26495)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=26495) it.</sub>

2021-11-01 11:02 UTC, vonzshik commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +        private IEnumerable<sqlite3_stmt> Statements
Taking into account the sheer size of this method, I'm not sure we should change it into a property. There is also a potential optimization here (raised in #26494), which doesn't look that great with it being a property.

2021-11-01 20:13 UTC, Dr-Ogden-Wernstrom commented on src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
> +        internal Stopwatch? Timer
Implemented as per your suggestion.

2021-11-01 20:13 UTC, Dr-Ogden-Wernstrom commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            var dataReader = new SqliteDataReader(this, _connection.Timer!, Statements, closeConnection);
Added the reset.

2021-11-01 20:13 UTC, Dr-Ogden-Wernstrom commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +        private IEnumerable<sqlite3_stmt> Statements
Reverted the conversion to a property.

2021-11-19 15:38 UTC, vonzshik approved these changes
Sorry for the wait, was a little bit busy with 6.0 release and other stuff. Looks, great, thank you!

2021-11-19 16:21 UTC, vonzshik commented
Benchmarked the change.

Before (main):

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 5 5600X, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=6.0.100
  [Host]     : .NET Core 6.0.0 (CoreCLR 6.0.21.52210, CoreFX 6.0.21.52210), X64 RyuJIT
  DefaultJob : .NET Core 6.0.0 (CoreCLR 6.0.21.52210, CoreFX 6.0.21.52210), X64 RyuJIT


```
|    Method |     Mean |   Error |  StdDev |        Op/s |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |---------:|--------:|--------:|------------:|-------:|------:|------:|----------:|
| SelectOne | 313.8 ns | 1.00 ns | 0.89 ns | 3,187,115.3 | 0.0186 |     - |     - |     312 B |


After (Dr-Ogden-Wernstrom:26295_SqliteTimerAsField):

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 5 5600X, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=6.0.100
  [Host]     : .NET Core 6.0.0 (CoreCLR 6.0.21.52210, CoreFX 6.0.21.52210), X64 RyuJIT
  DefaultJob : .NET Core 6.0.0 (CoreCLR 6.0.21.52210, CoreFX 6.0.21.52210), X64 RyuJIT


```
|    Method |     Mean |   Error |  StdDev |        Op/s |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |---------:|--------:|--------:|------------:|-------:|------:|------:|----------:|
| SelectOne | 299.0 ns | 1.73 ns | 1.44 ns | 3,344,267.4 | 0.0153 |     - |     - |     256 B |


<details>
<summary>Benchmark code</summary>

```csharp
public class Prepared
{
	private readonly SqliteCommand command;

	public Prepared()
	{
		var csb = new SqliteConnectionStringBuilder
		{
			DataSource = ":memory:",
		};

		var conn = new SqliteConnection(csb.ToString());
		conn.Open();

		command = conn.CreateCommand();
		command.CommandText = "SELECT 1";
		command.Prepare();
	}

	[Benchmark]
	[MethodImpl(MethodImplOptions.NoInlining)]
	public object? SelectOne() => command.ExecuteScalar();
}
```

</details>

2021-12-02 19:03 UTC, Dr-Ogden-Wernstrom commented
@vonzshik @bricelam Is there anything I need to do to get the PR completed?

2021-12-03 10:35 UTC, vonzshik commented
@Dr-Ogden-Wernstrom I'm afraid, we just have to wait for @bricelam to review: he's the one responsible for Sqlite from efcore team.

2021-12-03 10:38 UTC, Dr-Ogden-Wernstrom commented
Thanks @vonzshik. My first PR on GitHub so just wanted to make sure it wasn't sitting with me unawares.

2022-01-25 22:42 UTC, bricelam requested changes

2022-01-25 22:42 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
This doesn't seem right to me. A connection can have multiple readers open at the same time. I'm pretty sure we need a new instance for every reader...

2022-01-25 22:45 UTC, bricelam commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
Would using something like [ValueStopwatch](https://github.com/dotnet/aspnetcore/blob/main/src/Shared/ValueStopwatch/ValueStopwatch.cs) instead also help perf?

2022-01-26 00:09 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
In Npgsql we cache StopWatch on the physical (pooled) connection to reuse them. Maybe ValueStopWatch is a good solution too..

2022-01-26 09:36 UTC, roji commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
See https://github.com/dotnet/runtime/issues/48570 for some discussion on ValueStopWatch (which was closed for some reason).

If we don't do ValueStopWatch, we can still "pool" a single StopWatch instance on the connection, so that uses which don't involve multiple open readers can benefit (but those with multiple readers would allocatE).

2022-01-26 10:44 UTC, vonzshik commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
Okay, `ValueStopwatch` in a way it's implemented in ASP.NET Core wouldn't work here. The main offender is `SqliteDataReader`:
https://github.com/dotnet/efcore/blob/afe299fa586ea35eba6c937e1addf136e31410c4/src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs#L157-L173

Every time a `NextResult` is called on a reader the timer isn't reset, but continues to measure the elapsed time from where it left on a previous call.

2022-02-06 15:52 UTC, Dr-Ogden-Wernstrom commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
> If we don't do ValueStopWatch, we can still "pool" a single StopWatch instance on the connection, so that uses which don't involve multiple open readers can benefit (but those with multiple readers would allocate).

@roji Could this be something as simple as allocating a new Stopwatch if the connection has multiple commands like my latest change?

<hr/>

> Every time a `NextResult` is called on a reader the timer isn't reset, but continues to measure the elapsed time from where it left on a previous call.

@vonzshik My initial feeling is that adding stop/start functionality to ValueStopwatch would result in something almost the same as the standard Stopwatch implementation, so not much benefit. What do you think?

2022-02-07 15:46 UTC, vonzshik commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
> @vonzshik My initial feeling is that adding stop/start functionality to ValueStopwatch would result in something almost the same as the standard Stopwatch implementation, so not much benefit. What do you think?

Well, there is the fun fact that both `SqliteCommand.PrepareAndEnumerateStatements` and `SqliteDataReader.NextResult` are supposed to use the exact same instance of `Stopwatch` and the result from `SqliteCommand.PrepareAndEnumerateStatements` is passed as `IEnumerable` to the reader...

https://github.com/dotnet/efcore/blob/802d4c5d18e18afbd6d0a0eb9d3165c16c8bf33f/src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs#L313

2022-02-21 21:44 UTC, Dr-Ogden-Wernstrom commented on src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> +            _connection.Timer.Reset();
Hey @vonzshik, that is a fun fact. 
Sorry, I've been so slow getting to this, and for being a total noob on this project, but would you mind taking another look, please.

2022-06-07 22:58 UTC, bricelam commented
&nbsp;                | Before | After
--------------------- | ------ | -----
**CPU Usage (%)**     | 54     | 57
**Working Set (MB)**  | 394    | 396
**Requests/sec**      | 29,055 | 28,704
**Mean latency (ms)** | 8.83   | 8.92

2022-06-08 06:48 UTC, vonzshik commented
@bricelam that's interesting, since I do see a small improvements in a simple benchmark

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1706 (21H2)
AMD Ryzen 5 5600X, 1 CPU, 12 logical and 6 physical cores
.NET SDK=7.0.100-preview.4.22252.9
  [Host]     : .NET 7.0.0 (7.0.22.22904), X64 RyuJIT
  DefaultJob : .NET 7.0.0 (7.0.22.22904), X64 RyuJIT


```

From

|    Method |     Mean |   Error |  StdDev |        Op/s |  Gen 0 | Allocated |
|---------- |---------:|--------:|--------:|------------:|-------:|----------:|
| SelectOne | 277.5 ns | 0.70 ns | 0.59 ns | 3,603,227.7 | 0.0186 |     312 B |

To

|    Method |     Mean |   Error |  StdDev |        Op/s |  Gen 0 | Allocated |
|---------- |---------:|--------:|--------:|------------:|-------:|----------:|
| SelectOne | 274.8 ns | 0.86 ns | 0.81 ns | 3,639,623.7 | 0.0162 |     272 B |

<details>
<summary>Code</summary>

```csharp
public class Prepared
{
	private readonly SqliteCommand command;

	public Prepared()
	{
		var csb = new SqliteConnectionStringBuilder
		{
			DataSource = ":memory:",
		};

		var conn = new SqliteConnection(csb.ToString());
		conn.Open();

		command = conn.CreateCommand();
		command.CommandText = "SELECT 1";
		command.Prepare();
	}

	[Benchmark]
	[MethodImpl(MethodImplOptions.NoInlining)]
	public object? SelectOne() => command.ExecuteScalar();
}
```

</details>

Though, the main point here was to reduce allocations, which it does. To improve the rps, I was thinking on rewriting [SqliteCommand.GetStatements](https://github.com/dotnet/efcore/blob/3f8febf417136567d6c1f2ec7043c7ab3dfa8bef/src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs#L319) to something like this:

```csharp
private IEnumerable<sqlite3_stmt> GetStatements(Stopwatch timer)
{
	if (_prepared)
	{
		for (var statementIndex = 0; statementIndex < _preparedStatements.Count; statementIndex++)
		{
			(var stmt, var expectedParams) = _preparedStatements[statementIndex];

			yield return GetStatementsCore(stmt, expectedParams, _parameters, timer);
		}
	}
	else
	{
		foreach ((var stmt, var expectedParams) in PrepareAndEnumerateStatements(timer))
		{
			yield return GetStatementsCore(stmt, expectedParams, _parameters, timer);
		}
	}

	static sqlite3_stmt GetStatementsCore(sqlite3_stmt stmt, int expectedParams, SqliteParameterCollection? parameters, Stopwatch timer)
	{
		var boundParams = parameters?.Bind(stmt) ?? 0;

		if (expectedParams != boundParams)
		{
			var unboundParams = new List<string>();
			for (var i = 1; i <= expectedParams; i++)
			{
				var name = sqlite3_bind_parameter_name(stmt, i).utf8_to_string();

				if (parameters != null
					&& !parameters.Cast<SqliteParameter>().Any(p => p.ParameterName == name))
				{
					unboundParams.Add(name);
				}
			}

			if (sqlite3_libversion_number() < 3028000 || sqlite3_stmt_isexplain(stmt) == 0)
			{
				throw new InvalidOperationException(Resources.MissingParameters(string.Join(", ", unboundParams)));
			}
		}

		return stmt;
	}
}
```

Which gives a nice rps bump, while also reducing allocations:

|    Method |     Mean |   Error |  StdDev |        Op/s |  Gen 0 | Allocated |
|---------- |---------:|--------:|--------:|------------:|-------:|----------:|
| SelectOne | 256.9 ns | 0.89 ns | 0.84 ns | 3,893,317.3 | 0.0138 |     232 B |



> Before	After
> **CPU Usage (%)**	54	57
> **Working Set (MB)**	394	396
> **Requests/sec**	29,055	28,704
> **Mean latency (ms)**	8.83	8.92

I assume you were running [Orchard](https://github.com/aspnet/Benchmarks/tree/main/scenarios#orchard-benchmarks) benchmark? I'll try to take a look in the next few days.

2022-06-13 11:03 UTC, ajcvickers commented
@vonzshik We really appreciate your work on this, but we discussed this as a team, and given the code is a little more complex and the performance results are not compelling, we have decided not to merge this.

2022-06-13 11:03 UTC, closed without merging