Add AtTimeZoneExpression and some relevant translations
dotnet/efcore pull request #26972
Opened 2021-12-12 11:54 UTC by roji

* Adds AtTimeZoneExpression support to relational, along with support in QuerySqlGenerator, SqlNullabilityProcessor.
* Adds SQL Server translation support for TimeZoneInfo.ConvertTimeBySystemTimeZoneId (datetimeoffset -> datetimeoffset)
* Adds SQL Server-specific EF.Functions.AtTimeZone for datetime/datetime2 -> datetimeoffset

Closes #26199
Closes #26971

2021-12-14 22:38 UTC, smitpatel commented
Build failing.
> TimeZoneInfo.ConvertTimeBySystemTimeZoneId

Does string timezone identifier C# always matches the Server side strings? If not, we should add translation for this. `EF.Functions` one is fine since it corresponds to server always.

2021-12-14 22:46 UTC, roji commented
> Does string timezone identifier C# always matches the Server side strings? If not, we should add translation for this. EF.Functions one is fine since it corresponds to server always.

Here's what the [docs say](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.converttimebysystemtimezoneid?view=net-6.0#System_TimeZoneInfo_ConvertTimeBySystemTimeZoneId_System_DateTime_System_String_):

> This method retrieves information on the time zone whose identifier is specified by the destinationTimeZoneId parameter from the registry on Windows systems and from the ICU Library on Linux and macOS.

So the interpretation of that string on .NET is platform-dependent, based on whether on Windows or Linux - so even in puer .NET this parameter isn't cross-platform. I think the method corresponds well for this translation (I've also done this for PG), but I can change to EF.Functions if you think that's better.

2022-01-12 20:57 UTC, bricelam commented
🤔 I wonder if we should translate `localtime` and `utc` on SQLite. Probably a bit of a stretch...

2022-01-12 21:59 UTC, roji commented
Don't forget there's [DateTime.ToUniversalTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.touniversaltime?view=net-6.0#system-datetime-touniversaltime) and [ToLocalTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tolocaltime?view=net-6.0), should we just translate those? That seems like a pretty good fit if SQLite does the right thing...

Otherwise if we have to do it on EF.Functions, I'd go with two different functions rather than a string parameter (e.g. AtUtc, AtLocalTime)

2022-01-12 23:34 UTC, roji commented
@smitpatel updated PR ready for review

2022-01-28 21:55 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +    public virtual async Task Where_AtTimeZone_datetimeoffset_constant()
conditional theory.

2022-03-11 22:30 UTC, stevendarby commented
Does this function work when the time zone is a column, and if so is it worth adding a test for that? I read a good blog on storing time zones in the database... 😃

2022-04-14 08:53 UTC, sommmen commented
Any reason this is still not merged in or?

2022-05-19 16:32 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/AtTimeZoneExpression.cs
> +    ///     The left operand.
check docs in this and timezone

2022-05-19 16:43 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                _sqlExpressionFactory.ApplyDefaultTypeMapping(timeZone),
Looking at t-sql docs, timezone is just string. Though it is not unicode string so "N'" is unnecessary.
- Should we support parameter (based on test looks like it is working but SqlServer example not mentioning it). This would be similar to language term in freetext which has to be constant in t-sql. I am fine either way.
- The name needs to be quoted at the least. If it is just constant then we can use sqlfragment too (though need to do something about quoting to avoid sql injection). Or we can just assign type mapping (which always do appropriate thing for sql inject but assign non-unicode type mapping explicitly here rather than default one.

2022-05-19 16:46 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                _typeMappingSource.FindMapping(typeof(DateTimeOffset)));
Should we assign typemapping here or should it be inferred from outside (if this is top level we assign default anyway).
Hypothetical scenario
`a + (b + c)` where `c` is our above translation and `a` is column with type mapping. If we assign type mapping here then b will take default from here rather than b/c taking type mapping from a which could be more appropriate.

2022-05-19 16:46 UTC, smitpatel requested changes
Minor comments

2022-05-24 08:38 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                _sqlExpressionFactory.ApplyDefaultTypeMapping(timeZone),
> Should we support parameter [...]

Yeah, I figured that if it works, let's support it... Non-constant time zone could be important for various usages - a typical usage would to store the time zone in a column next to the UTC timestamp, so that it can vary across rows.

> [...] but assign non-unicode type mapping explicitly here rather than default one.

But what about Unicode timezone names :trollface: 

Assigned non-unicode mapping, dropping the N does look nicer.

2022-05-24 08:45 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +    public virtual async Task Where_AtTimeZone_datetimeoffset_constant()
Did you mean to make it a theory for constant/parameter/column, or something else (do we really want to have a single theory with different results/SQL baselines rather than just different tests)?

2022-05-24 14:55 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                _typeMappingSource.FindMapping(typeof(DateTimeOffset)));
The scenario you mentioned is comparison so if neither side has type mapping then it will get default one for the type. expression.Type is DateTimeOffset and default of that we need to assign then inference would work fine for that.
Isn't datetimeoffset time on SqlServer has different precision or is it datetime thing only?

2022-05-24 14:58 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +    public virtual async Task Where_AtTimeZone_datetimeoffset_constant()
Example pattern for non AssertQuery tests
https://github.com/dotnet/efcore/blob/3ff83c4516e715147c39122813020243c2c8c8f2/test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs#L149-L154

2022-05-24 16:02 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                _typeMappingSource.FindMapping(typeof(DateTimeOffset)));
Good questions.

Yeah, datetimeoffset does support precision and scale ([docs](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-ver16)); and it bubbles up those facets from the operand (for both datetime2 and datetimeoffset operands).

So if I'm getting things right, that means that if the operand has a type mapping (column), we should bubble it up (and for datetime/datetime2 mapping, bubble up the facets and return the appropriate datetimeoffset mapping. But if the operand has no mapping, we shouldn't set a result mapping to allow it to be inferred from the outside.

Does that sound good? If so I'll implement that.

2022-05-24 16:07 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                _typeMappingSource.FindMapping(typeof(DateTimeOffset)));
For reference, here's the T-SQL with the investigation:

```sql
-- Default precision/scale for datetimeoffset is 34, 7
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset), 'BaseType'); -- datetimeoffset
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset), 'Precision'); -- 34
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset), 'Scale'); -- 7

-- datetimeoffset with non-default precision/scale
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset(2)), 'BaseType'); -- datetimeoffset
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset(2)), 'Precision'); -- 29
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset(2)), 'Scale'); -- 2

-- AT TIME ZONE with datetimeoffset operand - bubbles up precision/scale
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset(2)) AT TIME ZONE 'UTC', 'Precision'); -- 29
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00+02:00' AS datetimeoffset(2)) AT TIME ZONE 'UTC', 'Scale'); -- 2

-- AT TIME ZONE with datetimeoffset operand - bubbles up precision/scale
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00' AS datetime2(2)) AT TIME ZONE 'UTC', 'Precision'); -- 29
SELECT SQL_VARIANT_PROPERTY(CAST('2020-01-01T12:00:00' AS datetime2(2)) AT TIME ZONE 'UTC', 'Scale'); -- 2
```

2022-05-24 18:31 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +    public virtual async Task Where_AtTimeZone_datetimeoffset_constant()
Ah, understood - sure.

2022-05-24 19:36 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                _typeMappingSource.FindMapping(typeof(DateTimeOffset)));
OK, I went ahead and implemented bubbling of precision - in both directions. This means that for `x.SomeColumn == EF.Functions.AtTimeZone(someParam, "UTC")`, someParam will get SomeColumn's precision, just as if it's compared directly without AtTimeZone. This stuff may be important - I'm not sure how SQL Server behaves when comparing datetimeoffsets with different precisions...

Note that there's now a SqlServerSqlExpressionFactory to have the specific bubbling logic. This is a bit more complicated than I originally thought, let me know what you think and if we should simplify.

2022-05-24 20:39 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlExpressionFactory.cs
> +            ApplyTypeMapping(atTimeZoneExpression.Operand, operandTypeMapping),
short if operandTypeMapping is null.

2022-05-24 20:55 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                        return null;
Should we return null or just ignore that we couldn't bubble type mapping properly? Latter gives chance to query to work.

2022-05-24 20:56 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +        Assert.Equal(2, Assert.Single(missions).Id);
Use mission.

2022-05-24 20:56 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> +        Assert.Equal(2, Assert.Single(missions).Id);
same in other tests

2022-05-24 20:57 UTC, smitpatel approved these changes

2022-05-24 21:37 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                        return null;
I guess you're right (though not sure which scenario that would be), changing.

2022-05-24 21:48 UTC, smitpatel commented
Did you remove SqlServerSqlExpressionFactory?

2022-05-24 22:45 UTC, roji commented
Nope, just botched the squashing...

2022-05-24 22:45 UTC, merged