Update tool to require .NET 6 at minimum.
dotnet/efcore pull request #27671
Opened 2022-03-20 07:14 UTC by AraHaan

This is needed otherwise it will try to require ".NET 2.0 Runtime" to be installed, which can cause roll forward to fail to load 6.0.0's System.Runtime. Discovered at: https://github.com/dotnet/efcore/issues/27660#issuecomment-1073184551

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ ] The code builds and tests pass locally (also verified by our automated build checks) **Unkown, change done on the github website.**
- [ ] Commit messages follow this format: **Not yet, not sure if this change will fully fix the issue I face in #27660.**
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features) **N/A**
- [x] Code follows the same patterns and style as existing code in this repo **(tool projects TFM change)**

2022-03-20 11:56 UTC, AraHaan commented
Welp just tested these changes and it looks like there is 1 more place where it expects ef.dll in ``.nuget\packages\dotnet-ef\7.0.0-dev\tools\net6.0\any\tools\netcoreapp2.0\any\`` :pensive:

2022-03-20 13:00 UTC, AraHaan commented
@roji does this look good to you on the fix for my issue?

2022-03-22 19:24 UTC, bricelam requested changes
Most of these changes seem unnecessary and won't actually address the issue you're seeing.

2022-03-22 20:39 UTC, AraHaan commented
The change works.

2022-03-23 07:17 UTC, AraHaan commented
@bricelam I have completed the requested changes and verified that they work still on fixing the issue.

2022-03-25 12:08 UTC, AraHaan commented
Now the github actions check should be rerun and it *should* pass.

2022-03-28 09:56 UTC, merged

2022-03-28 09:57 UTC, ajcvickers commented
Merged following team review. Cosmos failure was a known issue.

Thanks @AraHaan.