Translate spatial aggregates
dotnet/efcore pull request #28115
Opened 2022-05-27 12:55 UTC by roji

Closes #13278

2022-05-27 12:56 UTC, roji commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            typeof(Geometry));
Need to look at the type mapping here - though no database implements these aggregate functions for geography, as far as I know.

2022-05-27 15:44 UTC, smitpatel commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +        var functionName = method == GeometryCombineMethod
ouch!! I didn't expect this from you!
Use switch expression.

2022-05-27 15:45 UTC, smitpatel commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            typeof(Geometry));
I think you should also verify somewhere that sqlExpression has geometry type mapping only and (it had spatial type mapping for sure). Though @bricelam would know better.

2022-05-27 15:46 UTC, smitpatel commented on src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
> +            || (method != GeometryCombineMethod && method != UnionMethod && method != ConvexHullMethod))
Why use different patterns in 2 providers in same PR. 😉

2022-05-27 15:47 UTC, smitpatel commented
Amazing. 🎉

2022-05-27 15:53 UTC, roji commented on src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
> +            || (method != GeometryCombineMethod && method != UnionMethod && method != ConvexHullMethod))
Only because in SQLite we need to compose the additional Collect before doing ST_ConvexHull...

2022-05-27 16:50 UTC, bricelam commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            typeof(Geometry));
They're valid for both [geometry](https://docs.microsoft.com/sql/t-sql/spatial-geometry/envelopeaggregate-geometry-data-type) and [geography](https://docs.microsoft.com/sql/t-sql/spatial-geography/envelopeaggregate-geography-data-type) on SQL Server.

2022-05-27 17:16 UTC, bricelam requested changes
So cool to see this. EF6 never had them!

2022-05-27 17:16 UTC, bricelam commented on src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
> +        // Spatialite has no built-in aggregate convex hull, but we can simply apply Collect beforehand
Personally, I don't think we should translate this on SQLite. I'd rather just force users to write `GeometryCombiner.Combine(geoms).ConvexHull()` themselves.

2022-05-27 17:16 UTC, bricelam commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
> +    public IEnumerable<IAggregateMethodCallTranslator> Translators { get; }
(SQLite too)

2022-05-27 17:16 UTC, bricelam commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +        = typeof(UnaryUnionOp).GetRuntimeMethod(nameof(UnaryUnionOp.Union), new[] { typeof(IEnumerable<Geometry>) })!;
(SQLite too)

2022-05-27 17:16 UTC, bricelam commented on src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
> +                    argumentsPropagateNullability: new[] { false },
Also technically `true`.

2022-05-27 17:16 UTC, bricelam commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +                var eCollection = (GeometryCollection)e.Combined;
Cast e.Point to Geometry above instead?

2022-05-27 17:16 UTC, bricelam commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +                Assert.Equal(eLineString.Coordinates.OrderBy(p => p), aLineString.Coordinates.OrderBy(p => p));
I think we handle this differently in other tests. Was it a custom Geometry comparer?

2022-05-27 17:16 UTC, bricelam commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +                Assert.Equal(eLineString.Coordinates.OrderBy(p => p), aLineString.Coordinates.OrderBy(p => p));
(Below too)

2022-05-27 17:16 UTC, bricelam commented on test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
> +    // No SqlServer Translation
These should be `geography::CollectionAggregate()`, etc.

2022-05-27 17:22 UTC, bricelam commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            typeof(Geometry));
Note, the result of `geography::EnvelopeAggregate` will fail to serialize on the client since it contains curves. But I still think we should translate it so you can use it as a sub-expression to other queries. Adding `EF.Functions.CurveToLine()` (or telling users to map `STCurveToLine` manually) would also provide a decent workaround.

2022-05-27 17:25 UTC, bricelam commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +                var eCollection = (GeometryCollection)e.Combined;
...never mind, I see what you mean.

2022-05-27 18:21 UTC, smitpatel commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            argumentsPropagateNullability: new[] { false },
![image](https://user-images.githubusercontent.com/1528107/170768548-8e86cbcb-6e79-43f4-ae46-27e39ace638f.png)
Potentially could apply, if all args are null some of them return null results (if I understand correctly)

2022-05-27 18:40 UTC, bricelam commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            typeof(Geometry));
Sumbitted PR #28118 for CurveToLine

2022-05-27 18:54 UTC, roji commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +        = typeof(UnaryUnionOp).GetRuntimeMethod(nameof(UnaryUnionOp.Union), new[] { typeof(IEnumerable<Geometry>) })!;
Envelope turned out a bit problematic :cry:: https://github.com/dotnet/efcore/issues/13278#issuecomment-1139593123

Let me know if I'm missing some creative idea here...

2022-05-27 19:02 UTC, roji commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            argumentsPropagateNullability: new[] { false },
I wondered about this too (note that for the standard aggregate operators [we do this as well](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/Internal/QueryableAggregateMethodTranslator.cs)).

It's true that most aggregate methods return null when there are no rows or all values are null (that's why nullable is true). But I'm not sure it makes sense to say that the enumerable argument *itself* can be null or that it can be propagated - that's a different thing.  That seems to correspond to this non-sensical SQL:

```sql
SELECT MAX(null) FROM data;
```

... which I don't think we'd ever generate, and which errors with "Operand data type NULL is invalid for max operator" on SQL Server (but does return null on PG). In any case, IIRC the idea of  argumentsPropagateNullability is to allow us to optimize away the function call when we know that a null-propagating argument is null - but once again I don't think we'd ever generate SQL with NULL in the place of the enumerable argument.

In any case, we can split out to a separate issue and discuss if we feel there's a problem here, /cc @smitpatel @maumar

2022-05-27 19:04 UTC, bricelam commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            argumentsPropagateNullability: new[] { false },
Yeah, I have no idea what `argumentsPropagateNullability` means or how its used in the context of aggregate functions. And are empty set semantics a thing? So many questions...

2022-05-27 19:05 UTC, roji commented on src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
> +        // Spatialite has no built-in aggregate convex hull, but we can simply apply Collect beforehand
I don't feel very strongly about it, but it seems like a nice shortcut given that NTS happens to have that exact method... i.e. I wouldn't have proposed adding an EF.Functions thing, but given that it's already there...

2022-05-27 19:05 UTC, roji commented on src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
> +                    argumentsPropagateNullability: new[] { false },
Yeah, we should decide about this for aggregates in general as per https://github.com/dotnet/efcore/pull/28115#discussion_r883911178

2022-05-27 19:10 UTC, bricelam commented on src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
> +        // Spatialite has no built-in aggregate convex hull, but we can simply apply Collect beforehand
Hmm, I guess there's value in making it work cross-provider. Keep it.

2022-05-27 19:17 UTC, roji commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            typeof(Geometry));
> They're valid for both [geometry](https://docs.microsoft.com/sql/t-sql/spatial-geometry/envelopeaggregate-geometry-data-type) and [geography](https://docs.microsoft.com/sql/t-sql/spatial-geography/envelopeaggregate-geography-data-type) on SQL Server.

Oh thanks, missed that.

2022-05-27 19:21 UTC, roji commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +                Assert.Equal(eLineString.Coordinates.OrderBy(p => p), aLineString.Coordinates.OrderBy(p => p));
You're right - as in the existing ConvexHull test (GeometryComparer.InstancE)

2022-05-27 19:29 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
> +    // No SqlServer Translation
Works like a charm.

2022-05-27 20:34 UTC, roji commented
FYI corresponding support for PostGIS: https://github.com/npgsql/efcore.pg/pull/2383/commits/f77330d3e0b8eff0f8f8573802af29d7732005bf

2022-05-27 21:09 UTC, bricelam approved these changes

2022-05-27 21:37 UTC, roji commented
@smitpatel will hold off merging for a bit in case you have further comments.

2022-05-28 19:05 UTC, roji commented
BTW @bricelam PostGIS has a few more spatial aggregate functions: https://postgis.net/docs/PostGIS_Special_Functions_Index.html#PostGIS_Aggregate_Functions

2022-06-04 17:20 UTC, roji commented
FYI holding off merging this until we decide on top-level aggregate strategy, as per https://github.com/dotnet/efcore/issues/28104#issuecomment-1142427678.

2022-06-18 15:43 UTC, roji commented
@smitpatel now that we've excluded top-level aggregates (https://github.com/dotnet/efcore/issues/28264), I think we can come back to this (@bricelam approved for the spatial side but maybe you have comments on the query aggregate side).

2022-06-20 23:02 UTC, smitpatel commented on src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
> +            _typeMappingSource.FindMapping(typeof(Geometry), storeType));
Validate that sqlExpression has TypeMapping assigned (like other method/member translators in NTS. If you want to default fallback to geometry then assign the type mapping to sqlExpression first and then just propagate here.

2022-06-21 16:23 UTC, smitpatel commented on src/Shared/Check.cs
> +        => throw new Exception($"Check.DebugAssert failed: {message}");
Message points to DebugAssert :/

2022-06-21 16:23 UTC, smitpatel approved these changes

2022-06-21 18:54 UTC, merged