Cosmos: Add translator for Regex.IsMatch method
dotnet/efcore pull request #28121
Opened 2022-05-28 00:06 UTC by Marusyk

Add translator for Regex.IsMatch method to [REGEXMATCH](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-regexmatch)

Adding support of RegexOptions is in progress.

Fixes #28078

2022-05-28 00:15 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
>                  new CosmosStringMethodTranslator(sqlExpressionFactory),
Shouldn't we rename it to `StringMethodTranslator`?

2022-05-28 00:17 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            typeof(Regex).GetRuntimeMethod(nameof(Regex.IsMatch), new[] { typeof(ReadOnlySpan<char>), typeof(string) })!
Does it make sense to add `ReadOnlySpan<char>`? There are not tests for this

2022-05-28 07:59 UTC, roji requested changes
Thanks, it's nice to see this!

In addition to the below, please take a look at the regex options as suggested by @AndriySvyryd (https://github.com/dotnet/efcore/issues/28078#issuecomment-1137549557) - there seems to be at least some correspondence with the .NET API here.

Note that we'd only support constant regex options, which we can interpret at compile-time and translate to the appropriate Cosmos constant string. [The PostgreSQL translator](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRegexIsMatchTranslator.cs) may provide some help.

2022-05-28 07:59 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            typeof(Regex).GetRuntimeMethod(nameof(Regex.IsMatch), new[] { typeof(ReadOnlySpan<char>), typeof(string) })!
We can, though I'm not sure where `ReadOnlySpan<char>` would be useful in an expression tree... This overload is useful in cases where you want to avoid needless string allocations in .NET, but that doesn't apply to expression trees being translated to SQL. I don't think we translate any other `ROS<char>` string methods, so I'd leave that out for now - if needed we can go over them all in a separatep pass.

2022-05-28 07:59 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +                typeMapping);
This doesn't seem right - RegexMatch returns a bool, not a string.

2022-05-28 07:59 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
>                  new CosmosStringMethodTranslator(sqlExpressionFactory),
I think more the other way - the [SQL Server](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs) and [SQLite](https://github.com/dotnet/efcore/blob/main/src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs) translators always have the provider prefix.

2022-05-28 07:59 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            var newArguments = arguments.Select(e => _sqlExpressionFactory.ApplyTypeMapping(e, typeMapping));
For 2 arguments I'd just lay out the arguments and call ApplyTypeMapping inside the Function call below (see other translators).

2022-05-28 07:59 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            var typeMapping = arguments.Count == 2
I don't think the 3rd argument (regex options) should be inferred - just make it the default string type mapping.

2022-05-28 22:44 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
>                  new CosmosStringMethodTranslator(sqlExpressionFactory),
agree. Should it be in a separate PR?

2022-05-28 22:50 UTC, Marusyk commented
Thanks for the review, but it's not ready yet (Draft status). I'm almost done with RegexOptions:

> Adding support of RegexOptions is in progress.

2022-05-28 23:03 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            var typeMapping = arguments.Count == 2
ok, well in this way we don't need something like [SqlRegexMatchExpression](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Query/Expressions/Internal/PostgresRegexMatchExpression.cs)

2022-05-28 23:03 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +                typeMapping);
method.ReturnType is bool

2022-05-29 08:31 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
>                  new CosmosStringMethodTranslator(sqlExpressionFactory),
I think it's OK to rename the types here if you want to.

2022-05-29 08:33 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +                typeMapping);
I'm referring to the type mapping. In the latest version of the PR it's `stringTypeMapping`, which doesn't match bool.

As a sidenote/nit: I personally prefer embedding the type name (`typeof(bool)`) when we know it, rather than method.ReturnType which is slightly less explicit.

2022-05-29 08:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +        var stringTypeMapping = ExpressionExtensions.InferTypeMapping(input, pattern);
You're not actually applying the inferred type mapping to the arguments (input and pattern).

2022-05-29 08:39 UTC, roji requested changes

2022-05-29 08:39 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +    private static readonly ISet<RegexOptions> AllowedOptions = new HashSet<RegexOptions>
You already have a switch below translating the RegexOptions to a Cosmos options string, this Set shouldn't be needed

2022-05-29 08:39 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            new[] { input, pattern, _sqlExpressionFactory.Constant(modifier) },
It would be better not to pass an empty argument when RegexMatch is called without options.

2022-05-29 08:39 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +        string modifier = options switch
What about multiple options being specified?

2022-05-29 14:04 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +    private static readonly ISet<RegexOptions> AllowedOptions = new HashSet<RegexOptions>
we don't need it for validation to return `null`?

2022-05-29 14:06 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            new[] { input, pattern, _sqlExpressionFactory.Constant(modifier) },
what is the reason? The [docs](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-regexmatch) says that it is ok

>  If you'd like to run RegexMatch with no modifiers, you can either add an empty string or omit entirely.

2022-05-29 14:07 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +        string modifier = options switch
good point, thx

2022-05-29 14:19 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            new[] { input, pattern, _sqlExpressionFactory.Constant(modifier) },
Sure, but omitting the argument would be better than an empty string (terser/clearer SQL).

2022-05-29 14:23 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +            new[] { input, pattern, _sqlExpressionFactory.Constant(modifier) },
ok, I'll update

2022-05-29 15:08 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +    private static readonly ISet<RegexOptions> AllowedOptions = new HashSet<RegexOptions>
I'm just not sure you'll need the supported options to be listed twice, once in this Set and again in the switch below - the exact code will likely look different once you implement the multiple options.

2022-05-29 16:59 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +    private static readonly ISet<RegexOptions> AllowedOptions = new HashSet<RegexOptions>
ok then, what behavior is expected when I specify the unsupported option like `RegexOptions.RightToLeft`? Ignore it and use "" or `InvalidOperationException`?

2022-05-29 18:20 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/SqlRegexMatchExpression.cs
> +public class SqlRegexMatchExpression : SqlExpression, IEquatable<SqlRegexMatchExpression>
Is this needed? In Cosmos regex is just a simple function call, not a special expression...

2022-05-29 18:21 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
> +                modifier += option switch
Your switch could return a `char?`, with unsupported options (default) returning null. Then, if you get null out, you know the option is unsupported without an additional AllowedOptions set check.

2022-05-29 18:23 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
> +                modifier += option switch
Another simpler option here - instead of GetValues above with Where - is to simply check with HasFlags for each option we support, adding the appropriate character. A check for unsupported options would just turn off the supported bits and checking if the result is non-zero.

2022-05-29 18:33 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/SqlRegexMatchExpression.cs
> +public class SqlRegexMatchExpression : SqlExpression, IEquatable<SqlRegexMatchExpression>
oops, no sorry

2022-05-29 18:37 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
> +                modifier += option switch
why `char?`, what about `ix` and other combinations?

2022-05-29 18:42 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
> +    private static readonly ISet<RegexOptions> AllowedOptions = new HashSet<RegexOptions>
No - we do need to return null for unsupported options. I'm just suggesting not having an additional AllowedOptions Set for checking that, since you already have to convert the options one by one anyway from RegexOptions to Cosmos's string.

2022-05-29 19:06 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
> +                modifier += option switch
I'm not sure that I understood you correctly. Do you mean
string modifier = "";

            if (options.HasFlag(RegexOptions.Multiline))
            {
                modifier += "m";
            }
            if (options.HasFlag(RegexOptions.Singleline))
            {
                modifier += "s";
            }
            if (options.HasFlag(RegexOptions.IgnoreCase))
            {
                modifier += "i";
            }
            if (options.HasFlag(RegexOptions.IgnorePatternWhitespace))
            {
                modifier += "x";
            }

2022-05-29 19:36 UTC, Marusyk commented
I have no idea what 2 tests start failing. It works in the previous commit and there are no changes related to count

2022-05-29 19:37 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
> +                modifier += option switch
Yep, I'd personally write it like that - just checking the options one by one seems simplest/clearest.

For the unsupported check, the pattern of supported options (`RegexOptions.Multiline | RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.IgnorePatternWhitespace`) can go in a const. Note that RegexOptions.None is the absence of options, so you don't need to include that.

2022-05-29 21:58 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
> +                        _sqlExpressionFactory.Constant(modifier, typeMapping)
It probably doesn't matter, but I'm not sure it makes sense to apply the inferred type mapping here - the options string is just that, a string - regardless of the type mapping of the other two operands. So I'd just apply the default type mapping for string.

2022-05-29 22:08 UTC, Marusyk commented on src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
> +                        _sqlExpressionFactory.Constant(modifier, typeMapping)
`_sqlExpressionFactory.Constant(modifier)` right?

2022-05-30 08:17 UTC, roji approved these changes
Thanks @Marusyk!

2022-05-30 08:17 UTC, merged

2022-06-01 14:46 UTC, smitpatel commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +            ss => ss.Set<Customer>().Where(o => Regex.IsMatch(o.CustomerID, "^T", RegexOptions.IgnoreCase | RegexOptions.IgnorePatternWhitespace)),
Should we consider case where regex options are passed as a variable here so it won't be constant. We can force "constantization" in parameter extraction through evaluatablefilter.

2022-06-02 08:34 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +            ss => ss.Set<Customer>().Where(o => Regex.IsMatch(o.CustomerID, "^T", RegexOptions.IgnoreCase | RegexOptions.IgnorePatternWhitespace)),
Right, we definitely can... Added that to #28139.

2022-06-02 08:35 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +WHERE ((c[""Discriminator""] = ""Customer"") AND RegexMatch(c[""CustomerID""], ""^T"", """"))");
I'd go with Smit's suggestion, always better to emit clearer, more concise SQL. Added to #28139.

2022-06-02 09:56 UTC, Marusyk commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +WHERE ((c[""Discriminator""] = ""Customer"") AND RegexMatch(c[""CustomerID""], ""^T"", """"))");
ok, assign 28139 to me

2022-06-17 15:37 UTC, smitpatel commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +    [Fact]
ConditionalTheory
sync/async both version
Use `AssertQuery` syntax

cc: @roji

2022-06-17 15:39 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> +    [Fact]
Yep, doing as part of #28139