Json Columns initial work
dotnet/efcore pull request #28171
Opened 2022-06-07 00:44 UTC by maumar

Finished work:
- basic metadata,
- property/navigation access translation,
- materialization (entity, collection, with nesting)

Remaining work:
- validation,
- migration,
- update,
- collections of primitives,
- array access/operations (force non-tracking!)
- some metadata fixes (e.g. using actual type mapping for properties mapped to json, rather than default mappings), flowing json type info (npgsql),
- honoring json property name attribute for custom naming,
- custom serialization (???),
- lots of fixes, cleanups, documentation,
- testing

2022-06-07 15:59 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
> +    //protected override Expression VisitJsonMappedPropertyExpression(JsonMappedPropertyExpression jsonMappedPropertyExpression)
removed commented code

2022-06-07 16:00 UTC, smitpatel commented on src/EFCore.Relational/Query/QuerySqlGenerator.cs
> +        => jsonPathExpression;
This should either have default printing or throw.

2022-06-07 16:01 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonPathExpression.cs
> +    public class JsonPathExpression : SqlExpression
Split this into 2 different expressions scalar/non-scalar.
Does non-scalar has anything other than entity type as result?

2022-06-07 16:02 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            case JsonCollectionResultExpression jsonCollectionResultExpression:
If collection result expression is not needed here then this shouldn't be either. What is the case where you are visiting this?

2022-06-07 16:06 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                    var table = FindTable(navigation, entityType);
You shouldn't need to find the table

2022-06-07 16:09 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                    var jsonColumn = table.Columns.Single(x => x.Name == jsonColumnName);
Since JSON here is always owned and they are auto-included always, the parent entity type shaper/projection expression should already contain the json column (which would be on ITableBase).

2022-06-07 16:12 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                    var jsonProjectionExpression = _selectExpression.GenerateJsonProjectionExpression(
Remove this function, utilize the entity projection and do processing on that.

2022-06-07 16:14 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                        var jsonColumnName = targetEntityType.MappedToJsonColumnName();
Similar to collection case, remove this way of processing.

Also make structure as inner level fork on collection and outer on mappedtojson

2022-06-07 16:17 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                            && materializeCollectionNavigationExpression.Subquery is MethodCallExpression methodCallSubquery
What is the tree here that inner subquery is methodcall?
In very base case it would be JsonCollectionResult. Do we have test for it? (when entity has only one owned collection without nesting)

2022-06-07 16:19 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                                && RemoveJsonIncludes(selectLambda.Body) == selectLambda.Parameters[0])
MaterializeCollection only happens for collection navigations. So any includes on top of it has to be owned only. If other includes are arising then either we should find a way to translate it or throw in translationpreprocessor.

2022-06-07 16:20 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                        return QueryCompilationContext.NotTranslatedExpression;
why don't we allow projection member based binding? EntityProjection allows it.

2022-06-07 16:23 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
> +            if (entityType.MappedToJson())
Move this check for line 93 set.

2022-06-07 16:26 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonProjectionExpression.cs
> +                throw new InvalidOperationException("shouldnt happen");
What if owned collection has own PK defined rather than borrowing. This will happen.

2022-06-07 16:29 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
> +            if (entityReferenceExpression.ParameterEntity.ValueBufferExpression is JsonProjectionExpression jsonProjectionExpression)
what about subquery case?

2022-06-07 19:41 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
> +    public static EntityTypeBuilder<TEntity> MapReferenceToJson<TEntity, TRelatedEntity>(
We should discuss in design meeting. I was thinking more along the lines of:
``` C#
modelBuilder.Entity<Customer>().OwnsOne(
    c => c.Details, b =>
    {
        b.ToJson("Details");
    });
```

2022-06-07 19:56 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static bool MappedToJson(this IReadOnlyEntityType entityType)
These two can be inlined

2022-06-07 20:05 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +        var result = GetDefaultColumnName(property, storeObject);
Change `GetDefaultColumnName` to return nullable

2022-06-07 20:09 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +        return result == string.Empty && property.DeclaringEntityType.MappedToJson()
You can change all empty strings to `null` here, not just for json

2022-06-07 20:11 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.JsonInfra.cs
> +    private class JsonMappedEntityCompilingExpressionVisitor : ExpressionVisitor
integrate into main visitor

2022-06-07 20:17 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +                return null;
Return `column` even if `column` is not `null`, JSON-splitting is not supported

2022-06-07 21:18 UTC, AndriySvyryd commented
When you add validation also throw if an entity type is mapped to JSON, but the principal type is not mapped to a table or view (and add a note to support this for raw SQL and function mappings in #19970 and #21627)

2022-06-07 22:18 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                throw new InvalidOperationException("unsupported type");
![image](https://user-images.githubusercontent.com/1528107/172492605-b254b38f-10a5-4d6e-846e-88011d1b0512.png)

2022-06-08 00:11 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
> +                    propertyNames.Add(columnName);
what is the use case for returning partial names?

2022-06-08 00:12 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +    public class RelationalMapToJsonConvention : IEntityTypeAnnotationChangedConvention
dependencies

2022-06-08 00:12 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                if (tableName == null)
of entity type is mapped to json column why would it have a table name?

2022-06-08 00:14 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
> +            if (entityType.MappedToJson())
why so? or do we have validation somewhere to block mapping 2 different entity types to same json column?

2022-06-08 00:14 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/StoreGenerationConvention.cs
> +        if (property.DeclaringEntityType.MappedToJson())
would we allow store generation for properties for entities inside json column.

2022-06-08 00:17 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +            // in case of entities mapped to json, unique and non unique FKs can be compatible
Doesn't unique/non-unique FK would still throw in change tracker? The only thing which would be different in JSON case is the uniqueness cannot be enforced on server side

2022-06-08 00:18 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +        IRelationalTypeMappingSource? relationalTypeMappingSource,
may be better to pass whole dependencies object here?

2022-06-08 00:20 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +                    mappedType.AddRuntimeAnnotation(RelationalAnnotationNames.MapToJsonTypeMapping, jsonColumnTypeMapping);
do we access this again? Where?

2022-06-08 00:21 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +                    jsonColumn.IsNullable = false;
This can be null if the json reference mapped is optional dependent.

2022-06-08 00:21 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +                    jsonColumn.IsNullable = false;
Default itself shouldn't be false or don't set it

2022-06-08 00:23 UTC, smitpatel commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +        //// maumar: DRY this! also identify json column properly (with annotation or something)
remove if the PR doesn't contain changes related to mgirations

2022-06-08 00:23 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> +    [ConditionalFact]
Remove, we are not allowed to add tests in this class

2022-06-08 00:24 UTC, smitpatel commented on test/EFCore.Sqlite.FunctionalTests/Query/JsonQuerySqliteTest.cs
> +            protected override string StoreName => throw new NotImplementedException();
:trollface:

2022-06-08 00:24 UTC, smitpatel commented on test/EFCore.Specification.Tests/TestModels/JsonMappedEntitiesModel/JsonBasicOwnedBranch.cs
> +    internal class JsonBasicOwnedBranch
internal?

2022-06-08 00:26 UTC, smitpatel commented on src/EFCore.Relational/Storage/JsonTypeMapping.cs
> +    public abstract class JsonTypeMapping : RelationalTypeMapping
what is printing scheme for SQL literal?

2022-06-08 00:26 UTC, smitpatel commented on src/EFCore.SqlServer/Storage/Internal/SqlServerJsonTypeMapping.cs
> +    public class SqlServerJsonTypeMapping : JsonTypeMapping
Do we need anything specific to configure parameters?

2022-06-08 00:27 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +        if (jsonPathExpression.Type == typeof(JsonElement))
Splitting in 2 expressions would resolve this issue.

2022-06-08 00:27 UTC, AndriySvyryd commented
Add a test to `RelationalModelTest` that has nested JSON types and some of the column names are the same on between levels

2022-06-08 00:38 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                        ? AddJsonProjection(jsonProjectionExpression, null)
you need to do deduplication here also

2022-06-08 00:38 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            if (!entityProjectionExpression.EntityType.MappedToJson())
if returns same?

2022-06-08 00:40 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                var match = jsonClientProjectionDeduduplicationMap.Single(e => e.Value.Contains(jsonProjectionExpression));
use some index map instead

2022-06-08 00:40 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                var jsonColumnIndex = AddToProjection(match.Key.JsonPathExpression);
likewise

2022-06-08 00:41 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            var sourcePath = sourceExpression.JsonPathExpression.JsonPath.ToList();
this is IReadOnlyList only, why call ToList again?

2022-06-08 00:42 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +    public JsonProjectionExpression GenerateJsonProjectionExpression(
Just need to delete this :wink:

2022-06-08 00:43 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +        nullable = jsonPathExpression.JsonColumn.IsNullable;
Top level should take from column, inner level should be nullable unless it is on path of required dependent and property type

2022-06-08 00:44 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressionFactory.cs
> +            // maumar - apply default mapping should apply it to arguments also, like we do for other expressions
It shouldn't require to apply type mapping, make sure that JSONScalar expression always have type mapping since it is generated from metadata side

2022-06-08 00:45 UTC, smitpatel commented on src/EFCore.Relational/Query/QuerySqlGenerator.cs
> +        _relationalCommandBuilder.Append("JSON(");
Is this common syntax, better to throw than invalid SQL

2022-06-08 00:46 UTC, smitpatel commented
Requires actual query tests.

Why don't we not allow projection member binding for JsonEntityExpression?

2022-06-14 21:21 UTC, maumar commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                if (tableName == null)
discussed with @AndriySvyryd

2022-06-14 21:21 UTC, maumar commented on src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
> +            if (entityType.MappedToJson())
discussed with @AndriySvyryd

2022-06-14 21:50 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                        return QueryCompilationContext.NotTranslatedExpression;
corner case, will ignore for now

2022-06-14 23:00 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
> +                    propertyNames.Add(columnName);
we use this to find match between PK and FK in the ValidateSharedKeysCompatibility

2022-06-15 00:04 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +            // in case of entities mapped to json, unique and non unique FKs can be compatible
non creating constraint for those keys instead, per suggestion from @AndriySvyryd

2022-06-15 00:15 UTC, maumar commented on src/EFCore.Relational/Metadata/Conventions/StoreGenerationConvention.cs
> +        if (property.DeclaringEntityType.MappedToJson())
we could, but in a future pr

2022-06-15 00:22 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +                    mappedType.AddRuntimeAnnotation(RelationalAnnotationNames.MapToJsonTypeMapping, jsonColumnTypeMapping);
in SelectExpression ctor, when we create json column for the owned navigation - SelectExpression doesn't have access to type mapping source so we need to propagate it via annotation

2022-06-15 00:35 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                                && RemoveJsonIncludes(selectLambda.Body) == selectLambda.Parameters[0])
will throw in validation instead - navigation to non-json entity (apart from the outer-most owner) is not supported for now

2022-06-15 09:14 UTC, roji reviewed
Great to see this coming along. Did some comments, but don't feel obligated to answer - I know this is a WIP draft etc.

Are we planning to support navigations from inside the JSON document outside and vice versa? If so, I didn't think this would be part of a 1st version - it certainly hasn't been requested on the PG side (and sounds complicated).

Another general thought... Currently the JSON support here is implemented in relational only. But there are many non-relational JSON-based databases out there - Cosmos is one example. I wonder if we should have parts of this (e.g. the metadata) in core, and have the Cosmos provider simply make all owned entities JSON-mapped by convention...

That may mean considerable work in Cosmos, so we may not want to do it right away - but designing the general JSON feature in a way that supports this (with proper things going into core instead of relational) may be a good idea.

2022-06-15 09:14 UTC, roji commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +    protected virtual SqlExpression VisitJsonPathExpression(
Very nice that with the owned entity approach, we can do nullability properly - in the PG approach things are complicated (we only have CLR proprty nullability, and accessing that from the appropriate place...).

2022-06-15 09:14 UTC, roji commented on src/EFCore.Relational/Storage/JsonTypeMapping.cs
> +    public abstract class JsonTypeMapping : RelationalTypeMapping
I think we'd use System.Text.Json to serialize to a string

2022-06-15 09:14 UTC, roji commented on src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
> +                { typeof(JsonElement), _json }
Is this to support weakly-typed non-POCO mapping (e.g. as in [EFCore.PG](https://www.npgsql.org/efcore/mapping/json.html#jsondocument-dom-mapping)), where the user has an entity property of type JsonElement (I haven't seen infra elsewhere for that)? 

(for weakly-typed non-POCO mapping, we should think if we want to allow top-level properties of type JsonElement, as opposed to JsonDocument, which better represent an entire JSON document)

2022-06-15 15:19 UTC, smitpatel commented
> Are we planning to support navigations from inside the JSON document outside and vice versa? If so, I didn't think this would be part of a 1st version - it certainly hasn't been requested on the PG side (and sounds complicated).

It came up yesterday and we need to have a nice design meeting discussion about it

2022-06-16 01:37 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
> +            // entity mapped to json can have part of it's key mapped to a column (i.e. part that is FK pointing to the PK of the owner)
this is for the general owned collection case - the entity which is a member of collection has a composite key - one part is "borrowed" from its owner, i.e. owner's PK and int property representing element in that collection. Wrt owned entity referencing a non-owned entity - we won't be supporting it from the get-go and I will add validation to block this scenario. This might be quite tricky to implement because of how we deal with includes (i.e. chop them off before they can get to translation phase and then re-create them from scratch in the shaper)

2022-06-16 01:48 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column
yes, we can then get the proper type mapping for every individual property of the json, rather than apply default mapping. also initially we thought it would be needed for optional dependent but we ended up not needed them (OD is super easy problem for the json case)

2022-06-16 01:52 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static string? MappedToJsonColumnTypeName(this IReadOnlyEntityType entityType)
yeah, i havent done this yet. was planning to make it in such a way that people wouldn't have to change their postgres code - so yeah columntype annotation or fluent api should be possible to use.

2022-06-16 01:54 UTC, maumar commented on src/EFCore.Relational/Query/SqlExpressions/JsonPathExpression.cs
> +    public class JsonPathExpression : SqlExpression
forgot to nuke this class, using JsonScalarExpression instead, but yeah it's supposed to be translatable to JSON_QUERY/JSON_VALUE - will look into PostgresJsonTraversalExpression!

2022-06-16 09:10 UTC, roji commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                            && n.TargetEntityType.IsOwned()))
That sounds like it would land us in the same place as Cosmos was, where to store a simple JSON document you have manually specify "owned" on everything inside it... IMHO that's not a great experience. I think the overwhelming user scenario with JSON is to store recursively owned entities, and for references out to be the exception.

I also *think* that if we do this, it shouldn't block us from adding support for non-owned navigations out of the JSON document; the by-convention default would be for navigations to be owned within JSON documents, but users should still be able to override that by explicitly saying that a specific navigation is non-owned, no?

Going back to Cosmos, note that we have the same thing... We made navigations owned by default (which makes sense), but we still have #16920 for non-owned navigations. It's basically the same thing.

2022-06-16 09:29 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column
OK, I'm not familiar with the whole context and haven't thought this through... (and I'm guessing you and @AndriySvyryd already discussed this).

One reason this seems weird to me, is that almost nothing in IColumn actually applies to a JSON property: none of the facets (length/precision/scale), default/computed values, or even a list of property mappings (I think). At the end of the day, properties inside a JSON document really aren't columns in the relational sense.

I understand the goal of getting the proper type mapping for every property... But isn't RelationalSqlTranslatingExpressionVisitor.VisitMember already returning a JsonPathExpression (and not a ColumnExpression), which should contain the accurate type mapping as taken from the (regular, non-relational) model? Are we sure we need an IColumn representation of JSON properties in the relational model?

One slightly exotic reason against this, is that the relational model (currently) isn't open for extension - we can add a JsonColumn but providers can't (and can't tweak it either). For example, in PG there's a similar concept of a composite type, which is like a true struct - it can hold fields with any PG types (unlike JSON which has a constrained type set). I've been holding off implementing that (https://github.com/npgsql/efcore.pg/issues/22) until after JSON is done, so I could do roughly the same, so ideally we wouldn't do stuff here which can't be done in a provider. But of course, I don't want to hold up this JSON work either, assuming it's necessary to do things this way for some reason.

2022-06-16 18:51 UTC, maumar commented on src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
> +                { typeof(JsonElement), _json }
no, it's for the strongly typed stuff, just associated it with the arbitrary clr type

2022-06-16 19:05 UTC, roji commented on src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
> +                { typeof(JsonElement), _json }
OK, this might just be WIP, but won't including this here mean that the provider will "support" properties of type JsonElement (but things will break later since not really supported?)

2022-06-22 22:04 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.JsonInfra.cs
> +                        Expression.Call(
This would certainly need to pass through a value converter somewhere

2022-06-22 22:06 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var jsonString = dataReader.GetString(index);
Doesn't work

2022-06-22 22:08 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        private (ParameterExpression, ParameterExpression, Expression, Expression) PrepareForJsonShaping(ProjectionBindingExpression projectionBindingExpression, IEntityType entityType)
Is this used from multiple places?

2022-06-22 22:10 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    else if (includeExpression.Navigation.TargetEntityType.MappedToJson())
The NavigationExpression is supposed to be RelationalEntityShaper (or collection equivalent for json),
It shouldn't be hecked this way

2022-06-22 22:13 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    var jsonMappedEntityCompilingExpressionVisitor = new JsonMappedEntityCompilingExpressionVisitor(_parentVisitor);
Remove nested visitor

2022-06-22 22:14 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    && property.DeclaringEntityType.MappedToJson())
Avoid repeated checks for MappedToJson.
Check here based on mapping parameter that what kind of value we are reading

2022-06-22 22:18 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.JsonInfra.cs
> +            var result = shaper(queryContext, keyPropertyValues, jsonElement);
Why there are 2 methods for root & non-root. All the arguments passed to both of them should be same. (We do read from datareader outside of this method

2022-06-22 23:55 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.JsonInfra.cs
> +                        keyPropertyValuesParameter.Type.GetProperty("Item"),
we always store those key values as array of objects

2022-06-22 23:56 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    var jsonMappedEntityCompilingExpressionVisitor = new JsonMappedEntityCompilingExpressionVisitor(_parentVisitor);
already done

2022-06-22 23:58 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.JsonInfra.cs
> +            var result = shaper(queryContext, keyPropertyValues, jsonElement);
root meaning json enity without it's owned (so there is no navigation and no fixup to the parent) vs include case where the parent entity is present. Just did it to avoid if checks in runtime - can combine

2022-06-23 17:53 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
> +                    propertyNames.Add(columnName);
The caller code should be responsible for iterating in that case. This method in itself shouldn't be returning partial list.
If it does then callee need to always check if there was some property which was not mapped to a column and if that is the case then would be hard to find the property which was not mapped.

2022-06-23 17:54 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                throw new InvalidOperationException("need table name");
How so? If you are processing an entityType which is mapped to a JSON column, why there is a table name on this entity type

2022-06-23 17:56 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                        && n.DeclaringEntityType == entityTypeBuilder.Metadata
Is this for hierarchy scenario? You are calling GetNavigations so declaring type would be same unless hierarchy. If you want just navigation on this type then call GetDeclaredNavigations instead.

2022-06-23 17:56 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalNavigationJsonPropertyNameAttributeConvention.cs
> +        => navigationBuilder.HasJsonElementName(attribute.Name, fromDataAnnotation: true);
Check if attribute name is null/whitespace like Property case.

2022-06-23 17:57 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/StoreGenerationConvention.cs
> +        //if (property.DeclaringEntityType.MappedToJson())
This is skipping the skipping of validation

2022-06-23 17:59 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +                if (inner.TryGetValue(columnName, out var result))
merge ifs

2022-06-23 18:04 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +        // TODO: should we update these also?
yes

2022-06-23 18:06 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        public virtual IReadOnlyList<(IProperty, ColumnExpression)> KeyPropertyMap { get; }
Why map is not a dictionary, why this is public?

2022-06-23 18:08 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        public virtual SqlExpression BindProperty(IProperty property)
check property is related to the entity type rather than using match

2022-06-23 18:10 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
> +            RelationalTypeMapping? typeMapping)
This has to have non-nullable type mapping as there is no reason to assign to it.

2022-06-23 18:11 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
> +            List<string> jsonPath)
Readonly

2022-06-23 18:22 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
> +            case JsonQueryExpression:
What particular expression tree require this?

2022-06-23 18:28 UTC, smitpatel commented
Add validation for not allowing JSON column for TPT/TPC

2022-06-23 18:30 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +    //private readonly IReadOnlyDictionary<INavigation, EntityShaperExpression> _jsonNavigationMap;
If you are not going to use same map then have the other one return JSONQueryExpression

2022-06-23 18:35 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                        nullable: true);
Why nullable always? What if it is required reference dependent

2022-06-23 18:37 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                    var keyProperties = ownedJsonNavigation.IsCollection
Since you don't really need the actual array of properties, use the properties count in for loop to control skipping the last property for collection.

2022-06-23 18:39 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                        FindTableReference(this, tableExpression),
Why do you need this? There is only 1 table.

2022-06-23 18:40 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                    Check.DebugAssert(primaryKey != null, "primary key is null.");
Remove. Rather have check in JsonQueryExpression to avoid creating without PK (if there is any such need)

2022-06-23 18:52 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                        ? AddJsonProjection(jsonQueryExpression, null)
Did you enable this? This also needs deduplication

2022-06-23 18:53 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            if (!entityProjectionExpression.EntityType.MappedToJson())
Remove

2022-06-23 18:53 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            Dictionary<JsonScalarExpression, List<JsonQueryExpression>>? jsonClientProjectionDeduduplicationMap)
non-null

2022-06-23 18:55 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                ? jsonClientProjectionDeduduplicationMap
In deduplication map get remapping dict to do this so you can avoid doing expensive Where with SequenceEqual over a list

2022-06-23 18:56 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            foreach (var keyPropertyMapElement in jsonQueryExpression.KeyPropertyMap)
Hide KeyPropertyMap and use entity type to iterate over PK

2022-06-23 18:59 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            for (var i = 0; i < sourcePath.Count; i++)
can use sequence equal

2022-06-23 19:03 UTC, smitpatel commented on src/EFCore.SqlServer/Storage/Internal/SqlServerJsonTypeMapping.cs
> +                            typeof(SqlString)),
What is SqlString?

2022-06-23 19:04 UTC, smitpatel commented on src/EFCore.Relational/Storage/JsonTypeMapping.cs
> +            => $"'{EscapeSqlLiteral((string)value)}'";
is this right way to print in all provider or we should abstract it

2022-06-23 19:09 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                if (newExpression.Arguments[0] is ParameterExpression valueBufferParameter
else if
and if this block doesn't match, throw

2022-06-23 19:18 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    else if (includeExpression.Navigation.TargetEntityType.MappedToJson())
This shouldn't be used this way. Look at NavigationExpression instead

2022-06-23 19:19 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                property != null || type.IsNullableType() || typeMapping is JsonTypeMapping, "Must read nullable value from database if property is not specified.");
We still read nullable value from database regardless of it being JSON

2022-06-23 22:37 UTC, maumar commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +    //private readonly IReadOnlyDictionary<INavigation, EntityShaperExpression> _jsonNavigationMap;
I am using the same map - at least between json and non-json navigations

2022-06-24 18:10 UTC, ajcvickers commented
👍

2022-06-24 22:01 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                            && materializeCollectionNavigationExpression.Subquery is MethodCallExpression methodCallSubquery
I added the test for entity with single json collection - the tree is:

```
MaterializeCollectionNavigation(
    Navigation: JsonEntitySingleOwned.OwnedCollection,
    subquery: JsonQueryExpression(j.json_collection, "")
        .AsQueryable())
```

2022-06-24 22:46 UTC, roji commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            // TODO: type mapping should depend on json path or not?
Can you give more context, like a sample query or something?

2022-06-28 00:55 UTC, maumar commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                            && n.TargetEntityType.IsOwned()))
I talked with @AndriySvyryd about this a bit and apparently this would be quite tricky to do due to the way conventions are ran and relationships being discovered (i.e. we discover them before we know the aggregate is mapped to json, so later we would have to undo all the work and re-configure them as owned. We should discuss on the design meeting

2022-06-28 01:02 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        private (ParameterExpression, ParameterExpression, Expression, Expression) PrepareForJsonShaping(ProjectionBindingExpression projectionBindingExpression, IEntityType entityType)
used in 3 places: include scenario, projecting json entity at top level, projecting collection of json entities at top level. Pretty much every time we need to build JsonElement from the data reader info

2022-06-28 04:58 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +    public EntityProjectionExpression(
No need for this. You can just use existing API of AddNavigation.

2022-06-28 07:17 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    else if (includeExpression.Navigation.TargetEntityType.MappedToJson())
NavigationExpression can be RelationalEntityShaper for the non-json case also - I need to know that the target type is mapped to json, since the processing is different in both cases

2022-06-28 08:31 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            foreach (var keyProperty in entityType.FindPrimaryKey()!.Properties.Where(p => p.IsForeignKey()))
supposed to filter out the ordinal key property, switched to checking if navigation and cutting last key property if so

2022-06-28 20:13 UTC, maumar commented on src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
> +            case JsonQueryExpression:
projecting json scalar - we get here when we try to bind scalar json property. We visit entity reference that contains the property and it happens to be JQE

2022-06-28 20:48 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IDictionary<IProperty, ColumnExpression> keyPropertyMap)
IReadOnlyDictionary

2022-06-28 20:49 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        public JsonQueryExpression(
make this private. Force the use of BindNavigation.

2022-06-28 21:31 UTC, maumar commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +        nullable = jsonPathExpression.JsonColumn.IsNullable;
we don't have access to metadata, so hard to tell if the path is required navs only, will go for column nullability on root level and nullable = true for inner

2022-06-29 03:38 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                case CollectionResultExpression collectionResultExpression
this looks much more different now, that jsonelement variable is nullable and we do the null checks here. Also, the "case" condition would be quite complicated if those two were combined. Would rather keep them separate, even though there is a good number of similarities

2022-06-29 06:13 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +        var ownedNavigationMap = new Dictionary<INavigation, EntityShaperExpression>();
This needs to be verified. Earlier we didn't do it for owned navigations which are table sharing. Visiting this can cause unintended side-effects. While I agree that we may need this for JSON columns, we should verify the scenarios, why and where are we doing VisitChildren for Entityprojection

2022-06-29 06:13 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +        return new EntityProjectionExpression(EntityType, propertyExpressionMap, _ownedNavigationMap, discriminatorExpression);
You may also need to make the relevant JSON column inside owned navigations nullable.

2022-06-29 06:14 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                            && materializeCollectionNavigationExpression.Subquery is MethodCallExpression methodCallSubquery
Does this tree appear for all scenarios (including non-JSON). If yes then it should be fine else we need to investigate why there is Additional AsQueryable when it is not needed.

2022-06-29 06:15 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                                && RemoveJsonIncludes(selectLambda.Body) == selectLambda.Parameters[0])
Then RemoveJsonIncludes should be removed here?

2022-06-29 06:17 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                    case JsonQueryExpression jsonQueryExpression
What is the input to this visitor for projected JSON in case of reference and collection both?

2022-06-29 06:19 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                            var projectionBinding = AddClientProjection(jsonQuery, typeof(ValueBuffer));
Utilize cache like entity projection, we don't want to add same JSONQuery repeatedly.

2022-06-29 06:20 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                if (entityShaperExpression.ValueBufferExpression is JsonQueryExpression jsonQueryExpression)
code is same as entity projection, write a helper method on T which can be either JSONQueryExpression or EntityProjectionExpression.

2022-06-29 06:22 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            INavigation navigation,
Why there is navigation in JsonQueryExpression. It represents an entity type which is encoded as JSON in server.

2022-06-29 06:24 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            var typeMapping = property.FindRelationalTypeMapping();
Can you find relevant JsonColumn from relational model here?

2022-06-29 06:24 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            var foreignKeyProperties = navigation.ForeignKey.Properties.ToList();
Why ToList here?

2022-06-29 06:25 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            foreach (var (property, column) in _keyPropertyMap)
Why are you iterating over a dictionary?

2022-06-29 06:25 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +                var keyIndex = primaryKeyProperties.IndexOf(property);
Don't use IndexOf, you already have a dictionary.

2022-06-29 06:25 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
> +using System.Text.Json;
unnecessary

2022-06-29 06:26 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            if (jsonQueryExpression != null)
Make TryGet method bool with out var

2022-06-29 06:26 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                    var newNullable = entityShaperExpression.IsNullable || !navigation.ForeignKey.IsRequired || navigation.IsCollection;
inline

2022-06-29 06:29 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
> +        public JsonScalarExpression(
Do we have a scalar as json without any path?

2022-06-29 06:32 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                foreach (var jsonNavigationMapElement in jsonNavigationMap)
Remove foreach and remove jsonNavigationMap

2022-06-29 06:32 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                        ? primaryKeyProperties.Count() - 1
Is Count() required or you can use `Count`

2022-06-29 06:33 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                index++;
Convert foreach to for if you are running index.

2022-06-29 06:34 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            var jsonClientProjectionDeduplicationMap = BuildJsonProjectionDeduplicationMap(_clientProjections);
Apply ofType filter here also.

2022-06-29 06:34 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                    .Where(x => x.x is JsonQueryExpression)
so you can remove this.

2022-06-29 06:35 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                    .Select(x => new { Expression = (JsonQueryExpression)x.x, Index = x.i })
and collapse this Select into earlier one.

2022-06-29 16:08 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                        jsonScalarExpression = match ?? new JsonScalarExpression(
match is always null here coalesce is not needed

2022-06-29 16:10 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                jsonQueryExpression.JsonPath.ToList());
You can pass the same list, no need to create additional copy

2022-06-29 16:12 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +        var jsonPath = string.Join(".", jsonScalarExpression.JsonPath);
Just combine "$" in front of the path and use string join. It will give desired results without the if-else below.

2022-06-29 17:19 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            = typeof(ShaperProcessingExpressionVisitor).GetTypeInfo().GetDeclaredMethod(nameof(MaterializeRootJsonEntityCollection))!;
MaterializeJsonEntityCollection

2022-06-29 17:20 UTC, smitpatel commented
>         private readonly IDictionary<ParameterExpression, IDictionary<IProperty, int>> _materializationContextBindings

can make these all dictionaries concrete Dictionary type?

---
Refers to: src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs:133 in b40e728. [](commit_id = b40e7283c5f6382b7b5d062fc75d0f8019043d37, deletion_comment = False)

2022-06-29 17:22 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                else if (newExpression.Arguments[0] is ParameterExpression valueBufferParameter
What parameter is this?

2022-06-29 17:23 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    when collectionResultExpression.Navigation is INavigation navigation
Make condition work based on ProjectionBindingExpression.
This is shaper, avoid looking into metadata as much as possible. The bindings are supposed to give you necessary information.

2022-06-29 17:27 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    && property.DeclaringEntityType.IsMappedToJson())
Remove this condition. Figure out based on the dictionaries you have for mappingParameter key to figure out which path to take.

2022-06-29 17:28 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            keyPropertyValuesParameter.Type.GetProperty("Item"),
keyPropertyValuesParameter type will always be same. Save this reflected PropertyInfo in a static field

2022-06-29 17:28 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            null,
indentation and many other places

2022-06-29 17:29 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            + methodCallExpression.Arguments[1].GetConstantValue<int>();
use index you computed above already

2022-06-29 17:31 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            return jsonElementProperty.Deserialize(returnType);
Why deserialize here?
You already have JSONElement. Nested property shouldn't be serialized

2022-06-29 17:31 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    throw new InvalidOperationException("Required Json entity not found.");
TODO: resources string

2022-06-29 17:32 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var result = shaper(queryContext, keyPropertyValues, jsonElement);
what is JSONElement is null here? Is shaper created null safe?

2022-06-29 17:34 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                var resultElement = elementShaper(queryContext, newKeyPropertyValues, jsonArrayElement);
innerShaper

2022-06-29 17:36 UTC, smitpatel requested changes
Stop using `IsMappedToJson` in the shaper compiler. Your bindings and their types are supposed to pass you all information.

2022-06-29 17:40 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    if (entityShaperExpression.EntityType.IsMappedToJson())
The caching part still relevant. You don't want to materialize multiple instances of json references at top level

2022-06-29 17:45 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    if (entityShaperExpression.EntityType.IsMappedToJson())
Check what is the kind of value of ProjectionBindingExpression

2022-06-29 17:45 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            (ProjectionBindingExpression)entityShaperExpression.ValueBufferExpression,
You already have projectionBindingExpression variable with right type

2022-06-29 17:46 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                        _variables.Add(entityParameter);
Why cannot you do the same thing as what other part is doing? It replaces ProjectionBindingExpression to actual value after generating the entity materializer
Then you can avoid all this processing and only vary about how to replace the PBE

2022-06-29 18:31 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    when collectionResultExpression.Navigation is INavigation navigation
check based on projection binding, visit base if not same (can also throw because we don't process it anyway

2022-06-29 18:34 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +    private sealed class JsonValueBufferExpression : Expression
Remove this and the next class and inline processing. If you want to DRY then create a method

2022-06-30 00:00 UTC, maumar commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +        var jsonPath = string.Join(".", jsonScalarExpression.JsonPath);
I would need to construct a new json path list with that additional "$" in front, no? seems unnecessary

2022-06-30 00:08 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +        var jsonPath = string.Join(".", jsonScalarExpression.JsonPath);
string.Join takes enumerable, just concat.

2022-06-30 00:59 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var result = shaper(queryContext, keyPropertyValues, jsonElement);
we should only call these methods if the json element is not null - we add the null check before calling it

2022-06-30 01:00 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var result = shaper(queryContext, keyPropertyValues, jsonElement);
```
    namelessParameter{5}.HasValue ? ShaperProcessingExpressionVisitor.MaterializeIncludedJsonEntityCollection<JsonEntityBasic, MyOwnedRootShared>(
        queryContext: queryContext, 
        jsonElement: namelessParameter{5}.Value, 
        keyPropertyValues: namelessParameter{4}, 
        entity: namelessParameter{3}, 
        innerShaper: (queryContext, namelessParameter{12}, namelessParameter{13}) => (...)

```

2022-06-30 01:02 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var newKeyPropertyValues = new object[keyPropertyValues.Length + 1];
we do it in JsonShapingPreProcess

2022-06-30 01:06 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            return jsonElementProperty.Deserialize(returnType);
this is just for scalars (maybe the name should indicate this better), using deserialize rather than specific method for every return type

2022-06-30 03:47 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            return jsonElementProperty.Deserialize(returnType);
Do we need to use type call or just convert works?

2022-06-30 03:47 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var newKeyPropertyValues = new object[keyPropertyValues.Length + 1];
I am talking about the collection to populate for include - the entity collection.

2022-06-30 03:48 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var result = shaper(queryContext, keyPropertyValues, jsonElement);
Why cannot you not do null check inside this method like the include version?

2022-06-30 04:16 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +        nullable = jsonScalarExpression.JsonPath.Count == 0
May be propagate nullability from outer? Though think of the case where value is just missing if the key is not present in JSON. What is the value we get from server in that case?

2022-06-30 04:55 UTC, maumar commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +        nullable = jsonScalarExpression.JsonPath.Count == 0
depends on the path mode - either null or it throws. Default is null, but we could issue queries in strict mode @roji - thoughts?

2022-06-30 16:14 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +            var pkPropertiesToMatch = mappedToJson
This is erroneous logically. 
What if the FK properties count is higher than Pk properties or vice-versa.
You need better logic than this. which is comparing PK as is if unique or drop last one from PK and compare.

2022-06-30 16:16 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static string? MappedToJsonColumnTypeName(this IReadOnlyEntityType entityType)
IEntityType and IMutable type versions?

2022-06-30 16:17 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
> +        if (foreignKey.IsOwnership && foreignKey.DeclaringEntityType.IsMappedToJson() && !foreignKey.IsUnique)
Can we create constraint for unique JSON ownerships?

2022-06-30 16:21 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +        if (key.DeclaringEntityType.IsMappedToJson())
If not mapped to JSON send foreignKey.Properties as is rather than applying Take over it.

2022-06-30 16:21 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +    public static IEnumerable<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyForeignKey key)
nit:foreignKey

2022-06-30 16:27 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +            if (property.DeclaringEntityType.IsMappedToJson())
cache this outside of for loop

2022-06-30 16:28 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +            else
you can also avoid the check. For normal scenario the index is never -1

2022-06-30 16:37 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                // no need to check json-mapped types (or is there, just different?)
rather than adding checks to skip in different places, you can exclude the entity type in outer loop computing tables map.

2022-06-30 16:40 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                        navigation.TargetEntityType.SetAnnotation(RelationalAnnotationNames.MapToJsonColumnName, jsonColumnName);
there is no builder API for this?

2022-06-30 16:45 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +        if (key.DeclaringEntityType.IsMappedToJson())
same notes as the FK version applies

2022-06-30 16:50 UTC, AndriySvyryd commented
> @AndriySvyryd can we just use mapping strategy method now?

Yes

2022-06-30 16:57 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +                if (jsonColumn == null)
Do we allow mapping multiple aggregates to same column in database?

2022-06-30 17:01 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +              new ReadOnlyDictionary<INavigation, EntityShaperExpression>(
the double-nesting is not necessary

2022-06-30 17:03 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +            if (shaper.EntityType.IsMappedToJson())
can you add tests and verify if this is safe to do for normal owned entities too?

2022-06-30 17:04 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +                    keyPropertyMap[keyProperty] = keyColumn.MakeNullable();
umm now you are forking multiple different columns for same key column as you go down aggregate

2022-06-30 17:05 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +        foreach (var (navigation, entityShaperExpression) in _ownedNavigationMap)
add test for this too for non-json owned entity

2022-06-30 17:06 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                        nullable: entityShaperExpression.IsNullable || !navigation.ForeignKey.IsRequired || navigation.IsCollection);
navigation.IsCollection is always false here

2022-06-30 17:08 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    throw new InvalidOperationException($"Unsupported argument to the MaterializationContext constructor: '{newExpression.Arguments[0]}'.");
this should let it pass as is rather than throw.

2022-06-30 17:08 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    throw new InvalidOperationException($"Unsupported argument to the MaterializationContext constructor: '{newExpression.Arguments[0]}'.");
we only throw for scenario which can cause must be reducible node error

2022-06-30 17:10 UTC, smitpatel commented on src/EFCore.Relational/Storage/JsonTypeMapping.cs
> +            => $"'{EscapeSqlLiteral((string)value)}'";
shouldn't this use a serializer instead?

2022-06-30 17:11 UTC, smitpatel commented on src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
> +        var property = column.PropertyMappings.FirstOrDefault()?.Property;
Do JSON column have annotations over it? Else it should be skipped reaching this code path

2022-06-30 17:12 UTC, smitpatel commented on src/EFCore.SqlServer/Storage/Internal/SqlServerJsonTypeMapping.cs
> +                return Expression.Property(parse, nameof(JsonDocument.RootElement));
MakeMemberAccess by passing MemberInfo.
This internally performs reflection every time

2022-06-30 22:16 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressionVisitor.cs
> +    protected abstract Expression VisitJsonScalarExpression(JsonScalarExpression jsonScalarExpression);
```suggestion
    protected abstract Expression VisitJsonScalar(JsonScalarExpression jsonScalarExpression);
```

2022-06-30 22:17 UTC, smitpatel commented on src/EFCore.Relational/Query/QuerySqlGenerator.cs
> +        => throw new InvalidOperationException("This node should be handled by provider-specific sql generator.");
TODO: resource string

2022-06-30 22:22 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonProjectionExpression.cs
> +                throw new InvalidOperationException("shouldnt happen");
Can you make sure to add test for it? You can block the scenario in model validation if you don't plan to support it in initial.

2022-06-30 23:01 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                                    && RemoveJsonIncludes(selectLambda.Body) == selectLambda.Parameters[0])
Given we are not supporting nav to non-owned from json, drop this whole thing. Though match that selector is either same parameter or IncludeExpression where EntityExpression is same parameter (IncludeExpression will certify that it is something what we generated.

2022-06-30 23:09 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            if (targetEntityType.IsMappedToJson())
You can avoid this check and just call BindNavigation always. If it is non-null you can return. If it is null then it is certainly not mapped to JSON and you can do the processing as before.
You would add this check to figure out if you need to unwrap the shaper for JSON.

2022-06-30 23:12 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                    var jsonColumnTypeMapping = (RelationalTypeMapping)targetEntityType.FindRuntimeAnnotationValue(RelationalAnnotationNames.MapToJsonTypeMapping)!;
API

2022-06-30 23:15 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
> +        => new JsonQueryData();
Cache the result, you could be calling this from multiple tests

2022-06-30 23:15 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
> +                        Assert.Equal(ee.OwnedCollectionSharedRoot.Count, aa.OwnedCollectionSharedRoot.Count);
Move this inside AssertOwnedRoot?

2022-06-30 23:17 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
> +            ss => ss.Set<JsonEntityBasic>().Select(x => x.OwnedReferenceSharedRoot).AsNoTracking());
Avoid using NoTracking, we should just fork the concrete test class into both.

2022-07-01 13:13 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                                    && methodCallSubquery.Arguments[0] is JsonQueryExpression)
you can drop this check since you are checking for subquery being jsonQueryExpression below again.

2022-07-01 13:14 UTC, smitpatel commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                                && jsonQueryExpression.IsCollection)
throw when it is non-collection, or may be use debug assert because only a bad tree is supposed to give you that scenario.

2022-07-01 13:14 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        public override ExpressionType NodeType => ExpressionType.Extension;
inheritdoc

2022-07-04 04:55 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                else if (newExpression.Arguments[0] is ParameterExpression valueBufferParameter
original value buffer expression (projection binding) gets replaced with this parameter. This way we can re-use the code for the original RelationalEntityShaperExpression and the ones we synthesize during shaper processing

2022-07-04 05:27 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            return jsonElementProperty.Deserialize(returnType);
convert doesn't work

2022-07-04 05:29 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var result = shaper(queryContext, keyPropertyValues, jsonElement);
my thought process was that I only need to do the check on top level before sending it to the first Materialize* method, but that's not true - we can have a null JsonElement when traversing the json object. Will change to nullable json and check in the method

2022-07-04 05:33 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var newKeyPropertyValues = new object[keyPropertyValues.Length + 1];
fixup generates the necessary code, e.g.:

```
                fixup: (namelessParameter{25}, namelessParameter{26}) => 
                {
                    return ClrICollectionAccessor<MyOwnedRootShared, List<MyOwnedBranchShared>, MyOwnedBranchShared>.Add(
                        entity: namelessParameter{25}, 
                        value: namelessParameter{26}, 
                        forMaterialization: True);
                }
```

2022-07-05 01:37 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                // no need to check json-mapped types (or is there, just different?)
we will need some validation here and there (eventually)

2022-07-05 02:15 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                            && materializeCollectionNavigationExpression.Subquery is MethodCallExpression methodCallSubquery
example tree from owned query tests:

```
MaterializeCollectionNavigation(
    Navigation: OwnedPerson.Orders,
    subquery: ShapedQueryExpression: 
        QueryExpression: 
            Projection Mapping:
                EmptyProjectionMember -> EntityProjectionExpression: Order
            SELECT 1
            FROM Order AS o
        ShaperExpression: EntityShaperExpression: 
                OwnedQueryTestBase<OwnedQuerySqlServerTest+OwnedQuerySqlServerFixture>+Order
                ValueBufferExpression: 
                    ProjectionBindingExpression: EmptyProjectionMember
                IsNullable: False

        .Where(namelessParameter{0} => object.Equals(
            objA: (object)EF.Property<int>(EntityShaperExpression: 
                OwnedQueryTestBase<OwnedQuerySqlServerTest+OwnedQuerySqlServerFixture>+OwnedPerson
                ValueBufferExpression: 
                    ProjectionBindingExpression: Outer
                IsNullable: False
            , "Id"), 
            objB: (object)EF.Property<int>(namelessParameter{0}, "ClientId")))
        .AsQueryable()
        .Select(o0 => IncludeExpression(
            EntityExpression:
            o0, 
            NavigationExpression:
            MaterializeCollectionNavigation(
                Navigation: Order.Details,
                subquery: EF.Property<List<OrderDetail>>(o0, "Details")
                    .AsQueryable()), Details)
        ))
```

2022-07-08 03:10 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +            while (currentEntity.IsOwned())
this scenario is blocked for now, you are right that this is a problem - will add note in the method to keep this in mind once the scenario is enabled

2022-07-08 22:36 UTC, maumar commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            if (targetEntityType.IsMappedToJson())
bindNavigation can return non-null for json and normal owned entities. So I'd have to check if the type is mapped to json to decide which processing needs to happen (as they differ significantly).

2022-07-10 04:02 UTC, maumar commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +        foreach (var (navigation, entityShaperExpression) in _ownedNavigationMap)
already there: Query_with_OfType_eagerly_loads_correct_owned_navigations but just like with IsNullable, there is nothing in the _ownedNavigationMap, as the includes run after all the other query stuff is finished

2022-07-10 04:17 UTC, maumar commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +        var ownedNavigationMap = new Dictionary<INavigation, EntityShaperExpression>();
we have 180 tests in in ownedtypes that hit this code path, but there's never anything in the _ownedNavigationMap by the time do VisitChildren. We could only perform update for json entities and leave other ones as they are, just in case.

2022-07-10 04:23 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +                if (jsonColumn == null)
now only looking at the outer-most navigation when determining json column nullability

2022-07-10 04:55 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +            var pkPropertiesToMatch = mappedToJson
removed this entire logic, we don't want/need the collection FKs to be recognized as row internal fks

2022-07-10 05:23 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                if (entityShaperExpression.ValueBufferExpression is JsonQueryExpression jsonQueryExpression)
cache type is different. I could conditionally go for one cache object or the other, depending on the type of generic arg, but that doesn't seem to be worth it.

2022-07-10 05:31 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
> +                    case JsonQueryExpression jsonQueryExpression
```
new { 
    OwnedReferenceSharedLeaf = EntityShaperExpression: 
        TestModels.JsonQuery.JsonEntityBasic.OwnedReferenceSharedRoot#MyOwnedRootShared.OwnedReferenceSharedBranch#MyOwnedBranchShared.OwnedReferenceSharedLeaf#MyOwnedLeafShared
        ValueBufferExpression: 
            JsonQueryExpression(j.json_reference_shared, "OwnedReferenceSharedBranch.OwnedReferenceSharedLeaf")
        IsNullable: False
    , 
    OwnedCollectionSharedLeaf = MaterializeCollectionNavigation(
        Navigation: JsonEntityBasic.OwnedReferenceSharedRoot#MyOwnedRootShared.OwnedReferenceSharedBranch#MyOwnedBranchShared.OwnedCollectionSharedLeaf,
        subquery: JsonQueryExpression(j.json_reference_shared, "OwnedReferenceSharedBranch.OwnedCollectionSharedLeaf")
            .AsQueryable()), 
 }
```

2022-07-11 08:00 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +        IRelationalTypeMappingSource? relationalTypeMappingSource,
will remove this dependency altogether

2022-07-13 17:41 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static string? SetJsonColumnName(
mutable version returns void and this returns string.

2022-07-13 17:43 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static RelationalTypeMapping? SetJsonColumnTypeMapping(
+1

2022-07-13 17:44 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
> +        if (foreignKey.IsOwnership && foreignKey.DeclaringEntityType.IsMappedToJson() && !foreignKey.IsUnique)
what happens to unique ownerships? What does constraint name mean for them?

2022-07-13 17:45 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalNavigationExtensions.cs
> +    public static string GetJsonElementName(this IReadOnlyNavigationBase navigation)
If you are prefix-ing this with Get then do the same for JsonColumnName, JsonColumnTypeName on entity type extensions

2022-07-13 17:46 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalOwnedNavigationBuilderExtensions.cs
> +                var navigationName = builder.Metadata.GetNavigation(false)!.Name;
what does false mean? Add named argument.

2022-07-13 17:47 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +        var mappedToJson = property.DeclaringEntityType.IsMappedToJson();
unused

2022-07-13 17:49 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            if (NavigationChainContainsJsonCollection(key.DeclaringEntityType))
would you reach here given we don't do validation for shared table in json

2022-07-13 17:50 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                throw new InvalidOperationException(
file an issue to enable support

2022-07-13 17:50 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                // TODO: blocking just in case for now, but it *should* be fine to enable this
file an issue

2022-07-13 17:53 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +        var mappingStrategy = (string?)rootType[RelationalAnnotationNames.MappingStrategy];
Use GetMappingStrategy

2022-07-13 17:54 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                throw new InvalidOperationException(
File an issue, json column should be fine in leaf types in TPT/TPC

2022-07-13 17:57 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                    entityTypeBuilder.Metadata.SetJsonColumnTypeMapping(jsonColumnTypeMapping);
If this sets json column type mapping then relational model doesn't need to do it

2022-07-13 17:59 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +        if (foreignKey.IsOwnership && foreignKey.DeclaringEntityType.IsMappedToJson() && !foreignKey.IsUnique)
this was somewhere else too

2022-07-13 18:00 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +        if (foreignKey.DeclaringEntityType.IsMappedToJson())
if you invert if you can reduce nestng

2022-07-13 18:00 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +    public static IReadOnlyList<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyKey key)
Do how other methods to thing with casting and just having one method with logic

2022-07-13 18:07 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
explain the SqlExpression here

2022-07-13 21:15 UTC, maumar commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                    entityTypeBuilder.Metadata.SetJsonColumnTypeMapping(jsonColumnTypeMapping);
it's needed in migration workflow - we can't serialize the type mapping in the model snapshot, so I need to re-create it in RelationalModel :(

2022-07-13 21:19 UTC, maumar commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
future proofing for support of weakly typed json (i.e. JsonElement properties) - we would probably be translating queries like:

```cs
myVariable = "SomeNumber";
(...)
myEntity.MyJsonProperty.GetProperty("Collection").GetProperty(myVariable).GetInt32()
```

the path argument can be a non-constant (parameter, perhaps column, or some other expression). @roji

2022-07-13 21:40 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
is that valid syntax in SQL?

2022-07-13 21:45 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalOwnedNavigationBuilderExtensions.cs
> +                var navigationName = builder.Metadata.GetNavigation(false)!.Name;
pointsToPrincipal

2022-07-13 22:42 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +    public static IReadOnlyList<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyKey key)
return type is problematic (IProperty : IReadonlyProperty), I could make both methods return IReadonlyList<IReadOnlyProperty> but then I'd have to change a bunch of properties into read only versions.

2022-07-13 23:47 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
> +        if (foreignKey.IsOwnership && foreignKey.DeclaringEntityType.IsMappedToJson() && !foreignKey.IsUnique)
i added this code originally to prevent key validation for the json collection scenario. now that we validate json entities separately this code can be removed

2022-07-14 00:22 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static string? SetJsonColumnName(
all the other Set methods with IConventionEntity argument return nullable string.

2022-07-14 00:37 UTC, maumar commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +                newShaper = shaper.Update(newJsonQueryExpression).MakeNullable();
MakeNullable already makes a check to see what was the nullability before and only makes changes if it was different than the new one. Also, I'm having trouble coming up with scenario where _ownedNavigationMap would have anything else than json entities (i.e. regular owned). All translation which calls into MakeNullable is done before we populate _ownedNavigationMap which happens at the expand owned entities step (as opposed to json entities where it happens at the time of construction of SelectExpression)

2022-07-14 01:17 UTC, maumar commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
in postgres you can put anything you want in the path apparently. On sql server you can do it by concatenating strings. All 3 return the same results:

```
SELECT JSON_QUERY([j].[OwnedReferenceRoot],'$.OwnedReferenceBranch.OwnedReferenceLeaf'), [j].[Id]
FROM [JsonEntitiesBasic] AS [j]

SELECT JSON_QUERY([j].[OwnedReferenceRoot],'$.OwnedReferenceBranch' + '.OwnedReferenceLeaf'), [j].[Id]
FROM [JsonEntitiesBasic] AS [j]

DECLARE @path nvarchar(100) = '.OwnedReferenceLeaf';


SELECT JSON_QUERY([j].[OwnedReferenceRoot],'$.OwnedReferenceBranch' + @path), [j].[Id]
FROM [JsonEntitiesBasic] AS [j]


```

2022-07-14 01:21 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            if (NavigationChainContainsJsonCollection(key.DeclaringEntityType))
good catch, remnant from previous version when we did validation for both

2022-07-15 06:12 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static string? SetJsonColumnName(
@AndriySvyryd

2022-07-15 06:12 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +    public static IReadOnlyList<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyKey key)
Would enumerable return type work?

2022-07-15 06:14 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +                newShaper = shaper.Update(newJsonQueryExpression).MakeNullable();
subquery which uses owned entity in where predicate and put the result of that subquery in right side of join.

That MakeNullable is about avoiding creating new object but you are visiting and updating whole lot of different objects which are made nullable here, if the json shaper is already nullable then you don't need to update everything.

2022-07-15 06:15 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
Then List of SqlExpression is also problematic.

2022-07-15 07:00 UTC, maumar commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
How so? I was thinking we would peek into the expressions and if they are constants we would stitch their values into one string and if not, then we would concatenate using + operation. Should work, at least for the common cases no?

2022-07-15 20:40 UTC, roji commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
@smitpatel discussed this with @maumar a couple days ago. A good example even without JsonElement mapping is if someone wants to traverse into a JSON array via a parameter:

```c#
var i = 8;
_ = ctx.Blogs.Where(b => b.JsonDoc.ArrayProp[i] == "foo").ToList();
```

In PG I don't use jsonpath to traverse - there's a dedicated expression syntax which supports regular SQL expressions: `WHERE b.CustomerElement #>> ARRAY[@p__i_0]`. [Here's the PG test](https://github.com/npgsql/efcore.pg/blob/main/test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs#L277) which exercises this.

It's true that things are more awkward with SQL Server since a single jsonpath string must be provided, but like @maumar said, we should be able to use concatenation of expression results here, no?

2022-07-16 03:03 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
The issue is the list of SqlExpression. If it is concatenation then use SqlBinary with +. If it is not concatenated string and can be anything then don't make it SqlExpression especially if values inside is constant or parameter.

2022-07-16 03:38 UTC, maumar commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            IReadOnlyList<SqlExpression> jsonPath)
the sql representation of the path is provider specific, so I always have to keep individual path elements separate somehow, until sql generation.

2022-07-29 21:54 UTC, AndriySvyryd reviewed
Some old comments that I forgot to post

2022-08-12 21:14 UTC, smitpatel commented on src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs
> +            var foo = prop.RequiresValueGenerator();
why....

2022-08-12 21:14 UTC, smitpatel commented on src/EFCore/Metadata/RuntimeProperty.cs
> +        //[DebuggerStepThrough]
revert

2022-08-12 21:14 UTC, smitpatel commented on src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
> +            if (property.Name == "Id" && property.IsShadowProperty())
...

2022-08-12 21:15 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
> +    ///     Returns a value indicating whether the given value can be used as a JSON property name for a given navigation.
where is the navigation?

2022-08-12 21:16 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
> +    /// <returns><see langword="true" /> if the given value can be set as JSON property name for this navigation.</returns>
navigation

2022-08-12 21:18 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalNavigationJsonPropertyNameAttributeConvention.cs
> +            navigationBuilder.Metadata.TargetEntityType.Builder.HasJsonPropertyName(attribute.Name, fromDataAnnotation: true);
cc: @AndriySvyryd builder to metadata to builder. Is there any other path?

2022-08-12 21:20 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Conventions/RelationalNavigationJsonPropertyNameAttributeConvention.cs
> +            navigationBuilder.Metadata.TargetEntityType.Builder.HasJsonPropertyName(attribute.Name, fromDataAnnotation: true);
This is is the best one available

2022-08-12 21:21 UTC, AndriySvyryd commented
Is this draft ready for review yet? So we can really start commenting

2022-08-12 21:22 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +            }
you are storing non-json as is. Either make those nullable too or remove them from dict

2022-08-12 21:22 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/PropertyExtensions.cs
> +            Console.WriteLine("");
👀

2022-08-12 21:23 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +                for (var i = 0; i < primaryKeyProperties.Count(); i++)
Its a list. Call just Count property rather than method

2022-08-12 21:24 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +            if (shaper.EntityType.IsMappedToJson())
check if shaper is already nullable (for whatever reason)

2022-08-12 21:26 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +                    changed = true;
Is changed useful given you are allocating and populating dict anyway and ctor is just doing assignment. and you are recreating the expression

2022-08-12 21:31 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            return new JsonScalarExpression(
Make JsonScalar take IProperty

2022-08-12 21:32 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            var typeMapping = targetEntityType.GetJsonColumnTypeMapping()!;
Why do you need type mapping for Json if you are already inside json context

2022-08-12 21:33 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            for (var i = 0; i < sourcePrimaryKeyProperties.Count; i++)
this is same as _keyPropertyMap.Count so use it directly.

2022-08-12 21:33 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            var sourcePrimaryKeyProperties = EntityType.FindPrimaryKey()!.Properties.Take(_keyPropertyMap.Count).ToList();
remove ToList on both, use Zip and directly enumerate in foreach

2022-08-12 21:34 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        public virtual JsonQueryExpression MakeNullable(Dictionary<IProperty, ColumnExpression> nullableKeyPropertyMap)
readonlydict

2022-08-12 21:35 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +    public class JsonQueryExpression : Expression, IPrintableExpression
Equals/HashCode

2022-08-12 21:48 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    if (GetProjectionIndex(projectionBindingExpression) is ValueTuple<int, List<(IProperty, int)>, string[]> jsonProjectionIndex)
inside cache

2022-08-12 21:50 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                var property = methodCallExpression.Arguments[2].GetConstantValue<IProperty>();
property could be null

2022-08-12 21:50 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    (var jsonElementParameter, var keyPropertyValuesParameter) = _jsonMaterializationContextParameterMapping[mappingParameter];
move var outside

2022-08-12 21:51 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                        var extractJsonPropertyExpression = Expression.Call(
create method similar to CreateGetReadValue to read from jsonelement so that you can throw detailed exception message when enabled

2022-08-12 21:53 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            if (jsonElement.HasValue)
What if this doesn't have a value?

2022-08-12 21:53 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            if (nullable)
why don't we check for value kind being null?

2022-08-12 21:57 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                                    Expression.Property(
Don't use property. Use memberaccess with passing propertyinfo

2022-08-12 22:02 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var visitedExpressionsArray = entityShaperMaterializer.Expressions.ToArray();
Just do nested blocks. Save result of inner block in a variable and then return at the end of outer block

2022-08-12 22:05 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            null,
why there is null here?

2022-08-12 22:05 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                    var table = entityType.GetViewOrTableMappings().SingleOrDefault()?.Table
ouch!

2022-08-12 22:06 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                else
remove else block.

2022-08-12 22:07 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            else
remove else

2022-08-12 22:10 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
> +        protected override Expression VisitChildren(ExpressionVisitor visitor)
update method

2022-08-12 22:12 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                else if (projection is JsonQueryExpression jsonQueryExpression)
We don't do distinct over collection. Block it at the start by checking Jsonquery being collection

2022-08-12 22:13 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
>                  result[projectionMember] = expression is EntityProjectionExpression entityProjection
do switch expression

2022-08-12 22:16 UTC, smitpatel commented on src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
> +            nameof(RelationalOwnedNavigationBuilderExtensions.ToJson), new[] { typeof(OwnedNavigationBuilder), typeof(string) })!;
Why this is in SqlServer rather than relational?

2022-08-12 22:17 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
> +        => jsonScalarExpression;
You may need to visit inside the path if you make it something other than list of string

2022-08-13 00:48 UTC, maumar commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +                    changed = true;
we could improve this logic and only create new EntityProjectionExpression if any of the columns in dict was made nullable. In other MakeNullable() methods we avoid creating new instances when no changes were made

2022-08-13 17:52 UTC, AndriySvyryd commented on src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
>          var declaringTable = property.GetMappedStoreObjects(StoreObjectType.Table).FirstOrDefault();
This needs to return the table to be able to move the logic above to relational

2022-08-13 17:53 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Conventions/RelationalJsonPropertyNameAttributeConvention.cs
> +public class RelationalJsonPropertyNameAttributeConvention : PropertyAttributeConventionBase<JsonPropertyNameAttribute>
Remove, already exists

2022-08-13 17:55 UTC, AndriySvyryd commented on src/EFCore.Relational/Update/Internal/SharedTableEntryMap.cs
> +            var dependentEntries = _updateAdapter.GetDependents(entry, foreignKey).ToList();
```suggestion
            var dependentEntries = _updateAdapter.GetDependents(entry, foreignKey);
```

2022-08-13 18:01 UTC, AndriySvyryd commented on test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
> +    public class SqlServerJsonTest : RelationalJsonTestBase
Merge into `SqlServerOwnedTypes`

2022-08-14 02:04 UTC, maumar commented on test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
> +    public class SqlServerJsonTest : RelationalJsonTestBase
bad merge

2022-08-14 03:15 UTC, maumar commented on src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
> +            nameof(RelationalOwnedNavigationBuilderExtensions.ToJson), new[] { typeof(OwnedNavigationBuilder), typeof(string) })!;
bad merge

2022-08-14 05:25 UTC, maumar commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +                    changed = true;
#28707

2022-08-14 08:43 UTC, maumar commented on src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
>          var declaringTable = property.GetMappedStoreObjects(StoreObjectType.Table).FirstOrDefault();
Table doesn't get returned because the code goes thru GetDefaultColumnName which returns null for entities mapped to json. Seems like too much work to fork this code path to return a name for json property in this specific case.

2022-08-14 08:44 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var visitedExpressionsArray = entityShaperMaterializer.Expressions.ToArray();
flattened structure looks better no? unless I'm misunderstanding you here

2022-08-14 10:22 UTC, maumar commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +            return new JsonScalarExpression(
this seems superfluous. JsonScalar not always has IProperty, sometimes we create one directly from JsonQuery (without binding a property), so we need ctor that takes type mapping and type also.

2022-08-14 23:47 UTC, maumar commented on src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
>          var declaringTable = property.GetMappedStoreObjects(StoreObjectType.Table).FirstOrDefault();
alternatively, we could make it so that key properties of the json column returns a name. they kind of are mapped to the key property of the owner entity. But that's something we can test/experiment with later.

2022-08-15 06:56 UTC, AndriySvyryd commented on src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
>          var declaringTable = property.GetMappedStoreObjects(StoreObjectType.Table).FirstOrDefault();
It's fine to do this later

2022-08-15 07:34 UTC, maumar commented on src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
>          var declaringTable = property.GetMappedStoreObjects(StoreObjectType.Table).FirstOrDefault();
#28714

2022-08-15 14:52 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +            var visitedExpressionsArray = entityShaperMaterializer.Expressions.ToArray();
> flattened structure looks better no?

Not when you are generating code. Keeping independent code blocks which are separate is better here as no one is going to read the code.

2022-08-15 19:37 UTC, smitpatel commented on src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
> +        ///     Can't navigate to parent entity.
This needs to be more detailed. What is parent entity. What navigation, what entity type.

2022-08-15 19:39 UTC, smitpatel commented on src/EFCore.Relational/Query/EntityProjectionExpression.cs
> +            var newShaper = shaper;
move variable declaration to close to usage

2022-08-15 19:42 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// <param name="entityType">The entity type.</param>
better doc comments

2022-08-15 19:44 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// The JSON column.
tab by one indent.

2022-08-15 19:44 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +                    RelationalStrings.JsonCantNavigateToParentEntity);
you have navigation and both entity types here, use them in exception message

2022-08-15 19:46 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        public virtual SqlExpression? JsonPath { get; }
Can path be empty in all providers? SqlServer requires min $ sign. cc: @roji

2022-08-15 19:51 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
> +            if (valueBufferExpression is JsonQueryExpression jsonQueryExpression)
This thing is not handled yet!!!!

2022-08-15 19:57 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
> +        /// <param name="jsonColumn">The JSON column expression.</param>
article A

2022-08-15 19:58 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
> +        /// <param name="jsonColumn">The JSON column expression.</param>
Actually check docs on other SqlExpression.Update and make it like those

2022-08-15 20:35 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                    nullable: !ownedJsonNavigation.ForeignKey.IsRequired || ownedJsonNavigation.IsCollection);
is required dependent?

2022-08-15 20:36 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                    !ownedJsonNavigation.ForeignKey.IsRequired);
required dependent?

2022-08-15 20:38 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +                        jsonClientProjectionDeduplicationMap = BuildJsonProjectionDeduplicationMap(_clientProjections.OfType<JsonQueryExpression>());
this recomputes the map again for existing projection too. Avoid it here.

2022-08-15 20:39 UTC, smitpatel commented
>                     earlierClientProjectionCount = _clientProjections.Count;

This is where we do process after lifting from single result subquery. Recompute the dedupe map here from this point to end point.

---
Refers to: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs:846 in f2ab2b9. [](commit_id = f2ab2b9ba510d47ab49e39f8d4b325cfd19873ae, deletion_comment = False)

2022-08-15 20:52 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
> +            while (currentPath is SqlBinaryExpression sqlBinary)
validate add operation

2022-08-15 20:59 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                resultExpression = Expression.Invoke(
Why invocationexpression rather than replacing like the other method?

2022-08-15 21:02 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        private Expression CreateJsonShapers(
Move method after Visit*

2022-08-15 21:04 UTC, smitpatel commented
cc: @AndriySvyryd to review metadata/update pipeline changes.

2022-08-15 21:25 UTC, AndriySvyryd commented on test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
> +        public virtual void Json_entity_and_normal_owned_can_exist_side_to_side_on_same_entity()
Shouldn't these be in Relational?

2022-08-15 21:26 UTC, AndriySvyryd approved these changes

2022-08-15 21:43 UTC, maumar commented on test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
> +        public virtual void Json_entity_and_normal_owned_can_exist_side_to_side_on_same_entity()
will move all the tests in further pr

2022-08-15 21:44 UTC, maumar commented on test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
> +        public virtual void Json_entity_and_normal_owned_can_exist_side_to_side_on_same_entity()
#28736

2022-08-15 22:07 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// <param name="entityType">An entity type.</param>
An entity type being represented by this expression

2022-08-15 22:08 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// <param name="collection">a value indicating whether this expression represents a collection.</param>
A capital

2022-08-15 22:08 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// <param name="keyPropertyMap">A map of key properties and columns they map to.</param>
append that when they map to actual column in database

2022-08-15 22:08 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +    ///     Expression representing an entity or a collection of entities mapped to a JSON column.
and the path to access them

2022-08-15 22:09 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        public override Type Type => _type;
do we need field for type or assign directly

2022-08-15 22:10 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// <param name="type">A type of the expression.</param>
a type of the element represented by this expression

2022-08-15 22:10 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        ///     The column containg JSON.
value on the path is applied

2022-08-15 22:12 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// </summary>
document parameter and returns

2022-08-15 22:12 UTC, smitpatel commented on src/EFCore.Relational/Query/JsonQueryExpression.cs
> +        /// </summary>
same for other methods in this class. Also check JsonScalarExpression class

2022-08-15 22:13 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
> +    ///     Expression representing a scalar mapped to a JSON column.
scalar is not mapped to the json column. Scalar is being extracted from a json column

2022-08-15 22:14 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +using System.Data;
why do we need this?

2022-08-15 22:14 UTC, smitpatel approved these changes

2022-08-15 23:25 UTC, merged