Add support for CSharpHelper for List literals
dotnet/efcore pull request #28212
Opened 2022-06-13 00:17 UTC by yinzara

Fixes #19274

Also relates to https://github.com/npgsql/efcore.pg/pull/2402

- [X ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [X ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [X] The code builds and tests pass locally (also verified by our automated build checks)
- [X] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Code follows the same patterns and style as existing code in this repo

2022-06-13 00:17 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=28212) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=28212) before we can accept your contribution.<br/><br/>:x: yinzara [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=28212)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=28212) it.</sub>

2022-06-13 08:13 UTC, roji requested changes

2022-06-13 08:13 UTC, roji commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +                if (!HandleList(listExpr.Initializers.Select(_ => _.Arguments.First()), builder, simple: true))
```suggestion
                if (!HandleList(listExpr.Initializers.Select(i => i.Arguments.First()), builder, simple: true))
```

2022-06-13 08:13 UTC, roji commented on test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> +    public void Literal_works_when_string_list_no_arguments()
Add Literal_works_when_empty_string_list for completeness (also below)

2022-06-13 08:13 UTC, roji commented on test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> +    public void Literal_works_when_string_list_no_arguments()
Rename to Literal_works_when_string_list_without_ctor_arguments for precision.

Also, can remove "string_" from all test names to make shorter.

2022-06-13 17:38 UTC, yinzara commented
All comments addressed. TY!

2022-06-21 17:17 UTC, roji commented
Note: waiting for @bricelam to make sure it aligns with his work etc.

2022-06-24 16:30 UTC, bricelam commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +    public virtual string Literal<T>(IList<T> values, bool vertical = false)
```suggestion
    public virtual string Literal<T>(List<T> values, bool vertical = false)
```
I think these overloads should be very specific to the type of literal they generate. There are lots of types that implement IList\<T>

2022-06-24 16:30 UTC, bricelam commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +            case ExpressionType.ListInit:
Do you intend to use this? If not, I say remove it until it's needed.

2022-06-24 16:30 UTC, bricelam commented on test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> +            @"new List<string> { }");
I have a slight preference for `new List<string>()` but this is also fine.

2022-06-24 19:40 UTC, yinzara commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +            case ExpressionType.ListInit:
Funny enough I added it because I was going to use it in EFCore.PG but if I just get regular literals working, it solves the problem without the additional code in PG so I'm kinda ambivalent.

I guess I don't really see the use of the `HandleExpression` functionality much anyway except for libraries like EFCore.PG to handle special cases specific to their implementation. It would allow more complex literal list expressions to be handled but I don't see much value in that.

I did add test cases to verify it works: `Literal_with_list_init_without_ctor_arguments` and `Literal_with_list_init_with_ctor_arguments` but I can remove it if you want.

2022-06-24 19:40 UTC, yinzara commented on test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> +            @"new List<string> { }");
It was the difference between special code to handle that case and not.  I considered it :) I just didn't think the extra code was worth it for a preference in syntax.

2022-06-24 19:41 UTC, yinzara commented on test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> +
No problem

2022-06-24 19:41 UTC, yinzara commented on src/EFCore.Design/Design/Internal/CSharpHelper.cs
> +    public virtual string Literal<T>(IList<T> values, bool vertical = false)
Fine with me.

2022-06-24 19:57 UTC, yinzara commented on test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> +            @"new List<string> { }");
I think I figured out a way to make it the better syntax with very minimal additional code (2 lines effectively) and no additional wasted overhead. :) You tell me

2022-06-27 05:16 UTC, yinzara commented
All comments have been addressed. I think we're ok for merge.

2022-06-27 16:04 UTC, bricelam approved these changes

2022-06-27 17:14 UTC, merged