Implement BulkDelete
dotnet/efcore pull request #28492
Opened 2022-07-21 22:20 UTC by smitpatel

Part of #795

2022-07-26 01:04 UTC, smitpatel commented
This covers basic scenario and ability to convert to subquery form. Allowing additional tables is very provider specific. I will add support for it in SqlServer in separate PR. (This PR does improvement for SqlServer when there is only Take specified).

Pending negative cases
- TPT
- TPC
- Entity splitting
- Table splitting
- Non entity

@roji - This is something which can allow you to test against Npgsql.

2022-07-26 01:05 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
> +    ///     TBD
@dotnet/efteam - Can someone suggest docs? :trollface:

2022-07-26 01:05 UTC, smitpatel commented on src/EFCore.Relational/Query/NonQueryExpression.cs
> +#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
Will fill in these later once bulkupdate is implemented.

2022-07-26 01:06 UTC, smitpatel commented on src/EFCore.Relational/Query/QuerySqlGenerator.cs
> +            throw new InvalidOperationException();
@dotnet/efteam - This is where it would throw error if provider said they support more pattern but didn't write custom code for it to generate SQL.

2022-07-26 01:06 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                    throw new InvalidOperationException("specific message about keyless");
Exception message about keyless entities cannot be converted to subquery form.

2022-07-26 01:07 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +        return null;
Exception message about bulk delete applied on non-entity projection.

2022-07-26 01:07 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +        try
Does bulk operation requires concurrency detector?
Checking for task cancellation?
What can be other exceptions?

2022-07-26 01:07 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/DeleteExpression.cs
> +public sealed class DeleteExpression : Expression, IPrintableExpression
Same as NonQueryExpression

2022-07-26 01:08 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +            throw new NotSupportedException();
Same as QuerySqlGenerator

2022-07-26 06:36 UTC, roji commented
Thanks @smitpatel, will review and implement the PG side against this to validate :+1:

2022-07-26 18:30 UTC, roji commented on src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
> +    ///     TBD
Submitted #28523 against this branch with suggestions

2022-07-26 18:31 UTC, roji commented on src/EFCore.Relational/Query/QuerySqlGenerator.cs
> +            throw new InvalidOperationException();
Makes sense, a bit like a debug.assert for providers.

2022-07-26 18:31 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                    throw new InvalidOperationException("specific message about keyless");
Submitted in #28523

2022-07-26 18:31 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +        return null;
Submitted in #28523

2022-07-26 18:33 UTC, roji requested changes
Look great @smitpatel, definitely simpler/smaller than I feared it may be :cupid:

2022-07-26 18:33 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +            throw new NotSupportedException();
Submitted in #28523

2022-07-26 18:46 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/DeleteExpression.cs
> +    public sealed override ExpressionType NodeType
you wanted this in all custom expression at some point lol.

2022-07-26 18:47 UTC, smitpatel commented on src/EFCore.Relational/Query/QuerySqlGenerator.cs
> +            && selectExpression.Tables[0] == deleteExpression.Table
Set operation are represented as select expression so if table is TableExpression then this doesn't represent set operation by default.

2022-07-26 18:48 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +        NonQueryExpression CheckTranslated(NonQueryExpression? translated)
But the base has it at top. We have a pending discussion on convention.

2022-07-26 18:50 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +    protected virtual bool IsValidSelectExpressionForBulkDelete(
"Feature" is too subjective. Given there is entity shaper here, if provider wants to throw custom message for keyless when there is offending feature, they can easily do so.

2022-07-26 18:50 UTC, roji commented on src/EFCore.Relational/Query/SqlExpressions/DeleteExpression.cs
> +    public sealed override ExpressionType NodeType
I did??

2022-07-26 18:50 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +            // Throw friendly message
Just logging.

2022-07-26 18:50 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +            Visit(selectExpression.Tables[0]);
Yes.

2022-07-26 18:51 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +    protected virtual bool IsValidSelectExpressionForBulkDelete(
This was more about doing it in relational.. Providers will likely copy whatever we do here in relational (along with error reporting). But not critical.

2022-07-26 19:03 UTC, roji commented
I thought we used the concurrency detector also because database connections aren't thread-safe... For example, we also use it in ExecuteSqlRaw, which also doesn't have anything to do with the change tracker.

Not sure there's a downside to having it here by default (it can always be disabled for extra perf). /cc @ajcvickers

2022-07-26 21:45 UTC, smitpatel commented on src/EFCore.Relational/Query/SqlExpressions/DeleteExpression.cs
> +    public sealed override ExpressionType NodeType
https://github.com/dotnet/efcore/issues/15662
2nd last point.

2022-07-26 21:51 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
> +            Visit(selectExpression.Tables[0]);
Added support for join.

2022-07-26 23:08 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +        try
let's discuss in a design meeting.

2022-07-26 23:08 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    protected virtual void ClearLog()
Added set operations, joins. Will add few more manual joins in inheritance tests.

2022-07-27 00:02 UTC, smitpatel commented
@roji - Join tests are in for you to light up using syntax.

2022-07-27 07:19 UTC, roji commented on src/EFCore.Relational/Query/SqlExpressions/DeleteExpression.cs
> +    public sealed override ExpressionType NodeType
Ah sure - my point here was only that it's unnecessary to seal this specific property if the whole class is sealed. In other words, if the CLR type weren't sealed, then yeah, it would make sense to seal the NodeType specifically...

2022-07-27 09:27 UTC, roji approved these changes
LGTM - seems mergeable (but am happy to continue iterating on this if you want to add more stuff). Synced my PG PR https://github.com/npgsql/efcore.pg/pull/2449 (filtered by last commit) to do join via PG USING.

2022-07-27 16:24 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    [ConditionalTheory(Skip = "Issue#28525")]
It should work hence skipped.

2022-07-27 16:25 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            // TODO: Throw better exception message indicating that delete requires an entity type
Sorry for renaming the test names.

2022-07-27 16:26 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            // TODO: Throw better exception message indicating that delete requires an entity type
I will add few more tests around inheritance and query filters (hence added those test bases).

2022-07-27 18:44 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            // TODO: Throw better exception message indicating that delete requires an entity type
No worries, it's very little work to react, feel free to change anything.

2022-07-28 22:02 UTC, smitpatel commented
Added test to block all invalid scenarios
- Entity splitting
- Table splitting
- TPT
- TPC non-leaf type
- Non-entity projection
- Keyless entity which requires subquery form

Also added test for query filter, set operations, FromSql, positive cases for TPT/TPC. Using TPT/TPC in predicate while deleting other entity types.

2022-07-28 23:33 UTC, smitpatel commented
/azp run

2022-07-29 15:27 UTC, roji approved these changes
Here you go @smitpatel. Also synced https://github.com/npgsql/efcore.pg/pull/2449 to the latest state of this.

2022-07-29 16:15 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
> +            @"DELETE FROM [o]
Let me check if it works in SQL server.

2022-07-29 16:28 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
> +            @"DELETE FROM [o]
Right, I see that this isn't supported with the alias. We could do it without the alias:

```sql
DELETE FROM [Order Details]
WHERE [Order Details].[OrderID] < 10300
```

But this would probably be non-trivial to do in our pipeline. Also it could result in longer SQL if the table name is big and repeated.

2022-07-29 17:09 UTC, smitpatel commented on test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
> +            @"DELETE FROM [o]
Implicit column binding works so table name can be excluded. The implementation in-line with what we had discussed. I think we should leave it customer feedback here because the current way is more maintainable for us.

2022-07-29 17:10 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +        }
I didn't do this way because there were only 2 labels.

2022-07-29 17:34 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +                relationalQueryContext.QueryLogger.QueryIterationFailed(contextType, exception);
Update this to NonQueryFailed.

2022-07-29 17:34 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +                relationalQueryContext.QueryLogger.QueryCanceled(contextType);
See if we can make it more-generic.

2022-07-29 17:40 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +
empty line

2022-07-30 13:16 UTC, roji commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
What happens for set operations with different source tables? smiling_imp

(trying to think up more negative scenarios for you)

2022-07-30 19:46 UTC, smitpatel commented on src/EFCore.Relational/Diagnostics/RelationalEventId.cs
> +    public static readonly EventId BulkOperationFailed = MakeQueryId(Id.BulkOperationFailed);
We don't know which operation it is when we are executing it. It is just a non-query expression.

2022-07-30 19:49 UTC, smitpatel commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +    protected virtual NonQueryExpression? TranslateBulkDelete(ShapedQueryExpression source)
This one I will align with the name but we need to have another design meeting about the word "bulk".
While API is more intuitive from name perspective, there is no "execute" operations. The issue title contains "bulk" and for years it has remained that way and no one complained. "bulk operation" as a concept is not a wrong term to use.

2022-07-30 19:49 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
Set operations are always converted to subquery form so regardless of source tables, it just works

2022-07-30 21:27 UTC, roji commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
But wait, if I do `ctx.Blogs1.Concat(ctx.Blogs2).ExecuteDelete()`, that looks like it should delete all rows from *both* tables, which would mean two SQL statements, no? At least that's what the corresponding query does.

If so, this would possibly be covered by #28520.

2022-07-31 06:39 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
Does `ToList` on that query work? If the `Blogs1` & `Blogs2` are 2 different tables then regardless of their CLR types being same (else Concat wouldn't work), their IEntityType must be different. We don't support set operations between 2 different entity types.

2022-07-31 12:40 UTC, roji commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
OK. It may still be a good idea to add a negative test - if one day we do add support set operations over different entity types, updates would still need to be blocked (unless we implement it via multiple DMLs). But can also forget about it.

2022-07-31 18:00 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
> if one day we do add support set operations over different entity types

We cannot support it. Both entity types would have different materialization paths. It is not something we haven't yet added support for, it is something which is not possible to do.

2022-07-31 22:34 UTC, roji commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
Couldn't we could synthesize a discriminator column if we wanted to - don't we do that for TPT/TPC? In fact a Concat between two entity types seems quite similar to selecting the root of a TPC hierarchy, in both cases two concrete tables are being selected back (and unless I'm mistaken we use a UNION ALL for that).

But anyway...

2022-07-31 23:59 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
We decided not to do discriminator thing on #16243

2022-08-01 18:00 UTC, smitpatel commented on test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
> +    public virtual Task Delete_Concat(bool async)
I had more thoughts about this. Have some guidelines about testing, let's discuss in today's design meeting.

2022-08-01 18:02 UTC, smitpatel commented on src/EFCore.Relational/Properties/RelationalStrings.resx
> +  <data name="BulkDeleteOnTableSplitting" xml:space="preserve">
named variable operation and removed bulk from that. Though there are multiple usage of bulk and no easy way to refer to it. We do need to discuss bulk naming again. (not necessarily change API name but concept is not gone)

2022-08-01 22:04 UTC, smitpatel commented on src/EFCore.Relational/Diagnostics/RelationalEventId.cs
> +    public static readonly EventId BulkOperationFailed = MakeQueryId(Id.BulkOperationFailed);
Filed #28568

2022-08-03 02:33 UTC, merged

2022-08-03 09:35 UTC, jimjimjimhaha commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +    protected virtual NonQueryExpression? TranslateBulkDelete(ShapedQueryExpression source)
> The issue title contains "bulk" and for years it has remained that way and **no one complained**

Sorry to sneak my way in here, but just wanted to say you probably haven't checked out that thread for a long time. This very word has been complained about over and over again. I thought `Execute` was finalized? It received much more positive feedback.