Add a static flag in EF that will be set when code is being executed for design-time discovery
dotnet/efcore pull request #28508
Opened 2022-07-25 15:08 UTC by ajcvickers

Fixes #27306.

2022-07-25 15:09 UTC, ajcvickers commented
@bricelam Is there a better way to test this?

2022-07-25 16:18 UTC, bricelam reviewed
We should also set it in `DbContextActivator.CreateInstance`.

2022-07-25 16:18 UTC, bricelam commented on src/EFCore.Design/Design/OperationExecutor.cs
> +            EF.IsDesignTime = true;
Hmm, maybe move this to `Execute`.

I wonder if we should also set it back to `false` afterwards incase the process/AppDomain is reused. Probably not very important.

2022-07-25 16:31 UTC, bricelam commented
> Is there a better way to test this?

This is exactly how I'd do it.

2022-07-26 10:55 UTC, ajcvickers commented
@bricelam New version up.

2022-07-26 23:52 UTC, bricelam requested changes
We should also set it in `DbContextActivator.CreateInstance`. That's is what [ASP.NET Scaffolding uses](https://github.com/dotnet/Scaffolding/blob/main/src/Scaffolding/VS.Web.CG.EFCore/EntityFrameworkModelProcessor.cs#L562) at design-time.

2022-07-28 15:32 UTC, bricelam approved these changes

2022-07-28 17:27 UTC, merged