Metadata work for json.
dotnet/efcore pull request #28540
Opened 2022-07-29 01:20 UTC by maumar

Separated from main PR to make the review easier.

This PR includes:

- builder methods,
- conventions,
- relational model,
- model validation,
- migrations,
- update.

2022-07-29 01:27 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    ///     TODO
will add all the docs once we are ok with the api

2022-07-29 01:28 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +        static bool IsMapped(IReadOnlyForeignKey foreignKey, StoreObjectIdentifier storeObject)
do we need this part?

2022-07-29 01:31 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalOwnedNavigationBuilderExtensions.cs
> +            string? jsonColumnName = null)
or should we have 2 methods, parameterless for the navigation name default and one with explicit column name, where null value would mean unwinding the map to json process?

2022-07-29 01:33 UTC, maumar commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +    private JsonNode CreateJsonDocument(IUpdateEntry entry, IEntityType entityType, int? ordinal)
will refactor/ DRY this

2022-07-29 09:26 UTC, roji requested changes
Here's a 1st round of comments from me. There are some questions we may want to discuss in design (e.g. distinction between columns and JSON properties, whether JSON properties should be represented as columns in the relational model).

2022-07-29 09:26 UTC, roji commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnTypeMapping(this IMutableEntityType entityType, RelationalTypeMapping typeMapping)
Not sure exactly what this means - I can see it being set to a mapping with CLR type JsonElement below in RelationalMapToJsonConvention, but I'm not sure why the nested owned JSON entity types would need a type mapping... Of course the top-level navigation property to the JSON document needs to have the column type (json/jsonb or whatever), but I'm not sure why this is needed on all nested ones.

Is this to be able to determine the actual column type for the JSON column (e.g. json/jsonb in PG, varchar(max) in SQL Server)? If so, isn't it enough to just

2022-07-29 09:26 UTC, roji commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                    typeof(JsonElement))!;
See comment above about the necessity of having a type mapping on nested owned JSON entity types.

2022-07-29 09:26 UTC, roji commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                        navigation.TargetEntityType.SetJsonColumnName(jsonColumnName);
See comment about maybe not setting an annotation on all owned types in a JSON hierarchy (but rather calculating it from the top-most navigation property).

2022-07-29 09:26 UTC, roji commented on src/EFCore.Relational/Metadata/Conventions/RelationalNavigationJsonPropertyNameAttributeConvention.cs
> +///     A convention that configures a json element name for the navigation property mapped to json
We should probably use JSON in uppercase throughout.

2022-07-29 09:26 UTC, roji commented on src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
> +            // don't uniquify json columns
As above, I may be misunderstanding the overall design, but OTOH I don't believe we should represent JSON properties as columns (which should be reserved for true table columns)... In other words, for entity types mapped to JSON, we should consider having GetColumnName should return null for all properties.

Regardless, this check can be moved outside of the foreach (just return from the function immediately for JSON-mapped entity types).

2022-07-29 09:26 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +namespace Microsoft.EntityFrameworkCore.Metadata.Internal
File-scoped namespace declaration

2022-07-29 09:26 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
I know we diescussed it before, but this seems problematic to me (JSON properties aren't relational columns). We should maybe have a design meeting about this.

2022-07-29 17:28 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static bool IsMappedToJson(this IReadOnlyEntityType entityType)
This overload is enough, you can remove the other ones.

2022-07-29 18:04 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnName(this IMutableEntityType entityType, string columnName)
This is for both top-level column (when called on the first owned type) and the JSON property on the parent object (on nested entity types), so I think calling them columns should be ok as a compromise.

Currently we don't have `SetColumnName` on entity types, but if we want to be very clear then we could add it and only use `SetJsonColumnName` for JSON property names (and rename it)

2022-07-29 18:05 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static string? JsonColumnName(this IReadOnlyEntityType entityType)
Remove the other overloads

2022-07-29 18:16 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnTypeMapping(this IMutableEntityType entityType, RelationalTypeMapping typeMapping)
@roji Seems that your comment got trimmed

I wonder if we could get away with just setting the store type

2022-07-29 18:19 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static RelationalTypeMapping? JsonColumnTypeMapping(this IReadOnlyEntityType entityType)
`GetJsonColumnTypeMapping` if we are going to keep it. And remove other overloads.

2022-07-29 18:26 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +        var mappedToJson = entityType.IsMappedToJson();
inline variable and combine with previous if.

2022-07-29 18:29 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static RelationalTypeMapping? JsonColumnTypeMapping(this IConventionEntityType entityType)
Get or Find? we have APIs without verb?

2022-07-29 18:30 UTC, smitpatel commented on src/EFCore.Relational/Extensions/RelationalNavigationExtensions.cs
> +    public static string JsonElementName(this IReadOnlyNavigationBase navigation)
+1

2022-07-29 19:32 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalNavigationExtensions.cs
> +    public static string JsonElementName(this IReadOnlyNavigationBase navigation)
GetJsonElementName

2022-07-29 19:37 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalNavigationBuilderExtensions.cs
> +    public static IConventionNavigationBuilder? HasJsonElementName(
It's better to store the JSON property name on the entity type as it can only have one, so multiple navigations with this would be ambiguous

2022-07-29 20:08 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalOwnedNavigationBuilderExtensions.cs
> +            string? jsonColumnName = null)
> I think a parameterless ToJson() should simply mean "map to JSON" (with default naming), passing an explicit null could be the thing which undoes JSON mapping.

That's how it works for ToTable(), we should align

2022-07-29 20:11 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
> +    public static PropertyBuilder HasJsonElementName(
It's `ToJsonProperty` in Cosmos

2022-07-29 21:25 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +                linkingRelationship = FindRowInternalForeignKeyForJson(principalProperty.DeclaringEntityType, storeObject);
Instead add a pubternal overload of `FindRowInternalForeignKeys` with a parameter `traverseJson`, that would be set to `false` by default but when `true` it would prevent empty result for entity types mapped to JSON.

In this method `traverseJson` would be set outside of the loop to `!property.DeclaringEntityType.IsMappedToJson()`

2022-07-29 21:28 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelRuntimeInitializer.cs
> +                RelationalDependencies.RelationalTypeMappingSource,
```suggestion
                (IRelationalTypeMappingSource)Dependencies.ModelDependencies.TypeMappingSource,
```

2022-07-29 21:29 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelRuntimeInitializerDependencies.cs
> +    public IRelationalTypeMappingSource RelationalTypeMappingSource { get; init; }
Not needed

2022-07-29 21:32 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +    private Dictionary<StoreObjectIdentifier, List<IEntityType>> BuildSharedTableEntityMap(IEnumerable<IEntityType> entityTypes)
Instead of calling this you can refactor and call `ValidateJsonEntities` from `ValidateSharedTableCompatibility`

2022-07-29 21:32 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilderDependencies.cs
> +    public IRelationalTypeMappingSource RelationalTypeMappingSource { get; init; }
Not needed

2022-07-29 21:33 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Conventions/RelationalRuntimeModelConvention.cs
> +                    RelationalDependencies.RelationalTypeMappingSource,
```suggestion
                    (IRelationalTypeMappingSource)Dependencies.TypeMappingSource,
```

2022-07-29 21:34 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +            AddTables(databaseModel, entityType, relationalTypeMappingSource);
What about views?

2022-07-29 21:46 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static RelationalTypeMapping? JsonColumnTypeMapping(this IConventionEntityType entityType)
Get per Andriy's suggestion

2022-07-29 21:54 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +                ? entityType.FindForeignKeys(primaryKey.Properties.ToArray()[..^1])
If it's an owned type mapped to JSON just use the ownership, don't look for other FKs

2022-07-29 21:56 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalNavigationBuilderExtensions.cs
> +    public static IConventionNavigationBuilder? HasJsonElementName(
@roji this is to allow customizing name of the key part of the kvp. Basically fluent api version of `JsonPropertyNameAttribute`. Will rename

2022-07-29 23:02 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                    "Json mapped type can't be owned by a non-json owned type. Only regular entity types or json mapped types are allowed.");
"Owned entity type '{rootType}' is mapped to table '{table}' and contains JSON columns. This is currently not supported. All owned types containing a JSON column must be mapped to a JSON column themselves."

2022-07-29 23:06 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            var distinctRootTypes = nonOwnedTypes.Select(x => x.GetRootType()).Distinct();
Calling `Distinct` shouldn't be necessary

2022-07-29 23:14 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                .GroupBy(x => x.JsonColumnName())
This should only be done for ownerships where `rootAggregateType` is principal. It's fine to use the same JSON property name on different levels. Nested types would be checked below

2022-07-30 00:04 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +        var columnNames = foreignKey.GetMappedKeyProperties().GetColumnNames(storeObject);
Revert these changes. The ownership FKs on JSON entity types should have `null` constraint name, so this won't be called

2022-07-30 00:06 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
>              return null;
Return `null` when on JSON instead

2022-07-30 00:09 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> -        var columnNames = key.Properties.GetColumnNames(storeObject);
Revert these changes. The PK on JSON entity types should return `null` constraint name, so this won't be called

2022-07-30 00:10 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +        if (key.DeclaringEntityType.IsMappedToJson())
Combine with previous condition

2022-07-30 00:11 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +    public static IReadOnlyList<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyKey key)
Remove these

2022-07-30 00:22 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                $"Entity type '{jsonEntityType.DisplayName()}' has incorrect number of primary key properties.");
Just validate against the direct owner and add the correct number to the message

2022-07-30 00:31 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            if (!ordinalKeyProperty.IsShadowProperty() || ordinalKeyProperty.ClrType != typeof(int) || !ordinalKeyProperty.Name.EndsWith("Id", StringComparison.Ordinal))
Also validate that JsonPropertyName is null

2022-07-30 00:46 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            }
Also validate that that all properties and nested owned types are mapped to unique JSON properties

2022-07-30 00:58 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
This represent a column of JSON type. We can use a different type for nested properties when we add them to the relational model

2022-07-30 00:58 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +        private readonly ValueComparer _provierValueComparer;
```suggestion
        private readonly ValueComparer _providerValueComparer;
```

2022-07-30 00:59 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
> +    public static IEnumerable<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyForeignKey foreignKey)
Remove

2022-07-30 01:27 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnName(this IMutableEntityType entityType, string columnName)
Andriy also suggested calculating JsonColumnName / IsMappedToJson by traversing back to the parent. I chose to propagate the annotation to children using convention instead, but I see the wisdom of your suggestion now - will change, so that only the top level json entity has the annotation. This way we can (hopefully) mitigate scenarios where the model is partially configured, and one entity is already mapped to json, but some of it's children are not.

This is supposed to only be used to set up column name where the entire json object will be stored. To customize names of individual json properties, we use `HasJsonPropertyName` (formerly known as `HasJsonElementName`

2022-07-30 01:29 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
> +    public static PropertyBuilder HasJsonElementName(
I still like `HasJsonPropertyName` the most, but could live with `ToJsonProperty` if you guys think it's a better name.

2022-07-30 01:33 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +    public static string? GetDefaultColumnName(this IReadOnlyProperty property, in StoreObjectIdentifier storeObject)
this method should always return null when entity is mapped to json

2022-07-30 01:39 UTC, maumar commented on src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
> +            // don't uniquify json columns
yup, that's what should be happening, in some cases we might be returning column when asking for a name of key property, which kinda maps to a key column on the parent entity. But maybe I will be able to work around this and always return nulls for json properties across the board. Will remove this check regardless.

2022-07-30 01:44 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
this only describes actual json column in the database - we create them for each json structure (each mapped to a different column, when we use .ToJson() in the model configuration). Earlier we had idea to store the entire complex structure of all the faux columns that the properties of a json entity maps to, but this idea was scrapped (at least for now). We might need some more sophisticated representation later to enable all the fancy mappings, but for what we are aiming to support now it's not needed. Distinguishing json column from a regular column is valuable though, since json column has no property mappings and a lot of processing on a column blindly assumes there should always be some. Also, in migrations we have somewhat separate processing for json and non-json, so this allows us to easily distinguish between the two

2022-07-30 07:45 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            if (nonOwnedTypesCount == 0)
case with 0 non-owned types can happen when you have normal entity, with owned collection (non-json), and that owned collection owns a json entity. Non-json owned collections are mapped to a separate tables, so we have one table for the root entity, second table for owned collection entity, and json entity also maps to that second table.

So the input dictionary would have 2 entries

`key = table1 value = { root_entity } `

and

`key = table2, value = { owned_collection_entity, json_entity }`

2022-07-30 07:46 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            if (nonOwnedTypesCount == 0)
tests that hit this code paths are: Throw_when_non_json_entity_is_the_owner_of_json_entity_col_ref and Throw_when_non_json_entity_is_the_owner_of_json_entity_col_col

2022-07-30 11:45 UTC, roji commented on src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
> +    public static PropertyBuilder HasJsonElementName(
Am personally OK with both (the important thing for me was more to use "property" as opposed to element/column/anything). It's true that HasJsonPropertyName seems more consistent with our relational HasColumnName (they're very similar); we also have ToTable/ToView though..

There's something to be said for being consistent with Cosmos, it's maybe possible to imagine some future where we promote JSON support to core... But it doesn't seem super important.

2022-07-30 11:47 UTC, roji commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnTypeMapping(this IMutableEntityType entityType, RelationalTypeMapping typeMapping)
Yeah, that's what my trimmed comment was about to say :)

2022-07-30 12:03 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
Ah I see - I think I had the previous design in mind where we had "faux" JsonColumns for each property in the nested hierarchy etc. (previous conversation in https://github.com/dotnet/efcore/pull/28171#discussion_r897684535).

> We can use a different type for nested properties when we add them to the relational model

Do we think we need to do that? OTOH the structure inside a JSON column isn't 

> Distinguishing json column from a regular column is valuable though, since json column has no property mappings and a lot of processing on a column blindly assumes there should always be some.

Yeah, I get that. My motivation here is to find a more general way to make this work, which isn't JSON-specific and could cover various other UDT scenarios as well (see https://github.com/dotnet/efcore/pull/28171#discussion_r898888607 about supporting PostgreSQL composite types). Maybe we could make processing react to the where no property mappings are defined, instead of checking for a specific JsonColumn type (after all, you need to modify all that code to handle JSON columns in any case.

But I know we don't have a lot of time and I don't want to hold this back - we can also maybe improve this in the future. 

> Also, in migrations we have somewhat separate processing for json and non-json, so this allows us to easily distinguish between the two

IIRC at least right now, migrations don't actually interact with the relational model, e.g. ColumnOperation only the string name, CLR type, etc. of the column, and no reference to an IColumn; so I'm not sure that's going to help you there...

2022-07-30 21:40 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +                linkingRelationship = FindRowInternalForeignKeyForJson(principalProperty.DeclaringEntityType, storeObject);
removing this completely, after changing IsMappedToJson to be calculated dynamically based on owner

2022-07-30 21:42 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            var distinctRootTypes = nonOwnedTypes.Select(x => x.GetRootType()).Distinct();
distinct makes a difference in TPH scenarios

2022-07-30 22:25 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +    public static IReadOnlyList<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyKey key)
these are needed in query part, but will remove them for now

2022-07-31 01:06 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
> +    public static IReadOnlyList<IReadOnlyProperty> GetMappedKeyProperties(this IReadOnlyKey key)
There should be another way of getting this information without assuming that the last property is the ordinal for collections

2022-08-01 01:07 UTC, maumar commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnTypeMapping(this IMutableEntityType entityType, RelationalTypeMapping typeMapping)
query needs full type mapping during materialization - when extracting json element from data reader we call into `CreateGetValueExpression` which requires type mapping and calls into `CustomizeDataReaderExpression` and `GetDataReaderMethod`

2022-08-01 17:05 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnTypeMapping(this IMutableEntityType entityType, RelationalTypeMapping typeMapping)
You can get the type mapping using the store type and store it on the corresponding IColumnBase

2022-08-02 03:38 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
@roji when migration model differ compares 2 columns it looks into stuff like IsFixedLength, DefaultValue, Collation, Comment etc. and the way those properties are implemented in IColumn (default interface method) is to get first property mapping, take it's property and retrieve the value from that property. But json column doesn't have any mappings so that logic fails  (see `ColumnStructureEquals` method on `MigrationsModelDiffer`) Alternative was to create a parallel Diff logic for json columns, where we could only diff/initialize parts of the column that are relevant, but this was more terse.

2022-08-02 18:13 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +            .Concat(Diff(source.Columns.OfType<JsonColumn>(), target.Columns.OfType<JsonColumn>(), diffContext))
Why is this necessary?

2022-08-02 18:15 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +            GetSortedColumns(target).OfType<JsonColumn>().SelectMany(p => Add(p, diffContext, inline: true)).Cast<AddColumnOperation>());
Why is this necessary?

2022-08-02 18:18 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
> +    public static void SetJsonColumnTypeMapping(this IMutableEntityType entityType, RelationalTypeMapping typeMapping)
But this can be done later, when we have the full relational model for JSON

2022-08-02 19:31 UTC, maumar commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +            .Concat(Diff(source.Columns.OfType<JsonColumn>(), target.Columns.OfType<JsonColumn>(), diffContext))
not needed anymore, we used to process json columns separately

2022-08-02 20:26 UTC, smitpatel commented
>         var ownership = entityType.FindOwnership();

What about owned entity whose owner is mapped to view? We are doing some processing in GetTableName but none in GetViewName

---
Refers to: src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs:318 in c017e1a. [](commit_id = c017e1a5b05e3a08851b7aae12d7dd771d7b7c78, deletion_comment = False)

2022-08-02 20:28 UTC, smitpatel commented
>             && ownership.IsUnique)

here

---
Refers to: src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs:391 in c017e1a. [](commit_id = c017e1a5b05e3a08851b7aae12d7dd771d7b7c78, deletion_comment = False)

2022-08-02 20:51 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            if (nonOwnedTypesCount == 0)
This limitation exist because we don't yet support marking owned entity as json in middle of aggregate

2022-08-02 21:00 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            if (jsonEntitiesMappedToSameJsonColumn.Any())
If you do FirstOrDefault is check then you can combine Any + First into one

2022-08-02 21:01 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                throw new InvalidOperationException(
Is aggregate starts at owner or first owned entity?

2022-08-02 21:02 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +        if (rootAggregateType.BaseType != null)
It is already root type, this check shouldn't be needed

2022-08-02 21:05 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                .Where(x => x.FindOwnership() is IForeignKey ownership && ownership.PrincipalEntityType == rootAggregateType)
If the owned entity starts at derived then this will find nothing. You need to find in hierarchy

2022-08-02 21:14 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                .GroupBy(x => x.JsonColumnName())
Is it fixed that the aggregate which has multiple owned navigations, all of them would map to JSON column?

2022-08-02 21:24 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            Debug.Assert(jsonPropertyName != null);
Make it non-debug

2022-08-02 21:24 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            var jsonPropertyName = property.JsonPropertyName();
GetJsonPropertyName align with the method on navigation

2022-08-02 21:26 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                    $"Entity '{jsonEntityType.DisplayName()}' is mapped to JSON and it contains multiple properties or navigations which are mapped to the same JSON property '{jsonPropertyName}'. Eac
The table sharing validation also indicate the duplicate, may be similar to say which property/navigation is using the same json name

2022-08-02 21:27 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalJsonPropertyNameAttributeConvention.cs
> +public class RelationalJsonPropertyNameAttributeConvention : PropertyAttributeConventionBase<JsonPropertyNameAttribute>
RelationalPropertyJsonPropertyNameAttributeConvention
align with navigation?

2022-08-02 21:28 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                var jsonColumnTypeMapping = ((IRelationalTypeMappingSource)Dependencies.TypeMappingSource).FindMapping(
It should also utilize the store type to find type mapping

2022-08-02 21:29 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                ConfigureEnumConversion(navigation.TargetEntityType, convesionType);
We should do this in modelfinalizing

2022-08-02 21:30 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                throw new InvalidOperationException(
owner

2022-08-02 21:32 UTC, maumar commented on src/EFCore.Relational/Metadata/Conventions/RelationalMapToJsonConvention.cs
> +                var jsonColumnTypeMapping = ((IRelationalTypeMappingSource)Dependencies.TypeMappingSource).FindMapping(
store type has been scrapped for now. will add once functionality is good enough for npgsql to switch to it

2022-08-02 21:52 UTC, smitpatel commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +            var ownership = mappedType.GetForeignKeys().Where(fk => fk.IsOwnership).Single();
Use single here rather than Where

2022-08-02 21:56 UTC, smitpatel commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +        columnOperation.ClrType = typeof(string);
is it always string?

2022-08-02 22:02 UTC, smitpatel commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +                var currentOwnership = currentEntry.EntityType.FindOwnership()!;
Is this an opportunity for a do-while loop

2022-08-02 22:43 UTC, smitpatel commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +                    if (ordinal != null)
merge ifs

2022-08-02 22:45 UTC, smitpatel commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +        var enumerable = navigationValue as IEnumerable;
Feels risky if whatever random value ends up being also implementing enumerable. How about passing in actual navigation here instead to see collection or reference since navigationValue is always fetched via parentEntry.GetCurrentValue(navigation). You can do that inside this method

2022-08-02 22:48 UTC, smitpatel commented on src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
> +            && jsonColumnNameAnnotation != null && jsonColumnNameAnnotation.Value is string jsonColumnName)
Given that we only have ToJson on ownedNavigationBuilder, verify before printing out the code that the annotations are on owned entity type only else we will generate uncompilable code.

2022-08-02 22:50 UTC, smitpatel commented on src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
> +            if (property?.IsSparse() is bool isSparse)
why is this nullable?

2022-08-02 22:52 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +        var jsonColumnName = mappedType.JsonColumnName();
We'd need to store the `JsonColumnName` for views separately as it doesn't need to be the same as for tables.

2022-08-02 23:01 UTC, smitpatel commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                throw new InvalidOperationException(
Exception message needs correction then.

2022-08-02 23:17 UTC, AndriySvyryd commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +        => property.IsKey() && property.Name == "Id" && property.IsShadowProperty() && property.ClrType == typeof(int);
Make this a pubternal extension so it can also be used in `RelationalModelValidator`

2022-08-02 23:24 UTC, AndriySvyryd commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +        foreach (var property in entityType.GetDeclaredProperties())
```suggestion
        foreach (var property in entityType.GetProperties())
```

2022-08-02 23:24 UTC, AndriySvyryd commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +        foreach (var navigation in entityType.GetDeclaredNavigations())
```suggestion
        foreach (var navigation in entityType.GetNavigations())
```

2022-08-02 23:28 UTC, AndriySvyryd commented on src/EFCore.Relational/ValueGeneration/RelationalValueGeneratorSelector.cs
> +            && property.ClrType == typeof(int))
Use extension method

2022-08-02 23:31 UTC, AndriySvyryd commented on src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
> +    }
Redundant

2022-08-02 23:33 UTC, AndriySvyryd commented on src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
> +            && property.ClrType == typeof(int))
Move to relational and use extension method

2022-08-02 23:35 UTC, AndriySvyryd commented on src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
> +            var property = column.PropertyMappings.First().Property;
Could combine with condition using `FirstOrDefault`

2022-08-02 23:36 UTC, AndriySvyryd commented on src/EFCore.SqlServer/Storage/Internal/SqlServerJsonTypeMapping.cs
> +    /// </summary>
This is pubternal

2022-08-02 23:41 UTC, AndriySvyryd commented on test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
> +            },
👀

2022-08-02 23:45 UTC, AndriySvyryd commented on test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.Json.cs
> +        public abstract class RelationalJsonTestBase : ModelBuilderTestBase
You can put these in `RelationalOwnedTypesTestBase`

2022-08-02 23:47 UTC, AndriySvyryd commented on test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
> +
👀

2022-08-02 23:50 UTC, AndriySvyryd commented on test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
> +            Assert.Equal(2, ownedEntities.Where(e => e.IsOwned() && !e.IsMappedToJson()).Count());
You should assert `JsonColumnName` and `JsonElementName` in these tests (also for entity types where these would be `null`)

2022-08-02 23:51 UTC, AndriySvyryd reviewed
Time to write XML docs and resource strings

2022-08-03 01:16 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                    $"Entity '{jsonEntityType.DisplayName()}' is mapped to JSON and it contains multiple properties or navigations which are mapped to the same JSON property '{jsonPropertyName}'. Eac
we provide entity name and the json property name. people should be able to easily figure it out

2022-08-03 01:18 UTC, maumar commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +        columnOperation.ClrType = typeof(string);
will do something smarter (flow from type mapping) in a future PR

2022-08-03 02:27 UTC, maumar commented on test/EFCore.Cosmos.FunctionalTests/TestUtilities/CustomPartitionKeyIdGenerator.cs
> +                || CosmosPropertyExtensions.GetJsonPropertyName(property) == StoreKeyConvention.IdPropertyJsonName)
any idea why i'm getting name clash with `RelationalPropertyExtensions.GetJsonPropertyName` here? (i.e. why cosmos tests have access to relational assembly?)

2022-08-03 04:07 UTC, AndriySvyryd commented on test/EFCore.Cosmos.FunctionalTests/TestUtilities/CustomPartitionKeyIdGenerator.cs
> +                || CosmosPropertyExtensions.GetJsonPropertyName(property) == StoreKeyConvention.IdPropertyJsonName)
Microsoft.EntityFrameworkCore.Cosmos.FunctionalTests ->
Microsoft.EntityFrameworkCore.Specification.Tests ->
Microsoft.EntityFrameworkCore.Design ->
Microsoft.EntityFrameworkCore.Relational

2022-08-03 04:28 UTC, AndriySvyryd commented on test/EFCore.Cosmos.FunctionalTests/TestUtilities/CustomPartitionKeyIdGenerator.cs
> +                || CosmosPropertyExtensions.GetJsonPropertyName(property) == StoreKeyConvention.IdPropertyJsonName)
I'll try to remove this dependency

2022-08-03 06:04 UTC, maumar commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +    private Dictionary<StoreObjectIdentifier, List<IEntityType>> BuildSharedTableEntityMap(IEnumerable<IEntityType> entityTypes)
I'd rather keep them separate for now, for simpler logic and to reduce chance of breaking existing scenarios

2022-08-03 10:37 UTC, roji commented on src/EFCore.Relational/Update/ModificationCommand.cs
> +                var currentOwnership = currentEntry.EntityType.FindOwnership()!;
There are no opportunities to do a do-while loop.

2022-08-03 10:41 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
Shouldn't the model differ simply ignore all properties which aren't mapped to columns, which is the case with JSON properties? I mean, JSON properties have no existence whatsoever in migrations.

In other words, ideally shouldn't the model differ even see any properties/columns in JSON-mapped owned entities?

2022-08-03 17:00 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
Maurycy refers to the JSON column that's on the table, not the nested JSON properties

2022-08-03 17:25 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
OK, thanks. I'd consider just modifying IsFixedLength and friends to handle the case when there's no property mapping (and e.g. return default), rather than introduce a subclass and handle that in a special way in model differ (again, that's something I can't do in PG).

But I'll stop bugging you guys with this, we can revisit later.

2022-08-03 18:22 UTC, bricelam reviewed
Migrations changes LGTM

2022-08-03 18:22 UTC, bricelam commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +        columnOperation.ClrType = typeof(string);
`object` might also work. I don't think this value is actually used when ColumnType is specified.

2022-08-03 18:22 UTC, bricelam commented on src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
> +            fragments.Add(toJsonCall);
Should this be done in the Relational base?

2022-08-03 19:01 UTC, maumar commented on src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
> +        columnOperation.ClrType = typeof(string);
We seem to be using it to create default value and that's what my concern is about. It might not be a real problem, since if json column is nullable we can easily construct a null value, and when the json column in required (i.e. json entity it stores is required), there is no way we can construct a meaningful json

2022-08-03 23:34 UTC, maumar commented on src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
> +        var jsonColumnName = mappedType.JsonColumnName();
filed #28584 to track this

2022-08-04 09:42 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
One last thought on this... If we're discussing the actual JSON column on the table, then that actually does need to support facts in the general case; in SQL Server, you store JSON in a regular textual column, and that column may have facets.

I'm specifically thinking about the collation and unicode-ness of the column containing the JSON property, and crucially about the fact that SQL Server doesn't allow indexes on `nvarchar(max)`. So if we always create JSON columns as `nvarchar(max)` without allowing the user to override this, it won't be possible to define an index on it.

In other words, a JSON column really is just a column from a relational model point of view.

2022-08-04 18:23 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
> In other words, a JSON column really is just a column from a relational model point of view, including facets etc.

Yes and when accessed as `IColumn` it would be, but unlike other columns it isn't mapped to a `Property` where the facet configuration would be normally stored, so we need a different implementation.

> So if we always create JSON columns as nvarchar(max) without allowing the user to override this, it won't be possible to define an index on it.

We don't support indexes on JSON columns yet, probably that requieres https://github.com/dotnet/efcore/issues/11336

2022-08-04 18:47 UTC, AndriySvyryd commented
Add a JSON column to `ModelSnapshotSqlServerTest`

2022-08-04 18:49 UTC, AndriySvyryd commented
Add a test to `MigrationsModelDifferTest` for JSON

2022-08-04 18:53 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/Internal/RelationalPropertyInternalExtensions.cs
> +namespace Microsoft.EntityFrameworkCore.Extensions.Internal
```suggestion
namespace Microsoft.EntityFrameworkCore.Metadata.Internal
```

We usually use the namespace of the target type

2022-08-04 18:54 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/Internal/RelationalPropertyInternalExtensions.cs
> +                && property.ClrType == typeof(int);
```suggestion
                && property.ClrType == typeof(int)
                && property.GetJsonPropertyName() == null;
```

2022-08-04 19:00 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/Internal/RelationalPropertyInternalExtensions.cs
> +                && property.Name == "Id"
```suggestion
            => property.FindContainingPrimaryKey() is IReadOnlyKey key
                && key.Properties.Count > 1
                && !property.IsForeignKey()
```

2022-08-04 19:00 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/Internal/RelationalPropertyInternalExtensions.cs
> +        public static bool IsOrdinalKey(this IReadOnlyProperty property)
```suggestion
        public static bool IsOrdinalKeyProperty(this IReadOnlyProperty property)
```

2022-08-04 19:07 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
> +            //JSON-splitting is not supported
#28574

2022-08-04 19:12 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                throw new InvalidOperationException(
#28584

2022-08-04 19:20 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            var ordinalKeyProperty = primaryKeyProperties.Last();
#28594

2022-08-04 19:20 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +                throw new InvalidOperationException(
#28594

2022-08-04 19:31 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +            throw new InvalidOperationException(
#28594

2022-08-04 19:34 UTC, AndriySvyryd commented on src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
> +        foreach (var property in jsonEntityType.GetDeclaredProperties().Where(p => !p.IsKey()))
Don't skip key properties, instead skip properties where `GetJsonPropertyName` is `null` or empty

2022-08-05 01:23 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/Internal/RelationalPropertyInternalExtensions.cs
> +                && property.Name == "Id"
This check shouldn't be needed

2022-08-05 01:26 UTC, AndriySvyryd commented on test/EFCore.Cosmos.FunctionalTests/TestUtilities/CustomPartitionKeyIdGenerator.cs
> +                || CosmosPropertyExtensions.GetJsonPropertyName(property) == StoreKeyConvention.IdPropertyJsonName)
These could be reverted now

2022-08-05 01:29 UTC, AndriySvyryd approved these changes

2022-08-05 07:37 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
> Yes and when accessed as IColumn it would be, but unlike other columns it isn't mapped to a Property where the facet configuration would be normally stored, so we need a different implementation

OK. Is there already an issue tracking this specific thing, or should I open one?

> We don't support indexes on JSON columns yet, probably that requieres https://github.com/dotnet/efcore/issues/11336

Are you referring to indexes on properties *inside* the JSON document? Because for indexes purely on the JSON column itself, it seems like just an index on a single column (which happens to be mapped to an owned entity). I can open an issue for this too if you think it's not covered.

2022-08-05 07:42 UTC, merged

2022-08-05 15:41 UTC, AndriySvyryd commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
> OK. Is there already an issue tracking this specific thing, or should I open one?

I'm not sure what would it be tracking. Is this one enough? https://github.com/dotnet/efcore/issues/28591

>  I can open an issue for this too if you think it's not covered.

It's for the index over the JSON column, but we don't have any way of representing it in metadata. Go ahead.

2022-08-05 18:38 UTC, roji commented on src/EFCore.Relational/Metadata/Internal/JsonColumn.cs
> +    public class JsonColumn : Column, IColumn
> I'm not sure what would it be tracking. Is this one enough? https://github.com/dotnet/efcore/issues/28591

Yep, looks good.

> It's for the index over the JSON column, but we don't have any way of representing it in metadata. Go ahead.

#28591