Translate DateTimeOffset.ToUnixTime[Seconds|Milliseconds]
dotnet/efcore pull request #28978
Opened 2022-09-04 01:32 UTC by Marusyk

Added translation for `DateTimeOffset.ToUnixTime[Seconds|Milliseconds]`

Fixes #28975

Could anyone help me improve the tests? 
Thank you in advance

2022-09-04 06:17 UTC, roji requested changes
See also SQLite test failures, you probably need to implement those tests and assert on them failing (unless there's a translation on SQLite as well).

2022-09-04 12:01 UTC, Marusyk commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +            var startDate = _sqlExpressionFactory.Constant(DateTimeOffset.UnixEpoch);
do you mean `private static readonly DateTimeOffset UnixEpoch = DateTimeOffset.UnixEpoch;`?

2022-09-04 18:52 UTC, ajcvickers commented
Marked as `blocked` since we shouldn't merge until we are actively working in `main` again.

2022-09-06 10:56 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +            var startDate = _sqlExpressionFactory.Constant(DateTimeOffset.UnixEpoch);
The 1st.

2022-09-07 04:23 UTC, smitpatel commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                   new[] { _sqlExpressionFactory.Fragment(timePart), UnixEpoch, instance! },
UnixEpoch needs to get type mapping from instance.

2022-09-07 04:25 UTC, smitpatel commented on test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
> +            ss => ss.Set<Order>().Where(c => unixEpochMilliseconds == ((DateTimeOffset)c.OrderDate.Value).ToUnixTimeMilliseconds()));
GearsOfWar test base has datetimeoffset propery. Move tests there and don't add cast in test.

2022-09-07 04:27 UTC, smitpatel commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> +        => AssertTranslationFailed(() => base.DateTimeOffset_to_unix_time_seconds(async));
Sqlite has `unixepoch` function. It should work at least for seconds. Implement for Sqlite too. @bricelam would know if there is a way to translate for milliseconds too. Given we are just diffing with a different date, it may be possible.

2022-09-07 04:32 UTC, smitpatel commented
Cosmos has `DateTimeToTicks` which returns ticks since unix epoch though not sure if Cosmos can handle DateTimeOffset as a type. Add translation if it is supported.

2022-09-07 06:43 UTC, roji commented
Converting to draft for now as we're not merging this for 7.0.

2022-09-10 23:22 UTC, Marusyk commented on test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> +        => AssertTranslationFailed(() => base.DateTimeOffset_to_unix_time_milliseconds(async));
to do this I need to extend the `SqliteDateTimeAddTranslator`, right?

2022-09-11 00:32 UTC, Marusyk commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                   new[] { _sqlExpressionFactory.Fragment(timePart), UnixEpoch, instance! },
Do you mean smth like
```
var typeMapping = ExpressionExtensions.InferTypeMapping(UnixEpoch, instance!);

            instance = _sqlExpressionFactory.ApplyTypeMapping(instance, typeMapping);
            var unixEpochArgument = _sqlExpressionFactory.ApplyTypeMapping(UnixEpoch, typeMapping);

            return _sqlExpressionFactory.ApplyDefaultTypeMapping(
               _sqlExpressionFactory.Function(
                   "DATEDIFF_BIG",
                   new[] { _sqlExpressionFactory.Fragment(timePart), unixEpochArgument, instance! },
                   nullable: true,
                   argumentsPropagateNullability: new[] { false, false, true },
                   typeof(long)));
```

2022-09-11 00:43 UTC, Marusyk commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +    private static readonly MethodInfo ToUnixTimeSeconds
Should I create the new one SqliteDateTimeMethodTranslator, rename SqliteDateTimeAddTranslator -> SqliteDateTimeMethodTranslator, or leave it as is?
could you suggest?

2022-09-11 09:49 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +    private static readonly MethodInfo ToUnixTimeSeconds
I'd rename SqliteDateTimeAddTranslator to SqliteDateTimeMethodTranslator, I don't think we need more translator types here.

2022-09-14 18:47 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    : null;
Can't do this. SQLite will ignore the time zone and you'll get incorrect results.

2022-09-14 22:03 UTC, Marusyk commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    : null;
Could you please explain? I don't have a lot of experience with MySql ☹. The main idea was to add the translation only for SQL Server

2022-09-15 18:20 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    : null;
The SQLite date and time functions can't work with DateTimeOffset values. DateTimeOffest includes a timezone, but the SQL functions will simply ignore it and the result will be wrong.

Personally, I'd be fine just adding the SQL Server translations in this PR and filing an issue (or keeping the existing one open) to add the SQLite ones later. @smitpatel Is there a reason they need to be added in this PR?

2022-09-15 19:39 UTC, smitpatel commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    : null;
Fine to split into a different issue. Most times we forget to add till someone files an issue on us. So if the translation is easy and straightforward add in the same PR so feature is lighted up across providers. If translation is complex ok to defer especially for community contributions.

2022-09-15 23:47 UTC, Marusyk commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    : null;
I don't mind to add the SQLite ones if you give me some advice

2022-09-21 22:47 UTC, Marusyk commented on src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
> +                   new[] { _sqlExpressionFactory.Fragment(timePart), UnixEpoch, instance! },
@smitpatel what about this? could you suggest

2022-11-11 00:30 UTC, Marusyk commented
Can I mark it "ready for review"?

2023-03-20 18:53 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
> +                    : null;
I didn't realize there weren't corresponding methods on `DateTime`. Nothing to do on SQLite.

2023-03-20 18:54 UTC, bricelam commented
Rebased, removed SQLite translations, and copied the type mapping from `instance` to `UnixEpoch`.

2023-03-20 18:56 UTC, bricelam approved these changes

2023-03-30 16:38 UTC, merged