Update file "getting and building the code.md"
dotnet/efcore pull request #29361
Opened 2022-10-14 17:56 UTC by ZarakiKanzaki

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ ] The code builds and tests pass locally (also verified by our automated build checks)
- [ ] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Code follows the same patterns and style as existing code in this repo

This PR fixes Issue #25278

2022-10-17 13:20 UTC, ajcvickers commented on docs/getting-and-building-the-code.md
>  ## Using Visual Studio
Add a new line here.

2022-10-17 13:21 UTC, ajcvickers requested changes
.

2022-10-17 13:30 UTC, ZarakiKanzaki commented on docs/getting-and-building-the-code.md
> +**Note**, to enable developer builds, create a file named `AspNetCoreSettings.props` above the repo root with the following contents.
> Make this a new heading. Also, provide some details as to what it means to have a developer build.

Is there a place where this information is documented already so that I can include them? or should I write something myself?
I'm asking to be sure

2022-10-19 09:17 UTC, ajcvickers commented on docs/getting-and-building-the-code.md
> +**Note**, to enable developer builds, create a file named `AspNetCoreSettings.props` above the repo root with the following contents.
@ZarakiKanzaki It will need to be written.

2022-10-19 17:32 UTC, ZarakiKanzaki commented on docs/getting-and-building-the-code.md
> +**Note**, to enable developer builds, create a file named `AspNetCoreSettings.props` above the repo root with the following contents.
@ajcvickers then I need to ask you another question, as far as I'm understanding from this chunk of code it seems like a "custom" propertyGroup that I'm not really aware of what developer build should do. By looking on the web it seems it was never mentioned outside of the PR linked in the issue I mentioned. Please let me know if you could explain to me  in few words, then I'll try to write something in a single commit. thank you :)

2022-10-25 10:03 UTC, ZarakiKanzaki commented on docs/getting-and-building-the-code.md
> +**Note**, to enable developer builds, create a file named `AspNetCoreSettings.props` above the repo root with the following contents.
@ajcvickers  sorry to bother you, but I think I'm not able to finish this PR without the information I asked you a few days ago ☝️

2022-10-27 07:39 UTC, AndriySvyryd commented on docs/getting-and-building-the-code.md
> +**Note**, to enable developer builds, create a file named `AspNetCoreSettings.props` above the repo root with the following contents.
IRC it skips building for older runtimes and only builds the latest one

2023-03-19 20:23 UTC, ajcvickers commented
Closing this, since the contributor does not have the necessary knowledge to document this.

2023-03-19 20:23 UTC, closed without merging