Fix to #28816 - Json: add support for Sqlite provider
dotnet/efcore pull request #30302
Opened 2023-02-17 00:09 UTC by maumar

Adding support for Sqlite.

Limitation:
When accessing element of a JSON array we can only use constant values. Unlike Sql Server which supports parameters, columns or even arbitrary expressions.

Also since JSON aggregates are mapped to own types, in case of collections users need to ignore SqliteEventId.CompositeKeyWithValueGeneration

Fixes #28816

2023-02-20 10:43 UTC, maumar commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +                if (columnModification.Property.ClrType == typeof(bool))
ideally I'd do this change in ModificationCommand -> GenerateColumnModifications (where we  create json for single property case). However this requires ModificationCommand to be provider specific. Thoughts?

2023-02-21 23:48 UTC, AndriySvyryd commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +                if (columnModification.Property.ClrType == typeof(bool))
Yes, we should avoid doing a `replace` like this as it could result in unintended matches.
A provider-specific `ModificationCommand` is totally fine, that's why we introduced `IModificationCommandFactory`

2023-02-21 23:56 UTC, AndriySvyryd commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +                if (columnModification.Property.ClrType == typeof(bool))
Alternatively, with https://github.com/dotnet/efcore/issues/28043 the serialization could be provider-specific

2023-02-23 11:03 UTC, maumar commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteModificationCommand.cs
> +                var modifiedPropertyValue = boolPropertyValue
is there more "elegant" way to do this? i.e. without hard-coding the "true"/"false" values? @bricelam

2023-02-23 11:18 UTC, maumar commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteModificationCommand.cs
> +            var valueConverter = property.GetValueConverter();
I was expecting property.GetProviderClrType() to do the job, but it doesn't

2023-02-23 12:58 UTC, roji requested changes
Really nice that this required so little changes etc. - but see comments; I think we may need some more generalized infra, looking forward.

One additional note... SQLite supports two methods for extracting values out of JSON documents: json_extract and the `->`/`->>` operators (which PG and MySQL support too). At least from a clean SQL perspective, these may be a better fit: instead of piecing together a JSONPATH string (and concatenating where non-constant data is provided), we can just use these operators. Compare the following two:

```sql
SELECT json_extract(json, '$.c[' || ind || ']') FROM data;
SELECT json->'$.c'->ind FROM data;
```

There's even a (theoretical) chance the -> would be faster, since we're expressing things more directly/simply, rather than concatenating arbitrary things to form the JSONPATH string.

Note that these operators were introduced in SQLite 3.38.0 (2022-02-22), though I don't think that should be an issue.

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
> +        if (column is not JsonColumn)
nit: invert condition to return early

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
> +        if (column is not JsonColumn)
Over in [SqlServerAnnotationProvider](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs#L214), most of the code isn't under a check against JsonColumn; for example, I can see the identity code doing it's thinking without checking for JSON.

Should we change things over in SQL Server too?

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
> +            var srid = property.GetSrid();
This does raise the question of spatial data inside JSON :trollface:

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
> +        Sql.Append(",'");
nit for slightly nicer function calling syntax:

```suggestion
        Sql.Append(", '");
```

If so, we should do the same on the SQL Server side...

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
> +                else
I see a validation step that checks again non-constant array indexes. I think they can be (see other comment), but if they're really not supported, we should have a Debug.Assert here rather than this code, no?

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryTranslationPostprocessor.cs
> +                throw new InvalidOperationException(
I think non-constant array indexes should be doable:

```c#
DROP TABLE IF EXISTS data;
CREATE TABLE data (
    ind INT,
    json TEXT
);
INSERT INTO data (ind, json) VALUES (1, '{"a":2,"c":[4,5,6]}');
SELECT json_extract(json, '$.c[' || ind || ']') FROM data;
```

(note that the SQLite string concat operator is `||`, like in PG).

But see note in the main review notes about using -> instead of json_extract for a simple method.

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteJsonTypeMapping.cs
> +    private static readonly MethodInfo _getStringMethod
```suggestion
    private static readonly MethodInfo GetStringMethod
```

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteJsonTypeMapping.cs
> +public class SqliteJsonTypeMapping : JsonTypeMapping
This looks like a copy-paste of SqlServerJsonTypeMapping; should it be in relational?

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +            && columnModification.JsonPath != "$")
```suggestion
        if (columnModification.JsonPath is not (null or "$"))
```

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +    protected override void AppendUpdateColumnValue(
Should we extract out an overridable AppendJsonModification method, called when columnModification.JsonPath is non-null? This would more cleanly separate JSON updates from non-JSON updates, and be the extension point for implementing partial updates etc.

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +        if (columnModification.JsonPath != null
(regardless of this PR) there seems to be an assumption that the path for modification will be a JSONPATH string - that's unfortunately not always true. For example, the PG [jsonb_set](https://www.postgresql.org/docs/current/functions-json.html) function receives a different kind of path - a PG array of strings, where each element is a path segment.

The query pipeline has an `IReadOnlyList<PathSegment>` to represent the path - and it's only rendered as JSONPATH in the query SQL generator; we should probably have the same for the update pipeline.

2023-02-23 12:58 UTC, roji commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +                // and wrap json() function around it to avoid conversion to 0/1
Isn't it enough that we're transforming the value into true/false strings in SqliteModificationCommand.GenerateJsonForSinglePropertyUpdate? The `json()` function is documented as "verifies that its argument X is a valid JSON string and returns a minified version of that JSON string"; is it somehow preventing a conversion here or something?

2023-02-23 22:04 UTC, AndriySvyryd commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteModificationCommand.cs
> +    protected override JsonNode? GenerateJsonForSinglePropertyUpdate(IProperty property, object? propertyValue)
I agree that we should eventually remove this. Either moving the functionality to type mappings or a new service (https://github.com/dotnet/efcore/issues/28043). But the current approach doesn't look too bad. We can discuss in design meeting.

2023-02-24 09:38 UTC, maumar commented on src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
> +        if (column is not JsonColumn)
code in SqlServer now has null ref protection, so it should be fine. We used to access property like this:

```cs
var property = column.PropertyMappings.First().Property
```

2023-02-24 09:39 UTC, maumar commented on src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
> +            var srid = property.GetSrid();
backlog :trollface:

2023-02-24 09:40 UTC, roji commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteModificationCommand.cs
> +    protected override JsonNode? GenerateJsonForSinglePropertyUpdate(IProperty property, object? propertyValue)
Sure, we can also do this as a temporary measure and remove it later - but then it may be better to make it internal, to prevent breaking changes to providers later.

2023-02-24 09:41 UTC, roji commented on src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
> +            var srid = property.GetSrid();
Yep :trollface:

2023-02-24 09:43 UTC, roji commented on src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
> +        if (column is not JsonColumn)
OK, I see.

It would probably be a bit clearer if the entire SQL Server code block were wrapped in `if (column is not JsonColumn)` like this PR does for Sqlite, just to make it explicit exactly when we don't expect the code to be relevant.

2023-02-24 10:51 UTC, maumar commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
> +                else
removed the validation and added support for arbitrary indexes

2023-02-24 10:59 UTC, maumar commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +        if (columnModification.JsonPath != null
filed https://github.com/dotnet/efcore/issues/30335

2023-02-24 11:06 UTC, maumar commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteJsonTypeMapping.cs
> +public class SqliteJsonTypeMapping : JsonTypeMapping
I'm ok to put the common logic in relational, but won't you need some sort of customization in npg? (e.g. two json type mappings one for json and one for jsonb).

2023-02-24 11:43 UTC, maumar commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +                // and wrap json() function around it to avoid conversion to 0/1
yes, without json around the call the value after update is stored as:

```
"TestBoolean":"true"
```

whereas before (and what we ultimately want) is:

```
"TestBoolean":false
```

Funny enough, `select json_extract('["true"]', '$[0]');` and `select json(json_extract('["true"]', '$[0]'));` seem to return the same result: `true` 

 ¯\_(ツ)_/¯

2023-02-24 12:15 UTC, roji commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteJsonTypeMapping.cs
> +public class SqliteJsonTypeMapping : JsonTypeMapping
Right, Npgsql would probably have two instances of this (it already accepts the store type in the constructor).

2023-02-24 12:39 UTC, roji commented on src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> +                // and wrap json() function around it to avoid conversion to 0/1
OK...

I think this also related to https://github.com/dotnet/efcore/pull/30302#discussion_r1115567681; if we had a more general thing that says how to create a literal JSON from the value, we'd just be able to directly get `true` out, rather than having to jump through hoops and use server-side logic to convert stuff. Unless I'm mistaken, this would allow us to remove the CAST in SQL Server and the json_extract/json here in SQLite.

2023-02-24 18:45 UTC, roji approved these changes

2023-02-24 21:01 UTC, merged