add readme for sql server
dotnet/efcore pull request #30466
Opened 2023-03-13 19:22 UTC by lyndaidaii

- [ ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ ] The code builds and tests pass locally (also verified by our automated build checks)
- [ ] Commit messages follow this format:
```
        Summary of the changes
        - Add readme file for Microsoft.EntityFrameworkCore.SqlServer nuget package [Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.0-preview.1.23111.4)

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Code follows the same patterns and style as existing code in this repo

2023-03-15 16:11 UTC, ajcvickers commented on src/EFCore.SqlServer/README.md
> +Microsoft.EntityFrameworkCore.SqlServer is Microsoft SQL Server EF Core Database Provider, which enables you to use Entity Framework Core with Microsoft SQL Server (including Azure SQL Database).
```suggestion
Microsoft.EntityFrameworkCore.SqlServer is the database provider for Microsoft SQL Server and Azure SQL. This providers allows you to use Entity Framework Core with Microsoft SQL Server and Azure SQL databases.
```

2023-03-15 16:11 UTC, ajcvickers commented on src/EFCore.SqlServer/README.md
> +Explain how to use your package, provide clear and concise getting started instructions, including any necessary steps.
This seems like placeholder text.

2023-03-15 16:12 UTC, ajcvickers commented on src/EFCore.SqlServer/README.md
> +- The provider references Microsoft.Data.SqlClient (not System.Data.SqlClient). If your project takes a direct dependency on SqlClient, make sure it references the Microsoft.Data.SqlClient package.
Make these links?

2023-03-15 16:12 UTC, ajcvickers commented on src/EFCore.SqlServer/README.md
> +In this example, we're using the (localdb)\mssqllocaldb server with the MyDatabase database. You'll need to adjust the connection string to match your own SQL Server instance and database.
Link to guidance on this?

2023-03-15 16:18 UTC, ajcvickers commented on src/EFCore.SqlServer/README.md
> +- In-memory tables
```suggestion
The SQL Server provider  supports all common features of [Entity Framework Core](https://learn.microsoft.com/ef/core/) as well as some [SQL Server-specific features](https://learn.microsoft.com/ef/core/providers/sql-server/?tabs=dotnet-core-cli) including temporal tables and memory-optimized tables.
```

2023-03-15 16:18 UTC, ajcvickers requested changes
Looking food; needs a few updates.

2023-09-06 15:06 UTC, ajcvickers approved these changes

2023-09-06 16:12 UTC, merged

2023-09-06 16:16 UTC, ErikEJ commented
Why is there a section about .Design??

2023-09-06 18:21 UTC, ErikEJ commented
I was looking at the wrong branch, my bad.