Fix to #30115 - IndexOutOfRangeException in CreateNavigationExpansionExpression(Expression sourceExpression, IEntityType entityType) / get_Chars(Int32 index) when EF class named "<>f__AnonymousType01Child" in 7.0.2 version
dotnet/efcore pull request #30537
Opened 2023-03-21 07:18 UTC by maumar

Check if ShortName returns empty string, and if so use token parameter name.

Fixes #30115

2023-03-24 14:54 UTC, roji approved these changes

2023-03-24 14:54 UTC, roji commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
This looks OK for a targeted patch, but as a proper fix going forward, should ShortName return null for this case and force callers to deal with the lack of name? I think I'm seeing various other invocations of ShortName which probably don't behave well when an empty string is given back.

2023-03-24 14:57 UTC, roji commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
BTW looking at the [function](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/IReadOnlyTypeBase.cs#L116), is there any reason why we derive the short name from the CLR type for non-STET cases, but the entity name for STET? If we just always looked at Name instead of the CLR type we wouldn't have this issue - what was the reasoning here?

2023-03-24 21:24 UTC, AndriySvyryd commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
The proper fix should be to never return an empty string from `ShortName`, i.e. just skip the first two characters if the name begins with `<>`

> If we just always looked at Name instead of the CLR type we wouldn't have this issue - what was the reasoning here?

`Name` includes the CLR namespace so the first character of most entity type names would be the same

2023-03-24 21:26 UTC, AndriySvyryd requested changes
Fix `ShortName()` instead

2023-03-24 23:29 UTC, roji commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
@AndriySvyryd I was referring to the entity type name, not to the CLR type name.

2023-03-25 00:06 UTC, AndriySvyryd commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
> @AndriySvyryd I was referring to the entity type name, not to the CLR type name.

For non-STETs those are the same

2023-03-25 16:48 UTC, roji commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
OK, yeah, I looked a bit and I agree that just skipping the first two chars in ShortName is best.

There's maybe the orthogonal question of whether we actually want IEntityType.Name to return `<>f__AnonymousType01Child` when the CLR type is anonymous (and possibly also DisplayName?)... We could do the sanitization there as well, just return e.g. AnonymousType01Child (am assuming we have uniquification for entity type names). That would depend on how we actually use it.

2023-03-25 19:19 UTC, AndriySvyryd commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
> (am assuming we have uniquification for entity type names)

We don't

2023-03-25 21:05 UTC, roji commented on src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
> +        var entityTypeName = entityType.ShortName();
OK then. If the entity type's name is actually used anywhere, it seems problematic to actually expose Roslyn's internal unspeakable names for anonymous types.

2023-03-28 01:21 UTC, maumar commented
updated

2023-03-28 17:30 UTC, AndriySvyryd approved these changes

2023-03-28 17:36 UTC, merged