Fix to #30326 - Query: converter from bool used in predicate without comparison fails on sqlite (and other non-sql server backends?)
dotnet/efcore pull request #30666
Opened 2023-04-12 02:12 UTC by maumar

SqlServer doesn't have the problem because search condition replacing visitor already converts all bool values in the predicate into conditions. Fix is to re-purpose this visitor to be used by other providers also and convert bool values to conditions when they have a converter.

Fixes #30326

2023-04-12 08:02 UTC, roji requested changes
General question... Is there a reason we need to run this visitor in RelationalParameterBasedSqlProcessor, rather than in RelationalQueryTranslationPostprocessor? It doesn't seem to need to look at any parameter values, is there some ordering dependency where it must run after e.g. the nullability processor?

I'm asking since this PR now introduces this additional visitation for all providers (not just SQL Server), and the parameter-based processor gets invoked again for different parameter nullabilities etc.

(not critical and can be done separately)

2023-04-12 08:02 UTC, roji commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteParameterBasedSqlProcessor.cs
> +        return new SearchConditionConvertingExpressionVisitor(
Is this intentional? It seems duplicated from RelationalParameterBasedSqlProcessor.

2023-04-12 17:49 UTC, maumar commented on src/EFCore.Relational/Query/SearchConditionConvertingExpressionVisitor.cs
> +///         A visitor that processes the query expression converting from condition to value and the other way around where needed.
I like that, I'm also naming most new visitors FooBarVerber instead.

2023-04-12 17:51 UTC, maumar commented on src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs
> +                    selectExpression.GroupBy.Count > 0
null semantics and simplifier collapse predicates into true/false from more complex expressions, so search condition needs to run after.

2023-04-12 19:04 UTC, maumar commented
@roji updated. Much better and simpler change. Thanks for the hint!

2023-04-13 09:19 UTC, roji approved these changes
Looks great! We should consider patching...

2023-04-13 09:19 UTC, roji commented on src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
> +            && sqlExpression.TypeMapping.Converter != null)
In case you haven't noticed I'm really excited about pattern matching lately ;)

```suggestion
        if (sqlExpression is ColumnExpression or JsonScalarExpression { TypeMapping.Converter: not null }
            && sqlExpression.TypeMapping!.ClrType == typeof(bool))
```

2023-04-13 20:06 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
> +            && sqlExpression.TypeMapping.Converter != null)
not worth in this case tho, `sqlExpression.TypeMapping.Converter != null` needs to apply to both types

2023-04-13 20:36 UTC, roji commented on src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
> +            && sqlExpression.TypeMapping.Converter != null)
It's just a nit, up to you :) Though doing `sqlExpression is ColumnExpression or JsonScalarExpression` does seem simply better than `sqlExpression is ColumnExpression || sqlExpression is JsonScalarExpression`.

2023-04-13 21:53 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
> +            && sqlExpression.TypeMapping.Converter != null)
oh yeah, that one i can get behind :)

2023-04-14 04:57 UTC, merged