Allow configuration of the sentinel value that indicates a property has not been set
dotnet/efcore pull request #30760
Opened 2023-04-25 18:45 UTC by ajcvickers

Fixes #701

Part of #13224, #15070, #13613

This PR contains the underlying model and change tracking changes needed to support sentinel values. Future PRs will add model building API surface and setting the sentinel automatically based on the database default.

There is a breaking change here: explicitly setting the value of a property with a temporary value no longer automatically makes the value non temporary.

2023-04-26 19:21 UTC, AndriySvyryd commented on src/EFCore/Metadata/IReadOnlyPropertyBase.cs
> +    object? Sentinel { get; }
Should this be on IReadOnlyProperty?

2023-04-26 19:31 UTC, AndriySvyryd requested changes
Also fix `CSharpRuntimeModelCodeGenerator`

2023-04-28 08:54 UTC, ajcvickers commented on src/EFCore/Metadata/IReadOnlyPropertyBase.cs
> +    object? Sentinel { get; }
It's here because there are a lot of places where we check navigations in the same way as non-navigation properties. It always returns null for navigations (currently) but it means that we don't need to split the code paths when using it on any PropertyBase.

2023-04-28 12:26 UTC, ajcvickers commented
@AndriySvyryd Updated to revert the breaking change and fix CSharpRuntimeModelCodeGenerator

2023-04-28 18:33 UTC, AndriySvyryd approved these changes

2023-04-29 09:23 UTC, merged