Refactor test infrastructure
dotnet/efcore pull request #30814
Opened 2023-05-02 19:06 UTC by DoctorKrolic

Closes: https://github.com/dotnet/efcore/issues/30803

- Moved all analyzer tests to `Microsoft.CodeAnalysis.Testing`
- Created separate folders for different kinds of tests (this comes in handy when analyzer count is potentially large)
- In roslyn and similar repos analyzer tests usually only check for diagnostic location via markup to simplify things and produce less boilerplate. Verification of message format, args etc. is done only when fixing a bug, that affects this things. However, I kept every single check there, including severity, message format and argments, which makes overall simplification less noticeable

2023-05-03 09:26 UTC, roji requested changes
Looks good, thanks!

Aside from the code alignment (see below), I think Analyzers and Suppressors folders are unneeded at this point, given that we only have one of each. We can always add these later.

2023-05-03 09:26 UTC, roji commented on test/EFCore.Analyzers.Tests/Analyzers/InternalUsageDiagnosticAnalyzerTests.cs
> +            """, "Microsoft.EntityFrameworkCore.Internal.MethodInfoExtensions");
nit: my preference is to align the code to the beginning of the line, like we do e.g. with SQL assertions (some code samples here bypass the 120 char limit).

```suggestion
        => VerifySingleInternalUsageAsync("""
using System;
using Microsoft.EntityFrameworkCore.Internal;

class C
{
    void M()
    {
        var x = typeof(object).GetMethod(nameof(object.ToString), Type.EmptyTypes).{|#0:DisplayName|}();
    }
}
""", "Microsoft.EntityFrameworkCore.Internal.MethodInfoExtensions");
```

2023-05-03 10:24 UTC, roji approved these changes
Thanks!

2023-05-03 11:32 UTC, DoctorKrolic commented
@roji CI is green. Merge?

2023-05-03 11:34 UTC, merged

2023-07-24 22:52 UTC, amcasey commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisTestingVersion>1.1.2-beta1.23251.2</MicrosoftCodeAnalysisTestingVersion>
This is a very specific version of Roslyn.  Is it important that we not use `MicrosoftCodeAnalysisVersion` and, if so, is it important to use a particular beta?

2023-07-24 23:36 UTC, amcasey commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisTestingVersion>1.1.2-beta1.23251.2</MicrosoftCodeAnalysisTestingVersion>
Evidently, it is the newest one available.  I suspect that means it's not supported, but at least the choice of version makes sense.

2023-07-25 07:12 UTC, roji commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisTestingVersion>1.1.2-beta1.23251.2</MicrosoftCodeAnalysisTestingVersion>
Yeah, good question - I'm not sure if we require some specific capability of the newest version here. Given that it's just test infrastructure (and doesn't affect the product), we can wait until 1.1.2 is released and then switch to that, sounds reasonable?

2023-07-25 07:32 UTC, DoctorKrolic commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisTestingVersion>1.1.2-beta1.23251.2</MicrosoftCodeAnalysisTestingVersion>
Unfortunately, there are some problems with `MS.CA.Testing` versioning, which made me use beta version of it. There is an [issue](https://github.com/dotnet/roslyn-sdk/issues/1047) asking for publishing `1.1.2` to NuGet, and the short answer is that [there are some organizational problems with that](https://github.com/dotnet/roslyn-sdk/issues/1047#issuecomment-1523360798). To be clear, other roslyn-related repos from .NET ecosystem use beta versions as well, including [roslyn itself](https://github.com/dotnet/roslyn/blob/520e2f10078ab0e5f85c78fdd95d786d78b9676a/eng/Versions.props#L24) and [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/blob/27abf4b5897e489ad540e8a0865bea2e9b0da131/eng/Versions.props#L93). We are also unable to downgrade to "stable" version `1.1.1` since it doesn't contain importand bug fixes, e.g. [this one](https://github.com/dotnet/roslyn-sdk/pull/1091), which are required for this repo to work

2023-07-25 07:37 UTC, DoctorKrolic commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisTestingVersion>1.1.2-beta1.23251.2</MicrosoftCodeAnalysisTestingVersion>
As about `MicrosoftCodeAnalysisVersion`: it is tied with supported versions of Visual Studio, so it should be updated carefully. `4.5.0` corresponds to the VS `17.5`, which was probably the latest available at the moment. Since EF Core 8 will target .NET 8, we are free to bump `MS.CA` version to the first one, that will support .NET 8, which will probably be `17.7` or `17.8`

2023-07-25 08:47 UTC, roji commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisTestingVersion>1.1.2-beta1.23251.2</MicrosoftCodeAnalysisTestingVersion>
Thanks for the explanations @DoctorKrolic! Makes sense!

And yeah, we can bump MS.CA, though I'm not aware of a specific need for that at this point.

2023-07-25 17:11 UTC, amcasey commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisTestingVersion>1.1.2-beta1.23251.2</MicrosoftCodeAnalysisTestingVersion>
Thanks for the explanation!