Add `migrations check-pending` Command
dotnet/efcore pull request #31164
Opened 2023-06-30 17:46 UTC by justindbaur

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #26348
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

I could not find anything that tests `MigrationOperations` methods or anything that directly tests the CLI. Please let me know if I missed anything and I'd be happy to write some tests.

My biggest question is the code I added in `MigrationsOperations`. It seems like a bit to much code for what normally goes in those methods but I don't know where the ideal location for this logic would sit. The code I wrote is a combination of the existing [code here](https://github.com/dotnet/efcore/blob/81c2440d848ecfe2ad9b8147150d607526d036b8/src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs#L143-L149) and from the comment on the [issue here](https://github.com/dotnet/efcore/issues/26348#issuecomment-1243730207).

Also feel free to let me know the exact wording you would like for the resource strings, I doubt what I have there is great.

2023-07-07 20:04 UTC, bricelam commented on src/EFCore.Design/Design/Internal/MigrationsOperations.cs
> +        var hasDifferences = modelDiffer.HasDifferences(lastModel, model.GetRelationalModel());
@ajcvickers This checks pending model changes

2023-07-07 20:07 UTC, bricelam commented on src/ef/Commands/MigrationsCommand.cs
> +        command.Command("check-pending", new MigrationsCheckPendingCommand().Configure);
We need to discuss the name in a design meeting. This proposal was intended to check for any un-applied migrations.

2023-07-07 20:34 UTC, bricelam commented
Open questions:

- Should we implement context.Database.HasChangesForAddMigration() at the same time and have it call that? (tentative method name)
- What should this output? Should it summarize the changes pending? Would a --dry-run flag on migrations add be better?
-should this have a PMC equivalent?
-Should it support --json?

2023-07-07 21:48 UTC, bricelam requested changes

2023-07-07 21:48 UTC, bricelam commented on src/EFCore.Design/Properties/DesignStrings.resx
> +    <value>You have pending migrations.</value>
Maybe something like:

> Changes have been made to the model since the last migration. Add a new migration.

2023-07-07 21:48 UTC, bricelam commented on src/dotnet-ef/Properties/Resources.resx
> +    <value>Checks if there are pending migrations.</value>
Maybe:

> Checks if any changes have been made to the model since the last migration.

2023-07-07 21:48 UTC, bricelam commented on src/ef/Commands/MigrationsCheckPendingCommand.cs
> +        return base.Execute(args);
We want this to return an error code when there are pending migrations so this can easily be utilized in a CI.

2023-07-07 21:48 UTC, bricelam commented on src/ef/Commands/MigrationsCheckPendingCommand.cs
> +        return base.Execute(args);
Oh I see, you're relying on an exception to be thrown. That's probably fine until we decide whether to add a `--json`

2023-07-07 21:48 UTC, bricelam commented on src/ef/Commands/MigrationsCheckPendingCommand.cs
> +        executor.CheckPendingMigrations(Context!.Value());
We should probably output something when there are no changes. Something like:

> No changes have been made to the model since the last migration.

2023-07-07 21:48 UTC, bricelam commented on src/dotnet-ef/Properties/Resources.resx
> +    <value>Checks if there are pending migrations.</value>
(Don't forget to update the resources in `ef` too.)

2023-07-07 21:51 UTC, bricelam commented
You can add tests to [Tests/Design/Internal/MigrationsOperationsTest.cs](https://github.com/dotnet/efcore/blob/main/test/EFCore.Design.Tests/Design/Internal/MigrationsOperationsTest.cs). See the ones in [DbContextOperationsTest](https://github.com/dotnet/efcore/blob/main/test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs) for a better example.

2023-07-10 21:12 UTC, bricelam commented
## 📝 Design Meeting Notes

- The command should be called `dotnet ef migrations has-pending-model-changes`
- The logic for this should be implemented as an extension method in [RelationalDatabaseFacadeExtensions](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs) called `HasPendingModelChanges` that returns a `bool`
- A corresponding PMC command, and the --json option should wait for more/actual user requests before implementing them
- The command should always output some message saying whether or not there are changes (as already requested in PR review)
  - A summary of changes is not useful/actionable (just run migrations add)

2023-07-10 21:13 UTC, bricelam commented on src/ef/Commands/MigrationsCommand.cs
> +        command.Command("check-pending", new MigrationsCheckPendingCommand().Configure);
See [design meeting notes](https://github.com/dotnet/efcore/pull/31164#issuecomment-1629739850)

2023-07-10 21:15 UTC, bricelam commented
@justindbaur Alright, the comments should contain all the changes we'd like to see before mering this. Let us know if you have any follow up questions. It's looking really good.

2023-07-10 21:21 UTC, justindbaur commented
@bricelam Thank you so much, I did start trying to write some tests but was having some issues because `MockAssembly.Name != typeof(TestContext). Assembly.Name` but maybe with making it an extension method off `DatabaseFacade` makes writing a test a bit easier.  But thanks for the feedback, I'll hopefully have something ready for a second pass in the next couple days.

2023-07-14 17:18 UTC, justindbaur commented
Hi @bricelam I believe I have addressed all feedback, the tests are not the prettiest things I have ever written. I had a bit of a learning curve trying to figure out how a snapshot model and design time model are created so I could best fake them while still achieving a high probability that the test is actually testing something. Let me know if you have a better way of achieving what I did.

2023-07-17 21:17 UTC, bricelam reviewed
LGTM

2023-07-17 21:17 UTC, bricelam commented on src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
> +    /// <param name="databaseFacade">Tbe facade from <see cref="DbContext.Database"/>.</param>
```suggestion
    /// <param name="databaseFacade">The facade from <see cref="DbContext.Database"/>.</param>
```

2023-07-18 16:50 UTC, bricelam approved these changes

2023-07-18 17:17 UTC, merged

2023-07-19 00:11 UTC, justindbaur commented
@bricelam Thank you so much for taking it across the finish line. Can't wait to add this to our CI!