Metadata for primitive collection mapping
dotnet/efcore pull request #31351
Opened 2023-07-25 12:58 UTC by ajcvickers

Part of #30730

Some stuff remaining, but wanted to get this out there for initial review.

Missing:
- ElementType in compiled model
- Negative cases
- More tests

2023-07-25 17:21 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/PropertyBuilder.cs
> +    public virtual PropertyBuilder IsCollection(Action<ElementTypeBuilder> builderAction)
We should add a parameterless overload that returns `PropertyBuilder`

2023-07-25 17:47 UTC, AndriySvyryd commented on src/EFCore/Metadata/Conventions/PropertyDiscoveryConvention.cs
> +            var builder = entityTypeBuilder.Property(propertyInfo);
Might as well set the `TypeMapping` on the property

2023-07-25 17:52 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/Property.cs
> +        => (IElementType?)SetOrRemoveAnnotation(CoreAnnotationNames.ElementType, elementType, configurationSource)?.Value;
We'll need `OnElementTypeChanged` convention type for this or we could make it readonly.

2023-07-25 18:46 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalElementTypeBuilderExtensions.cs
> +    public static IConventionElementTypeBuilder? ElementsHaveDatabaseType(
We use `StoreType` in other API

2023-07-25 18:48 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalElementTypeExtensions.cs
> +    public static string? GetCollation(this IReadOnlyElementType elementType)
Remove

2023-07-25 18:53 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalElementTypeExtensions.cs
> +            ?? elementType.FindAnnotation(RelationalAnnotationNames.StoreType)?.Value);
We usually give the annotation priority.

2023-07-25 19:07 UTC, AndriySvyryd commented
Are we going to support nested collections?

2023-07-25 19:12 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ElementTypeBuilder.cs
> +    public virtual ElementTypeBuilder HasAnnotation(string annotation, object? value)
`ElementsHaveAnnotation`?

2023-07-25 19:24 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/Property.cs
> +        => (IElementType?)SetOrRemoveAnnotation(CoreAnnotationNames.ElementType, elementType, configurationSource)?.Value;
Also, you need to call `SetRemovedFromModel` on the previous element type

2023-07-25 20:41 UTC, AndriySvyryd commented on src/EFCore/Storage/TypeMappingInfo.cs
> +            }
```suggestion
            var precision = elementType.GetPrecision();
            if (precision != null)
            {
                fallbackPrecision = precision;
            }
```

2023-07-25 20:42 UTC, AndriySvyryd commented on src/EFCore/Storage/TypeMappingInfo.cs
> +            }
```suggestion
            var scale = elementType.GetScale();
            if (scale != null)
            {
                fallbackScale = scale;
            }
```

2023-07-25 20:43 UTC, AndriySvyryd commented on src/EFCore/Storage/TypeMappingSource.cs
> +                var (info, providerType, converter, elementMapping) = k;
Either make all parameter names match outer names or make sure none do

2023-07-26 08:24 UTC, ajcvickers commented
> Are we going to support nested collections?

We said not now; maybe later.

2023-07-26 12:05 UTC, ajcvickers commented on src/EFCore.Relational/Extensions/RelationalElementTypeExtensions.cs
> +            ?? elementType.FindAnnotation(RelationalAnnotationNames.StoreType)?.Value);
This was copied from `GetColumnType`. Is it wrong there too?

2023-07-26 12:19 UTC, ajcvickers commented on src/EFCore/Metadata/Conventions/PropertyDiscoveryConvention.cs
> +            var builder = entityTypeBuilder.Property(propertyInfo);
This won't work as things stand now, because even though this is the type mapping we would use by default for the given `PropertyInfo`, it's not the type mapping that we would ultimately use for the `IProperty`, which must be obtained by asking for the type mapping using the `IProperty`.

2023-07-26 17:31 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalElementTypeExtensions.cs
> +            ?? elementType.FindAnnotation(RelationalAnnotationNames.StoreType)?.Value);
Most likely yes

2023-07-27 06:37 UTC, AndriySvyryd commented
> > Are we going to support nested collections?
> 
> We said not now; maybe later.

We should at least propose a model building API so that we don't have to make breaking changes.

2023-07-28 16:28 UTC, ajcvickers commented on src/EFCore.Relational/Extensions/RelationalElementTypeExtensions.cs
> +            ?? elementType.FindAnnotation(RelationalAnnotationNames.StoreType)?.Value);
@AndriySvyryd I investigated this. Looks like the column type one is intentional because the column type specified can be augmented with precision/scale/size such that the column type used at runtime is different. For example, if "varchar" is specified and max length is 64, then we need to use `varchar(64)`.

So I'll fix this case,  but leave the column type one unchanged.

2023-07-28 16:30 UTC, AndriySvyryd commented on src/EFCore.Relational/Extensions/RelationalElementTypeExtensions.cs
> +            ?? elementType.FindAnnotation(RelationalAnnotationNames.StoreType)?.Value);
Ok, add a comment please

2023-07-30 18:29 UTC, ajcvickers commented
@AndriySvyryd Updated per API review. Does this shape look correct?

2023-07-30 21:16 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +    public virtual ComplexTypePrimitiveCollectionBuilder HasPrecision(int precision, int scale)
Do we need these?

2023-07-30 21:41 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexTypePropertyBuilder.cs
> +    public virtual ElementTypeBuilder ElementType()
Why are these being added to the non-collection builder?

2023-07-30 21:46 UTC, AndriySvyryd commented on src/EFCore/Metadata/Conventions/PropertyDiscoveryConvention.cs
> +                    new ElementType(
The Metadata objects are usually instantiated by other Metadata objects. So `HasElementType` should instead accept a `Type`

2023-07-30 21:49 UTC, AndriySvyryd commented on src/EFCore/Metadata/Conventions/PropertyDiscoveryConvention.cs
> +                    new ElementType(
However, we could just push this to `Property` call instead to make it consistent with `ComplexProperty` and closer to the Fluent API

2023-07-30 21:54 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
> +        CopyElementType(builder, discriminatorProperty, configurationSource);
This should've been handled by `Attach` instead.

2023-07-31 08:52 UTC, ajcvickers commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +    public virtual ComplexTypePrimitiveCollectionBuilder HasPrecision(int precision, int scale)
Do you mean precision and scale in general? Or on ComplexTypePrimitiveCollectionBuilder specifically?

2023-07-31 08:55 UTC, ajcvickers commented on src/EFCore/Metadata/Builders/ComplexTypePropertyBuilder.cs
> +    public virtual ElementTypeBuilder ElementType()
Because it's hard to keep track of what builders do what. :-) What does this builder do? I thought it would be what you use if you want a primitive property (which could be a collection) as part of a complex type.

2023-07-31 17:27 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +    public virtual ComplexTypePrimitiveCollectionBuilder HasPrecision(int precision, int scale)
In general

2023-07-31 17:31 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexTypePropertyBuilder.cs
> +    public virtual ElementTypeBuilder ElementType()
No, this builder configures a non-collection property on a complex type.
You already added the correct methods to `ComplexPropertyBuilder` and `ComplexTypePrimitiveCollectionBuilder`

2023-07-31 17:32 UTC, ajcvickers commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +    public virtual ComplexTypePrimitiveCollectionBuilder HasPrecision(int precision, int scale)
I think we need them given that they impact the store type mapping.

2023-07-31 17:34 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +    public virtual ComplexTypePrimitiveCollectionBuilder HasPrecision(int precision, int scale)
I don't see how they impact the collection store type mapping, they should only be needed for the element type.

2023-07-31 17:38 UTC, ajcvickers commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +    public virtual ComplexTypePrimitiveCollectionBuilder HasPrecision(int precision, int scale)
Oh, good point. I will remove.

2023-08-01 19:07 UTC, ajcvickers commented
@AndriySvyryd I still have the "ModelBuilding" tests to finish here, but I'm not going to get that done this evening, so I'm sending out for review now since, bugs, negative cases, and testing aside, I think this is ready to merge.

2023-08-01 20:48 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +    public virtual ComplexTypePrimitiveCollectionBuilder HasValueGenerator(Func<IProperty, ITypeBase, ValueGenerator> factory)
Remove this overload as the value is low and it will not be compatible with compiled model.

2023-08-01 20:50 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexTypePrimitiveCollectionBuilder.cs
> +        return new ElementTypeBuilder((IMutableElementType)Builder.Metadata.GetElementType()!);
Use the type returned from `Builder.HasElementType`

2023-08-01 20:54 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
> +                    ConfigurationSource.Explicit)!.HasElementType(ConfigurationSource.Explicit)!.Metadata);
I think `PrimitiveCollection` on the internal builder would be cleaner

2023-08-01 20:55 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
> +    IConventionPropertyBuilder? HasElementType(Action<IConventionElementTypeBuilder> builderAction, bool fromDataAnnotation = false);
Remove, IConvention*Builders don't have nested lambdas

2023-08-01 20:57 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
> +                    ConfigurationSource.Explicit)!.HasElementType(ConfigurationSource.Explicit)!.Metadata);
And on the IConvention*Builders

2023-08-01 20:58 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/PrimitiveCollectionBuilder.cs
> +    public virtual PrimitiveCollectionBuilder HasValueGenerator(Func<IProperty, ITypeBase, ValueGenerator> factory)
Also here

2023-08-01 21:01 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/PrimitiveCollectionBuilder.cs
> +    ///     Configures this property as a collection containing elements of a primitive type.
```suggestion
    ///     Configures the elements of this collection.
```

And elsewhere

2023-08-01 21:10 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/Property.cs
> +        IElementType? elementType,
ElementType instance management shouldn't be exposed outside of `Property`
Also, pubternal Metadata API should use pubternal types when possible

2023-08-01 21:13 UTC, AndriySvyryd commented on src/EFCore/Metadata/RuntimeProperty.cs
> +    public virtual RuntimeElementType AddElementType(
```suggestion
    public virtual RuntimeElementType SetElementType(
```

2023-08-01 21:18 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/ElementType.cs
> +                }
Refactor to a common method

2023-08-01 22:23 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/InternalTypeBaseBuilder.cs
> +            var oldConfigurationSource = property.GetConfigurationSource();
```suggestion
            var oldConfigurationSource = property.GetElementTypeConfigurationSource();
```

Though, in general this should've been handled by `Attach`

2023-08-01 22:34 UTC, AndriySvyryd commented on test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
> +        // public override void Properties_can_be_made_concurrency_tokens()
👀

2023-08-01 22:40 UTC, AndriySvyryd commented on test/EFCore.Specification.Tests/ApiConsistencyTestBase.cs
> +                && !parameters[parameterIndex].ParameterType.FullName!.Contains("Builder")
revert

2023-08-01 22:49 UTC, AndriySvyryd commented on test/EFCore.Tests/ApiConsistencyTest.cs
> +            typeof(PrimitiveCollectionBuilder<>),
Also add the new types to `GenericFluentApiTypes` and `MetadataTypes` in `ApiConsistencyFixtureBase`

2023-08-01 22:50 UTC, AndriySvyryd commented on test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
> +
Reminder to cover the other convention types

2023-08-01 22:54 UTC, AndriySvyryd commented on test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
> +        public abstract TestPrimitiveCollectionBuilder<TProperty> PrimitiveCollection<TProperty>(string propertyName);
Also on complex properties

2023-08-01 22:59 UTC, AndriySvyryd commented on test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
> +    {
Doesn't look like these tests use primitive collections.
I'm fine with splitting adding for entity splitting into a separate (backlog) issue.
Review https://github.com/dotnet/efcore/issues/31238 and file equivalent issues for primitive collection features that aren't currently supported and add them to https://github.com/dotnet/efcore/issues/30731.

2023-08-01 23:01 UTC, AndriySvyryd commented on test/EFCore.Tests/ModelBuilding/PrimitiveCollectionsTestBase.cs
> +        // [ConditionalFact]
👀

2023-08-01 23:02 UTC, AndriySvyryd requested changes
Also add validation for invalid configuration that's only possible using Metadata API

2023-08-02 11:52 UTC, ajcvickers commented on src/EFCore/Metadata/Builders/PrimitiveCollectionBuilder.cs
> +    public virtual PrimitiveCollectionBuilder HasValueGenerator(Func<IProperty, ITypeBase, ValueGenerator> factory)
Should this overload be removed from `ComplexTypePropertyBuilder` as well? I think you added it there.

2023-08-02 12:14 UTC, ajcvickers commented on src/EFCore/Metadata/Internal/InternalTypeBaseBuilder.cs
> +            var oldConfigurationSource = property.GetConfigurationSource();
This was left over from before I implemented Attach. It is not now needed.

2023-08-02 12:19 UTC, ajcvickers commented on src/EFCore/Metadata/Internal/Property.cs
> +        IElementType? elementType,
So how should Attach be implemented? Should I deconstruct the existing element type into all its components and then pass them somehow to Property and have it create a new instance? Would I then have to make sure that any references to the existing instance is fixed up?

2023-08-02 16:47 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/PrimitiveCollectionBuilder.cs
> +    public virtual PrimitiveCollectionBuilder HasValueGenerator(Func<IProperty, ITypeBase, ValueGenerator> factory)
Yes, we can always add it later

2023-08-02 16:51 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/Property.cs
> +        IElementType? elementType,
Yes, you'd have to deconstruct the configuration and reenact it on the element type, the same way it's done for the property itself.

2023-08-02 16:55 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/Property.cs
> +        IElementType? elementType,
By not being able to manipulate the instance you now don't need to worry about any references to it as it can only be referenced from the Property instance that created it.

2023-08-06 15:43 UTC, ajcvickers commented on test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
> +
@AndriySvyryd What do you mean by "other convention types?"

2023-08-07 18:47 UTC, AndriySvyryd commented on test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
> +
[IElementTypeAnnotationChangedConvention.cs](https://github.com/dotnet/efcore/pull/31351/files#diff-bf2778b2fe9d474b4b4f10245672d8f0231b70507eac53de5be8452be82e88e2) and [IElementTypeNullabilityChangedConvention.cs](https://github.com/dotnet/efcore/pull/31351/files#diff-cc39d0b102230dfc37b4f559a1b116d5db77f82f9304f1248255fd521dcc1d67)

2023-08-07 18:55 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Extensions/CosmosPrimitiveCollectionBuilderExtensions.cs
> +    public static PrimitiveCollectionBuilder IsETagConcurrency(this PrimitiveCollectionBuilder primitiveCollectionBuilder)
This doesn't make sense for anything that's not mapped to a string.

2023-08-07 20:10 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Extensions/CosmosPrimitiveCollectionBuilderExtensions.cs
> +public static class CosmosPrimitiveCollectionBuilderExtensions
Add these to `FluentApiTypes`, `MetadataExtensionTypes` and `MirrorTypes` in `RelationalApiConsistencyTest`

2023-08-07 20:48 UTC, AndriySvyryd commented on test/EFCore.Tests/ModelBuilding/PrimitiveCollectionsTestBase.cs
> +//     public abstract class PrimitiveCollectionsTestBase : ModelBuilderTestBase
Remove this file

2023-08-07 20:52 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/ComplexPropertyBuilder`.cs
> +                .Metadata);
This doesn't call `PrimitiveCollection`

2023-08-07 20:57 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
> +                    ConfigurationSource.Explicit)!.PrimitiveCollection(ConfigurationSource.Explicit)!.Metadata);
I meant that we should call `Builder.PrimitiveCollection()` instead of `Builder.Property().PrimitiveCollection()`

2023-08-07 21:02 UTC, AndriySvyryd commented on src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
> +                    elementType.GetValueComparer(), elementType.GetValueComparerConfigurationSource() ?? ConfigurationSource.Convention);
We shouldn't convert default configuration to configuration by convention. This introduces subtle bugs.

2023-08-09 10:43 UTC, ajcvickers commented on src/EFCore.Cosmos/Extensions/CosmosPrimitiveCollectionBuilderExtensions.cs
> +public static class CosmosPrimitiveCollectionBuilderExtensions
What do you mean by "these" and how do I know what counts as a mirror-type?

2023-08-09 16:33 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Extensions/CosmosPrimitiveCollectionBuilderExtensions.cs
> +public static class CosmosPrimitiveCollectionBuilderExtensions
I am referring to the provider extensions. Mirror types have the same API shape like `PropertyBuilder` and `ComplexTypePropertyBuilder`

2023-08-09 17:32 UTC, AndriySvyryd commented on src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
> +    IConventionElementTypeBuilder? ElementType(bool fromDataAnnotation = false);
Add a `bool` parameter indicating whether the property should be a collection. The configuration source for the element type would only be checked when changing from collection to non-collection or vice-versa. When just configuring element type aspects we don't need to call `CanSetElementType`. This also means that the element type configuration source should be stored when the element type is `null`.

2023-08-09 17:32 UTC, AndriySvyryd approved these changes

2023-08-10 15:54 UTC, merged