Generate change-tracking delegates in the compiled model.
dotnet/efcore pull request #31443
Opened 2023-08-10 21:03 UTC by AndriySvyryd

Part of #29761

Still missing private constructors and service property bindings

2024-01-23 11:23 UTC, ajcvickers commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            string or bool or null => (ExpressionSyntax)_g.LiteralExpression(constant.Value),
Formatting looks wrong here. Also why is this condition separate from the one on the previous line?

2024-01-23 12:37 UTC, ajcvickers commented on src/EFCore/Query/Internal/EntityMaterializerSource.cs
> +    public static readonly MethodInfo PopulateListMethod
Should this move to a common, public, location?

2024-01-23 12:40 UTC, ajcvickers approved these changes

2024-01-24 12:37 UTC, roji commented
FYI starting to review (especially the LinqToCSharp changes).

2024-01-24 19:16 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            string or bool or null => (ExpressionSyntax)_g.LiteralExpression(constant.Value),
probably just to cut down on line length, I assume it would compile to the same code either way.

2024-01-24 22:24 UTC, roji requested changes
Reviewed the LinqToCSharpSyntaxTranslator changes; overall looks good but there are several things we should discuss (we can jump into a call tomorrow if you want).

2024-01-24 22:24 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (translatedLeft is ParenthesizedExpressionSyntax
?

2024-01-24 22:24 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            string or bool or null => (ExpressionSyntax)_g.LiteralExpression(constant.Value),
The separation was just to separate between numeric types and other primitives (and also to avoid a too-long line). No strong feelings.

2024-01-24 22:24 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            Snapshot snapshot
As above, it would be good to avoid hardcoded EF logic in this visitor, and have it in a sub-visitor instead.

2024-01-24 22:24 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (_knownInstances != null
Is this also something that makes sense as sub-visitor logic, or do the known instances actually change across invocations of the visitor (and therefore need to be accepted as an argument)?

2024-01-24 22:24 UTC, roji commented on test/EFCore.Design.Tests/Query/LinqToCSharpTranslatorTest.cs
> +    public void Constant_DateTime()
```suggestion
    public void Constant_DateTime_default()
```

2024-01-24 23:21 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +    private ExpressionContext? _context;
> I can see you've added a Translate() method which doesn't require the user to specify whether they expect a statement or expression (btw it's unused).

What prompted me to do it were some of the getters that we generate that had statements, however I managed to change them to expressions, so didn't actually had to use the new overload.

> According to my mental model, that means that when translating to CSharp, the user must specify the context externally - this isn't something that can be detected/inferred from the LINQ expression tree.

My thinking was that you'd call this in a place that you expect an expression, but could handle a statement as well if necessary. So, we'd assume expression context until we hit something that can't be translated. Sometimes this would require going back up the tree and producing a different translation, this and other cases aren't handled yet.

2024-01-24 23:37 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (assignment.Left is MemberExpression member
Yes, this part definitely would benefit from more documentation.

I don't agree that it's EF-specific, since private member access is a general issue with expression translation and Reflection is a subpar solution. However, I could still separate this out to a pre-translation visitor or a derived class, just to reduce the complexity in this class.

2024-01-24 23:42 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (translatedLeft is ParenthesizedExpressionSyntax
I changed `VisitMember` to add a cast after the `FieldInfo.GetValue` call, since that returns an `object`

2024-01-24 23:46 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (_knownInstances != null
The most common use case is for known instances to contain the variables in scope where the translated code will be generated, so they definitely change across invocations.

2024-01-25 09:23 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +    private ExpressionContext? _context;
OK. It's true that there are some LINQ expressions where the result **must** be a C# statement (e.g. anything that requires a block); the current behavior is for the translator to throw if TranslateExpression is expected. I don't think the opposite is a case, since if the caller prefers a statement they can always call TranslateStatement and that always works (the top-level expression can always be wrapped as a statement).

If we do need something like this, then it may be simpler to implement by simply have a general Translate() method (like the one you added) call a private TryTranslateExpression; if that fails, it can do TranslateStatement instead and return the result. This would remove the complexity of having to deal with a null context everywhere, for each and every expression type case.

But in any case, the question is probably whether we actually have a current need for this, which doesn't seem to case right now? Maybe it's better to just wait until the need arises before implementing...

2024-01-25 09:32 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (assignment.Left is MemberExpression member
Sure, the need to access private members is indeed general, but the specific replacing mechanism seems a bit EF-specific, i.e. the fact that two methods will be provided (for set/get), with the specific signatures (also possibly the fact that properties and fields are treated in the same way?).

In other words, I think it makes sense to have an extension point here for "read a private member" (or different for field/property), and another for "write a private member". The default implementation can do reflection, and subclasses can override, providing more efficient UnsafeAccessor-based alternatives, or whatever.

How does that sound?

2024-01-25 09:34 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (translatedLeft is ParenthesizedExpressionSyntax
OK. In this kind of case it's better to pattern-match on the pre-translated LINQ expression tree, rather than on the post-translated Roslyn syntax tree (syntax trees are brittle, we may end up changing the precise shape in various ways)

Also, probably still good to handle FieldInfo.GetValue without the cast, i.e. to unwrap the LINQ convert node before translating and then do the appropriate thing. Adding tests for both cases would be good too.

2024-01-25 09:35 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            if (_knownInstances != null
OK, makes sense then!

2024-01-25 19:15 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +    private ExpressionContext? _context;
Ok, moved this to https://github.com/dotnet/efcore/issues/32783#issuecomment-1910825957

2024-01-25 20:01 UTC, AndriySvyryd commented on src/EFCore/Query/Internal/EntityMaterializerSource.cs
> +    public static readonly MethodInfo PopulateListMethod
It points to a method on a pubternal class. To me it makes sense for it to be pubternal as well.

2024-01-26 06:01 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +        if (kind != SyntaxKind.SimpleAssignmentExpression)
Unless I'm mistaken, there's currently a bug where RuntimeModelLinqToCSharpSyntaxTranslator overrides TranslateNonPublicFieldAssignment, and as long as the member expression is in _memberAccessReplacements, it assumes we're dealing with simple assignment. In other words, `foo._a += 3` would be translated to a simple `foo._a = 3`.

Basically I think the handling of the compound assignment cases should be outside of this method, this way inheriting subclasses only need to deal with simple assignment, and not compound. This could be done by detecting e.g. ExpressionType.AddAssign *before* translation to C#, and pre-transforming it to the corresponding LINQ fragment without compound assignment (with ExpressionType.Assign instead); then, just visit that LINQ fragment again, and it would get naturally translated as a regular assignment.

2024-01-26 06:05 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +    protected virtual void TranslateNonPublicFieldAssignment(MemberExpression member, Expression value, SyntaxKind kind)
BTW @AndriySvyryd another good case for this to be an extension point rather than receiving replacing methods as an argument... In the NativeAOT pipeline, we have to actually generate UnsafeAccessors for each private field access, and then invoke them from inside the generated C# expression. But the actual UnsafeAccessor itself (the member) is outside of the generated tree, so the caller must be able to collect the required UnsafeAccessors as an output result of this pass.

2024-01-26 06:06 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +        return value switch
nit: expression-bodied

2024-01-26 06:06 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            + Environment.NewLine + value.ToString());
```suggestion
            + Environment.NewLine + value);
```

2024-01-26 06:08 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            var generic = GenericName(
I think we need this logic to produce fully-qualified names, to avoid the usual ambiguities etc. (unrelated to this PR).

2024-01-26 06:10 UTC, roji commented on src/EFCore.Design/Query/Internal/RuntimeModelLinqToCSharpSyntaxTranslator.cs
> +public class RuntimeModelLinqToCSharpSyntaxTranslator : LinqToCSharpSyntaxTranslator
Looks great.

2024-01-26 06:11 UTC, roji requested changes
Aside from the compound assignment issue for private fields, LGTM.

2024-01-26 08:23 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +    protected virtual void TranslateNonPublicFieldAssignment(MemberExpression member, Expression value, SyntaxKind kind)
The UnsafeAccessors are generated already in the compiled model, and I don't think we'd need any for types that aren't in the model. Basically, this isn't a responsibility for this or any derived types.

2024-01-26 10:59 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +    protected virtual void TranslateNonPublicFieldAssignment(MemberExpression member, Expression value, SyntaxKind kind)
Ah, I see... So the query pre-compilatiotion - which generates the interceptors - won't have to also generate unsafe accessors - the interceptors will simply reference once from the compiled model. Sounds good.

2024-01-26 19:23 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +        return value switch
Can't, contains local functions that you like so much

2024-01-26 19:28 UTC, roji approved these changes

2024-01-26 20:27 UTC, merged