31355: SQLite: Add EF.Functions.Unhex
dotnet/efcore pull request #31454
Opened 2023-08-12 16:36 UTC by smnsht

- [X] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [X] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [X] The code builds and tests pass locally (also verified by our automated build checks)
- [X] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Code follows the same patterns and style as existing code in this repo

2023-08-24 16:40 UTC, bricelam requested changes

2023-08-24 16:40 UTC, bricelam commented on src/EFCore.Sqlite.Core/Extensions/SqliteDbFunctionsExtensions.cs
> +        => throw new InvalidOperationException(CoreStrings.FunctionOnClient(nameof(Unhex)));
```suggestion
    /// <summary>
    ///     Maps to the SQLite <c>unhex</c> function which returns a BLOB representing decoding of the hexadecimal string.
    /// </summary>
    /// <remarks>
    ///     See <see href="https://aka.ms/efcore-docs-database-functions">Database functions</see>, and
    ///     <see href="https://aka.ms/efcore-docs-sqlite">Accessing SQLite databases with EF Core</see> for more information and examples.
    /// </remarks>
    /// <param name="_">The <see cref="DbFunctions" /> instance.</param>
    /// <param name="value">The hexadecimal string.</param>
    /// <returns>Decoded hexadecimal string as binary value.</returns>
    public static byte[] Unhex(this DbFunctions _, string value)
        => throw new InvalidOperationException(CoreStrings.FunctionOnClient(nameof(Unhex)));

    /// <summary>
    ///     Maps to the SQLite <c>unhex</c> function which returns a BLOB representing decoding of the hexadecimal string.
    /// </summary>
    /// <remarks>
    ///     See <see href="https://aka.ms/efcore-docs-database-functions">Database functions</see>, and
    ///     <see href="https://aka.ms/efcore-docs-sqlite">Accessing SQLite databases with EF Core</see> for more information and examples.
    /// </remarks>
    /// <param name="_">The <see cref="DbFunctions" /> instance.</param>
    /// <param name="value">The hexadecimal string.</param>
    /// <param name="ignoreChars">Characters that are ignored in <paramref name="value"/>.</param>
    /// <returns>Decoded hexadecimal string as binary value.</returns>
    public static byte[] Unhex(this DbFunctions _, string value, string ignoreChars)
        => throw new InvalidOperationException(CoreStrings.FunctionOnClient(nameof(Unhex)));
```

2023-08-24 16:40 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> +
Remove extra line break

2023-08-24 16:40 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> +        Assert.Equal(context.Set<ObjectBackedDataTypes>().Count(), context.SaveChanges());
Hmm, it might be simpler to just query `EF.Functions.Unhex(EF.Functions.Hex(e.Bytes))` and not mutate the seed data.

2023-08-24 16:40 UTC, bricelam commented on test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> +        Assert.Equal(context.Set<ObjectBackedDataTypes>().Count(), context.SaveChanges());
Likewise, just query `EF.Functions.Unhex(EF.Functions.Hex(e.Bytes) + "!?", "!?")`

2023-08-25 07:51 UTC, smnsht commented on src/EFCore.Sqlite.Core/Extensions/SqliteDbFunctionsExtensions.cs
> +        => throw new InvalidOperationException(CoreStrings.FunctionOnClient(nameof(Unhex)));
@bricelam changed

2023-08-25 07:51 UTC, smnsht commented on test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> +
@bricelam done

2023-08-25 07:52 UTC, smnsht commented on test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> +        Assert.Equal(context.Set<ObjectBackedDataTypes>().Count(), context.SaveChanges());
@bricelam fixed

2023-08-25 07:52 UTC, smnsht commented on test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> +        Assert.Equal(context.Set<ObjectBackedDataTypes>().Count(), context.SaveChanges());
@bricelam fixed

2023-08-28 16:37 UTC, bricelam commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteHexMethodTranslator.cs
> +                arguments[1].TypeMapping);
```suggestion
                typeof(byte[]));
```

2023-08-28 18:12 UTC, merged