Introduce liftable constants to shaper to prepare for precompilation
dotnet/efcore pull request #33351
Opened 2024-03-19 01:44 UTC by maumar

Part of #25009

json reader writer proper fix

2024-03-19 01:56 UTC, maumar commented
@roji created a separate PR to preserve the original code changes until we are happy with what we have. It's draft so far but should be ok to take a look. Only real outstanding issue is NTS, their value converter require SqlServerBytesReader/SqlServerBytesWriter, which in turn require NtsGeometryServices so it's a bit tricky to smuggle it in. Still a lot of small fixes, comments cleanups etc

2024-03-19 01:57 UTC, maumar commented on src/EFCore/Storage/ValueConversion/ValueConverter`.cs
> +            // TODO: hints are not supported
are these important?

2024-03-19 07:03 UTC, maumar commented on test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
> +        public Anais()
@ajcvickers for stuff like this, or private LazyLoading ctors, is it ok to make them public or are we better off disabling tests in AOT scenario. i.e. are we losing test coverage by making some of this stuff public?

2024-03-19 07:59 UTC, roji commented on test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
> +        public Anais()
FYI I recently realize that [unsafe accessors](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafeaccessorattribute?view=net-8.0) work also for private methods and constructors, so we have the option of keeping this private, which seems better...

For EF methods that internally get called from the shaper, it may be better to still make these pubternal (it's more immediately clear that they're actually needed outside the class, no IDE warnings on unused stuff) - we can discuss. But at least for private constructors on user types we should probably just make it work via unsafe accessors.

2024-03-19 17:47 UTC, maumar commented on test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
> +        public Anais()
great, thanks for the info! I agree about keeping EF private methods pubternal, my concern was 100% about the user code and scenarios.

2024-03-20 10:41 UTC, roji commented on test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
> +        public Anais()
@AndriySvyryd do you already handle private constructors via unsafe accessors in the compiled model?

2024-03-20 20:22 UTC, AndriySvyryd commented on test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
> +        public Anais()
No, but it's high on the to-do list

2024-03-22 09:23 UTC, roji commented on src/EFCore/Storage/ValueConversion/ValueConverter`.cs
> +            // TODO: hints are not supported
I think that comment only means that I didn't do the work for it in the original prototype PR, not that there's some particular problem with them (though I honestly don't remember at this point). I think that in general it's probably important to support these (/cc @ajcvickers)

2024-03-22 09:29 UTC, maumar commented on src/EFCore/Storage/ValueConversion/ValueConverter`.cs
> +            // TODO: hints are not supported
oh it was me who added the comment ;) - construction of the object is bit tricky, but perhaps what we will have to do with converters anyway is to find the path to the property and then access it's type mapping and then the converter. I went pretty far with constructing all the stuff manually with expression trees but that breaks with custom converters, for example

2024-03-22 09:31 UTC, roji commented on src/EFCore/Storage/ValueConversion/ValueConverter`.cs
> +            // TODO: hints are not supported
Oh sorry I misunderstood 😅 

Yeah, in general just finding the property and then its mapping and converter generally seems like the right path for all these types of issues...

2024-03-26 08:45 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
> +#pragma warning disable EF1001 // Internal EF Core API usage.
@maumar as written offline, it would be good if we don't require all providers to always use liftable constants (since that would break non-relational ones).

At that point, all the APIs around liftable constants can be flagged with `[Experimental(EFDiagnostics.PrecompiledQueryExperimental)]`, and implementing providers can suppress the warning for that at the project level.

2024-03-28 04:46 UTC, maumar commented on src/EFCore.Relational/Query/Internal/RelationalLiftableConstantExpressionDependencies.cs
> +public sealed record RelationalLiftableConstantExpressionDependencies
should this be moved to public/experimental also?

2024-03-28 07:01 UTC, maumar commented on src/EFCore/Metadata/FactoryMethodBinding.cs
> +    public FactoryMethodBinding(
obsolete the ctor without factoryInstanceExpression?

2024-03-28 08:28 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        // TODO: No, this must be a lifted constant, otherwise we re-instantiate on each query
TODO

2024-03-28 09:02 UTC, maumar commented
@ajcvickers specifically for changes in the EntityMaterializerSource and the area around (lazy loading, injectible service, parameter binding etc)

2024-03-28 09:39 UTC, maumar commented on src/EFCore/Query/LiftableConstantExpressionHelpers.cs
> +            null or Type or Enum or CultureInfo or Encoding or IPAddress => true,
TODO: clean these up

2024-03-28 09:41 UTC, roji commented on src/EFCore.Relational/Query/Internal/RelationalLiftableConstantExpressionDependencies.cs
> +public sealed record RelationalLiftableConstantExpressionDependencies
Yep - as part of the liftable constant infrastructure (which is part of precompilation)

2024-03-28 09:42 UTC, roji commented on src/EFCore/Metadata/FactoryMethodBinding.cs
> +    public FactoryMethodBinding(
Question for @AndriySvyryd or @ajcvickers?

2024-03-29 08:52 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        // TODO: No, this must be a lifted constant, otherwise we re-instantiate on each query
problem: in some scenarios at the time that we call `CreateReaderColumnsExpression` to generate the lambda (and would be shapshotting the LiftableConstant), `_readerColumns` can have different values than when we actually invoke the lambda.

2024-03-31 12:08 UTC, roji requested changes
Really nice to see this coming together! See first review comments.

2024-03-31 12:08 UTC, roji commented on src/EFCore/Storage/ValueConversion/BoolToStringConverter.cs
> +                                    Expression.Constant(trueValue),
Yeah, this is unfortunate...

(nit: using static System.Linq.Expressions.Expression)

2024-03-31 12:08 UTC, roji commented on src/EFCore/Storage/ValueConversion/ValueConverter.cs
> +    public abstract Expression ConstructorExpression { get; }
Let's discuss, still not sure why we can't use liftable constant to get the value converter from the property in the model

2024-03-31 12:08 UTC, roji commented on src/Shared/ExpressionExtensions.cs
> +        => expression switch
Looking at how this method is used, consider making it TryGetConstantValue

2024-03-31 12:08 UTC, roji commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +    [ConditionalTheory(Skip = "AOT: NTS is not supported")]
Let's discuss the problem with NTS (also, tracking issue?)

2024-04-01 07:25 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            var entityParameter = Parameter(shaper.Type, "entity");
yeah I was thinking we should add more variable names. When hunting all the liftable constant spots I was leaning heavily on named variables to find place in the code that I needed to adjust.

2024-04-01 07:28 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            var entityParameter = Parameter(shaper.Type, "entity");
filed https://github.com/dotnet/efcore/issues/33446

2024-04-01 07:32 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +            // TODO: Do the same for the other QueryingEnumerables
missed this one, my bad >.<

2024-04-01 07:52 UTC, maumar commented on src/EFCore/Query/LiftableConstantProcessor.cs
> +        return LiftableConstantExpressionHelpers.IsLiteral(node.Value)
good catch, remnant from a debugging session

2024-04-01 08:00 UTC, maumar commented on src/EFCore/Query/StructuralTypeShaperExpression.cs
> +                        : Convert(Call(Constant(concreteEntityTypes[i]), GetDiscriminatorValueMethod), discriminatorProperty.ClrType);
that's correct. Some cases use custom clr type as discriminator and we can't render it. Look for `new MyDiscriminator(1)` in  our graph update tests. My first approach was to flow liftable constant factory there, but that required a lot of changes (basically from it through entire translation pipeline), so I reverted these. We just use constant here, because after we inject materializer code template from the materializer source, we run a visitor (`MaterializationConditionConstantLifter`) that patches all the entities/properties, services etc.

2024-04-01 08:02 UTC, maumar commented on src/EFCore/Query/StructuralTypeShaperExpression.cs
> +                        : Convert(Call(Constant(concreteEntityTypes[i]), GetDiscriminatorValueMethod), discriminatorProperty.ClrType);
We do call the method every time now, which is a perf hit for everyone, but I didn't see a better alternative given the `MyDiscriminator` conundrum

2024-04-01 08:11 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                                Constant(ValueBuffer.Empty),
I like the idea of instant evaluation, but would rather do it in a separate PR.

2024-04-01 08:21 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                            var entityParameter = Parameter(shaper.Type, "entity");
> When hunting all the liftable constant spots I was leaning heavily on named variables to find place in the code that I needed to adjust.

Yeah, my thinking exactly... This is about helping ourselves...

2024-04-01 08:24 UTC, maumar commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +            // if constant is of interface type we blind guess it might be a service and try to resolve it
Case that prompted this change is ProxyFactory (IProxyFactory), which is defined in EFCore.Proxies, so we don't know about it in Core. Another case that will be a problem in the future is NTS, which requires some of NTS specific service to build some spatial converters

2024-04-01 08:30 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        private sealed class DisplayClassConstantFixer : ExpressionVisitor
```
JsonEntityAllTypes instance;
                            instance = new JsonEntityAllTypes();
                            instance.<Id>k__BackingField = dataReader.GetInt32(0);
                            {
                                IList<bool> namelessParameter{2};
                                namelessParameter{2} = instance.TestBooleanCollection;
                                namelessParameter{2} == null || dataReader.IsDBNull(1) ? default(IList<bool>) : (IList<bool>)(IEnumerable<bool>)<>c__DisplayClass0_0.collectionJsonReaderWriter.FromJsonString(
                                    json: (string)dataReader.GetFieldValue<object>(1), 
                                    existingObject: null) == null ? instance.TestBooleanCollection = dataReader.IsDBNull(1) ? default(IList<bool>) : (IList<bool>)(IEnumerable<bool>)<>c__DisplayClass0_0.collectionJsonReaderWriter.FromJsonString(
                                    json: (string)dataReader.GetFieldValue<object>(1), 
                                    existingObject: null) : EntityMaterializerSource.PopulateList<bool>(
                                    buffer: dataReader.IsDBNull(1) ? default(IList<bool>) : (IList<bool>)(IEnumerable<bool>)<>c__DisplayClass0_0.collectionJsonReaderWriter.FromJsonString(
                                        json: (string)dataReader.GetFieldValue<object>(1), 
                                        existingObject: null), 
                                    target: namelessParameter{2});
                            }
```

Basically materializing property from a json type. That code is generated in `CreateGetValueExpression` and we don't always have property there to produce the value in a correct way (we use TypeMapping, but we can't easily retrieve that from the context). Proper fix would be to flow property information throughout translation pipeline, but that's a lot of work, so definitely for a separate PR

2024-04-01 08:36 UTC, maumar commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +                return (BinaryExpression)Activator.CreateInstance(
Why not indeed :D Will try to remove - part that I added was due to the private accessors.

2024-04-01 08:59 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        private sealed class DisplayClassConstantFixer : ExpressionVisitor
OK. Just out of curiosity, how come we don't have the same problem with value converters?

2024-04-01 09:21 UTC, maumar commented on src/EFCore/Query/QueryCompilationContext.cs
> +            valueExtractorBody = _runtimeParameterConstantLifter.Visit(valueExtractorBody);
example:
`Contains_over_entityType_should_rewrite_to_identity_equality` test

```cs
ss.Set<Order>()
    .Where(o => o.CustomerID == "VINET")
    .Contains(ss.Set<Order>().Single(o => o.OrderID == 10248))
```

and materializer code looks like this:

```cs
queryContext => 
{
    queryContext.AddParameter(
        name: "__entity_equality_p_0_OrderID", 
        value: (object)Invoke(queryContext => RelationalSqlTranslatingExpressionVisitor.ParameterValueExtractor<int?>(
            context: queryContext, 
            baseParameterName: "__p_0", 
            complexPropertyChain: null, 
            property: Property: Order.OrderID (no field, int) Required PK AfterSave:Throw ValueGenerated.OnAdd), queryContext));
    return SingleQueryingEnumerable.Create<bool>(...)
}
```

2024-04-01 09:34 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                                Constant(ValueBuffer.Empty),
https://github.com/dotnet/efcore/issues/33447

2024-04-03 07:17 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                                        ? Default(typeof(IClrCollectionAccessor))
we don't need liftable constants for null values, so creating regular constant to make things simpler. Could always create LCE and just do some conditional logic around variable name (which uses navigation name to generate it's name). But what we have now doesn't look too bad for me

2024-04-03 08:11 UTC, maumar commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +                return (BinaryExpression)Activator.CreateInstance(
Simplified, but I don't think it's safe to remove this completely. If right side of the assignment into private field would be liftable constant (and that gets lifted/inlined), the default visitation would try to create a new Assign expression but without the AssignBinaryExpression trick.

2024-04-03 08:55 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        private sealed class DisplayClassConstantFixer : ExpressionVisitor
This is a problem with value converter, specifically `CollectionToJsonStringConverter`, it captures `JsonValueReaderWriter`. All other converters (afaict) produce non-capturing lambdas that get passed to the `ValueConverter<TModel, TProvider>`, so maybe changing the lambda that we build there is the right approach, until we do the proper fix of flowing IProperty into CreateGetValueExpression

2024-04-03 10:00 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                                        ? Default(typeof(IClrCollectionAccessor))
It's true we can do this to avoid the liftable constant, but is there a reason to do it? I mean, if you removed the check, you'd get a liftable constant that's sometimes null - seems like it would work just as well but with less code, no?

2024-04-03 10:09 UTC, roji commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +            // if constant is of interface type we blind guess it might be a service and try to resolve it
/cc @ajcvickers

2024-04-03 10:26 UTC, maumar commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
same problem as with converters - we don't (always) have access to IProperty when we generate code that uses JRWs

2024-04-03 10:57 UTC, roji commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
So yeah, IMHO the "right fix" would definitely be to plumb IProperty to wherever it is we generate code that needs to reference ValueConverters, JsonReaderWriters, or anything else that's "owned" by the property; anything else would unfortunately be hacky and brittle, effectively requiring us to inject quoting functionality into JsonValueReaderWriter - which is what ConstructorExpression does.

If that's unfeasible for this PR (too complex?), I'd maybe consider having JsonValueReaderWriter implement the same quoting interface as our SQL expressions (IRelationalQuotableExpression), since it's conceptually the same idea (though we'd probably want to rename it). Otherwise, we should at least make ConstructorExpression [Experimental] like the rest of the new precompilation-related APIs.

2024-04-04 07:01 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        // TODO: No, this must be a lifted constant, otherwise we re-instantiate on each query
this seems to be the problem for split query scenarios. _readerColumns object is initialized once per instance of `ShaperProcessingExpressionVisitor`, based on number of projections in the select expression. The individual elements in the array are filled with proper values in `CreateGetValueExpression` as we process the individual columns. 

What happens in the problematic case (split collection) when we go through shaper compilation (`ShaperCompilingExpressionVisitor`) is we generate outer `ShaperProcessingExpressionVisitor` (SPEV) to and call ProcessShaper. One of the output arguments to the ProcessShaper method is the readerColumns object, which will later be used to construct SplitQueryingEnumerable or PopulateSplitCollection call.

Inside ProcessShaper we visit the shaper expression, which happens to be `RelationalSplitCollectionShaperExpression`. Algorithm for dealing with it is to create another SPEV, which will process the inner shaper. As part of SPEV visitation we call into `CreateGetValueExpression` and fill _readerColumns with proper values. Then we visit ParentIdentifier using the current SPEV, and then visit ChildIdentifier using the inner SPEV we created to deal with inner shaper. However, since readerColumns in output parameter of  `innerSPEV.ProcessShaper`, so with LiftableConstant approach we `snapshot` it's value, but by that time we have only visited projections from the InnerShaper. Projections from the ChildIdentifier are yet to be seen, and the _readerColumn values for those is currently null. So that's what gets snapshotted.

In the lambda approach we are ok, because we build the lambda, but we only lazily generate actual Expression representing reader columns lazily when we are building a Call for `PopulateSplitCollection` or `SplitQueryingEnumerable`. 

To get away with LiftableConstant, we only need to generate the LiftableConstant after we have visited everything.

2024-04-05 23:57 UTC, maumar commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
@roji added logic to fish for Converter using IProperty when it's available. Did it in a separate commit so it's easier to review. Using IProperty works like a charm, but getting TypeMapping based on ClrType is quite unreliable. We still do it because AOT fails otherwise, but only as last resort. The logic I went with is, if the value expression (after plumbing the converters) contains a "forbidden" constant, we go for IProperty/TypeMapping strat, fetch converter from the type mapping and embed the delegate instead of the expression. However, if converter produces "clean" expression, we still do what we did before. 

I'm debating if it's even worth to use TypeMapping from clr type strat at all, or just let it fail. All our current tests pass with just old approach + IProperty for custom converters with captured variables, but the testing there is not thorough. Thoughts?

2024-04-06 06:10 UTC, maumar commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +    [ConditionalTheory(Skip = "AOT: NTS is not supported")]
The problem with NTS is that RelationalGeometryTypeMapping is "hiding" the converter in it's own property SpatialConverter and applies the conversion in the CustomizeDataReaderExpression step. From our perspective, the type doesn't have a converter so we can't even invoke the delegate (like we now do for custom converters that capture). Spatial converter itself captures geometry services, which is NTS specific service (that we don't know anything about either).

2024-04-06 06:12 UTC, maumar commented on src/Shared/ExpressionExtensions.cs
> +        => expression switch
I added TryGet, but also kept the original. Most of the uses assert that constant will be of that specific type, so idk if there's point in doing tryget that always succeeds.

2024-04-06 07:10 UTC, maumar commented on test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
> +    [ConditionalTheory(Skip = "AOT: NTS is not supported")]
I enabled the tests and just circumvented the constant check for the captured NTS object

2024-04-07 16:35 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                                        _ => JsonEncodedText.Encode(property.GetJsonPropertyName()!, null),
@maumar this liftable constant resolver expression captures `property`, which of course can't work; the constant validation infrastructure I wrote unfortunately didn't check that the resolver expressions themselves didn't contain any problematic constants - I pushed a commit to your PR which fixes that (so tests are failing now).

So the property has also has to become a liftable constant (as usual), inside the JsonEncodedText.Encode() liftable constant. I think ou have a similar problem just below, where you capture `innerShaperMapElement.Key`.

2024-04-07 18:11 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                        c => (RelationalTypeMapping)c.Dependencies.TypeMappingSource.FindMapping(type, c.Dependencies.Model, null)!,
Doing the same lookup for the regular/inline case would at least show us if there's a failing test where this logic isn't correct (this is in general why I prefer we avoid having different paths for regular vs. precompiled as much as possible).

2024-04-07 18:11 UTC, roji commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
So I think that in general, wherever we have an IProperty, using that is the right thing, and allows for whatever custom thing the user does, including captured variables or anything of the sort. So I'd go with that in any case wherever we have the property.

When we don't have a property is when things get interesting for me... First, I'm still curious which cases exist without a property, and with the type mapping not being the CLR default one - it would be good to at least have an idea. I admit that dumping the value expression is safest - when it's possible - but alternating between two strategies based on whether there's a "forbidden" constant is generally not great, since behavior suddenly changes in an unpredictable way just because the user e.g. captured something.

2024-04-08 04:11 UTC, maumar commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
The cases that break are almost always for uint mapping and some enums. We expect converter<unint, int>, but get <uint, long> instead

2024-04-08 04:14 UTC, maumar commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +            // TODO: this is not 100% reliable, see issue #33383
@roji any ideas to make this better?

2024-04-08 11:03 UTC, ajcvickers commented on src/EFCore/Metadata/FactoryMethodBinding.cs
> +    public FactoryMethodBinding(
@maumar Can you explain again why this needs to change? That is, why do we need to change to pass an Expression here? Is the liftable constant we need for the factory instance itself? Does it matter what is in there? Or am I missing the point again?

2024-04-08 11:11 UTC, ajcvickers commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +            // if constant is of interface type we blind guess it might be a service and try to resolve it
Unless I'm reading this wrong, it seems very specific to the implementation of proxies as a plugin. Do we have a general solution for plugins here?

2024-04-08 11:18 UTC, ajcvickers reviewed
Changes to `EntityMaterializerSource` seem okay.

2024-04-09 01:22 UTC, maumar commented on src/EFCore/Metadata/FactoryMethodBinding.cs
> +    public FactoryMethodBinding(
reverted

2024-04-09 01:23 UTC, maumar commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +            // TODO: this is not 100% reliable, see issue #33383
reverted

2024-04-09 09:01 UTC, maumar commented
@roji ready for the final peek, I removed all the changes not related to vanilla queries

2024-04-09 09:17 UTC, maumar commented on src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> +            // if constant is of interface type we blind guess it might be a service and try to resolve it
reverted all that code for now

2024-04-11 17:52 UTC, roji reviewed
This looks almost ready - see remaining comments, I don't think they're blocking if they're problematic (let's discuss if so).

2024-04-11 17:52 UTC, roji commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
So if I understand correctly, we don't have a clear idea at the moment of situations where there's no IProperty and the type mapping isn't the CLR default. Overall I think it's all OK for now, but let's have an issue tracking better support for type mapping in this precompiled world.

2024-04-11 17:52 UTC, roji commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonSqlHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
nit: wouldn't it be simpler here to just do Expression.Property(), rather than have a lambda above and extracting its Body?

(same for the other reader/writers)

2024-04-11 17:52 UTC, roji commented on src/EFCore/ChangeTracking/ValueComparer`.cs
> +    private readonly ConstructorInfo _constructorInfo
This looks like it always creates instances of `ValueComparer<T>`, rather than the specific class of the value comparer in question; for example, for CaseInsensitiveValueComparer we get `ValueComparer<string>` instead of the specific class.

Now, if such specific types are only about the equality/snapshot lambdas they contain, then it indeed doesn't matter much (that would raise the question of why we have specific types in the first place, rather than just use `ValueConverter<T>` everywhere...).

I guess we can go ahead with this for now, but we should at least track clearing up everything around converters/comparers/JsonValueReaderWriters (which is all basically about clearing up type mappings I think...).

/cc @ajcvickers

2024-04-11 17:52 UTC, roji commented on src/EFCore/ChangeTracking/ValueComparer.cs
> +    public abstract LambdaExpression ObjectEqualsExpression { get; }
This looks like it's used only for identifier comparison in the shaper, which boxes value types (see comment above). That's OK (this doesn't seem to make things worse), but long-term we want to get rid of this boxing...

/cc @ajcvickers

2024-04-11 17:52 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs
> -        private static bool CompareIdentifiers(IReadOnlyList<ValueComparer> valueComparers, object[] left, object[] right)
@maumar @ajcvickers just making sure - if my understand of this is correct, then we are boxing identifiers in the shaper when comparing them, right? This PR doesn't look like it changes that - just pointing it out.

2024-04-11 17:52 UTC, roji commented on src/EFCore/Query/LiftableConstantExpressionHelpers.cs
> +public class LiftableConstantExpressionHelpers
```suggestion
public static class LiftableConstantExpressionHelpers
```

2024-04-11 17:52 UTC, roji commented on src/EFCore/Query/LiftableConstantExpressionHelpers.cs
> +            IList list => IsCollectionOfLiterals(list),
Is this really a literal, in the sense that we support ConstantExpression of e.g. `List<int>`? For that matter, I'm not sure about the date/time/Guid types above either (though for these we can at least add support in the LINQ->C# translator)...

2024-04-11 17:52 UTC, roji commented on src/EFCore/Query/QueryCompilationContext.cs
> +    public virtual bool SupportsPrecompiledQuery => false;
[Experimental]

2024-04-11 17:52 UTC, roji commented on src/EFCore/Storage/Json/JsonBoolReaderWriter.cs
> +    private JsonBoolReaderWriter()
Any reason for this? Am not seeing this in the other reader/writers?

2024-04-11 17:52 UTC, roji commented on src/EFCore/Storage/Json/JsonBoolReaderWriter.cs
> +    [Experimental(EFDiagnostics.PrecompiledQueryExperimental)]
[Experimental] is inherited, so there shouldn't be a need to have these on overrides, unless I'm missing something...

2024-04-11 17:52 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        // TODO: No, this must be a lifted constant, otherwise we re-instantiate on each query
@maumar am not sure any more, is this resolved?

2024-04-11 18:59 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +        // TODO: No, this must be a lifted constant, otherwise we re-instantiate on each query
yes, just left unresolved, so that explanation is more visible

2024-04-11 19:09 UTC, maumar commented on src/EFCore/Storage/Json/JsonBoolReaderWriter.cs
> +    [Experimental(EFDiagnostics.PrecompiledQueryExperimental)]
hmm when looking at AttributeUsage on ExperimentalAttribute it states `Inherited = false`

2024-04-11 19:10 UTC, maumar commented on src/EFCore/Storage/Json/JsonBoolReaderWriter.cs
> +    private JsonBoolReaderWriter()
earlier experiments, removed

2024-04-11 21:13 UTC, maumar commented on src/EFCore/Query/LiftableConstantExpressionHelpers.cs
> +            IList list => IsCollectionOfLiterals(list),
removed List, it was throwing for some in memory tests, but now that InMemory is not part of the effort we should be fine, at least for now

2024-04-11 21:18 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                        property == null
already tracked here https://github.com/dotnet/efcore/issues/33447 - added the comment about nulls

2024-04-11 21:20 UTC, maumar commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                        property == null
We could actually do that already, by peeking into the value of original constant, but then CreateLiftableConstant would have to return an Expression rather than LiftableConstantExpression

2024-04-11 22:43 UTC, maumar commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonSqlHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
makes sense

2024-04-12 00:16 UTC, maumar commented
@roji updated with the latest feedback - all changes in separate commit for easier review

2024-04-12 07:07 UTC, maumar commented on src/EFCore.SqlServer.HierarchyId/Storage/Json/SqlServerJsonHierarchyIdReaderWriter.cs
> +    public override Expression ConstructorExpression => _instanceLambda.Body;
https://github.com/dotnet/efcore/issues/33517

2024-04-12 07:10 UTC, maumar commented on src/EFCore/ChangeTracking/ValueComparer`.cs
> +    private readonly ConstructorInfo _constructorInfo
from what I saw, all the code on comparers deriving from ValueComparer<T> is just helper methods for producing those three lambdas.

2024-04-12 14:20 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> +                        property == null
> but then CreateLiftableConstant would have to return an Expression rather than LiftableConstantExpression

That sounds perfectly OK to me... Would be a nice cleanup of the code.

2024-04-12 14:20 UTC, roji commented on src/EFCore/ChangeTracking/ValueComparer`.cs
> +    private readonly ConstructorInfo _constructorInfo
Yeah, I also didn't see other examples - I'm wondering if we shouldn't just get rid of those subtypes (/cc @ajcvickers)

2024-04-12 14:24 UTC, roji commented on src/EFCore/Storage/Json/JsonBoolReaderWriter.cs
> +    [Experimental(EFDiagnostics.PrecompiledQueryExperimental)]
Here's a minimal repro, the `child.Foo()` invocation below causes the following warning/error:

```
error XX001: 'Parent.Foo()' is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
```

```c#
var child = new Child();
child.Foo();

class Parent
{
    [Experimental("XX001")]
    public virtual void Foo()
        => throw new NotImplementedException();
}

class Child : Parent
{
    public override void Foo()
        => throw new NotImplementedException();
}
```

2024-04-12 14:27 UTC, roji approved these changes
LGTM, thanks @maumar!

Take a look at the remaining unresolved comments for final minor cleanup, but otherwise good to go!

2024-04-12 14:27 UTC, roji commented on src/EFCore/Query/LiftableConstantProcessor.cs
> +                || node.Type.Name == "ProxyFactory" || node.Type.Name == "Point")
nit:

```c#
                || node.Type.Name is "ProxyFactory" or "Point")
```

2024-04-12 23:13 UTC, merged

2024-04-13 07:23 UTC, roji commented
@maumar after rebasing the precompiled query PR (#33297) on top of this merged on, that PR build fails because of unsupported constant nodes (specifically ParameterBindingInfo, it seems). Can you please take a look?