Translate ToString() over enums
dotnet/efcore pull request #33706
Opened 2024-05-13 11:56 UTC by Danevandy99

Fixes #33635 and #20604

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

2024-05-16 00:57 UTC, Danevandy99 commented
@roji @cincuranet This is ready to review again.

2024-05-16 08:05 UTC, roji requested changes
In addition to the below comments, one more general note...

Translations where we duplicate an expression multiple times are problematic, since the expression may be arbitrarily complex. For example, if `instance` here is a complex subquery, that subquery would get evaluated by the database N times (once for each CASE); this is bad enough for perf that we refrain from translating in most such cases (e.g. entity equality).

At least for now, we should do the same here, i.e. perform the CASE/WHEN translation only when instance is a column or a parameter - can you please add that check?

2024-05-16 08:05 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
> +                    .Cast<object>()
Is this needed?

2024-05-16 12:38 UTC, Danevandy99 commented on src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
> +                return _sqlExpressionFactory.MakeUnary(ExpressionType.Convert, instance, typeof(string));
Yep! I did attempt to just return the instance without the cast, but ran into issues that seemed larger than the scope of this issue.

2024-05-16 12:40 UTC, Danevandy99 commented on src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
> +            && methodCallExpression.Method.Name != nameof(Nullable<int>.ToString))
Calling `ToString` on a nullable value type like an enum returns an empty string if the value is null, rather than null: https://learn.microsoft.com/en-us/dotnet/api/system.nullable-1.tostring?view=net-8.0 Without that check, the in-memory query returns null if the value of the nullable enum is null, rather than an empty string like C# usually does.

2024-05-17 01:20 UTC, Danevandy99 commented on src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
> +        if (instance.Type.IsEnum)
The existing methods handled by `StringMethodTranslator` are those called on string objects or on the string class (such as `string.IsNullOrEmpty`). Would it be better to rename `EnumHasFlagTranslator` to `EnumMethodTranslator` and include this code there? This would align with the fact that we are translating the `ToString` method called on an enum, similar to how we translate the `HasFlag` method on an enum.

2024-05-17 11:46 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
> +        if (instance.Type.IsEnum)
Yep, sounds good!

2024-06-03 05:14 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    // TODO: Unnecessary cast to string, #33733
I can this this PR introduces the Difficulty enum with an EnumToString value converter - but actual handling isn't implemented here (shouldn't this simply return the instance here?).

I'd prefer us to just finish the implementation for both issues in this PR, including the missing tests for the EnumToStringConverter case - no need to artifically do it in two PRs IMHO.

2024-06-03 05:14 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    return _sqlExpressionFactory.Case(cases, _sqlExpressionFactory.Constant(string.Empty, typeof(string)));
In .NET, you can assign any value to an enum:

```c#
var mood = (Mood)8;
Console.WriteLine(mood.ToString());
```

This prints out 8, i.e. if the numberic value doesn't match any of the enum's labels, a string containing the numberic representation is returned. It seems straightforward enough to implement the same in SQL, i.e. simply add a Convert node around the integer to turn it into a string - that seems more correct than arbitrarily returning an empty string.

2024-06-03 05:14 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    return _sqlExpressionFactory.Case(cases, _sqlExpressionFactory.Constant(string.Empty, typeof(string)));
Looking at this again, rather than having CASE/WHEN with many equality checks as this PR does:

```sql
SELECT CASE
    WHEN [w].[AmmunitionType] = 1 THEN N'Cartridge'
    WHEN [w].[AmmunitionType] = 2 THEN N'Shell'
...
```

... we can have the alternate form of CASE/WHEN, where a value is evaluated once and then compared against multiple values:

```sql
SELECT CASE [w].[AmmunitionType]
    WHEN 1 THEN N'Cartridge'
    WHEN 2 THEN N'Shell'
```

Aside from producing a tighter and more accurate SQL translation, this also means that the expression is only evaluated once - so we no longer need to check that the instance is a column or a parameter (i.e. [this comment of mine](https://github.com/dotnet/efcore/pull/33706#pullrequestreview-2059865253)).

This can be done simply by passing the instance as the first argument of `_sqlExpressionFactory.Case`.

2024-06-03 05:14 UTC, roji commented on src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
> +            && methodCallExpression.Method.Name != nameof(Nullable<int>.ToString))
See my new review comment about not returning an empty string as the default case, but rather a string representation of the integer enum value (which is what .NET does). If we do that, then the NULL should simply bubble out through the conversion, which I think is the behavior we want, right? If so, then this change shouldn't be necessary.

2024-06-03 05:15 UTC, roji requested changes
Thanks, this is starting to get close. I'll be available in the coming time to push this to completion (I was traveling quite a lot in recent weeks).

2024-06-03 12:40 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    return _sqlExpressionFactory.Case(cases, _sqlExpressionFactory.Constant(string.Empty, typeof(string)));
Oh cool, I didn't know that. Yes, returning a Convert node seems more correct.

2024-06-03 12:40 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    return _sqlExpressionFactory.Case(cases, _sqlExpressionFactory.Constant(string.Empty, typeof(string)));
Sweet. I'll make that change.

2024-06-03 12:47 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    // TODO: Unnecessary cast to string, #33733
This code does handle the EnumToStringConverter, but it can't just return the instance, because doing that causes issues later on in the translation when you translate something like ```myEnumProperty.ToString().Contains("string")```. Fixing that issue required changes in other unrelated areas of the codebase, and you made a new issue for this here: https://github.com/dotnet/efcore/issues/33733.

2024-06-03 12:50 UTC, Danevandy99 commented on src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
> +            && methodCallExpression.Method.Name != nameof(Nullable<int>.ToString))
Yes, the change you mentioned in your other comment seems like it should make this change unnecessary. I'll remove it and let you know if that doesn't end up working.

2024-06-03 13:42 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    && converterType.GetGenericArguments()[1] == typeof(int)
Sure thing - I don't think I meant int specifically (as opposed to numbers), but I can see how it could look that way.

2024-06-03 13:43 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    // TODO: Unnecessary cast to string, #33733
Ah sorry, I forgot about that, thanks - that's what happens when I take too much time to review etc.

2024-06-04 02:00 UTC, Danevandy99 commented
@roji GitHub wasn't letting me reply to this comment (https://github.com/dotnet/efcore/pull/33706#discussion_r1623792960), but the behavior we want is for the result to be an empty string if we call `ToString` on a nullable enum, since that's what C# does (https://learn.microsoft.com/en-us/dotnet/api/system.nullable-1.tostring?view=net-8.0). I tested it, and that change is still necessary, otherwise the code inside that if block bypasses the `ToString` call and just returns null instead of the empty string.

2024-06-04 05:53 UTC, roji requested changes
Good catch with the empty-string returning behavior of Nullable.ToString().

This is almost done - see some final comments. There are also some test failures.

2024-06-04 05:53 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +        = typeof(Enum).GetRuntimeMethod(nameof(Enum.HasFlag), new[] { typeof(Enum) })!;
```suggestion
        = typeof(Enum).GetRuntimeMethod(nameof(Enum.HasFlag), [typeof(Enum)])!;
```

2024-06-04 05:53 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +        = typeof(object).GetRuntimeMethod(nameof(ToString), new Type[] { })!;
```suggestion
        = typeof(object).GetRuntimeMethod(nameof(ToString), [])!;
```

2024-06-04 05:53 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                && converterType.IsGenericType)
nit: pattern matching can be used to simplify all this to:

```c#
        if (Equals(method, ToStringMethodInfo)
            && instance is { Type.IsEnum: true, TypeMapping.Converter: ValueConverter converter }
            && converter.GetType() is { IsGenericType: true } converterType)
```

This reduces a level of nesting from the code below.

2024-06-04 05:53 UTC, roji commented on test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
> +    WHEN "g"."Rank" = 0 THEN 'None'
This still needs to be updated (causes test failures)

2024-06-04 05:53 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                if (converterType.GetGenericTypeDefinition() == typeof(EnumToNumberConverter<,>))
nit: what we have here is a conceptual switch (checking for different values of converterType); I usually prefer doing the following that logic very clear:

```c#
switch (converterType)
{
    case not null when converterType.GetGenericTypeDefinition() == typeof(EnumToNumberConverter<,>):
        ...
    case not null when converterType.GetGenericTypeDefinition() == typeof(EnumToStringConverter<,>):    
        ...
}

2024-06-04 05:53 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                            _sqlExpressionFactory.Constant(string.Empty, typeof(string)));
nit: note that explicitly passing the type (`typeof(string)`) is unnecessary when the value cannot ever be null (`string.Empty`).

2024-06-04 05:53 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    if (instance is ColumnExpression { IsNullable: true })
Why restrict the coalescing behavior to when the instance is a column? For example, there could be some function returning a nullable int, shouldn't calling ToString() on that also coalesce the null to empty string? In other words, I'm proposing the coalesce be added whenever the instance type is a nullable enum.

Note that if ToString() is invoked over a constant or parameter, that would get evaluated client-side earlier in the query pipeline, so we'd never end up here in the first place.

2024-06-04 05:53 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +            && instance.Type.IsEnum)
Note that this doesn't match nullable enums (i.e. `typeof(SomeEnum?).IsEnum` returns false). You need to add a bit more pattern matching for that.

2024-06-04 11:55 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                && converterType.IsGenericType)
That does simplify things a lot. I need to look into pattern matching more.

2024-06-04 12:03 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    if (instance is ColumnExpression { IsNullable: true })
I didn't have a specific reason for restricting that to just columns, I just knew I wanted it to be applied on nullable numbers, and saw similar code in SqlServerObjectToStringTranslator. I'll change that so it checks whether the instance type is a nullable enum.

2024-06-04 12:14 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +            && instance.Type.IsEnum)
I ran the debugger on the tests for nullable enums that I had, and the value of `instance.Type` is just `SomeEnum`, rather than `Nullable<SomeEnum>`, so this should still let those nullable enums through.

2024-06-04 12:17 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    if (instance is ColumnExpression { IsNullable: true })
After debugging the nullable enum tests, I don't think we can just check whether `instance.Type` is a nullable enum. Since there are multiple expression classes that are nullable, it would be helpful to have an `INullableExpression` interface for those similar to the `IPrintableExpression` interface that allows us to easily use pattern matching here.

2024-06-04 13:24 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +            && instance.Type.IsEnum)
You're right - apologies, I forgot that we "normailze" nullable value types to their underlying types. So this should be fine.

2024-06-04 13:29 UTC, roji commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    if (instance is ColumnExpression { IsNullable: true })
You're right - apologies, I forgot that we "normailze" nullable value types to their underlying types. So this should be fine.

The question of determining whether an arbitrary expression is nullable or not is very complex, unfortunately - just today I opened #33889 with some thoughts on the matter. At this point, it simply isn't possible to know at this point of the query pipeline.

For now, I suggest just always adding the coalesce. We have #33890 which would optimize it away inside `_sqlExpressionFactory.Constant` when not needed, and in any case, this is the rare "else" arm which only happens when an "invalid" enum value is used, so it's not too bad to have the coalesce there.

2024-06-04 13:35 UTC, Danevandy99 commented on src/EFCore.Relational/Query/Internal/Translators/EnumMethodTranslator.cs
> +                    if (instance is ColumnExpression { IsNullable: true })
No worries. Always adding the coalesce sounds good. That seems better than accidentally missing a case where we do want it.

2024-06-04 14:41 UTC, roji approved these changes
Thanks for the quick turnaround and for the patience! LGTM.

2024-06-04 14:41 UTC, merged

2024-06-04 18:59 UTC, Danevandy99 commented
@roji Of course! Thanks for all your guidance. Is there anything I need to do for this to get it into a release build (I'm assuming it'll be in one of the .NET 9 previews)?

2024-06-04 19:07 UTC, roji commented
Nope, it's merged and will appear in a coming preview!

2024-06-05 11:37 UTC, Danevandy99 commented
Awesome, thanks!