TrimStart and TrimEnd with optional char array implementation for SQL Server
dotnet/efcore pull request #33715
Opened 2024-05-14 13:48 UTC by abdielcs

Fixes #22924

- [X ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ X] The code builds and tests pass locally (also verified by our automated build checks)
- [X ] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [X ] Tests for the changes have been added (for bug fixes / features)
- [X ] Code follows the same patterns and style as existing code in this repo

2024-05-14 14:03 UTC, abdielcs commented
@dotnet-policy-service agree

2024-05-14 22:06 UTC, abdielcs commented
Hi, I can't find which test failed or the log. It seems to be in EFCore.SqlServer.FunctionalTests, but since everything works fine in my local environment, it would be great to see which test failed in the CI for a clue. Any help would be appreciated.

2024-05-17 11:45 UTC, roji commented
/azp run

2024-05-24 09:09 UTC, cincuranet approved these changes

2024-05-24 09:13 UTC, cincuranet commented
@maumar or @roji  can I get 2nd set of eyes. Otherwise LGTM.

2024-05-26 16:46 UTC, roji requested changes
Thanks, here are some comments from me.

Note that there's also #22927 for Trim (as opposed to TrimStart/End) - it would be good to add this translation too (though it doesn't have to happen in the same PR).

2024-05-26 16:46 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +            throw new InvalidOperationException(compatibilityTooLowFunction(compatibilityLevel));
This would fail any queries using these functions with a low compatibility level; as @stevendarby [pointed out](https://github.com/dotnet/efcore/issues/22924#issuecomment-2093473994), this would be a breaking change if anyone is currently using these functions via client evaluation (in the final projection).

Ideally, we'd be able to log a translation failure here that would only get reported if the method call **isn't** in the final projection, to both avoid the breaking change and report an error when not in the final projection; but our error reporting infra doesn't yet support this.

So I **think** it makes most sense to simply not throw here for now, to allow client eval in the final projection, at the price of a slightly cryptic SQL Server error when this is used elsewhere on older databases.

2024-05-26 16:46 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +                var firstArgumentValue = (arguments[0] as SqlConstantExpression)?.Value as char[];
What happens if the argument isn't a constant? This looks like it would translate to a NULL, yielding incorrect results?

2024-05-28 19:36 UTC, abdielcs commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +            throw new InvalidOperationException(compatibilityTooLowFunction(compatibilityLevel));
So, I rolled back the throwing of the exception gracefully to avoid the breaking change.

2024-05-28 19:40 UTC, abdielcs commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +                var firstArgumentValue = (arguments[0] as SqlConstantExpression)?.Value as char[];
I decided to reuse the same code used in SQLite for resolve the Trim expressions, since it make sense. Is mostly the same code, I'm not sure if must be placed in some utility class for reusing code between providers, possibly not.

2024-05-28 19:49 UTC, abdielcs commented
> Thanks, here are some comments from me.
> 
> Note that there's also #22927 for Trim (as opposed to TrimStart/End) - it would be good to add this translation too (though it doesn't have to happen in the same PR).

Yes, I saw the Trim, but since it has a different syntax in the new version, it is unlikely that it can be done in the same way. So, @roji, if you agree, I would prefer to address it after finishing these.

For some reason, my SQLite tests are failing again. Maybe I'm doing something wrong in the merge or something?

2024-05-31 15:05 UTC, abdielcs commented
/azp run

2024-06-11 12:42 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
> +using Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal;
nit: Add empty line after using.

2024-06-11 12:42 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +                || TrimStartMethodInfoWithCharArrayArg.Equals(method))
nit: Missing indentation.

2024-06-11 12:42 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +            var charactersToTrim = new List<char>();
I think `StringBuilder` here would be better fit.

2024-06-11 12:43 UTC, cincuranet commented
/azp run

2024-06-19 07:37 UTC, cincuranet approved these changes

2024-06-19 13:31 UTC, roji requested changes

2024-06-19 13:31 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +            if (_sqlServerSingletonOptions.CompatibilityLevel >= 160)
This looks like it places the existing TrimStart translation - without args - inside the condition for the compatibility level, although that translation is fine for old versions; `LTRIM(x)` was always supported, `LTRIM(x, y)` is the new thing that's only supported in SQL Server 2022. So it seems like the compatibility level check should only apply when the argument isn't an empty array constant...

2024-06-20 20:28 UTC, roji approved these changes
Thanks, this is very close - see note below. I'll just go ahead and fix the remaining issue plus some cleanup.

Thanks for your contribution!

2024-06-20 20:28 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +                || (_sqlServerSingletonOptions.CompatibilityLevel >= 160
It's a bit of an annoying little detail, but the previous code did translate TrimStartMethodInfoWithCharArrayArg as long as the first argument is an empty array constant. I don't think it was an important thing to do, but once it's there I don't think we should be removing it (it's a very minor but also needless breaking change). So can we please preserve the previous behavior, and only put the new translation inside the CompatibilityLevel condition?

2024-06-20 20:44 UTC, maumar commented
I disabled auto merge, please check in after https://github.com/dotnet/efcore/pull/34043

2024-06-20 21:13 UTC, merged