Implement sum aggregation for `decimal` in SQLite
dotnet/efcore pull request #33721
Opened 2024-05-15 05:49 UTC by ranma42

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

2024-05-15 06:02 UTC, ranma42 commented
Some notes:
 - I ended up duplicating `CombineTerms` https://github.com/dotnet/efcore/blob/403ea8059096975b492fb14be477b3092a8dad4b/src/EFCore.Relational/Query/Internal/QueryableAggregateMethodTranslator.cs#L160-L180 It looks like most `IAggregateMethodCallTranslator` implementations are re-implementing this same operation, so it might be ok (even intentional to keep them independent), but I was not expecting it at first
 - I am not 100% confident about the handling of nullability:
   - in LINQ `.Sum` over an empty `decimal` enumerable returns a `decimal` `0`
   - in LINQ `.Sum` over an empty `decimal?` enumerable returns a `decimal?` `null`
   - in LINQ `.Sum` over a `decimal?` with some `null` would return `null` (I believe)
   being unsure, I replicated the handling of `SUM` https://github.com/dotnet/efcore/blob/403ea8059096975b492fb14be477b3092a8dad4b/src/EFCore.Relational/Query/SqlNullabilityProcessor.cs#L1394-L1403
 - adding/removing the `CombineTerms` step does not affect any of the existing tests; I plan to add at least a test that checks for that, but I might need some guidance in what is the best place to do so (should it be sqlite-specific or generic?)
 - adding/removing the nullability processing changes the SQL output, hence its effect is tested. OTOH, the results of the evaluation seem to pass regardless of that change, which might point out that additional tests are needed for that as well

2024-05-15 07:28 UTC, ranma42 commented
combined sum+avg as suggested in https://github.com/dotnet/efcore/pull/33720#issuecomment-2111757493
the max/min aggregation is left for a future PR as it might involve additional design around how to handle other types (`ulong`, `TimeSpan`, etc)

2024-05-28 09:11 UTC, cincuranet requested changes

2024-05-28 09:11 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlNullabilityProcessor.cs
> +            && string.Equals(resultFunctionExpression.Name, "ef_sum", StringComparison.OrdinalIgnoreCase))
I think, instead of handling it here, for SQLite, it could be handled where `CreateAggregate` for `ef_sum` is called and use the overload with `resultSelector`.

2024-05-28 09:11 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableAggregateMethodTranslator.cs
> +        {
Any reason why the 
```csharp
            if (sqlExpression is SqlFragmentExpression)
            {
                sqlExpression = _sqlExpressionFactory.Constant(1);
            }
```
is left out?

2024-05-28 10:00 UTC, ranma42 commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableAggregateMethodTranslator.cs
> +        {
the fragment is used to represent `*`, which should only be relevant for the `COUNT(*)` case

2024-05-28 10:13 UTC, ranma42 commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlNullabilityProcessor.cs
> +            && string.Equals(resultFunctionExpression.Name, "ef_sum", StringComparison.OrdinalIgnoreCase))
I am unsure if I understood your suggestion, in particular the "similar to `ef_avg`" part.

Currently `ef_avg` and `ef_sum` match the SQL semantics for (respectively) `AVG` and `SUM`.
In fact, the implementation of `ef_sum` is currently modeled that of `SUM`, including the nullability part, which matches
https://github.com/dotnet/efcore/blob/5eec48b0f0b48d011a79bedb446c73628a1f62aa/src/EFCore.Relational/Query/SqlNullabilityProcessor.cs#L1417-L1426

(in a similar way, `ef_avg` is modeled after `AVG`, which has no special nullability handling)

Should I make `ef_sum` implement the `IEnumerable.Sum` semantics instead (so that it never returns a null)?
I see this as making `ef_avg` and `ef_sum` less similar, but I can easily do that if that is what you recommend 😇

2024-05-28 12:14 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlNullabilityProcessor.cs
> +            && string.Equals(resultFunctionExpression.Name, "ef_sum", StringComparison.OrdinalIgnoreCase))
You're right. Better to keep it consistent across databases instead of having shortcuts for SQLite.

2024-05-28 12:15 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableAggregateMethodTranslator.cs
> +        {
Right. What was I thinking🤦‍♂️.

2024-05-28 12:15 UTC, cincuranet approved these changes

2024-05-28 12:16 UTC, cincuranet commented
@ranma42 Can you please resolve the conflict and then I can merge. Thanks.

2024-05-28 22:26 UTC, ranma42 commented
@cincuranet rebased 👍

2024-05-29 11:24 UTC, merged