Fix for #33702 Translation for the SQL Server PATINDEX function
dotnet/efcore pull request #33868
Opened 2024-06-01 14:40 UTC by smnsht

Fix for #33702 Translation for the SQL Server PATINDEX function

- [*] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [*] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [*] The code builds and tests pass locally (also verified by our automated build checks)
- [*] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2
```
- [*] Tests for the changes have been added (for bug fixes / features)
- [*] Code follows the same patterns and style as existing code in this repo

2024-06-01 16:43 UTC, ranma42 commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +                argumentsPropagateNullability: new[] { false, false },
according to the [documentation](https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql)
> If either pattern or expression is NULL, PATINDEX returns NULL.
apparently that is the only way PATINDEX can return null (if the pattern is not found, the result is 0)

you should be able to take advantage of nullability propagation here by setting:
```suggestion
                argumentsPropagateNullability: new[] { true, true },
```

I believe this should result in a (marginally) better query in your `PatIndex_null_pattern`

2024-06-02 08:15 UTC, roji requested changes

2024-06-02 08:15 UTC, roji commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +    /// <summary>
Please move this out of the "full text" region (as explained in the main issue, "full text" has a very specific meaning in the context of SQL Server, and this does not include PATINDEX.

2024-06-02 08:15 UTC, roji commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +    public static int? PatIndex(
The return value shouldn't be nullable, just like other EF.Functions method signatures on this class don't return nullable types, even though the corresponding SQL functions do return null when the arguments are null.

See https://github.com/dotnet/efcore/pull/33870#issuecomment-2143740875 and/or https://github.com/npgsql/efcore.pg/issues/3059#issuecomment-2028551770 for more context.

2024-06-02 08:15 UTC, roji commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +    public static int? PatIndex(
According to the [docs](https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver16&redirectedfrom=MSDN), PATINDEX returns bigint for `nvarchar(max)`, so `int` isn't correct here. Since on the C#/.NET side we don't have the distinction between `nvarchar(max)` and `nvarchar(x)` (both are .NET strings), I think method will need to always return long.

2024-06-02 08:15 UTC, roji commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +        [NotParameterized] string collation)
PATINDEX does not have a collation parameter - please remove this overload.

You likely added this because of [this example](https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver16&redirectedfrom=MSDN#e-using-collate-with-patindex):

```c#
SELECT PATINDEX ( '%ein%', 'Das ist ein Test'  COLLATE Latin1_General_BIN) ;  
```

The `COLLATE Latin1_General_BIN` here isn't a parameter, but rather a general SQL expression which can be added on any string, anywhere in SQL. To express that with LINQ, you can already do the following:

```c#
EF.Functions.PatIndex('x', EF.Functions.Collate('y', "Latin1_General_BIN")
```

2024-06-02 08:15 UTC, roji commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +        object propertyReference,
Why is this an object, as opposed to a string?

2024-06-02 08:15 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +            if (!(pattern is SqlParameterExpression || pattern is SqlConstantExpression))
Why these checks? Does SQL Server not support PATINDEX where the pattern isn't a parameter or constant? For example, can't the pattern be a column, or a concatenation of a parameter and a constant?

Same for below - why does "propertyReference" need to be a column? Can't it be a concatenation of two columns, for example?

2024-06-02 08:15 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +                argumentsPropagateNullability: new[] { false, false },
Yes, PATINDEX is [clearly documented](https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver16) as propagating nulls for both its parameters:

```
If either pattern or expression is NULL, PATINDEX returns NULL.
```

So the `false` here are incorrect, and should be `true` instead.

2024-06-02 18:33 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +        object propertyReference,
I implemented **PatIndex** following the same approach as the 2 fulltext extensions - **FreeText** and **Contains** - the second argument must be entity field.

2024-06-02 18:38 UTC, roji commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +        object propertyReference,
@smnsht have you checked whether PATINDEX actually requires a column (i.e. entity field)? I'm 99% sure it doesn't.

As I wrote before, full-text search really is a very specific feature of SQL Server that isn't related to PATINDEX in any way.

2024-06-02 18:44 UTC, smnsht commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +            if (!(pattern is SqlParameterExpression || pattern is SqlConstantExpression))
​1 ***pattern*** param - got it

2 **propertyReference** - similar to **FreeText**, nothing else

​Will remove both checks.

2024-06-02 18:50 UTC, smnsht commented
I will try to fix this as soon as possible, but it likely won't happen before Friday.

2024-06-02 20:09 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +        object propertyReference,
@roji 
Nop, PATINDEX does not require a column... This will work: 
`SELECT position = PATINDEX('%ter%', 'interesting data');`
[learn.microsoft.com....](https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver16)

I could not imagine why and where to use this query in the context of any ORM.

Just my bad. I will repair it.

2024-06-02 20:36 UTC, roji commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +        object propertyReference,
> I could not imagine why and where to use this query in the context of any ORM.

That particular query indeed doesn't make much sense (it it doesn't reference any data from the database). But you may want to perform PATINDEX e.g. over a concatenation of a column and a constant, or even on the result of some arbitrary function which itself reads some column.

Basically the function operates on expressions, regardless of where they come from (column, constant, parameter, more complex expression tree...).

2024-06-07 10:45 UTC, smnsht commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +                argumentsPropagateNullability: new[] { false, false },
Fixed

2024-06-07 10:46 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +    /// <summary>
@roji 
moved out of "full text" region

2024-06-07 10:47 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +    public static int? PatIndex(
@roji 
return value altered to **long**

2024-06-07 10:48 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +    public static int? PatIndex(
@roji 
fixed

2024-06-07 10:49 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +        [NotParameterized] string collation)
@roji 
overload with collation removed

2024-06-07 10:49 UTC, smnsht commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +            if (!(pattern is SqlParameterExpression || pattern is SqlConstantExpression))
@roji 
checks removed

2024-06-07 12:58 UTC, roji requested changes

2024-06-07 17:14 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +    ///     A DbFunction method stub that can be used in LINQ queries to target the SQL Server <c>PATINDEX</c> store function.
@roji 
fixed

2024-06-07 17:15 UTC, smnsht commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs
> +        if(PatIndexMethodInfo.Equals(method))
@roji fixed

2024-06-07 17:15 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +        Assert.Throws<InvalidOperationException>(() => EF.Functions.PatIndex("%test%", "teststring"));
@roji 
removed

2024-06-07 17:15 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public void PatIndex_with_collate_term()
@roji 
removed

2024-06-07 17:16 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public void PatIndex_multiple_predicates()
@roji 
removed

2024-06-07 17:16 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public void PatIndex_through_navigation()
@roji 
removed

2024-06-07 17:16 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public void PatIndex_through_navigation_with_collate_terms()
@roji 
removed

2024-06-07 17:17 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_not_throws_when_using_non_column_for_property_reference()
@roji 
removed

2024-06-07 17:37 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_null_expression()
@roji 
Before getting rid of coalescing, I can explain what I am trying to do here.

Coalescing logic in SqlServerStringMethodTranslator was altered to handle the situation. 
When **expression** in  **PATINDEX ( '%pattern%' , expression )**  is a nullable column or **PATINDEX ( NULL , expression)**, coalescing kicks in.

In the test (renamed to **PatIndex_nullable_column_coalesced_to_zero()**) EF.Functions.PatIndex applied on nullable column '**Region**' with pattern %WA%. There are 91 rows in the table, 3 rows with region WA, and the rest with Region set to other region(s) or NULL. I am expecting to retrieve 88 rows with region other then WA or NULL, and generated SQL should  wrap **PATINDEX** with **COALESCE**.

2024-06-08 17:41 UTC, smnsht commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +                c => EF.Functions.PatIndex(null, c.FirstName) == 0)
@roji 
test removed

2024-06-09 16:25 UTC, smnsht commented on src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
> +
@roji 
done

2024-06-09 16:25 UTC, smnsht commented on src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
> +
@roji 
done

2024-06-12 12:39 UTC, cincuranet commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_literal()
@roji @maumar do you think it would be valuable to add test where the first argument is not literal but column (however stupid that is in terms of _Employees_ table) - i.e. `EF.Functions.PatIndex(c.Whatever, c.FirstName)`?

2024-06-13 07:10 UTC, maumar commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_literal()
we could, more tests is (almost) always better. FunkyData has the appropriate data (e.g. stuff like `%B%`). This could also test how this works with chars like `%` and `_` in the expression, rather than pattern

2024-06-13 11:21 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_literal()
I think it's good to have a reason for different testing of literal vs. parameter vs. column for specific cases, rather than just doing it without reason. For example, I definitely do it when the translation code differs, but when the function translation doesn't care (as in this case), I don't... Otherwise we in theory need to do it for each and every argument of every function translation we do, and IMHO it doesn't actually add any coverage value...

2024-06-13 11:23 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_literal()
Re testing for wildcards with funky data, remember that this is an EF.Functions translation, so our job here is just to pass the string that the user gives us to the database, nothing more; this is very different from translations like string.StartsWith(), where we're the ones translating to LIKE, and so we have to concern ourselves with wildcard problems etc. So IMHO it's basically similar to the point above - if our translation doesn't care or do anything about wildcards, I'm not sure we need to add test coverage for them...

2024-06-13 11:25 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_literal()
Let me know what you think of the above - we can/should definitely discuss if you have other views! Otherwise this PR looks good to me - am going to approve but will wait for your feedback before merging.

2024-06-13 11:25 UTC, roji approved these changes
@smnsht thanks, LGTM!

2024-06-13 11:34 UTC, cincuranet commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> +    public async Task PatIndex_literal()
SGTM

2024-06-13 18:20 UTC, smnsht commented
@roji 
thanks for your patience

2024-06-14 07:44 UTC, maumar approved these changes

2024-06-14 07:45 UTC, merged

2024-06-14 07:46 UTC, cincuranet commented
@smnsht Thanks.