Support vector search on Cosmos DB
dotnet/efcore pull request #33991
Opened 2024-06-14 12:02 UTC by ajcvickers

Fixes #33783

 This PR introduces:

 - `IsVector()` to configure a property to be configured as a vector (embedding) in the document.
   - The distance function and dimensions are specified.
   - The data type can be specified, or otherwise is inferred.
 - `HasIndex().ForVectors()` to configure a vector index over a vector property.
 - `VectorDistance()` which translates to the Cosmos `VectorDistance` function
   - The distance function and data type are taken from the property mapping, or can be overridden.

 Known issues:

 - Float16 (Half) is not working in Cosmos--needs investigation
 - Exception on int array case--could be EF or Cosmos--needs investigation
 - Owned types mess up the materialization--this will be fixed by the ReadItem improvements I am working on

2024-06-14 12:08 UTC, ajcvickers commented on src/EFCore.Cosmos/EFCore.Cosmos.csproj
> -    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.40.0" />
Don't merge until we know more about timing of releases here. Also, the C.I. will need the emulator running with preview features enabled.

2024-06-14 12:55 UTC, cincuranet commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector1,
Does it make sense to have `T` here? Shouldn't we specify explicitly supported types or at least use generic math i.e. `INumber`/`IFloatingPoint`/etc.? Although it would fail at runtime if I used i.e. `IEnumerable<DateTime>`, it looks weird to allow it.

2024-06-14 12:56 UTC, cincuranet commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector2,
Do both vectors need to be same data type? I could call `VectorDistance` on `float32`s and `int8`s, isn't it?

2024-06-14 12:59 UTC, roji commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector2,
I don't actually think that's a thing in vector search - AFAIK the vector types must correspond... But maybe worth checking for Cosmos?

2024-06-14 13:04 UTC, roji commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector1,
Yeah, good point. We could even go even narrower, and have overloads for concrete types that are supported by Cosmos (one for each specific type).

Also about enumerable... In most vector SDKs (and in SK) we've centered around `ReadOnlyMemory<float>` (and friends) as the standard representation for vectors; this is nice because it allows easy slicing, and also even passing in non-heap memory without copying etc. This may be related to how the vector data is actually sent to the database when it's parameterized: if it's just sent as a JSON array (as text), this matter less, but if it's encoded efficiently (binary), then this may matter more.

BTW just for comparison, do we allow mapping to SQL Server `varbinary` via `IEnumerable<byte>` (as opposed to `byte[]`)? It's a bit similar, though may not completely (i.e. if Cosmos actually sends the data as a JSON array string).

2024-06-14 13:27 UTC, ajcvickers commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector1,
> Yeah, good point. We could even go even narrower, and have overloads for concrete types that are supported by Cosmos (one for each specific type).

All that Cosmos cares about it that there is JSON array with some numbers in it. Those numbers can come from any type. So we could restrict it numerically, although this would be the first time we have done so.

> ReadOnlyMemory<float>

We could restrict to this, but it would be basically arbitrary. All we need for Cosmos is a list of numbers.

> BTW just for comparison, do we allow mapping to SQL Server varbinary via IEnumerable<byte> (as opposed to byte[])? It's a bit similar, though may not completely (i.e. if Cosmos actually sends the data as a JSON array string).

Yes.

2024-06-14 13:29 UTC, ajcvickers commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector2,
They could be different, since all that matters is that a list of numbers come out at the end.

2024-06-14 14:11 UTC, luisquintanilla commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector1,
cc: @michaelgsharp @tannergooding @eiriktsarpalis for awareness. Maybe the patterns introduced in Tensor / TensorPrimitives may be relevant here.

2024-06-14 18:28 UTC, Pilchie commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector1,
There's actually a whole other thread about an `Embedding<T>` type that we might be able to use here someday, but not yet.  I think there the idea is to use `ReadOnlySpan<T>` most of the time, but there are interesting cases around bitpacked embeddings, half types, base64 encoded binary representations of vectors, etc.

2024-06-14 18:40 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector2,
Is there a reasonable scenario where the types need to be different?

2024-06-14 20:22 UTC, roji commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector2,
> They could be different, since all that matters is that a list of numbers come out at the end.

Even if that technically works on the Cosmos SDK side, I think actually doing this is very likely to be a developer error and could lead to skewed/wrong results...

2024-06-15 10:51 UTC, ajcvickers commented
@roji I added a JSON fragment expression, as we discussed.

2024-06-15 17:34 UTC, roji requested changes
Looks pretty good! See mainly nits.

Probably a good idea for @AndriySvyryd to take a look for the metadata/model and CosmosClientWrapper stuff.

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosQuerySqlGenerator.cs
> -    private static JToken? GenerateJToken(object? value, CoreTypeMapping typeMapping)
👍

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
> +                (CosmosTypeMapping?)sqlExpression.TypeMapping!.ElementTypeMapping!) is { } primitiveCollectionTranslation)
Here and in most other places where a cast is added, is it really important to check the the type mapping is CosmosTypeMapping? The code won't call actual methods on CosmosTypeMapping so it doesn't seem like it would care, so I'm not sure...

If we do want the casts, in this particular call site you can simply replace the `{ }` with CosmosTypeMapping.

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
> +        var elementTypeMapping = (CosmosTypeMapping?)_typeMappingSource.FindMapping(elementClrType)!;
Rather than adding all the casts, should we instead simply override FindMapping in CosmosTypeMappingSource to return CosmosTypeMapping (covariant return types)?

Maybe we can even do a similar thing for CosmosTypeMapping.ElementTypeMapping etc. (with `new`)

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
> +            CosmosTypeMapping typeMapping = null)
Just noting that we don't really have to change CoreTypeMapping->CosmosTypeMapping everywhere (i.e. where no actual CosmosTypeMapping API is needed), could simplify the code.

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
Unless I'm mistaken, there's nothing about this expression type that requires it to contain JSON - it's just an arbitrary query fragment that gets integrated into the NoSQL. So maybe call this FragmentExpression or CosmosFragmentExpression (and rename the Json property)?

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
Implement IPrintableExpression, also add the following (currently missing on various other expression types):

```c#
[DebuggerDisplay("{Microsoft.EntityFrameworkCore.Query.ExpressionPrinter.Print(this), nq}")]
```

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
Not sure this should extend SqlExpression - this doesn't have to actually represent a scalar (i.e. with a type mapping) - in fact it doesn't in this PR - and should never participate in type inference etc. I know that the relational SqlFragmentExpression implements SqlExpression, we should look into changing that.

When deriving directly from Expression you need to add a couple things (like override Type, NodeType...), you can take a look at one of the other non-SqlExpression types (like ObjectAccessExpression).

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Translators/CosmosVectorSearchTranslator.cs
> +            bruteForce = sqlExpressionFactory.Constant(false, (CosmosTypeMapping)typeMappingSource.FindMapping(typeof(bool))!);
When the type mapping is the default one (as here), you don't need to find it manually - `SqlExpressionFactory.Function()` (below) automatically applies the default type mapping to its arguments.

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Translators/CosmosVectorSearchTranslator.cs
> +            bruteForce = (SqlConstantExpression)arguments[3];
nit: can simplify:

```suggestion
            bruteForce = arguments[3] as SqlConstantExpression
                ?? throw new InvalidOperationException(
                    CosmosStrings.ArgumentNotConstant("useBruteForce", nameof(CosmosDbFunctionsExtensions.VectorDistance)));
```

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Translators/CosmosVectorSearchTranslator.cs
> +            typeof(double));
Technically it's a good idea to manually set the return type mapping, since we know exactly what the function returns (e.g. from the docs), and that allows e.g. a parameter/literal compared to the function result to get correctly inferred. Of course in Cosmos it's not very important, more for the principle of it.

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/ContainerProperties.cs
> +public readonly record struct ContainerProperties(
🎉

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
> +                // Model validation will ensure there is only one property.
Nit: assert instead of comment?

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
> +        // A provider should typically not override this because using the property directly causes problems with Migrations where
👍

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
> +        }
nit:

```suggestion
        if (mapping is not null
            && property.FindAnnotation(CosmosAnnotationNames.VectorType)?.Value is CosmosVectorType vectorType)
        {
            mapping = new CosmosVectorTypeMapping(mapping, vectorType);
        }
```

2024-06-15 17:34 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/CosmosVectorTypeMapping.cs
> +        = new(typeof(byte[]), new CosmosVectorType(DistanceFunction.Cosine, 0, VectorDataType.Int8));
Doesn't matter much, but change to float[] as the more usual "default"?

2024-06-15 17:34 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        var inputVector = new sbyte[] { 2, 1, 4, 6, 5, 2, 5, 7, 3, 1 };
nit: I've personally switched to collection initializers:

```suggestion
        sbyte[] inputVector = [2, 1, 4, 6, 5, 2, 5, 7, 3, 1];
```

2024-06-15 17:34 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +                e => EF.Functions.VectorDistance(e.DoubleArray, inputVector, false, DistanceFunction.DotProduct, VectorDataType.Float32))
```suggestion
                e => EF.Functions.VectorDistance(e.DoubleArray, inputVector, useBruteForce: false, DistanceFunction.DotProduct, VectorDataType.Float32))
```

2024-06-15 17:34 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        // Assert.Equal(3, booksFromStore.Count);
👀

2024-06-15 17:34 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        var inputVector = new List<int>
nit: one line (here and below)?

2024-06-15 17:34 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        // public Owned1 OwnedReference { get; set; } = null!;
Yeah, for completeness good to have at least one test doing vector search on an owned (but a smoke test should also be good enough for now).

2024-06-17 08:52 UTC, ajcvickers commented on src/EFCore.Cosmos/Extensions/CosmosIndexBuilderExtensions.cs
> +    public static IndexBuilder ForVectors(this IndexBuilder indexBuilder, VectorIndexType? indexType)
We made indexes a core feature so that we could use them in places like this. From what I have seen of the other possible index specification in Cosmos, I still think it makes sense to go this way.

2024-06-17 08:54 UTC, ajcvickers commented on src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
> +        ulong dimensions,
I went back and forth on this, and I'm still not sure. `ulong` is definitely silly, but is what the Cosmos SDK uses. I'm happy to make it an int, and that would be more consistent with .NET APIs in general.

2024-06-17 09:03 UTC, ajcvickers commented on src/EFCore.Cosmos/Storage/Internal/CosmosVectorTypeMapping.cs
> +        = new(typeof(byte[]), new CosmosVectorType(DistanceFunction.Cosine, 0, VectorDataType.Int8));
This is intentionally invalid. There is no reasonable default.

2024-06-17 09:52 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
The signature for function mapping requires arguments to be SqlExpressions, or am I missing something? (I know the type mapping is not needed here, but looking at other SqlExpressions, that's also the case. So, happy to do what you want here, just not sure what that is.

2024-06-17 10:02 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/Translators/CosmosVectorSearchTranslator.cs
> +            bruteForce = (SqlConstantExpression)arguments[3];
How does this check if the constant expression has a bool value as opposed to some other type?

2024-06-17 10:10 UTC, ajcvickers commented on src/EFCore.Cosmos/Storage/Internal/CosmosVectorTypeMapping.cs
> +        = new(typeof(byte[]), new CosmosVectorType(DistanceFunction.Cosine, 0, VectorDataType.Int8));
I added a comment. Do you think that I should file a bug?

2024-06-17 10:13 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        // public Owned1 OwnedReference { get; set; } = null!;
Yeah, this doesn't work--I mentioned this in the known issues. I get translation failures as soon as there is an owned type.

2024-06-17 10:15 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        // Assert.Equal(3, booksFromStore.Count);
Yes, this throws. See above and in the known issues.

2024-06-17 10:16 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        var inputVector = new List<int>
Is this codified somewhere?

2024-06-17 10:17 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +                e => EF.Functions.VectorDistance(e.DoubleArray, inputVector, false, DistanceFunction.DotProduct, VectorDataType.Float32))
Can't use a named argument in an expression tree...

2024-06-17 11:03 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
IPrintableExpression is implemented by the base class, and that attribute is also added on the base class. Is there some reason it needs to be on this class too? What am I missing?

2024-06-17 18:08 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
Yeah, as discussed offline, SqlFunctionExpression indeed currently requires SqlExpression - but this is already being changed in #33998 (see https://github.com/dotnet/efcore/pull/33998/files#diff-5c18e71a908ba6f85e2e434c3e503c3c71066e683729f6070b2a2a8ae872c9e0R23). Like in Cosmos, `ARRAY_LENGTH()` accepts an array of anything, including of JSON objects (i.e. structural types); such an array is  most definitely not a SqlExpression (it doesn't have a type mapping etc.).

Yet another way where a document database differs from relational, where functions generally accept only scalars...

2024-06-17 18:09 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/CosmosVectorTypeMapping.cs
> +        = new(typeof(byte[]), new CosmosVectorType(DistanceFunction.Cosine, 0, VectorDataType.Int8));
Nah, it doesn't really matter...

2024-06-17 18:10 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +                e => EF.Functions.VectorDistance(e.DoubleArray, inputVector, false, DistanceFunction.DotProduct, VectorDataType.Float32))
Ah right, makes sense.

2024-06-17 18:11 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
> +        var inputVector = new List<int>
You mean as a style guide? I don't think so - just seems to make sense (`[1, 2, 3...]`)

2024-06-19 14:19 UTC, roji commented on src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
> +        ulong dimensions,
Ah I see... No, I think you're right - our job is ultimately to expose whatever Cosmos "supports", so ulong sounds right.

2024-07-03 10:30 UTC, ajcvickers commented
@Pilchie What is the new guidance here given that the latest SDK has made all the code to configure vector indexes and embeddings internal?

2024-07-30 17:41 UTC, ajcvickers commented on src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
> +        IEnumerable<T> vector1,
Filed #34320 for `ReadOnlyMemory` support. We will discuss constraining the generic type in the next design meeting.

2024-07-30 17:43 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
@roji Do we need to do anything here for 9?

2024-07-30 17:44 UTC, ajcvickers commented
This has been updated to the latest SDK and the container configuration has been made to throw. Verified that all the tests pass if the container has already been created.

2024-08-05 04:11 UTC, samuelbarrionuevo commented on src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
> +    public static PropertyBuilder<TProperty> IsVector<TProperty>(
> If we decide to constrain the types supported (as per [this conversation](https://github.com/dotnet/efcore/pull/33991/files#r1639785281)), we may want to do the same here.

2024-08-05 08:24 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Expressions/JsonFragmentExpression.cs
> +public class JsonFragmentExpression(string json) : SqlExpression(typeof(string), CosmosTypeMapping.Default)
Ideally this shouldn't extend SqlExpression (and it should be possible/easy in the latest bits), but I definitely don't think it's a blocker for 9.0 - we can always make that change when a case comes up where a non-SqlExpression fragment is needed.

2024-08-05 22:30 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
> +        // => _executionStrategy.ExecuteAsync(this, DeleteDatabaseOnceAsync, null, cancellationToken);
❗

2024-08-05 22:41 UTC, AndriySvyryd approved these changes
Add a test to `CompiledModelCosmosTest`

2024-08-06 13:59 UTC, ajcvickers commented
@roji This is now constrained.

2024-08-09 11:41 UTC, roji approved these changes
LGTM.

As discussed offline, we really should deliver this feature with support for arrays as well (e.g. `float[]`). Maybe the best way forward is to build in support for it in this PR for the type mapping side and have failing tests for the query translation, which I'd work on fixing after rc1 (given feature work stops in a few days).

BTW at what level is Half (float16) not supported? Is the Cosmos SDK the blocking one here? If the intention is for it to be supported soon, it may be worth just implementing it on our side and letting Cosmos/the SDK fail, since it'll be harder to add it in later.

2024-08-09 11:41 UTC, roji commented on src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
> +    }
nit:

```suggestion
        => Enum.IsDefined(distanceFunction)
            ? new CosmosVectorType(distanceFunction, dimensions)
            : throw new ArgumentException(
                CoreStrings.InvalidEnumValue(distanceFunction, nameof(distanceFunction), typeof(DistanceFunction)));
```

2024-08-09 11:41 UTC, roji commented on src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
> +    public static void SetVectorType(this IMutableProperty property, CosmosVectorType? vectorType)
BTW does Cosmos actually support nullable vector properties? Might be worth checking

2024-08-09 11:41 UTC, roji commented on src/EFCore.Cosmos/Properties/CosmosStrings.resx
> +    <value>The type '{clrType}' is being used as a vector, but the vector data type cannot be inferred. Only 'ReadOnlyMemory&lt;byte&gt;, ReadOnlyMemory&lt;sbyte&gt;, and ReadOnlyMemory&lt;float&gt;
As discussed offline, arrays should also work.

2024-08-09 11:41 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
> +    }
nit:

```suggestion
        // A provider should typically not override this because using the property directly causes problems with Migrations where
        // the property does not exist. However, since the Cosmos provider doesn't have Migrations, it should be okay to use the property
        // directly.
        => base.FindMapping(property) switch
        {
            CosmosTypeMapping mapping when property.FindAnnotation(CosmosAnnotationNames.VectorType)?.Value is CosmosVectorType vectorType
                => new CosmosVectorTypeMapping(mapping, vectorType),

            var other => other
        };
```

2024-08-12 10:48 UTC, merged