Add SqlServer DATEPART support for Microsecond and Nanosecond properties.
dotnet/efcore pull request #34135
Opened 2024-07-01 19:00 UTC by CRFricke

Support added for Datetime, DateTimeOffset, TimeOnly, and TimeSpan.
Fixes #13481

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

2024-07-01 19:04 UTC, CRFricke commented
@dotnet-policy-service agree

2024-08-05 23:20 UTC, CRFricke commented
PR awaiting review. Also, the Cosmos test runs are awaiting approval.

2024-10-08 08:42 UTC, cincuranet commented
This looks good @CRFricke, I just pushed few, basically, formatting tweaks. I'll merge after the CI finishes.

2024-10-08 21:00 UTC, roji requested changes

2024-10-08 21:00 UTC, roji commented on test/EFCore.Specification.Tests/Query/DatepartQueryTestBase.cs
> +public abstract class DatepartQueryTestBase<TFixture> : QueryTestBase<TFixture>
Do we need a full test suite only to test Datepart? We already have lots of very similar tests in both in NorthwindWhereQueryTestBase (e.g. Where_datetime_second_component), though the Northwind data indeed doesn't contain data with microsecond etc. We also have GearsOfWarQueryTestBase (e.g. Where_datetimeoffset_now), where it should be easy to add the data we need, rather than adding a whole new test suite.

I'm also noting that Datepart is the name of a SQL Server function, and in no way universal (e.g. PostgreSQL has no DATEPART function), so it doesn't seem right to use that name in core specification tests.

2024-10-08 21:04 UTC, roji commented on test/EFCore.Sqlite.FunctionalTests/Query/DatepartQuerySqliteTest.cs
> +    public override Task OrderBy_timespan_nanosecond_component(bool async)
What's the goal of having tests for OrderBy and OrderByDescending? We usually test translations via simple Where(), and in some cases, we also have Select() to make sure that the type mapping is correct in the projected translation result.

2024-10-09 02:06 UTC, CRFricke commented on test/EFCore.Specification.Tests/Query/DatepartQueryTestBase.cs
> +public abstract class DatepartQueryTestBase<TFixture> : QueryTestBase<TFixture>
Initially, I tried adding valid non-zero Microsecond and Nanosecond values to existing table rows in both the Northwind & GearsOfWar databases. This failed miserably (the existing tests failed). After spending good week trying to make the existing tests as well as new ones work, I decided to regroup and go the full test suite route.

I took another look tonight and see that the existing Northwind & GearsOfWar Millisecond tests use a value of "0". I will do the same for the Microsecond and Nanosecond tests and remove the Datepart test suite.

2024-10-09 02:14 UTC, CRFricke commented
Apparently, at some point after my last commit, the SQLite DateTime.Millisecond conversion began rounding up rather than truncating when the Microsecond value is GE 500.

I will be reworking the tests as noted above. This should eliminate the test failures.

2024-10-09 02:44 UTC, CRFricke commented on test/EFCore.Sqlite.FunctionalTests/Query/DatepartQuerySqliteTest.cs
> +    public override Task OrderBy_timespan_nanosecond_component(bool async)
I usually write a test for every use case I can think of (they say there's no such thing as too many tests).

If you're saying that OrderBy and OrderByDescending will always end up in the same code path that Where() does when generating the T-SQL clause, then there no need for the extra tests. (I haven't been in the EFCore code anywhere near long enough to know.)

I'm happy to remove the extra tests if that's the case.

2024-10-09 10:35 UTC, roji commented on test/EFCore.Specification.Tests/Query/DatepartQueryTestBase.cs
> +public abstract class DatepartQueryTestBase<TFixture> : QueryTestBase<TFixture>
Thank you... I'm not asking for this in order to be annoying, but adding test suites for each translation/feature can very quickly get out of hand, and we're already in a place where we have lots of suites around the place, without a clear system/reason and lots of duplication etc.

Yeah, changing test data can indeed lead to existing tests failing - that can be problematic. Adding new rows with the new data should hopefully be less invasive (though there are no guarantees).

If you get stuck on this or find yourself doing a huge change, please let us know - we may be able to help with some ideas.

2024-10-09 10:39 UTC, roji commented on test/EFCore.Sqlite.FunctionalTests/Query/DatepartQuerySqliteTest.cs
> +    public override Task OrderBy_timespan_nanosecond_component(bool async)
> they say there's no such thing as too many tests

Unfortunately that's not quite true, tests do have a maintenance cost (and sometimes a runtime cost as well), and with a project of EF's size this can get significant.

So yes, we do make certain assumptions for testing translations: there's no need to test each translation with each and every LINQ operator (OrderBy, OrderByDescending, Where, Join...). Where() is usually the easiest operator to use (e.g. as it's easy to test that it gets the single row you want), and that's really sufficient.

For full coverage, we also have a test projecting the result of the translation out of the database (so Select()), to ensure that the resulting type and type mapping is correct (these usually don't matter for Where(), which is why just testing that isn't sufficient - but we're far from systematic on this).

2024-10-09 12:24 UTC, cincuranet commented
As it turns out this implementation is not correct, because it does not take into account the differences between C# behavior (the value is 0-999) and the SQL/[T-SQL](https://learn.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql?view=sql-server-ver16#fractional-seconds).

Because I'm already here, rework it and create new PR #34861.

2024-10-09 12:24 UTC, closed without merging