Stop including the discriminator in the JSON id by default
dotnet/efcore pull request #34208
Opened 2024-07-11 13:57 UTC by ajcvickers

Fixes #34179

There are also new APIs on the entity type and model builders to facilitate optional behaviors, including reverting to the pre-9 behavior:

- Entity<Blog>().IncludeDiscriminatorInJsonId();
- Entity<Blog>().IncludeRootDiscriminatorInJsonId();
- Entity<Blog>().AlwaysCreateShadowIdProperty();

Note that this change requires regeneration of the Northwind database.

2024-07-11 18:44 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                throw new InvalidOperationException(CosmosStrings.NoIdKey(entityType.DisplayName(), idProperty.Name));
Why do we no longer require that the property mapped to `id` should be part of a key?

2024-07-11 18:47 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                                entityType.DisplayName(), partitionKeyPropertyName, idProperty.Name));
Same question for partition key

2024-07-11 18:53 UTC, ajcvickers commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                throw new InvalidOperationException(CosmosStrings.NoIdKey(entityType.DisplayName(), idProperty.Name));
Why should we?

2024-07-11 18:53 UTC, ajcvickers commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                                entityType.DisplayName(), partitionKeyPropertyName, idProperty.Name));
Likewise.

2024-07-11 19:05 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                throw new InvalidOperationException(CosmosStrings.NoIdKey(entityType.DisplayName(), idProperty.Name));
This is part of the 1:1 mapping to `id` approach that we decided to pursue

2024-07-11 19:08 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                                entityType.DisplayName(), partitionKeyPropertyName, idProperty.Name));
`id` in conjunction with the partition key form a unique identifier, we need this information in our model to be able to respect this constraint.

2024-07-11 19:11 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            && !entityType.IsOwned() // Reactions required for: IForeignKeyOwnershipChangedConvention
Also `IForeignKeyRemovedConvention`

2024-07-11 19:17 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
Why isn't `jsonIdProperty` removed instead?

2024-07-11 19:18 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    entityTypeBuilder.Metadata.RemoveProperty(computedIdProperty);
Use `HasNoProperty` and remove `ConfigurationSource` check

2024-07-11 19:19 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            // IPropertyAddedConvention, IPropertyRemovedConvention
Duplicate

2024-07-11 19:23 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            var alwaysCreateId = entityType.GetAlwaysCreateShadowIdProperty() ?? entityType.Model.GetAlwaysCreateShadowIdProperty();
Move `entityType.Model.GetAlwaysCreateShadowIdProperty()` check inside `entityType.GetAlwaysCreateShadowIdProperty()`

2024-07-11 19:27 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            ProcessEntityType(entityType, context);
This should run only for entity types that don't have `CosmosAnnotationNames.AlwaysCreateShadowIdProperty` set.

2024-07-11 19:31 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +        if (entityType.BaseType == null // Reactions required for: IEntityTypeBaseTypeChangedConvention
Invert `if`

2024-07-11 19:34 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            case CosmosAnnotationNames.AlwaysCreateShadowIdProperty:
Don't run if old value is `null` and new value is the same as `entityType.Model.GetAlwaysCreateShadowIdProperty()`

2024-07-11 19:55 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinition.cs
> +            AppendValue(DiscriminatorEntityType.FindDiscriminatorProperty()!, DiscriminatorEntityType.GetDiscriminatorValue());
Store DiscriminatorProperty and DiscriminatorValue instead of DiscriminatorEntityType

2024-07-11 20:06 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
This is wrong, we shouldn't use partition key properties

2024-07-11 20:08 UTC, ajcvickers commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                throw new InvalidOperationException(CosmosStrings.NoIdKey(entityType.DisplayName(), idProperty.Name));
No, it isn't. The 1:1 mapping approach is about having a convention that does a 1:1 mapping when it can.

If the developer doesn't specify any explicit mappings, then `id` will come from a key. If they explicitly set it to be something else, then we let them. Just making it part of a key doesn't force Cosmos semantics anyway, so it won't fix any fundamental mapping errors.

2024-07-11 20:10 UTC, ajcvickers commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                                entityType.DisplayName(), partitionKeyPropertyName, idProperty.Name));
Again, by convention, we include the partition key in the primary key. But I don't think we should be forcing the partition keys into an EF key if the user has specified something else. There is no reason they _need_ to be part of a key defintion.

2024-07-11 20:11 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
What makes it safe to remove?

2024-07-11 20:11 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            // IPropertyAddedConvention, IPropertyRemovedConvention
This applies to the code below, not the code above.

2024-07-11 20:12 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            ProcessEntityType(entityType, context);
Why?

2024-07-11 20:13 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinition.cs
> +            AppendValue(DiscriminatorEntityType.FindDiscriminatorProperty()!, DiscriminatorEntityType.GetDiscriminatorValue());
Why?

2024-07-11 20:13 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
Why?

2024-07-11 20:50 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
I assume that this was done to support the legacy case where the PR was the partition key and the values were also included in the `id`. This could still be the case if `DiscriminatorInKeyBehavior.EntityTypeName` was specified, but we should also add `DiscriminatorInKeyBehavior.EntityTypeNameOnly` for which we wouldn't add the partition key values

2024-07-11 23:02 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                                entityType.DisplayName(), partitionKeyPropertyName, idProperty.Name));
We should require them to be part of the PK so that `Find` works as expected.

2024-07-11 23:10 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            // IPropertyAddedConvention, IPropertyRemovedConvention
It's still already contained in the next line

2024-07-11 23:14 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
This condition - `!jsonIdProperty.GetConfigurationSource().OverridesStrictly(ConfigurationSource.Convention)`

Otherwise, we'd just end up with useless unmapped properties in the model

2024-07-11 23:15 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            ProcessEntityType(entityType, context);
Perf

2024-07-11 23:16 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            case CosmosAnnotationNames.AlwaysCreateShadowIdProperty:
This should run only for entity types that don't have `CosmosAnnotationNames.AlwaysCreateShadowIdProperty` set.

2024-07-11 23:17 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            ProcessEntityType(entityType, context);
You should be able to remove this method entirely

2024-07-11 23:18 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinition.cs
> +            AppendValue(DiscriminatorEntityType.FindDiscriminatorProperty()!, DiscriminatorEntityType.GetDiscriminatorValue());
Perf

2024-07-12 00:13 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
We should validate that for all entity types in the same hierarchy, mapped to the same container the value of `GetDiscriminatorInKey` is the same

2024-07-12 00:16 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
And `AlwaysCreateShadowIdProperty` should only be allowed on the root entity type.

2024-07-12 00:20 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosKeyAugmenterConvention.cs
> -    private static void ProcessIdProperty(IConventionEntityTypeBuilder entityTypeBuilder)
What makes this non-static?

2024-07-12 04:01 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosKeyAugmenterConvention.cs
> +                var keyContainsPartitionProperties = false;
Rename to `keyContainsAllPartitionProperties` and invert values

2024-07-12 04:03 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosKeyAugmenterConvention.cs
> +            if (ConfigurationSource.Convention.Overrides(primaryKey.GetConfigurationSource()))
Merge with above and invert

2024-07-12 04:44 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                            entityTypeBuilder.Metadata.RemoveProperty(computedIdProperty);
Use `RemoveUnusedImplicitProperties`

2024-07-12 04:50 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                var keyProperty = (IConventionProperty?)idDefinition.Properties.FirstOrDefault();
Move inside the `if`

2024-07-12 10:27 UTC, roji commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                                entityType.DisplayName(), partitionKeyPropertyName, idProperty.Name));
This probably intersects with the question of whether to introduce a Cosmos–specific, which requires passing the partition key (this has come up several times).

2024-07-12 16:47 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
If it can't be removed then call `ToJsonProperty(null)`

2024-07-12 16:53 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    && jsonIdProperty.GetConfigurationSource().OverridesStrictly(ConfigurationSource.Convention))
Check JsonProperty ConfigurationSource instead

2024-07-12 16:53 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +
The above 2 blocks should be moved out and placed after the outer block. If there's explicit configuration we shouldn't do anything

2024-07-12 16:59 UTC, AndriySvyryd requested changes
How do we make sure that the Northwind database is recreated on the CI with the new values and is also correctly recreated with the old values when code from an older branch runs?

2024-07-12 21:06 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Extensions/CosmosEntityTypeBuilderExtensions.cs
> +    ///     <see langword="true" /> to force __id creation, <see langword="false" /> to not force __id creation,
Briefly describe when it would still be created for the `false` value

2024-07-12 21:11 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +
Also, we shouldn't be removing these properties if we end up recreating them below.

2024-07-12 21:14 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                ProcessEntityType(propertyBuilder.Metadata.DeclaringType.ContainingEntityType, context);
Only if the old or new value is `IdPropertyJsonName`

2024-07-12 21:28 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> +            }
Consider throwing if the value isn't equal to the discriminator value

2024-07-12 22:41 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> -            && (!jsonIdProperties.Contains(discriminatorProperty) || !_entityType.GetDerivedTypes().Any())
Is it really safe to remove this condition when id contains a non-root discriminator value?

2024-07-13 11:21 UTC, ajcvickers commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> -                                entityType.DisplayName(), partitionKeyPropertyName, idProperty.Name));
I agree we should push people to include them in the key. That's what the convention does, and also the warning/error if they explicitly define a primary key that does not contain the partition keys. But forcing them to be in the _PK_ is extreme--we don't even do that currently; we allow an alternate key that covers them. This is useless for find.

I don't know if we need the new Find overload now, as opposed to telling people they can only use Find if they have not moved the partition keys out of the PK. It certainly doesn't seem critical to me.

2024-07-13 11:27 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
The condition checks whether a property assigned to JSON id has been configured explicitly. If it has, then we reset the mapping to the JSON property. But because we're doing this in the convention, if that mapping has been made explicitly, then it will be a no-op and it won't be changed. This leaves the explicitly mapped property in place without the convention mapped property name.

Please explain, in detail, like I just did, how you think this code works. Otherwise your terse comments are meaningless, because they don't align with how I think the code works.

2024-07-13 11:27 UTC, roji commented
> How do we make sure that the Northwind database is recreated on the CI with the new values and is also correctly recreated with the old values when code from an older branch runs?

IMHO that's another good reason to not rely on a persistent database in CI, but rather to just use the emulator, where it's guaranteed to be recreated each time (I think we agreed we want to go in that direction anyway, possibly except for specific RBAC tests which can't be executed with the emulator?).

If we do want to stay with non-emulator tests, we could simply recreate the database each time, but on Ci only (to avoid making local runs slow), e.g. by checking the CI environment variable.

2024-07-13 11:31 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> -        if (discriminatorProperty is not null
Is it correct to remove this? Doesn't removing this mean that when the discriminator is part of the id, and there's no predicate check (because there's **currently** only one entity type), we wouldn't do ReadItem?

2024-07-13 11:36 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> -        if (discriminatorProperty is not null
If that's true, then it means I don't understand this code.

2024-07-13 11:41 UTC, ajcvickers commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
I'll do, but can you explain the real value we get from doing this?

2024-07-13 11:42 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            // IPropertyAddedConvention, IPropertyRemovedConvention
I'll move the comments to make it easier to see what they refer to.

2024-07-13 11:43 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    && jsonIdProperty.GetConfigurationSource().OverridesStrictly(ConfigurationSource.Convention))
Why? If there is a property mapped to JSON ID already, then we don't wat to change it. Please explain in detail why you think this change is needed.

2024-07-13 11:45 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +
- Please explain in more detail what you mean by this. "If there's explicit configuration we shouldn't do anything" Explicit configuration of what? And what should we not be doing explicitly?

2024-07-13 11:46 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                            entityTypeBuilder.Metadata.RemoveProperty(computedIdProperty);
Can you explain, in detail, when it is safe to call RemoveUnusedImplicitProperties. When I looked at the code, it didn't seem safe to use here.

2024-07-13 11:47 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            case CosmosAnnotationNames.AlwaysCreateShadowIdProperty:
Please explain in detail why this would be correct?

2024-07-13 11:48 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            ProcessEntityType(entityType, context);
Only if something  reacts to the ownership change. I didn't see anything, but I will double check.

2024-07-15 17:26 UTC, AndriySvyryd commented
> IMHO that's another good reason to not rely on a persistent database in CI, but rather to just use the emulator, where it's guaranteed to be recreated each time (I think we agreed we want to go in that direction anyway, possibly except for specific RBAC tests which can't be executed with the emulator?).

We need to do https://github.com/dotnet/efcore/issues/19973 first

> If we do want to stay with non-emulator tests, we could simply recreate the database each time, but on Ci only (to avoid making local runs slow), e.g. by checking the CI environment variable.

That would still not work for tests from old branches. We'd need to rename the database.

2024-07-17 00:00 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
The current code checks whether `__id` or a property mapped to `id` has been configured explicitly, if so then it tries to reset the mapping for the property mapped to `id` if it wasn't configured explicitly and tries to remove the `__id` property if it wasn't configured explicitly.
Otherwise, it proceeds to mapping a property to `id`.

1. However, the configuration source of the `__id` property shouldn't impact the resulting configuration. In general, our conventions should apply the same logic independently of how a property or facet they depend on was configured. E.g. a property called "Id" should be discovered as the PK whether it was found by convention or added explicitly.
2. Likewise, the configuration source of the property mapped to `id` shouldn't impact any of the logic below. The relevant part is the configuration source of the JSON mapping for this property. E.g. if we happen to map a PK property to `id` in the logic below and then that property becomes configured explicitly we should still keep it mapped to `id`.

2024-07-17 00:00 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    && jsonIdProperty.GetConfigurationSource().OverridesStrictly(ConfigurationSource.Convention))
See https://github.com/dotnet/efcore/pull/34208/files/e748e744dee11ec17a123e9cddbb77bbf231f5e8#r1680189105

2024-07-17 00:10 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                            entityTypeBuilder.Metadata.RemoveProperty(computedIdProperty);
`RemoveUnusedImplicitProperties` is safer, it checks that the property is in shadow state, was configured using Convention and is not referenced elsewhere.

In general, conventions shouldn't use Metadata API to perform changes, it's error-prone.

2024-07-17 00:12 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +
After you've addressed https://github.com/dotnet/efcore/pull/34208/files/e748e744dee11ec17a123e9cddbb77bbf231f5e8#r1680189105 this comment can be disregarded

2024-07-17 00:15 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                            entityTypeBuilder.Metadata.RemoveProperty(computedIdProperty);
After trying to remove `computedIdProperty` we should reset JSON mapping for `jsonIdProperty` if it's still in the model.

2024-07-17 00:16 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                .Metadata;
All of these can return `null`
```suggestion
            computedIdProperty = entityTypeBuilder
                .Property(typeof(string), DefaultIdPropertyName, setTypeConfigurationSource: false)
                ?.ToJsonProperty(IdPropertyJsonName)
                ?.IsRequired(true)
                ?.HasValueGeneratorFactory(typeof(IdValueGeneratorFactory))
                ?.Metadata;
```

2024-07-17 00:18 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            computedIdProperty.SetAfterSaveBehavior(PropertySaveBehavior.Throw);
Use `AfterSave` instead

2024-07-17 00:26 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +        }
Currently the code does this:

- If the entity type is the base document root with a configured PK
  - If GetAlwaysCreateShadowIdProperty is not true then we try to map the only PK property that is not a partition key if it's compatible
  - Otherwise, we configure `__id` to map to `id`

However, we should also react to when the preconditions change and undo the mapping.

- If the entity type is **not** the base document root with a configured PK
  - If GetAlwaysCreateShadowIdProperty is not true and the only PK property that is not a partition key is compatible we should reset its JSON mapping
  - Otherwise, we try to remove `__id`
    - If that fails we reset its JSON mapping, requiredness, ValueGeneratorFactory and AfterSaveBehavior

2024-07-17 00:31 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            case CosmosAnnotationNames.AlwaysCreateShadowIdProperty:
Because for entity types that have `CosmosAnnotationNames.AlwaysCreateShadowIdProperty` set the value of `AlwaysCreateShadowIdProperty` on the model is irrelevant, it's ignored. So, running the convention again wouldn't result in any change, since it would have the same inputs.

2024-07-17 00:34 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
> can you explain the real value we get from doing this?

It's the same value that we get from validating that a base property isn't ignored on a derived type. It's very likely a user error and an exception is expected when an explicit configuration is going to be ignored.

2024-07-17 10:52 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
So what happens in a case like this:

```C#
    public class Customer
    {
        public int Id { get; set; }

        [Key]
        public string Key { get; set; } = null!;
    }
```

The convention will initially create an `__id` property mapped to `id`. But then `Key` becomes the primary key, which means it gets mapped to `id` directly. So, in this case the `__id` should no longer exist, and the convention must remove it. But it would be wrong to remove `__id` if they have mapped it explicitly. In this case, we should remove the mapping to `id`, otherwise we have two different properties mapped to `id`.

So, can you explain the steps the convention would take to get to this model:

```
Model: 
  EntityType: Customer
    Properties: 
      Key (string) Required PK AfterSave:Throw
      Discriminator (no field, string) Shadow Required AfterSave:Throw
      Id (int) Required
      __jObject (no field, JObject) Shadow BeforeSave:Ignore AfterSave:Ignore ValueGenerated.OnAddOrUpdate
    Keys: 
      Key PK
```

from the code above, using the logic you are proposing?

2024-07-17 10:55 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
No. This is the case where the primary key and the partition key are the same property.

2024-07-17 13:24 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
So what should `id` include then? There are no other properties mapped to it.

2024-07-17 13:25 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            case CosmosAnnotationNames.AlwaysCreateShadowIdProperty:
That makes sense. Thanks for the details.

2024-07-17 13:31 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
This is that logic. Please be specific about which annotations change in the model and when they change in the process

2024-07-17 13:33 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
For DiscriminatorInKeyBehavior.None it would have the partition keys
For DiscriminatorInKeyBehavior.EntityTypeName it will include  the discriminator and the partition keys
For DiscriminatorInKeyBehavior.EntityTypeNameOnly it will only have the discriminator

2024-07-17 13:41 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
What I am saying is that we should separate this logic and only handle that case once we've found a compatible PK to map. We can get on a call when I get back

2024-07-17 13:45 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
When we get to this line, primaryKeyProperties contains all properties that are part of the primary key but are not also partition key properties. If this is not empty, then we are done because parition key properties should not be part of the id. On the other hand, if it is empty, then it means that the PK properties are also mapped to the partition key. We don't  do this by convention, but if this is the explicit configuration we are given, then we respect it, and include PK properties in the id so that there is some id. The only real scenario for this is legacy when the same property has been used for both the PK and the partition key.

(Btw, this has nothing to do with the discriminator behavior, which is orthogonal.)

2024-07-17 13:46 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
And other than being your preference, what is better about that?

2024-07-17 14:15 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +                    jsonIdProperty.Builder.ToJsonProperty(null);
The benefit is that we won't remove a property just to add it back later if the PK is not compatible. Adding a property triggers many conventions and could be expensive. Also, doing it in a convention that reacts to properties being added risks creating an endless loop.

2024-07-17 17:51 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> -        if (discriminatorProperty is not null
@roji What test can I write that will fail if this is wrong?

2024-07-17 17:52 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> -            && (!jsonIdProperties.Contains(discriminatorProperty) || !_entityType.GetDerivedTypes().Any())
@AndriySvyryd @roji What test can I write here that will fail with the current code?

2024-07-18 09:45 UTC, ajcvickers commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            ProcessEntityType(entityType, context);
Filed #34244

2024-07-18 15:18 UTC, ajcvickers commented
> How do we make sure that the Northwind database is recreated on the CI with the new values and is also correctly recreated with the old values when code from an older branch runs?

Decided to take a simple approach for now; change the database name. This will be Northwind2. This allows easy moving between branches that use the old verse new database.

2024-07-18 15:42 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> +            }
@AndriySvyryd What test can I write here that will fail with the current code?

2024-07-18 17:10 UTC, ajcvickers commented
@roji @AndriySvyryd New version up attempting to follow Andriy's guidance.

2024-07-23 16:38 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> -        if (discriminatorProperty is not null
Added tests to verify this scenario.

2024-07-23 16:38 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> -            && (!jsonIdProperties.Contains(discriminatorProperty) || !_entityType.GetDerivedTypes().Any())
Added tests to verify this scenario.

2024-07-23 16:39 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/CosmosReadItemAndPartitionKeysExtractor.cs
> +            }
Added tests to verify this scenario.

2024-07-23 17:59 UTC, ajcvickers commented
@roji This is now updated with fixes for discriminator checking and more tests. Can you check the test baselines to make sure you think we are doing `ReadItem` or not as appropriate? I commented on each test case where we don't do `ReadItem` indicating why not for that case.

2024-07-26 20:08 UTC, roji reviewed
Hey, here's a review of the ReadItemPartitionKey tests only. The actual behavior seems correct to me (i.e. I haven't noticed a case where we do ReadItem when we shouldn't or vice versa). So below see mainly some comments about the structure/factoring of these tests.

As a general comment, there's maybe a bit more systematic duplication of tests across various scenarios than I'd have personally done... This is definitely a matter of personal style/taste on how to test: more black box-style "cover all permutations" vs. more white-box "think about specific scenarios you want/need to cover" (I lean much more in the latter direction). For example, do we think we need all the duplication along the only/non-only axis, as well as everything on the leaf. I'm also noting that there seem to be relatively few tests which actually differ across the different implementations (e.g. HierarchicalPartitionKeyEntity is practically identical across all versions).

But I think it's all OK, hopefully it doesn't cost us in terms of maintainability/complexity.

Regardless FYI it took me a while to understand all the test factoring here and realize what extends from what and why :) It makes sense to me now, but maybe a comment on each test class to explain what it's there for could be useful for our future selves.

2024-07-26 20:08 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryDiscriminatorInIdTest.cs
> +        // This one _is_ ReadItem because SharedContainerEntity2Child is a leaf type.
I think this points to possibly removing SharedContainerEntity2Child; I wrote these inheritance tests within the same single test suite, but you're handling inheritance by splitting across test class implementations - doing both seems a bit duplicated/inconsistent

2024-07-28 10:42 UTC, ajcvickers commented
> As a general comment, there's maybe a bit more systematic duplication of tests across various scenarios than I'd have personally done... This is definitely a matter of personal style/taste on how to test: more black box-style "cover all permutations" vs. more white-box "think about specific scenarios you want/need to cover" (I lean much more in the latter direction). 

I very much believe that if I only do "white box" testing, then I will ship significantly more bugs. This is based on my experience of writing tests in this way and frequently finding a bug in a scenario I had never even thought of. So, at least for people of my ability, this will be a trade off for the advantages of having fewer tests against us shipping more bugs.

2024-07-28 10:44 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryDiscriminatorInIdTest.cs
> +        // This one _is_ ReadItem because SharedContainerEntity2Child is a leaf type.
I haven't done anything explicitly to improve testing for shared containers. Some of my tests use shared containers, but if these tests were written to cover some specific aspect of shared containers, then that was not something I considered. So, up to you if you think they should be removed.

2024-07-28 10:47 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryNoDiscriminatorInIdTest.cs
> +    public override async Task Multiple_incompatible_predicate_comparisons_cause_no_ReadItem_with_only_partition_key_leaf()
I'm not fully following. We currently have cases for non-inheritance, which is nominally "leaf" since there is no "tree", inheritance where the entity being fetched is the base type, and inheritance where the entity is a leaf type. Are you saying we should combine two of these cases?

2024-07-28 10:48 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryTest.cs
> +        // This could be ReadItem because all primary key values have been supplied, but it is a weird corner case.
Do you think we should write code to support this? I thought about it, but additional code to optimize a bizarre scenario seemed to be negative value to me, since we have additional code that nobody could possibly ever need?

2024-07-28 10:49 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryInheritanceTestBase.cs
Are you asking me to put them in a subfolder? Happy to do so, if that's what you want.

2024-07-28 10:50 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryNoDiscriminatorInIdTest.cs
> +                .HasDiscriminator<string>("Discriminator").IsComplete();
Will remove.

2024-07-28 10:51 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryFixtureBase.cs
> +            .IncludeRootDiscriminatorInJsonId()
I didn't change the shared container tests. As mentioned in another comment, I can remove them if you think the scenarios you added them for are now covered by other tests. Or we could move them to another test suite, but that's expensive.

2024-07-28 10:59 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosFixture.cs
> +        modelBuilder.Entity<Animal>().ToContainer("Animals");
They either need to be in separate containers, or we need to change the form of the test data, since as it stands, putting these in the same container results in JSON id collisions by default. I believe we could instead specify that the discriminator should be included in the id, if you think that's better. Or I can implement the test suite multiple times with different id and container configs. Of course, that's more "black box" testing. ;-) You choose.

2024-07-28 10:59 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
> +            modelBuilder.IncludeDiscriminatorInJsonId();
Because otherwise the test data results in conflicts in the JSON id values.

2024-07-28 11:00 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
> +ORDER BY c["id"]
Will invesigate.

2024-07-28 11:01 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryTestBase.cs
> +    public virtual Task Predicate_with_only_hierarchical_partition_key()
Happy to do it this way if you prefer. Just let me know.

2024-07-28 11:09 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
> +        Assert.Equal($"{item.Id}", id);
Here, `id` is a string, and `Id` is a GUID.

2024-07-28 11:20 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryNoDiscriminatorInIdTest.cs
> +                .HasPartitionKey(h => new { h.PartitionKey1, h.PartitionKey2, h.PartitionKey3 })
Moved to inheritance base class.

2024-07-28 11:25 UTC, ajcvickers commented on test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
> +ORDER BY c["id"]
Species is mapped directly to `id` because it is a single string primary key.

```C#
modelBuilder.Entity<Plant>().HasKey(e => e.Species);
```

2024-08-01 18:14 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            Console.WriteLine();
👀

2024-08-01 18:39 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +        computedIdPropertyBuilder.AfterSave(PropertySaveBehavior.Throw);
Use the newly returned builder if not `null` as the current `computedIdPropertyBuilder` might not be in the model anymore.
Something like `computedIdPropertyBuilder = computedIdPropertyBuilder.IsRequired(true) ?? computedIdPropertyBuilder;`

2024-08-01 18:43 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +        Check.DebugAssert(computedIdPropertyBuilder != null, "Expected to create/get compatible property builder.");
`DefaultIdPropertyName` might be explicitly ignored, so we need to handle the `null` case

2024-08-01 18:51 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +        computedIdPropertyBuilder.AfterSave(PropertySaveBehavior.Throw);
This is low priority though, as I don't think it's possible to hit this case currently

2024-08-01 21:26 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +            ProcessEntityType(entityType, context);
Ah, I see what's happening here, there's indeed a convention type missing.

As a workaround change `entityType.IsOwned()` to `entityType.GetForeignKeys().Any(fk => fk.IsOwnership)` in this file and in `JsonIdDefinitionFactory`

2024-08-01 21:53 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
> +        => ProcessEntityType(typeBaseBuilder.Metadata.ContainingEntityType, context);
Check that the entity type is still in the model.
```suggestion
    {
        if (!typeBaseBuilder.Metadata.IsInModel)
        {
            return;
        }
        
       ProcessEntityType(typeBaseBuilder.Metadata.ContainingEntityType, context);
   }
```

Also, in other `*Removed` methods.

2024-08-01 22:03 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> +            primaryKeyProperties = entityType.GetPartitionKeyProperties().ToList();
> and include PK properties in the id so that there is some id. The only real scenario for this is legacy when the same property has been used for both the PK and the partition key.

Right, but we don't have to include the PK properties in the id if the discriminator is going to be included.

We don't need to add this option for 9 though.

2024-08-01 22:13 UTC, AndriySvyryd commented on test/EFCore.Cosmos.FunctionalTests/ModelBuilding/CosmosModelBuilderGenericTest.cs
> +            modelBuilder.Entity<Customer>().HasAnnotation(CosmosAnnotationNames.AlwaysCreateShadowIdProperty, true);
Add a test extension instead of calling `.HasAnnotation` directly

2024-08-01 22:16 UTC, AndriySvyryd commented on test/EFCore.Cosmos.FunctionalTests/ModelBuilding/CosmosModelBuilderGenericTest.cs
> -                entity.GetKeys().First(k => k != entity.FindPrimaryKey()).Properties.Select(p => p.Name));
Assert that there are no other keys instead

2024-08-01 22:18 UTC, AndriySvyryd commented on test/EFCore.Cosmos.FunctionalTests/ReadItemTest.cs
> +﻿
👀

2024-08-01 22:19 UTC, AndriySvyryd approved these changes
There aren't any blocking issues

2024-08-02 15:36 UTC, merged

2024-08-03 08:52 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryNoDiscriminatorInIdTest.cs
> +    public override async Task Multiple_incompatible_predicate_comparisons_cause_no_ReadItem_with_only_partition_key_leaf()
Let's discuss in our next 1:1

2024-08-03 08:55 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryTest.cs
> +        // This could be ReadItem because all primary key values have been supplied, but it is a weird corner case.
No, not really - seems fine. Was mainly wondering what the precise scenario is where we don't transform...

2024-08-03 08:56 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryInheritanceTestBase.cs
Yeah that was the idea

2024-08-03 08:57 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/ReadItemPartitionKeyQueryTestBase.cs
> +    public virtual Task Predicate_with_only_hierarchical_partition_key()
Let's maybe revisit another time, especially as this is already merged

2024-08-03 08:58 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
> +ORDER BY c["id"]
Ah, makes sense - thanks!

2024-08-03 08:59 UTC, roji commented on test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
> +        Assert.Equal($"{item.Id}", id);
Ah, in that case I prefer ToString rather than "degenerate" interpolated string, but no big deal.