Translate Order & OrderDescending
dotnet/efcore pull request #34282
Opened 2024-07-24 18:08 UTC by bricelam

Hello, dear friends.

I tried to use these and they didn't work, so instead of screaming, "Freakin' Microsoft! This issues is two years old! What are they even working on?! Don't they have infinite resources?! I could implement it in like five minutes!" I decided to submit a PR. 😜

Fixes #28634

2024-07-24 18:10 UTC, bricelam commented on src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
>              visitedExpression = TryConvertEnumerableToQueryable(methodCallExpression);
Need a query expert to help with this. Is there a way to write a query using the Enumerable.Order method? If so, will my rewriting handle that?

2024-07-27 12:38 UTC, roji requested changes
Hey @bricelam 👋 ❤️ 

Looks good! See minor suggestions below.

2024-07-27 12:38 UTC, roji commented on test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
> +    public virtual Task Order(bool async)
The problem with GearsOfWar is that it's duplicated many times (TPC, TPT, temporal), and that's not useful for this test (I don't think it's great we have this duplication); it's also not implemented by Cosmos (and presumably other non-relational providers)...

So maybe consider implementing this test in NorthwindMiscellaneousQueryTestBase - there are some ordering tests there already.

2024-07-27 12:38 UTC, roji commented on src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
>              visitedExpression = TryConvertEnumerableToQueryable(methodCallExpression);
Sure. The enumerable->queryable transformation should work - it's generic logic for any method that exists with the same name (and parameters) on both Enumerable and Queryable.

But yeah, good idea to do a test; basically any usage of the operator **not** in the top-level is enumerable. For example, something like in Northwind:

```c#
AssertQuery(
    async,
    ss => ss.Set<Customer>().Where(c => c.Orders.Order().First().OrderID == xxxx));
```

Because the Order() is inside the Where and not a top-level operator, it's enumerable rather than querable.

2024-07-29 21:18 UTC, chrisvds942 commented on src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
>              visitedExpression = TryConvertEnumerableToQueryable(methodCallExpression);
There is a small typo in the comment.

2024-08-13 03:34 UTC, bricelam commented on src/EFCore/Infrastructure/ExpressionExtensions.cs
> +    public static LambdaExpression CreateIdentityLambda(Type type)
Removed.

2024-08-13 03:35 UTC, bricelam commented on test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
> +    public virtual Task Order(bool async)
Moved to Northwind. I had all the same thoughts while writing it. 😉

2024-08-13 03:38 UTC, bricelam commented
Feedback addressed. I'm realizing just how short two weeks is for an external contributor. Life gets busy!

2024-08-13 14:43 UTC, roji approved these changes
LGTM, thanks @bricelam! Rebased on latest main and fixed tests which broke because of a conflicting change in Cosmos.

Will merge this at the very last minute for EF 9 🎉

2024-08-13 15:22 UTC, merged