[WIP] New EF.Constant handling
dotnet/efcore pull request #34297
Opened 2024-07-26 17:55 UTC by cincuranet

Fixes #33674

2024-07-26 18:06 UTC, roji commented on src/EFCore/Query/QueryCompilationContext.cs
> +    public HashSet<Expression> ExplicitConstants = new();
Possibly ExpressionsToConstantize, but we can fight over naming later.

2024-07-26 18:06 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
> +        await AssertQuery(
See test Inline_collection_Contains_with_EF_Constant which I htink is already this. There's also a couple of non-collection tests in NorthwindWhereQueryTestBase (you can add more as needed).

One thing that's specifically lacking coverage is EF.Constant() over a parameterized collection, but with an operator **other** than Contains() (e.g. `EF.Constant(ids).Where(...)`).

2024-07-29 12:29 UTC, cincuranet commented on src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
> +        if (method.DeclaringType == typeof(EF)
My plan is to eventually refactor the body of `if` into something like `ExtractQueryMetadata` above and follow the same pattern.

2024-07-30 08:11 UTC, cincuranet commented on src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs
> +                    return Call(method, evaluatedArgument);
We need a little bit of code here - mostly because the `EF.Constant` needs to stay in the tree, so later the expression inside gets marked and processed.

I've also added comment there.

2024-08-02 16:03 UTC, roji requested changes
Really good first attempt @cincuranet, this covers many parts of the query pipeline and it's great to see all this work. See below for all my comments.

Note that it would be good to add some tests which cover the bugs in the current implementations (e.g. inline collection with a single scalar parameter, which shouldn't get treated as a "values parameter").

2024-08-02 16:03 UTC, roji commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +            string[] arr => HandleStringArray(arr),
I'm not a big fan of going down this route... The generated C# code we're shooting for is `new string[] { ... }`; in LINQ, this simply isn't represented as a ConstantExpression for an array value, but rather by NewArrayExpression (which LinqToCSharpSyntaxTranslator already supported well). So it would be more correct to have the input LINQ tree have the proper LINQ expression (NewArrayExpression), rather than modifying this translator to do this imprecise translation...

Also see below comments on keeping HashSet rather than array, which would mean using NewExpression instead of NewArrayExpression.

2024-08-02 17:42 UTC, roji commented on src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs
> +                    return Call(method, evaluatedArgument);
Yeah, makes sense.

2024-08-02 17:43 UTC, roji commented on src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
> +        if (method.DeclaringType == typeof(EF)
Maybe, let's maybe look at this class together after rc1?

2024-08-04 12:07 UTC, roji commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> -    protected virtual bool UseRelationalNulls { get; }
nit: I'd still keep these and just unpack the parameters object into them; that prevents the breaking change of removing these, and makes consuming code a bit nicer.

2024-08-05 08:48 UTC, cincuranet commented on src/EFCore.Relational/Query/SqlExpressions/ValuesExpression.cs
> +                columnNames.Count is 1 or 2,
Yes.

2024-08-06 08:46 UTC, cincuranet commented
/azp run

2024-08-08 08:00 UTC, cincuranet commented on src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
> +                                _sqlExpressionFactory.Constant(value, value?.GetType() ?? typeof(object), typeMapping)]));
I don't follow. The type mapping on the parameter is scalar (i.e. `IntTypeMapping`), inferred from `ApplyTypeMappingsOnValuesExpression`.

2024-08-08 10:00 UTC, cincuranet commented
@roji This is ready for another review pass.

2024-08-08 12:48 UTC, roji approved these changes
Almost LGTM, see only nits below 🎉 

Can fix the nits, but please don't merge yet though - I want to take a look at the precompiled query code there.

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/IRelationalParameterBasedSqlProcessorFactory.cs
> +    /// <param name="parameters">Parameteres for <see cref="RelationalParameterBasedSqlProcessor" /></param>
```suggestion
    /// <param name="parameters">Parameters for <see cref="RelationalParameterBasedSqlProcessor" />.</param>
```

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                    // Since VALUES may not guarantee row ordering, we add an _ord value by which we'll order.
nit: indentation

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +    ///     Provides an tableAlias to be used for the table returned from translation, which will represent the collection.
Revert? The comment already said "alias to be used for the table..."

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +                new[] { ValuesOrderingColumnName, ValuesValueColumnName });
```suggestion
                [ValuesOrderingColumnName, ValuesValueColumnName]);
```

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +        else
nit: can remove else as the if above returns

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +        if (TryExtractBareInlineCollectionValues(source, out var values, out _)
nit: can introduce an overload of TryExtractBareInlineCollectionValues without the 2nd out parameter for use in places which don't support values parameters (and which calls the real one). Would also remove the need to bang `values`.

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            if (valuesExpression.RowValues is not null)
switch

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalTypeMappingPostprocessor.cs
> +                    valuesParameter = (SqlParameterExpression)_sqlExpressionFactory.ApplyTypeMapping(valuesParameter, parameterTypeMapping);
Can also just call SqlParameterExpression.ApplyTypeMapping directly

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/RelationalTypeMappingPostprocessor.cs
> +                return new ValuesExpression(valuesExpression.Alias, null, valuesParameter, newColumnNames);
```suggestion

                return new ValuesExpression(valuesExpression.Alias, null, valuesParameter, newColumnNames);
```

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/SqlExpressions/ValuesExpression.cs
> +        if (valuesParameter is not null)
nit: we generally leave an empty line after closing curlies (e.g. here and below)

```suggestion

        if (valuesParameter is not null)
```

2024-08-08 12:48 UTC, roji commented on src/EFCore.Relational/Query/SqlExpressions/ValuesExpression.cs
> +        if ((rowValues is null ? 0 : 1) + (valuesParameter is null ? 0 : 1) != 1)
nit:

```suggestion
        if (rowValues is null ^ valuesParameter is null)
```

2024-08-08 12:48 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
> +            _isSearchCondition = parentSearchCondition;
In general, we don't try to restore visitor state when there's an exception, but rather assume that any exception immediately propagates all the way up and terminates the visitation... If we really want to change that for some reason, we should probably do a more systematic pass (but I don't think we need to/should). So revert unless there's some specific reason here?

2024-08-08 12:48 UTC, roji commented on src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
> +            var parameterExpression = (ParameterExpression)Visit(methodCallExpression.Arguments[0]);
```suggestion

            var parameterExpression = (ParameterExpression)Visit(methodCallExpression.Arguments[0]);
```

2024-08-08 12:48 UTC, roji commented on src/EFCore/Properties/CoreStrings.Designer.cs
> +        ///     'EF.Constant()' isn't supported by provider.
```suggestion
        ///     'EF.Constant()' isn't supported by your provider.
```

2024-08-08 12:48 UTC, roji commented on src/EFCore/Properties/CoreStrings.resx
> +    <value>'EF.Constant()' isn't supported by provider.</value>
```suggestion
    <value>'EF.Constant()' isn't supported by your provider.</value>
```

2024-08-08 12:48 UTC, roji commented on src/EFCore/Query/QueryCompilationContext.cs
> +    ///         Expressions on which EF.Constant was used. This will be later used to transform the parts into constants.
```suggestion
    ///         Names of parameters on which <see cref="EF.Constant{T}" /> was used. Such parameters are later transformed into constants.
```

2024-08-08 12:48 UTC, roji commented on test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
> +    public virtual Task Single_collection_parameter_Count_with_column_predicate_is_not_confused_with_EF_Constant(bool async)
Also move this to be next to the other Inline_collection tests

```suggestion
    public virtual Task Inline_collection_with_single_parameter_element_Count(bool async)
```

2024-08-08 12:48 UTC, roji commented on test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
> +    public virtual Task Single_collection_parameter_Contains_is_not_confused_with_EF_Constant(bool async)
Also move this to be next to the other Inline_collection tests

```suggestion
    public virtual Task Inline_collection_with_single_parameter_element_Contains(bool async)
```

2024-08-08 16:37 UTC, roji commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +        //var commandLiftableConstant = RelationalDependencies.RelationalLiftableConstantFactory.CreateLiftableConstant(
@cincuranet OK, I took a look at this and I indeed think there's no way to do this nicely - we can stick `new HashSet<string>()` into the expression lambda (we'd get a NewExpression for that from the compiler), but there's no way we can get a dynamic list of initializers with the expression lambda (if we had a fix number we'd be able to do it).

An alternative is to use an expression lambda and then amend the expression tree, e.g. having an NewExpression for the HashSet without an initializer, and then dynamically adding the initializers. It would probably simplify compared to the current code, so if you want to give it a shot go ahead. Otherwise I'm OK with merging as-is (after cleaning up the comment etc.

2024-08-11 12:11 UTC, cincuranet commented on src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> +        //var commandLiftableConstant = RelationalDependencies.RelationalLiftableConstantFactory.CreateLiftableConstant(
I told you so. ;) Tracked in #34400.

2024-08-11 12:15 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
> +            _isSearchCondition = parentSearchCondition;
I did it to mostly to cover multiple return paths in `switch` one time. But I can put it inside the `switch`, no problem with that.

2024-08-11 12:38 UTC, cincuranet commented on src/EFCore.Relational/Query/SqlExpressions/ValuesExpression.cs
> +        if ((rowValues is null ? 0 : 1) + (valuesParameter is null ? 0 : 1) != 1)
I don't like this syntax. I don't think it is readable. Does not work for 3 or more values. But whatever pleases your heart. :) 

And the suggestion is missing negation. But I understand you did that for my own good. :D

2024-08-11 13:23 UTC, merged

2024-08-11 15:26 UTC, roji commented on src/EFCore.Relational/Query/SqlExpressions/ValuesExpression.cs
> +        if ((rowValues is null ? 0 : 1) + (valuesParameter is null ? 0 : 1) != 1)
Ahaha right :) Yeah, missed the negation.

Readability is always a matter of what one is used to ;) And you're right that this doesn't "scale", but I find it works really nicely for two (better than the alternative conditional syntax anyway).

But such nits really are suggestions - if you don't agree with something I'm suggesting in that category I definitely won't merging the PR etc...