Context options to control constantization/parameterization of parameterized collections and EF.Parameter improvement collection parameters
dotnet/efcore pull request #34406
Opened 2024-08-12 09:49 UTC by cincuranet

Fixes #34344
Fixes #34345

2024-08-12 09:50 UTC, cincuranet commented
The naming is TBD.

2024-08-13 07:02 UTC, roji reviewed
Looking good, really only naming and some nits remaining...

2024-08-13 07:02 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
> +        await base.Inline_collection_Contains_with_EF_Parameter(async);
This one is interesting... I think we should actually throw an error if the user uses EF.Parameter() and the SQL compatibility is too low. After all, the user has very clearly indicated their intent with EF.Parameter(), but it's not possible to fulfil that intent...

What do you think?

2024-08-13 07:02 UTC, roji commented on test/EFCore.Sqlite.FunctionalTests/Query/NonSharedPrimitiveCollectionsQuerySqliteTest.cs
> +    protected override DbContextOptionsBuilder SetPrimitiveCollectionsParameters(DbContextOptionsBuilder optionsBuilder)
Add empty line

2024-08-13 08:16 UTC, cincuranet commented on test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
> +        await base.Inline_collection_Contains_with_EF_Parameter(async);
Fine with me.

2024-08-13 08:19 UTC, cincuranet commented
@roji This is now ready to review.

FYI I also included changes (`HashSet` -> `ISet`, etc.) related to this area from latest #33220.

2024-08-13 08:50 UTC, roji requested changes
Some last minor stuff.

2024-08-13 08:50 UTC, roji commented on src/EFCore.Relational/Internal/ParameterizedCollectionTranslationMode.cs
> +    Parameters,
As per the enum name, this is for a single parameterized collection, so plural "Parameters" doesn't work well here :trollface: 

I'd vote for Constantize vs. Parameterize, but if we hate these, just singular Parameter here seems reasonable (in any case it's internal).

2024-08-13 08:50 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            && !QueryCompilationContext.ParametersToNotConstantize.Contains(sqlParameterExpression.Name))
Note this means we throw a generic "could not translate" error, and the user has no idea what's going on... Ideally, do the check inside and add translation failure details that we can't parameterize because the database doesn't support it etc.

2024-08-13 08:50 UTC, roji commented on src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
> +            || (primitiveCollectionsBehavior == ParameterizedCollectionTranslationMode.Constants && !QueryCompilationContext.ParametersToNotConstantize.Contains(sqlParameterExpression.Name)))
nit: break line (larger than 120 char limit)

2024-08-13 08:50 UTC, roji commented on src/EFCore/Query/QueryCompilationContext.cs
> +    public virtual ISet<string> ParametersToConstantize { get; } = new HashSet<string>(StringComparer.Ordinal);
Isn't the default ordinal equality?

2024-08-13 08:50 UTC, roji commented on src/EFCore.Relational/Infrastructure/RelationalDbContextOptionsBuilder.cs
> +    /// </summary>
```suggestion
    /// <summary>
    ///     Configures the context to translate parameterized collections to inline constants.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         When a LINQ query contains a parameterized collection, by default EF Core parameterizes the entire collection as a single
    ///         SQL parameter, if possible. For example, on SQL Server, the LINQ query <c>Where(b => ids.Contains(b.Id)</c> is translated to
    ///         <c>WHERE [b].[Id] IN (SELECT [i].[value] FROM OPENJSON(@__ids_0) ...)</c>. While this helps with query plan caching, it can
    ///         produce worse query plans for certain query types.
    ///     </para>
    ///     <para>
    ///         <see cref="TranslateParameterizedCollectionsToConstants" /> instructs EF to translate the collection to a set of constants:
    ///         <c>WHERE [b].[Id] IN (1, 2, 3)</c>. This can produce better query plans for certain query types, but can also lead to query
    ///         plan bloat.
    ///     </para>
    ///     <para>
    ///         Note that it's possible to cause EF to translate a specific collection in a specific query to constants by wrapping the
    ///         parameterized collection in <see cref="EF.Constant{T}" />: <c>Where(b => EF.Constant(ids).Contains(b.Id)</c>. This overrides
    ///         the default.
    ///     </para>
    /// </remarks>
```

2024-08-13 08:50 UTC, roji commented on src/EFCore.Relational/Infrastructure/RelationalDbContextOptionsBuilder.cs
> +    /// </summary>
```suggestion
    /// <summary>
    ///     Configures the context to translate parameterized collections to SQL parameters.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         When a LINQ query contains a parameterized collection, by default EF Core parameterizes the entire collection as a single
    ///         SQL parameter, if possible. For example, on SQL Server, the LINQ query <c>Where(b => ids.Contains(b.Id)</c> is translated to
    ///         <c>WHERE [b].[Id] IN (SELECT [i].[value] FROM OPENJSON(@__ids_0) ...)</c>. While this helps with query plan caching, it can
    ///         produce worse query plans for certain query types.
    ///     </para>
    ///     <para>
    ///         <see cref="TranslateParameterizedCollectionsToConstants" /> instructs EF to translate the collection to a set of constants:
    ///         <c>WHERE [b].[Id] IN (1, 2, 3)</c>. This can produce better query plans for certain query types, but can also lead to query
    ///         plan bloat. <see cref="TranslateParameterizedCollectionsToParameters" /> can be used set the translation mode back to
    ///         parameters, which is the default.
    ///     </para>
    ///     <para>
    ///         Note that it's possible to cause EF to translate a specific collection in a specific query to a parameter by wrapping the
    ///         parameterized collection in <see cref="EF.Parameter{T}" />: <c>Where(b => EF.Parameter(ids).Contains(b.Id)</c>. This
    ///         overrides the default set by <see cref="TranslateParameterizedCollectionsToConstants" />.
    ///     </para>
    /// </remarks>
```

2024-08-13 09:00 UTC, cincuranet commented on src/EFCore/Query/QueryCompilationContext.cs
> +    public virtual ISet<string> ParametersToConstantize { get; } = new HashSet<string>(StringComparer.Ordinal);
Default is `StringEqualityComparer`. It has equivalent implementation as `OrdinalCaseSensitiveComparer`. But I want to be explicit here.

2024-08-13 09:56 UTC, roji approved these changes

2024-08-13 11:31 UTC, merged