Code cleanup
dotnet/efcore pull request #34450
Opened 2024-08-15 14:50 UTC by ajcvickers

2024-08-15 17:45 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Query/Internal/Expressions/SelectExpression.cs
> +    public override ExpressionType NodeType
Whoa, this is a behavior change!
Report the bug

2024-08-15 17:46 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Query/Internal/Expressions/SelectExpression.cs
> +    }
Questionable choice

2024-08-15 17:47 UTC, AndriySvyryd commented on src/EFCore.Cosmos/Storage/Internal/ReadOnlyMemoryConverter.cs
> +        => array.Length == 0 ? default : new ReadOnlyMemory<T>(array);
Hmmm...

2024-08-15 17:48 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/Expressions/SelectExpression.cs
> +    public override ExpressionType NodeType
It's not because the whole class is sealed.

2024-08-15 17:48 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/LinqToCSharpSyntaxTranslator.cs
> +using ConditionalExpression = System.Linq.Expressions.ConditionalExpression;
Suspicious change

2024-08-15 17:49 UTC, ajcvickers commented on src/EFCore.Cosmos/Query/Internal/Expressions/SelectExpression.cs
> +    }
We decided many years ago not to do expression bodies for constructors. 🤷 We can change the rule.

2024-08-15 17:49 UTC, AndriySvyryd commented on src/EFCore.Design/Query/Internal/PrecompiledQueryCodeGenerator.cs
> +        return new ScaffoldedFile(name, _code.ToString());
👀

2024-08-15 17:50 UTC, ajcvickers commented on src/EFCore.Cosmos/Storage/Internal/ReadOnlyMemoryConverter.cs
> +        => array.Length == 0 ? default : new ReadOnlyMemory<T>(array);
This was a decision from previous cleanup--we would not use target-typed new in places where the type is not obvious. Personally happy to change to use it everywhere.

2024-08-15 17:51 UTC, AndriySvyryd requested changes
Change the rules for lambda-body constructors and for target-typed new to preserve existing

2024-08-15 18:25 UTC, AndriySvyryd approved these changes

2024-08-16 09:48 UTC, ajcvickers commented
> Change the rules for lambda-body constructors and for target-typed new to preserve existing

I will do this for now, but I think it would be better for us to agree on one way or the other. Each time we do preserve-existing, the value of code cleanup goes down a little bit.

2024-08-16 09:58 UTC, roji commented on src/EFCore.Cosmos/Query/Internal/Expressions/SelectExpression.cs
> +    }
Yeah I'd vote for doing these, not sure why constructors should be treated differently than other methods...

2024-08-16 10:58 UTC, ajcvickers commented
Replaced by #34451

2024-08-16 10:58 UTC, closed without merging

2024-08-16 11:15 UTC, roji commented on src/EFCore.Cosmos/Storage/Internal/ReadOnlyMemoryConverter.cs
> +        => array.Length == 0 ? default : new ReadOnlyMemory<T>(array);
Yeah, I think we tried going all the way in a previous cleanup, and it was a bit too extreme, i.e. in some cases it would make the code harder to read because it's hard to figure out what type actually gets instantiated.

My vote would be to try `csharp_style_implicit_object_creation_when_type_is_apparent` - [see this discussion](https://github.com/dotnet/runtime/pull/67061/files#r837120758) - that's supposed to use target-typed only where the type really is obvious...

2024-08-16 11:15 UTC, roji commented on src/EFCore.Design/Query/Internal/PrecompiledQueryCodeGenerator.cs
> +                precompilationErrors.Add(new QueryPrecompilationError(querySyntax, e));
Good example of where IMHO target-typed new goes too far (I **think** `csharp_style_implicit_object_creation_when_type_is_apparent` would not do this)

2024-08-16 11:16 UTC, roji commented
@ajcvickers I just finished reviewing this and noticed it was closed :( Take a look at the above couple comments, but otherwise things seemed fine here. Can give the new PR a look as well later...

2024-08-16 12:19 UTC, ajcvickers commented
@roji Any comments that require me to change the rules means I start over.