Fix ESCAPE clause for Azure Synapse.
dotnet/efcore pull request #34463
Opened 2024-08-19 10:57 UTC by cincuranet

Fixes 33555

2024-08-19 11:13 UTC, roji requested changes
This looks like it just omits the ESCAPE clause for Synapse; doesn't that mean that bad results would be returned? In other words, the ESCAPE isn't needed to get the correct results, why do we have it there in the first place?

I think the fix needed here is to vary our **translation** for Synapse, translating to correct (but inferior) SQL which doesn't depend on LIKE+ESCAPE. You can look at pre-8.0 EF to see what we were doing (as this is a regression in 8.0).

2024-08-19 11:15 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NonSharedAzureSynapseQuerySqlServerTest.cs
> +        var foo = "aaa";
Try putting an actual wildcard here (e.g. `%`) - the test should fail.

2024-08-19 14:02 UTC, cincuranet commented
I took the previous translation and put it into `TryTranslateStartsEndsWithContainsOldStyle` (and downstream). No major refactoring or anything like that, because I don't want to introduce bugs.

2024-08-19 15:43 UTC, roji requested changes
If I look at the existing TryTranslateStartsEndsWithContains, doesn't the default case ("The pattern is a column or a complex expression") already contain exactly the logic we need? Any particular reason to duplicate the entire function for Synapse, rather than just jump to that case whenever we're on Synapse and would need to use ESCAPE? I don't really see any risk problem here...

2024-08-20 11:43 UTC, cincuranet commented
Now it's using the code from the original `default` case, but also has some optimizations based on the fact that for a constant pattern we can omit some checks.

2024-08-20 19:18 UTC, roji requested changes
LGTM, see mostly nits

2024-08-20 19:18 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                        string s when !s.Any(IsLikeWildChar) => _sqlExpressionFactory.Like(
nit: move `=>` to the next line

2024-08-20 19:18 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                            _sqlExpressionFactory.IsNotNull(translatedInstance),
Most of this is duplicated - extract out the common code and only compose the additional Like on it as needed with an if (so this switch expression would become a switch statement, I think).

2024-08-20 19:45 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                        string s when !s.Any(IsLikeWildChar) => _sqlExpressionFactory.Like(
What are the rules? For example the cases above all start on the same line.

2024-08-20 19:47 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                            _sqlExpressionFactory.IsNotNull(translatedInstance),
What _additional Like_ are you talking about?

2024-08-20 19:53 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                            _sqlExpressionFactory.IsNotNull(translatedInstance),
This case (Contains without patternIsNonEmptyConstantString) - returns the exact same expression tree as the above case (Contains with patternIsNonEmptyConstantString), except that it adds the Like on top, no?

2024-08-20 19:55 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                        string s when !s.Any(IsLikeWildChar) => _sqlExpressionFactory.Like(
Probably the rules are a bit hazy... I generally tend to do single-line if the whole thing fits on a single line, but when it's multi-line as in this case, putting the Like here makes the indentation harder to follow for the next lines... if you move the `=> (` to the next line, it's one readable block with the standard increasing indentation as you go in, rather than with `_sqlExpressionFactory.Like` much more inside/ahead than the following lines.

2024-08-20 19:55 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                        string s when !s.Any(IsLikeWildChar) => _sqlExpressionFactory.Like(
That's just nits, if you're against it can leave as-is.

2024-08-21 09:03 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                            _sqlExpressionFactory.IsNotNull(translatedInstance),
Nope. Also the not null check for `translatedPattern` is not inside there and hence also the `AndAlso` is not there. Only thing that might make sense to extract is the `GreaterThan` with `CHARINDEX`. Do you want at least this piece extracted?

2024-08-21 09:09 UTC, cincuranet commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                            _sqlExpressionFactory.IsNotNull(translatedInstance),
Hmm, it is somewhat nicer with the `GreaterThan` with `CHARINDEX` extracted. I'll leave it there and let's see what you think.

2024-08-21 13:34 UTC, roji approved these changes

2024-08-21 13:34 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                    return
nit: expression-bodied

2024-08-21 13:34 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
> +                            _sqlExpressionFactory.IsNotNull(translatedInstance),
My bad, I didn't look carefully enough.. Looks good to me as-is - whatever you prefer here.

2024-08-21 20:53 UTC, merged

2024-08-21 23:35 UTC, AndriySvyryd commented on test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs
> +    }
Use a different `StoreName` for these, otherwise initialization becomes a race condition: https://dev.azure.com/dnceng-public/public/_build/results?buildId=784149&view=ms.vss-test-web.build-test-results-tab

2024-08-21 23:37 UTC, AndriySvyryd commented on test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs
> +    }
Also add a condition so these tests only run when targeting AzureSynapse, see `SqlServerCondition.IsSqlAzure`

2024-08-22 09:12 UTC, cincuranet commented on test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs
> +    }
#34506

2024-08-22 09:24 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQueryAzureSynapseTest.cs
> +    }
Good catch with the store name...

We don't ever actually run our tests against Synapse, and even though we would in an ideal world, I'm not sure that's going to happen in the near future... In the meantime, this at least allows us to assert on SQL baselines for cases that we know are problematic...

2024-08-22 09:57 UTC, cincuranet commented
/backport to release/9.0