Acquire the migrations database lock in a transaction.
dotnet/efcore pull request #34489
Opened 2024-08-21 05:45 UTC by AndriySvyryd

Reacquire the lock when retrying.
Execute all migrations in a single transaction.

2024-08-21 05:46 UTC, AndriySvyryd commented
@roji Let me know if this is an acceptable design

2024-08-21 17:04 UTC, roji reviewed
@AndriySvyryd thanks, overall looks to me... There are some slight things I don't understand about flowing the state across Migrator/MigrationCommandExecutor, but that may just be the draft state of this PR. Otherwise see comments below.

I'm personally not seeing the value of the separation of Migrator vs. MigrationCommandExecutor - the separation may actually add more complexity/cognitive load rather than simplifying (especially now that transaction management and locking are also managed in Migrator...). Something to consider for the future...

2024-08-21 18:45 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +            _executionStrategy.Execute(
If the lock is taken before the history table creation, then PG won't have another chance to take a lock afterwards

2024-08-21 18:47 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +    private static IDbContextTransaction? Execute(
This is just to keep the compiler happy, otherwise I'd need to qualify the lambda where this is called

2024-08-21 20:29 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +            _executionStrategy.Execute(
I was thinking that the PG GetDatabaseLock() would internally do `CREATE TABLE IF NOT EXISTS "__MigrationsHistoryTable"`, and then `LOCK TABLE "__MigrationsHistoryTable"`, effectively making the table creation to be part of the lock acquisition. The "official" table creation triggered by EF would then always no-op.

How does that sound?

2024-08-21 20:31 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +                        executionState.DatabaseLock = await executionState.DatabaseLock.ReacquireAsync(transaction, cancellationToken)
Yeah, that looks good!

2024-08-21 20:43 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +            _executionStrategy.Execute(
Ooof, that goes against the idea of lock being a light-weight operation when there's no concurrency and messes with the single-responsibility principle, which in general, you seem to be against in this PR 😆 
Why not execute the same `CREATE TABLE IF NOT EXISTS "__MigrationsHistoryTable"` code in `IHistoryRepository.Create`? Then it doesn't matter that it's outside the lock

2024-08-21 20:56 UTC, AndriySvyryd commented
> I'm personally not seeing the value of the separation of Migrator vs. MigrationCommandExecutor - the separation may actually add more complexity/cognitive load rather than simplifying (especially now that transaction management and locking are also managed in Migrator...). Something to consider for the future...

This is mainly to reduce code duplication as it's also called from `RelationalDatabaseCreator.CreateTables`. However, the lock isn't taken there, since the migrations history table shouldn't be created.

2024-08-21 20:58 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +            _executionStrategy.Execute(
> Ooof, that goes against the idea of lock being a light-weight operation when there's no concurrency

I don't think this would matter in terms of efficiency - we could even batch both creation and lock in a single roundtrip, at which point there's basically zero overhead (`CREATE TABLE IF NOT EXISTS "__MigrationsHistoryTable"; LOCK TABLE "__MigrationsHistoryTable"`).

> Then it doesn't matter that it's outside the lock

The thing I care more about is the creation being out of the retrying strategy rather than the lock per se; this means that some transient error can cause the whole thing to abort without a retry... So if we can at least move the history table creation into the retried code, that's already better... 

If we additionally put the creation inside the lock, that would also protect against creation race conditions in the first deployment - though I agree this is a relatively unimportant edge case, which may not justify the ugliness of putting the creation inside GetDatabaseLock for PG...

So I agree that maybe doing table creation as part of locking (in PG) probably goes too far in terms of single-responsibility... But re single responsibility of Migrator vs. MigrationCommandExecutor, it's just that everything here really does seem to be quite intertwined, because of the nature of what we're doing... I'm not against separating things per se, but having two services which flow the elaborate state object back and forth, and both need to know about transaction management and the lock - that's starting to seem like an artificially imposed separation that doesn't really work... It's starting to seem to me more appropriate to just encapsulate all that complexity in a single service...

2024-08-21 20:59 UTC, roji commented
>> I'm personally not seeing the value of the separation of Migrator vs. MigrationCommandExecutor - the separation may actually add more complexity/cognitive load rather than simplifying (especially now that transaction management and locking are also managed in Migrator...). Something to consider for the future...
>
> This is mainly to reduce code duplication as it's also called from RelationalDatabaseCreator.CreateTables. However, the lock isn't taken there, since the migrations history table shouldn't be created.

OK. This is academic at the moment in any case, I'm not actually proposing we do anything for 9.0...

2024-08-21 21:00 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +            _executionStrategy.Execute(
> The thing I care more about is the creation being out of the retrying strategy rather than the lock per se; this means that some transient error can cause the whole thing to abort without a retry... So if we can at least move the history table creation into the retried code, that's already better...

Yes, I'll make sure everything is wrapped in an `ExecutionStrategy`

2024-08-23 20:51 UTC, artl93 approved these changes

2024-08-29 12:30 UTC, roji requested changes
I think it's getting closer @AndriySvyryd but I can still see some trouble (or stuff I don't understand), take a look.

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +    private async Task<bool> MigrateImplementationAsync(
The bool return value doesn't seem to be used - remove?

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +        await _connection.OpenAsync(cancellationToken).ConfigureAwait(false);
Just confirming: the RelationalConnection stays "open" regardless of any errors happening while executing, and the underlying ADO.NET connection getting closed and reopened, right? i.e. it's just a reference counting mechanism?

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +        var connectionOpened = await _connection.OpenAsync(cancellationToken).ConfigureAwait(false);
Related to my question on RelationalConnection above - is it necessary to open here given that we open outside?

2024-08-29 12:30 UTC, roji commented on src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationDatabaseLock.cs
> +    : IMigrationsDatabaseLock
Above: rename the relationalCommand parameter to releaseLockRelationalCommand or similar (also in SQLite)

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +        return await executionStrategy.ExecuteAsync(
If I understand correctly, we use the execution strategy both here and above in Migrator - so we retry inside of retry?

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +            && (migrationCommands.Any(x => x.TransactionSuppressed) || executionStrategy.RetriesOnFailure))
Re the suppression of the TransactionScope just below, should have this at the higher-level Migrator? It also executes stuff against the database, which we probably don't want wrapped in the TransactionScope...

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +                        connectionOpened = false;
This looks like a way to avoid re-refreshing the lock below if we refresh it here; if so, maybe have a separate lockAcquired to keep things cleaner?

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/IMigrationsDatabaseLock.cs
> +    IMigrationsDatabaseLock Refresh(bool connectionReopened, bool? transactionRestarted)
nit: transactionStarted rather than restarted?

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +                        executionState.DatabaseLock = await executionState.DatabaseLock.RefreshAsync(
If I'm reading the code correctly, we may get here from RelationalDatabaseCreator, and then acquire the lock here (possibly also in the block just above - not sure). But the code for releasing the lock is in Migrator, and AFAICT not in RelationalDatabaseCreator - so the lock would just be left there?

(The factoring/relationship between all the types here feels very complex and in need of some simplification... But I know this is not the time to do that)

2024-08-29 12:30 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +        var useTransaction = _connection.CurrentTransaction is null;
What happens if useTransaction is false (because `_connection.CurrentTransaction` is non-null), but the locking LockReleaseBehavior is Transaction? It would seem like we currently skip the lock altogether, which is bad... Am not sure in which situations _connection.CurrentTransaction is non-null, but should we throw for this case?

2024-08-29 18:07 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +    protected virtual IsolationLevel MigrationTransactionIsolationLevel => IsolationLevel.Unspecified;
> This is interesting... First, I wonder what case there would be to tweak this... The migration process itself doesn't read data from the database, except for the migration history table which is protected by the lock (so no concurrent access there, no need for worrying about isolation levels). So I can't really see a use for this.

This is for the locks that are transaction-dependent. If it's implemented by writing a value in a table (like for Sqlite) then the isolation level will determine whether they are visible from outside of the transaction. Unfortunately, Sqlite doesn't support the levels that would allow this to work, so I had to take the lock outside of the transaction. We can move it to `IHistoryRepository` if it's indeed useful for some provider

2024-08-29 18:08 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/HistoryRepository.cs
> +    public abstract LockReleaseBehavior LockReleaseBehavior { get; }
@dotnet/efteam API review question

2024-08-29 18:12 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +            _executionStrategy.Execute(
Mostly to avoid unnecessarily checking the existence of the history table during retries.

2024-08-29 18:15 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +                state.DatabaseLock = _historyRepository.AcquireDatabaseLock();
Right, it's only acquired here if `_historyRepository.LockReleaseBehavior != LockReleaseBehavior.Transaction`, otherwise it's take in `MigrateImplementation`.

As I mentioned above, Sqlite cannot take the lock inside a transaction. We could add yet another flag to `IHistoryRepository` to control this if you think it's orthogonal to `LockReleaseBehavior`

2024-08-29 18:23 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +            && (migrationCommands.Any(x => x.TransactionSuppressed) || executionStrategy.RetriesOnFailure))
This is also called from other places apart from `Migrator`

2024-08-29 18:24 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +        return await executionStrategy.ExecuteAsync(
Only the top execution strategy retries. This is called here to make sure we get retries in the other uses as well.

2024-08-29 18:28 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +                        executionState.DatabaseLock = await executionState.DatabaseLock.RefreshAsync(
In the uses where the lock is not acquired before calling this `executionState.DatabaseLock` is `null`, so the lock is not reacquired. If the caller acquires the lock before calling this, it's responsible for releasing it.

2024-08-29 18:35 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +        var useTransaction = _connection.CurrentTransaction is null;
Basically `useTransaction` is `true` for the legacy case where the user had to wrap this call in a transaction and wrap in an execution strategy. I don't think we can be sure that the transaction-based locking behavior will be working correctly in this case. But I'd prefer to keep it working as before unless there's a good reason to block it.

2024-08-29 18:55 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +        await _connection.OpenAsync(cancellationToken).ConfigureAwait(false);
Something like that. As long as `Close` is called the same amount of times as `Open` everything will work. That's why it should be called outside of the retry block.

2024-08-29 18:56 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +    private async Task<bool> MigrateImplementationAsync(
Again, this is to appease the compiler and avoid specifying the generic types

2024-08-29 18:59 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +        var connectionOpened = await _connection.OpenAsync(cancellationToken).ConfigureAwait(false);
Not really, it's more of an assert

2024-08-29 19:00 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/LockReleaseBehavior.cs
> +    Explicit
@dotnet/efteam API Review

2024-08-29 19:26 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/IMigrationsDatabaseLock.cs
> +    IMigrationsDatabaseLock Refresh(bool connectionReopened, bool? transactionRestarted)
@dotnet/efteam API Review

2024-08-29 19:37 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/IMigrationsDatabaseLock.cs
> +    IMigrationsDatabaseLock Refresh(bool connectionReopened, bool? transactionRestarted)
@dotnet/efteam API Review

2024-08-30 05:52 UTC, roji commented on src/EFCore.Relational/Migrations/IMigrationsDatabaseLock.cs
> +    IMigrationsDatabaseLock Refresh(bool connectionReopened, bool? transactionRestarted)
> I don't think this name accurately conveys the tri-value aspect.

Maybe, but transactionRestarted is also inaccurate for the case where we're just starting out and there nothing to re-start.

But never mind, this isn't important and it's a bit late for minor naming discussions...

2024-08-30 05:55 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +    protected virtual IsolationLevel MigrationTransactionIsolationLevel => IsolationLevel.Unspecified;
> This is for the locks that are transaction-dependent. If it's implemented by writing a value in a table (like for Sqlite) then the isolation level will determine whether they are visible from outside of the transaction.

Oh, good point... For SQLite-like cases where actual rows are being used for locking, ReadUncommitted would indeed be necessary to make sure the row is visible even though the transaction hasn't yet committed... But SQLite basically doesn't support isolation levels IIRC.

> We can move it to IHistoryRepository if it's indeed useful for some provider

Sounds good.

2024-08-30 05:56 UTC, roji commented on src/EFCore.Relational/Migrations/HistoryRepository.cs
> +    public abstract LockReleaseBehavior LockReleaseBehavior { get; }
Am also OK with the current naming if we don't get around to discussing this.

2024-08-30 05:59 UTC, AndriySvyryd commented on src/EFCore.Relational/Migrations/HistoryRepository.cs
> +    public abstract LockReleaseBehavior LockReleaseBehavior { get; }
Ok. We won't have any meetings for this, so if anyone else in @efteam has an opinion - speak up

2024-08-30 06:08 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/Migrator.cs
> +                state.DatabaseLock = _historyRepository.AcquireDatabaseLock();
Ah I see, I misread - this indeed isn't a problem for PG.

Just for completeness, I'm still not sure about the SQLite angle, and why the lock needs to be taken before creating the history repository, as opposed to just after... As far as I can tell, there's no transaction here in any case - one is only started later, in MigrateImplementation.

But I agree that for the cases where the lock isn't transaction-bound, it's generally better to start it earlier rather than later - if it protects against concurrent creation of the history repository, all the better.

2024-08-30 06:10 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +        return await executionStrategy.ExecuteAsync(
So you're saying we have a mechanism for detecting that we're already inside an execution strategy and ignoring the nested one? Was not aware...

2024-08-30 06:11 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +            && (migrationCommands.Any(x => x.TransactionSuppressed) || executionStrategy.RetriesOnFailure))
Sure, but why not also add the suppression to Migrator (in addition to keeping it here)?

2024-08-30 06:13 UTC, roji commented on src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
> +                        executionState.DatabaseLock = await executionState.DatabaseLock.RefreshAsync(
I see that now, thanks.

2024-08-31 06:57 UTC, roji approved these changes

2024-09-03 01:54 UTC, merged

2026-02-09 18:45 UTC, mahdiyar021 commented
@roji — is there a way to disable this? I’m using YugabyteDB (Postgres‑compatible), but it doesn’t support the advisory lock mechanism. How can I run automatic migrations without relying on advisory locks?