fix-kusto-scaffold
dotnet/efcore pull request #34832
Opened 2024-10-06 10:50 UTC by barnuri

- [ ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ ] The code builds and tests pass locally (also verified by our automated build checks)
- [ ] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Code follows the same patterns and style as existing code in this repo

2024-10-06 11:18 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private bool IsKusto()
Is there not a more reliable wau to detect Kusto?

2024-10-06 11:18 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private string _version;
use "string?"

2024-10-06 11:19 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +            command.CommandText = "SELECT @@VERSION;";
What is the output of @@VERSION ?

2024-10-06 11:20 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private bool IsKusto()
didnt found something more elegant, because _compatibilityLevel is 130 and _engineEdition is 5 (detected as sql server)

2024-10-06 11:20 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private string _version;
fixed

2024-10-06 11:20 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +            command.CommandText = "SELECT @@VERSION;";
Microsoft SQL Kusto

2024-10-06 11:22 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +            return result != null ? result : "";
Maybe ensure you can build locally before submitting a PR

`(string)result` might help - and use `string.Empty` iso `""`

2024-10-06 11:23 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +            command.CommandText = "SELECT @@VERSION;";
Please share the full output of @@VERSION on Kusto

2024-10-06 11:25 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private bool IsKusto()
5 is Azure SQL Database, but yes.

2024-10-06 11:27 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +            command.CommandText = "SELECT @@VERSION;";
this is the full output "Microsoft SQL Kusto"
![{4E03D11A-6323-4A58-9259-CC57ABF26FDF}](https://github.com/user-attachments/assets/fda8a19e-3e52-47b5-943f-69186b86ae3b)

2024-10-06 11:29 UTC, ErikEJ commented
What are the results of

`SELECT SERVERPROPERTY('Edition')`

and

`SELECT SERVERPROPERTY('EditionId')`

2024-10-06 11:30 UTC, barnuri commented
> SERVERPROPERTY('EditionId')

tried that too, its sql azure

![{54DC3F93-BC5A-4671-8528-D9A22683DA8D}](https://github.com/user-attachments/assets/2a6a7ac5-d5d3-4e26-8062-f49a2a06da1b)

2024-10-06 11:31 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +            command.CommandText = "SELECT @@VERSION;";
Wow! No version numbers - are you sure you see all the text in that grid?

2024-10-06 11:36 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private bool IsKusto()
I would probably just extend IsFullFeaturedEngineEdition() with

&& !_version.Contains("Kusto", StringComparision.Ordinal)

2024-10-06 11:39 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +            command.CommandText = "SELECT @@VERSION;";
yeah :)
i screenshot what the server returned

2024-10-06 11:42 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        => _compatibilityLevel >= 110 && IsFullFeaturedEngineEdition();
nit: Did you leave some white space here?

2024-10-06 11:43 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        => _engineEdition is not EngineEdition.SqlDataWarehouse and not EngineEdition.SqlOnDemand and not EngineEdition.DynamicsTdsEndpoint && !_version.Contains("Kusto", StringComparision.Ordinal);
Maybe break to a new line - and I think you need to use "version?" to avoid build errors?

2024-10-06 11:45 UTC, ErikEJ commented
@barnuri This looks valuable, I will get this added to EF Core Power Tools, including the CLI edition

2024-10-06 11:47 UTC, barnuri commented
> @barnuri please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

2024-10-06 11:49 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        => _engineEdition is not EngineEdition.SqlDataWarehouse and not EngineEdition.SqlOnDemand and not EngineEdition.DynamicsTdsEndpoint && !_version.Contains("Kusto", StringComparision.Ordinal);
change it to be a function with body looks more right, tell me if you feel otherwise

2024-10-06 11:50 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        => _compatibilityLevel >= 110 && IsFullFeaturedEngineEdition();
where ? i see no changes after i removed " && !IsKusto()"

2024-10-06 11:51 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        => _engineEdition is not EngineEdition.SqlDataWarehouse and not EngineEdition.SqlOnDemand and not EngineEdition.DynamicsTdsEndpoint && !_version.Contains("Kusto", StringComparision.Ordinal);
LGTM!

2024-10-06 11:51 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        => _compatibilityLevel >= 110 && IsFullFeaturedEngineEdition();
Fixed now

2024-10-06 11:53 UTC, ErikEJ commented
What tool are you using for coding this? I had a typo in my guess at spelling 😄

2024-10-06 11:58 UTC, barnuri commented
> What tool are you using for coding this? I had a typo in my guess at spelling 😄

using this scaffold cmd
```
dotnet ef dbcontext scaffold "$env:MyConnection" `
    Microsoft.EntityFrameworkCore.SqlServer `
    --output-dir "Models" `
    --context MyDbContext `
    --context-dir DAL `
    --no-onconfiguring `
    --table myTable `
    --force

```

2024-10-06 12:23 UTC, barnuri commented
local build passing any idea whats going on ? @ErikEJ

2024-10-06 13:39 UTC, ErikEJ approved these changes
LGTM

2024-10-06 13:39 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        if (_version != null && _version.Contains("Kusto", StringComparison.Ordinal))
`!string.IsNullOrEmpty(_version)`

2024-10-06 13:39 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +using System;
Probably not needed?

2024-10-06 13:47 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private string? _version;
Maybe rename to _versionInformation?

2024-10-06 13:49 UTC, ErikEJ commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        static string GetVersion(DbConnection connection)
static string? GetVersionInformation(DbConnection connection)
{
            using var command = connection.CreateCommand();
            command.CommandText = "SELECT @@VERSION;";
            var result = command.ExecuteScalar();
            return result as string;
   }

2024-10-06 13:59 UTC, ErikEJ commented
@barnuri 

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

https://github.com/ErikEJ/EFCorePowerTools/commit/77275a5387fe378ae505f43171a14f4a882906f6

2024-10-06 14:25 UTC, barnuri commented
> @barnuri
> 
> I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.
> 
> [ErikEJ/EFCorePowerTools@77275a5](https://github.com/ErikEJ/EFCorePowerTools/commit/77275a5387fe378ae505f43171a14f4a882906f6)

how can i use it ?
there is a way to install this version to dotnet tool ? and use it as ```dotnet ef dbcontext scaffold```

2024-10-06 14:27 UTC, ErikEJ commented
@barnuri Something similar, yes. Have a look at the readme here: https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/9.1.409-nightly

2024-10-06 17:39 UTC, barnuri commented
> @barnuri Something similar, yes. Have a look at the readme here: https://www.nuget.org/packages/ErikEJ.EFCorePowerTools.Cli/9.1.409-nightly

steps:
1) dotnet tool install --global ErikEJ.EFCorePowerTools.Cli --version 8.1.409-nightly
2) efcpt "$myconnectionstring" mssql

got this error now

```
Microsoft.Data.SqlClient.SqlException: Request is invalid and cannot be processed: Semantic error: OTR0001: Reference to missing column 't.object_id' [line:position=11:29]
RequestId: TDS;ffcf7bdb-9f2b-4789-b4b8-7384289d2773;11
Time: 2024-10-06T17:38:03.5688957Z
  at void Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
  at void Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
  at void Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, bool callerHasConnectionLock, bool asyncClose)
  at bool Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject    
     stateObj, out bool dataReady)
  at bool Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
  at _SqlMetaDataSet Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
  at void Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, string resetOptionsString, bool isInternal, bool forDescribeParameterEncryption,  
     bool shouldCacheForAlwaysEncrypted)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, bool isAsync, int timeout, out Task task,  
     bool asyncWrite, bool inRetry, SqlDataReader ds, bool describeParameterEncryptionRequest)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, TaskCompletionSource<object> completion, int  
     timeout, out Task task, out bool usedCache, bool asyncWrite, bool inRetry, string method)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, string method)
  at SqlDataReader Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
  at DbDataReader Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
  at void Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.PatchedSqlServerDatabaseModelFactory.GetTables(DbConnection connection, DatabaseModel databaseModel, Func<string,       
     string, string> tableFilter, IReadOnlyDictionary<string, ValueTuple<string, string>> typeAliases, string databaseCollation) in PatchedSqlServerDatabaseModelFactory.cs:650
  at DatabaseModel Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.PatchedSqlServerDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options) in   
     PatchedSqlServerDatabaseModelFactory.cs:154
  at DatabaseModel Microsoft.EntityFrameworkCore.SqlServer.Scaffolding.Internal.PatchedSqlServerDatabaseModelFactory.Create(string connectionString, DatabaseModelFactoryOptions options) in   
     PatchedSqlServerDatabaseModelFactory.cs:112
  at DatabaseModel RevEng.Core.TableListBuilder.GetDatabaseModel() in TableListBuilder.cs:132
  at List<TableModel> RevEng.Core.TableListBuilder.GetTableModels() in TableListBuilder.cs:43
  at void ErikEJ.EFCorePowerTools.Services.DisplayService.<>c__DisplayClass7_0`1.<Wait>b__0(StatusContext ctx) in DisplayService.cs:64
  at Task Spectre.Console.Status.<>c__DisplayClass14_0.<Start>b__0(StatusContext ctx) in Status.cs:44
  at void Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Status.cs:79
  at void Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Status.cs:120
  at void Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext() in Progress.cs:138
  at async Task<T> Spectre.Console.Internal.DefaultExclusivityMode.RunAsync<T>(Func<Task<T>> func) in DefaultExclusivityMode.cs:40
  at async Task<T> Spectre.Console.Progress.StartAsync<T>(Func<ProgressContext, Task<T>> action) in Progress.cs:121
  at async Task<T> Spectre.Console.Status.StartAsync<T>(string status, Func<StatusContext, Task<T>> func) in Status.cs:117
  at async Task Spectre.Console.Status.StartAsync(string status, Func<StatusContext, Task> action) in Status.cs:77
  at void Spectre.Console.Status.Start(string status, Action<StatusContext> action) in Status.cs:48
  at T ErikEJ.EFCorePowerTools.Services.DisplayService.Wait<T>(string message, Func<T> doFunc) in DisplayService.cs:59
  at List<TableModel> ErikEJ.EFCorePowerTools.HostedServices.ScaffoldHostedService.GetTablesAndViews() in ScaffoldHostedService.cs:187
  at async Task ErikEJ.EFCorePowerTools.HostedServices.ScaffoldHostedService.ExecuteAsync(CancellationToken stoppingToken) in ScaffoldHostedService.cs:43
  at async Task Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
  at async Task Microsoft.Extensions.Hosting.Internal.Host.ForeachService<T>(IEnumerable<T> services, CancellationToken token, bool concurrent, bool abortOnFirstException, List<Exception>    
     exceptions, Func<T, CancellationToken, Task> operation)
  at void Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(ref <>c__DisplayClass15_0 )
  at async Task Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
  at async Task<IHost> Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions.StartAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
  at void ErikEJ.EFCorePowerTools.Program.<>c.<<MainAsync>b__1_1>d.MoveNext() in Program.cs:55
  at async Task<int> ErikEJ.EFCorePowerTools.Program.MainAsync(string[] args) in Program.cs:65
  at async Task<int> ErikEJ.EFCorePowerTools.Program.Main(string[] args) in Program.cs:22
```

2024-10-06 17:52 UTC, ErikEJ commented
@barnuri Apparently some integration testing is needed! You can pull the actual queries out of the code snd run them in SSMS or similar

2024-10-06 17:54 UTC, barnuri commented
> @barnuri Apparently some integration testing is needed! You can pull the actual queries out of the code snd run them in SSMS or similar

yeah probably but what you sent look as different code 
i wanted to see whats happened after this fix will enter to the scaffolding and continue from there

2024-10-06 18:09 UTC, ErikEJ commented
Same code as in EF Core, with some very minor adjustments, actually

2024-10-07 06:48 UTC, roji commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        if (_versionInformation != null && _versionInformation.Contains("Kusto", StringComparison.Ordinal))
I'd rather be conservative here and match the entire string ("Microsoft SQL Kusto") rather than have a Contains() check, just to avoid possible false positives etc.

2024-10-07 06:49 UTC, roji commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        if (_versionInformation != null && _versionInformation.Contains("Kusto", StringComparison.Ordinal))
nit: please keep this method method bodied as before rather than introducing an if.

2024-10-07 06:50 UTC, roji commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private string? _versionInformation;
nit: rename to `_version` (that's what SQL Server calls it)

2024-10-07 07:05 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +    private string? _versionInformation;
done

2024-10-07 07:05 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        if (_versionInformation != null && _versionInformation.Contains("Kusto", StringComparison.Ordinal))
done

2024-10-07 07:05 UTC, barnuri commented on src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> +        if (_versionInformation != null && _versionInformation.Contains("Kusto", StringComparison.Ordinal))
done

2024-10-07 09:14 UTC, roji approved these changes
Thanks, this looks OK to me. @ErikEJ can I ask you to review and approve as well as you're particularly familiar with all this?

2024-10-07 09:35 UTC, barnuri commented
> Thanks, this looks OK to me. @ErikEJ can I ask you to review and approve as well as you're particularly familiar with all this?

he already approved

2024-10-07 09:48 UTC, ErikEJ commented
@roji @barnuri I am reluctant until @barnuri hase done some smoke testing, looking at the error from EF Core Power Tools above:

`Reference to missing column 't.object_id' [line:position=11:29]`

I believe you should be able to check out the latest Power Tools, and run the efpcpt.8 project, in order to get the query text, and then confirm if there are errors from running against a Kusto DB

2024-10-07 09:48 UTC, ErikEJ requested changes
Needs smoke testing

2024-10-07 11:31 UTC, barnuri commented
> Needs smoke testing

looks like the inner select is not working inside this query, debugging efreveng80
```
AND NOT EXISTS (SELECT *
    FROM [sys].[extended_properties] AS [ep]
    WHERE [ep].[major_id] = [t].[object_id]
        AND [ep].[minor_id] = 0
        AND [ep].[class] = 1
        AND [ep].[name] = N'microsoft_database_tools_support'
    )
```

2024-10-07 12:10 UTC, ErikEJ commented
@barnuri Yikes! Maybe you can rewrite to use a LEFT OUTER JOIN and a NULL check?

https://www.sqlinthewild.co.za/index.php/2010/03/23/left-outer-join-vs-not-exists/

2024-10-07 13:27 UTC, barnuri commented
did all the fixes that need in 
https://github.com/ErikEJ/EFCorePowerTools/pull/2564

2024-10-07 16:23 UTC, roji commented
> looks like the inner select is not working inside this query, debugging efreveng80

@barnuri if the inner select doesn't work, then this emulatio mode supports only a subset of SQL, and you're unlikely to be very successful using EF with it - EF generates SQL with similar subqueries for various queries, and that will also fail.

2024-10-07 18:55 UTC, ErikEJ commented
@roji @barnuri Maybe we should keep these changes in Power Tools for miw and see how it goes?

2024-10-07 18:58 UTC, roji commented
I'm not against doing tweaks in EF to accomodate Azure Data Studio, but we need a wider understanding here, i.e. how compatible is ADS really with SQL Server, how usable will it be with EF, etc. Just adding scaffolding capabilities - either to EF or to the Power Tools - doesn't make much sense if nothing is going to work after that's done.

2024-10-07 19:01 UTC, ErikEJ commented
And it is Azure Data Explorer ( ADX)

2024-10-07 19:16 UTC, roji commented
> Agree, but a way to find out is to enable queries against it based on a Power Tools generated DbContext - as an experimental feature..

I don't think any sort of scaffolding or Power Tools support is needed here, just in order to test what ADX supports and whether it makes sense to use EF with it... That's just something that someone needs to investigate. But of course if you want to add a feature to Power Tools sure :)

2024-10-07 20:22 UTC, barnuri commented
> > Agree, but a way to find out is to enable queries against it based on a Power Tools generated DbContext - as an experimental feature..
> 
> I don't think any sort of scaffolding or Power Tools support is needed here, just in order to test what ADX supports and whether it makes sense to use EF with it... That's just something that someone needs to investigate. But of course if you want to add a feature to Power Tools sure :)

after adding those fixes, i got full scaffolding of my db

2024-10-07 20:29 UTC, roji commented
@barnuri OK, but what are the actual SQL capabilities of ADX? The subquery above which you converted into a JOIN is a pretty bad sign of the SQL capabilities being very limited.

2024-10-07 20:40 UTC, barnuri commented
> @barnuri OK, but what are the actual SQL capabilities of ADX? The subquery above which you converted into a JOIN is a pretty bad sign of the SQL capabilities being very limited.

you are right, but most of the time you dont use sub queries anyway because its had bad performance, and its support the most common simple queries that we need and always we can also make it better it adx too

2024-10-07 20:42 UTC, roji commented
Is it only subqueries? Is there documentation anywhere saying what's supported and what isn't?

2024-10-07 20:42 UTC, roji commented
Also note that tests seem to be failing.

2024-10-09 10:52 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
Note that this LEFT JOIN isn't exactly the same as the correlated subquery it is replacing. The previous subquery returned only e.g. tables for which **no** extended property with the name `microsoft_database_tools_support` exists. The new LEFT JOIN does return such tables, it just doesn't join with that specific extended property row.

In other words, if a table with multiple extended properties exists - one of whom is `microsoft_database_tools_support` - then the previous subquery wouldn't return that table, but the new left join would.

@ErikEJ that that sound correct? If so, then this change is probably wrong?

2024-10-09 11:22 UTC, ErikEJ commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
Well, the purpose is to execlude tables with that extended property, so agree that this changes seems wrong

2024-10-09 11:59 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
but there is also where to check the join return null

2024-10-09 16:11 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
This query uses a LEFT JOIN to bring in the related data from the extended_properties table, and then it filters for rows where no matching records exist in extended_properties (i.e., ep.[major_id] IS NULL ensures that there is no match in the joined table). This effectively mimics the behavior of NOT EXISTS.


also tried to use chatgpt to rewrite the query and he give me the same thing that i did
![image](https://github.com/user-attachments/assets/83fdfba7-9a41-4ce5-8b36-3fb5a879d2bd)

2024-10-10 09:51 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
> and then it filters for rows where no matching records exist in extended_properties

This is not what it does.

 LEFT JOIN joins on the extended_properties rows; if there are several of these for a given object, you now have multiple rows for the same object - one per extended property that exists for that object. At that point, your WHERE clause filters out only thos rows where the extended property major_id is NULL, but leaves any other rows where it isn't. The rewriting from the subquery to LEFT JOIN is correct only if you can assume there's only one extended_property row per object at most, which clearly isn't the case here.

2024-10-10 12:26 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
you have any suggestion how to make this query works without exists ?

2024-10-10 13:20 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
what about doing the op way ?
```sql
IF EXISTS
    SELECT * FROM [sys].[objects] o
    INNER JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
    WHERE [o].[type] != 'U' AND [o].[is_ms_shipped] != 0
SELECT 0 ELSE SELECT 1
```

2024-10-10 13:21 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
do the op inside the query and if exists return 0 else 1 (before it was 1 else 0)

2024-10-10 21:04 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
@roji let me know if you thinks its ok, if yes i will fix it in the code and in the tests

2024-10-11 07:37 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
@barnuri I'm not sure I understand (what op are you referring to here?), but the above SQL fragment doesn't seem to actually look at the table name... If it's integrated into an existing query, then it's still a correlated subquery, and so presumably not supported.

A way to do this would be to do a separate query for all tables which **do** have the bad extended property (using a regular inner join, and then exclude those tables client-side, in .NET code. That starts to be more of a change to the scaffolding code, just to account for this ADX SQL limitation - I'm not sure I love that idea.

2024-10-13 05:59 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
@roji found a solution, subqueries is working without referencing query values and without using exists
this query works 
```sql
IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND [o].[object_id] NOT IN (SELECT [ep].[major_id]
        FROM [sys].[extended_properties] AS [ep]
        WHERE [ep].[minor_id] = 0
            AND [ep].[class] = 1
            AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
```

2024-10-13 07:36 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     AND [o].[object_id] NOT IN (SELECT [ep].[major_id]
Good work here @barnuri! This indeed replaces a correlated EXISTS subquery with a non-correlated IN. I'd actually accept that as an improvement regardless of the SQL limitations of ADX - we did this improvement in EF's query generation in 8.0, both because the SQL more clearly matches the intent and because it can be (dramatically) faster on some databases (but not on SQL Server).

2024-10-13 07:37 UTC, roji commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     LEFT JOIN sys.extended_properties AS [ep] on [ep].[major_id] = [o].[object_id] AND [ep].minor_id = 0 AND [ep].class = 1 AND [ep].[name] = N'microsoft_database_tools_support'
Great, see https://github.com/dotnet/efcore/pull/34832/files#r1798126585.

2024-10-13 07:38 UTC, roji commented
@ErikEJ @barnuri after the last modifications, I'm OK with merging the PR as it is. Has the appropriate smoke testing been done, @ErikEJ are you OK with this as well?

2024-10-13 07:40 UTC, ErikEJ commented
Let me do a little smoke testing on the Power Tools PR that resembles this

2024-10-13 09:35 UTC, barnuri commented on test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> +     AND [o].[object_id] NOT IN (SELECT [ep].[major_id]
thanks :)
and thanks for the collaboration 💪🏾

2024-10-14 06:39 UTC, ErikEJ commented
@roji @barnuri I have done some smoke testing with the EF Core Power Tools daily build, and everything works as expected.

I like the minimal footprint this PR has. 

🐑 🇮🇹

2024-10-14 06:52 UTC, roji approved these changes

2024-10-14 06:55 UTC, merged

2024-10-14 06:55 UTC, roji commented
Merged for 10, thanks for your contribution @barnuri!