Avoid using `^` and `~` when invalid because of value converters
dotnet/efcore pull request #35124
Opened 2024-11-16 10:52 UTC by ranma42

The transformation of equality/in-equality in a (negated) XOR is only possible
when the expressions are BIT or integer types on the SQL side (i.e. taking value
conversion into account).

Similarly, the Boolean negation `NOT` can be implemented as `~` only if the
underlying expression is a BIT.

Fixes #35093.

2024-11-28 09:47 UTC, roji requested changes
@ranma42 thanks for working on this and sorry it took a while to review (lots of workload at the moment post-9.0!).

See my two comments and let me know what you think... FYI the deadline for getting a fix into 9.0.1 is extremely close (ideally we'd have this finished today). If you can, please let me know if you don't have time to iterate over this right away - I'm happy to take over and do changes.

Once we're good here I'll also prepare a backport PR for 9.0.1.

2024-11-28 09:47 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs
> +                && (leftType == typeof(bool) || leftType.IsEnum || leftType.IsInteger())
I think the IsEnum case can be removed, since now that we're looking at the provider type is should never be an enum (enums are value-converted to int)

2024-11-28 09:47 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs
> +                    sqlUnaryExpression.TypeMapping?.Converter is null &&
Isn't a more correct fix here to look at `sqlUnaryExpression.TypeMapping?.Converter?.ProviderClrType ?? sqlUnaryExpression.Type` above (in the `when` comparing to `typeof(bool)`)? For example, if there's a Y/N string being value converted to BIT, I think we do want this code to go through and do OnesComponent (on the database side it's just a BIT).

2024-11-28 15:58 UTC, ranma42 commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs
> +                    sqlUnaryExpression.TypeMapping?.Converter is null &&
yup, I just thought that it was not a very likely scenario; will update ASAP

2024-11-28 16:16 UTC, ranma42 commented
I will try to push the changes tonight (aka in ~4 hours)

2024-11-28 18:51 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs
> +                    sqlUnaryExpression.TypeMapping?.Converter is null &&
You'd be surprised what people do 🤣

2024-11-28 20:50 UTC, ranma42 commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs
> +                    sqlUnaryExpression.TypeMapping?.Converter is null &&
I am not even sure if it is possible to build an expression in which a y/n string is being negated 🤔 
I applied your suggestion, but I don't have time to add a test for this case right now (I can work on it in the weekend, if needed).

2024-11-29 18:21 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/SearchConditionConverter.cs
> +                    sqlUnaryExpression.TypeMapping?.Converter is null &&
You're generally complete right... Though I'll point out that `Expression.Not()` has an [overload](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.not?view=net-7.0#system-linq-expressions-expression-not(system-linq-expressions-expression-system-reflection-methodinfo)) which accepts an implementing method - this allows arbitrary types to be "negatable". Similarly, IIRC user types which implement the a not operator via operator overloading should also be supported (by am no longer sure about that).

Of course, it could be argued that EF shouldn't translate negation for those cases (where the implementing method/operator obviously are not taken into account)... But this is all indeed highly academic. I also don't think a test is necesary here at this point.

2024-11-29 18:22 UTC, roji approved these changes
Thanks as always @ranma42!

2024-11-29 18:22 UTC, merged

2024-11-30 09:21 UTC, roji commented
Backport PR: https://github.com/dotnet/efcore/pull/35241