Adding Half type support for SqlLite
dotnet/efcore pull request #35193
Opened 2024-11-24 22:14 UTC by newmasterSG

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #30931 
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

2024-11-24 22:16 UTC, newmasterSG commented
> Contributor

@dotnet-policy-service agree company="Microsoft"

2024-12-03 09:09 UTC, cincuranet requested changes
Thanks for your contribution. This looks good, just some small details to iron out.

2024-12-03 09:09 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +        private const string HalfFormatConst = "{0:0.0####}";
Not that it matters too much, but isn't more correct format `0.0###`?

2024-12-03 09:09 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +        protected override string GenerateNonNullSqlLiteral(object value) => Convert.ToDouble((Half)value).ToString("R");
I think this shouldn't be here, given we have proper implementation for `SqlLiteralFormatString`.

2024-12-03 09:09 UTC, cincuranet commented on src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
> +#endif
```suggestion
#endif

```

2024-12-03 09:09 UTC, cincuranet commented on src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
> +#endif
```suggestion
#endif

```

2024-12-03 12:13 UTC, newmasterSG commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +        private const string HalfFormatConst = "{0:0.0####}";
Yeah, you are right. I will change

2024-12-03 12:23 UTC, newmasterSG commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +        protected override string GenerateNonNullSqlLiteral(object value) => Convert.ToDouble((Half)value).ToString("R");
Just remove this code?

2024-12-04 17:55 UTC, bricelam requested changes

2024-12-04 17:55 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
> +        { typeof(Half), new FloatTypeMapping(RealTypeName) },
I don't think this should be FloatTypeMapping. Is there a relational mapping for half? If not, this should probably be a new SqliteHalfMapping type.

2024-12-04 18:02 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +            => "'" + HalfFormatConst + "'";
Hmm, this doesn't look right. It will store them as TEXT values, not REAL. I think this whole implementation should look more like FloatTypeMapping and DoubleTypeMapping.

2024-12-04 18:04 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +            => "'" + HalfFormatConst + "'";
Also, should this be added to Relational instead?

2024-12-04 19:48 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +        protected override string GenerateNonNullSqlLiteral(object value) => Convert.ToDouble((Half)value).ToString("R");
Yes.

2024-12-04 19:49 UTC, cincuranet commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
> +        { typeof(Half), new FloatTypeMapping(RealTypeName) },
Good catch. I missed that.

2024-12-04 21:49 UTC, newmasterSG commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +            => "'" + HalfFormatConst + "'";
What do you mean as Relation?

2024-12-04 23:29 UTC, bricelam commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +            => "'" + HalfFormatConst + "'";
In EFCore.Relaional (next to the ones for float and double). This would allow other providers to reuse them.

2024-12-05 06:48 UTC, newmasterSG commented on src/EFCore.Sqlite.Core/Storage/Internal/SqliteHalfTypeMapping.cs
> +            => "'" + HalfFormatConst + "'";
Yeah, thanks. I re-wrote from sqlhalftypemapping to simple half type mapping

2024-12-05 15:02 UTC, cincuranet commented
Looking at it with fresh eyes now and also after talking with the team... This should be split into two PRs. First would handle only the `Microsoft.Data.Sqlite` part (what #30931 is basically about). And for EF you should open issue first to discuss it first - because it definitely needs a discussion - and after it is approved you can submit another PR. I'll close this now @newmasterSG and feel free to open new PR for the `Microsoft.Data.Sqlite` part.

2024-12-05 15:02 UTC, closed without merging

2024-12-05 15:09 UTC, newmasterSG commented
@cincuranet , so I need create two issues. First only for sqllite and second for full ef?

2024-12-05 15:48 UTC, bricelam commented
Yeah, the Microsoft.Data.Sqlite changes here look ready to go to me (FWIW), but there's more to consider on the EF side like value converters, compiled models, migrations, etc.