Add SqlServer translation for DateOnly.ToDateTime(timeOnly)
dotnet/efcore pull request #35194
Opened 2024-11-25 00:02 UTC by mseada94

Fixes #35076

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ ] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

2024-11-25 00:04 UTC, mseada94 commented
The translation is done as expected but I have issue in the where comparison which compare date with datetime

Error Message on test: 
```
Microsoft.Data.SqlClient.SqlException : Conversion failed when converting date and/or time from character string.
```

SQL sent to the database:
```sql
SELECT [m].[Id], [m].[BriefingDocument], [m].[BriefingDocumentFileExtension], [m].[CodeName], [m].[Date], [m].[Difficulty], [m].[Duration], [m].[Rating], [m].[Time], [m].[Timeline]
FROM [Missions] AS [m]
WHERE DATETIMEFROMPARTS(DATEPART(year, [m].[Date]), DATEPART(month, [m].[Date]), DATEPART(day, [m].[Date]), DATEPART(hour, [m].[Time]), DATEPART(minute, [m].[Time]), DATEPART(second, [m].[Time]), DATEPART(millisecond, [m].[Time])) = '1990-11-10T10:15:50.5000000'
```

2024-11-25 00:05 UTC, mseada94 commented
@dotnet-policy-service agree

2024-11-25 05:10 UTC, roji requested changes
I think the translation should be to [DATETIME2FROMPARTS](https://learn.microsoft.com/en-us/sql/t-sql/functions/datetime2fromparts-transact-sql?view=sql-server-ver16) (which returns SQL Server `datetime2`), rather than [DATETIMEFROMPARTS](https://learn.microsoft.com/en-us/sql/t-sql/functions/datetimefromparts-transact-sql?view=sql-server-ver16) (which returns the discouraged `datetime`.

We also need to refrain from doing the translation when either the DateOnly or the TimeOnly are a complex SQL expression (anything other than a column/constant/parameter), for performance reasons; see https://github.com/dotnet/efcore/issues/35076#issuecomment-2470372494.

2024-11-25 05:10 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerDateOnlyMethodTranslator.cs
> +                    argumentsPropagateNullability: new[] { false, true },
```suggestion
                    argumentsPropagateNullability: [true, true],
```

2024-11-25 05:10 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerDateOnlyMethodTranslator.cs
> +                return _sqlExpressionFactory.Constant(((TimeOnly)constantArgument.Value!).Hour, typeof(int));
nit: use switch expression

2024-11-25 05:10 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerDateOnlyMethodTranslator.cs
> +            if (datepart == "hour")
Don't forget to do this, and also add a test for this case

2024-11-25 05:10 UTC, roji commented on src/EFCore.SqlServer/Query/Internal/Translators/SqlServerDateOnlyMethodTranslator.cs
> +            }
You need to pass in the resulting type mapping (for `datetime2`, assuming you change the function to DATETIME2FROMPARTS. This is why your test is failing with the datetime/string comparison.

2024-12-15 21:30 UTC, roji approved these changes
@mseada94 thanks for your contribution... In the interest of time, I've rebased this on top of the latest main - porting the test to the new translations test suite - and done a bit of fixup/cleanup. I'll merge once everything's green.

2024-12-15 22:10 UTC, merged