Fix query filters with context accessors
dotnet/efcore pull request #35237
Opened 2024-11-29 08:25 UTC by cincuranet

Fixes #35111

2024-11-29 15:07 UTC, roji requested changes

2024-11-29 15:07 UTC, roji commented on src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs
> +        if (testState.IsEvaluatable)
This can go under `case StateType.ContainsEvaluatable` below, along with the other tests for IsEvaluatable, for the other expression components (ifTrue, ifFalse); at that point the comment on line 547 can go away.

Note that this isn't just about nice refactoring: if the ifTrue and ifFalse components of the conditional expression happen to also be evaluatable, then the entire ConditionalExpression is evaluatable (an expression is evaluatable if all its children are). In that case, we should **not** evaluate the test component - the whole ConditionalExpression (or even a larger tree containing it) will be evaluated at some point up the stack.

This is why in this visitor, we first visit all the components, getting a state for each one of them (evaluatable, contains evaluatable...). We then combine those states, resulting in the state of the entire node (ConditionalExpression in this case), and then switch over it to decide what to do. You'll note that if the combined state is evaluatable (either with or without a captured variable), we simply do nothing and bubble the evaluatable state up. Only if the state is ContainsEvaluatable (which means that at least one child is evaluatable, but at least one child is also **not** evaluatable), we need to stop here and start evaluating the evaluatable children.

It's a complex and interesting visitor :) Happy to discuss it further!

2024-11-29 16:10 UTC, cincuranet commented on src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs
> +        if (testState.IsEvaluatable)
Is e6957e8a1795113c10a0fc399954989105b6cf4d what you had in mind?

2024-11-30 08:16 UTC, roji approved these changes

2024-11-30 08:16 UTC, merged

2024-11-30 08:16 UTC, roji commented on src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs
> +        if (testState.IsEvaluatable)
Yep